app/components/public/speaker-item.js, app/components/public/speaker-list.js, app/controllers/public/index.js, app/styles/pages/public-event.scss, app/styles/partials/all.scss, app/styles/partials/speaker.scss, app/templates/components/public/speaker-item.hbs, app/templates/components/public/speaker-list.hbs, app/templates/public/index.hbs, tests/integration/components/public/speaker-item-test.js, tests/integration/components/public/speaker-list-test.js
Adds layout for speakers to the public event page. 
**Screenshot**
Fixes #13  
@niranjan94 Please review this. Thanks
=> Adds speaker layout for events page

app/templates/components/events/events-table.hbs
Merges the logo and name into one column using default header of semantic UI.
Fixes #41
=> Use semantic UI header for logo and and event name

app/controllers/public.js, app/templates/components/public/side-menu.hbs, app/templates/public.hbs, tests/integration/components/public/side-menu-test.js
Replaces the rails with standard menu to make it stackable and responsive on the mobile
-
-
-
Fixes #30
=> Make rails responsive on public event page

app/components/public/speaker-item.js, app/styles/components/all.scss, app/styles/components/speaker-list.scss, app/templates/components/public/featured-speaker-list.hbs, app/templates/components/public/speaker-list.hbs
Fixes the speakers UI on Medium screens
**Portrait view is same as before**
**Normal speakers**
**Featured speakers**
Fixes #58
=> Fixes the speakers UI on Medium screens

app/templates/components/public/ticket-list.hbs
On the mobile portrait view, there is an overflow in the row containing order now button.
**Mobile portrait**
**Mobile landscape**
**Tablet**
Fixes #
=> Fixes the small screen overflow of order now button in tickets

app/components/public/session-filter.js, app/components/public/session-item.js, app/components/public/session-list.js, app/controllers/public/sessions.js, app/styles/pages/public-event.scss, app/templates/components/public/session-filter.hbs, app/templates/components/public/session-item.hbs, app/templates/components/public/session-list.hbs, app/templates/public/sessions.hbs, tests/integration/components/public/session-filter-test.js, tests/integration/components/public/session-item-test.js, tests/integration/components/public/session-list-test.js, tests/unit/controllers/public/sessions-test.js
Adds session layout in public events page
Added components
- Session-filter
- Session-list
- Session-item
####Screenshot
Fixes #63 
@niranjan94 Please review.
=> Adds sessions layout public event

app/components/public/event-map.js, app/styles/pages/public-event.scss, app/templates/components/public/event-map.hbs, app/templates/public/index.hbs, tests/integration/components/public/event-map-test.js
added map and location with the street view two fingers dragging on touchscreen devices on the public event page.
Added location and address support to public event page.
-Added location and address support
Fixes #14
=> added map and location on public event page

app/components/events/view/export/api-response.js, app/components/events/view/export/download-common.js, app/components/events/view/export/download-zip.js, app/router.js, app/routes/events/view/export.js, app/styles/components/all.scss, app/styles/components/events/view/export.scss, app/templates/components/events/view/export/api-response.hbs, app/templates/components/events/view/export/download-common.hbs, app/templates/components/events/view/export/download-zip.hbs, app/templates/events/view/export.hbs, tests/integration/components/events/view/export/api-response-test.js, tests/integration/components/events/view/export/download-common-test.js, tests/integration/components/events/view/export/download-zip-test.js, tests/unit/routes/events/view/export-test.js
Adds the UI for event export page.
Fixes #82
=> Add UI for event export

app/components/public/event-map.js, app/styles/pages/public-event.scss, app/templates/public/index.hbs
Over flow of map component
Fixes #95
=> Fix map component overflow on smaller screens

app/templates/events/view.hbs
added tabs and buttons to events/view.hbs
Fixes #77
=> added tabs and buttons to events/view.hbs

app/mixins/reset-scroll-position.js, app/routes/public/cfs.js, app/routes/public/sessions.js, tests/unit/mixins/reset-scroll-position-test.js
It resets the scroll position when the user changes tab on public event menu.
It adds a mixin to resolve the issue and add it to sessions and call for speakers sub routes for now.
Fixes #110
=> fix: reset the scroll upon tab change on public event menu

app/routes/settings/index.js, tests/unit/routes/settings/index-test.js
Earlier visting `/settings` route resulted in no active tabs
`/settings` route now redirects to `/settings/contact-info`
Fixes #130
=> Redirects /settings to /settings/contact-info

app/components/settings/password-section.js, app/templates/components/settings/password-section.hbs, tests/integration/components/settings/password-page-test.js
Adds UI for settings/password page (with form validation)
Fixes #126
=> Adds UI for settings/password route

app/templates/events/view/tickets.hbs
Fixes overflowing pointing menu on tickets page caused due to renaming of `grid` to `segment` in `view.hbs`
**Before:**
**After**
Fixes #142
=> Fixes overflowing pointing menu on tickets page

app/templates/components/nav-bar.hbs
because of `href-to`, the back browser back button is not functional for event and settings route, this PR will resolve that.
**Before:**
**After:**
Fixes #165
=> makes the browser back button functional on events and settings route

app/templates/components/events/event-import-section.hbs
Improves the width of the import event section for mobile devices,.
**BEFORE**
**AFTER**
Fixes #171
=> Improves width of import event in mobile devices

app/controllers/events/view/tickets/add-order.js, app/templates/components/public/ticket-list.hbs, app/templates/events/view/tickets/add-order.hbs
Disables continue button when there is no order. This also wraps the ticket-list & add-order table inside a form element, to follow a common design practice.
**When There is no order made.**
**When an order is made.**
Fixes #174
=> Adds form in add-order & ticket-list and disables continue button when there is no order.

app/routes/events/view/tickets/attendees.js
Fixes the bug which prevented buyer name from being displayed on the attendees sub-route.
*Before:*
*After:*
Fixes #204
=> Fixes buyer name not displaying (attendees sub route)

app/templates/components/widgets/forms/time-picker.hbs
The `id` attribute was missing from start and end time fields of create event wizard.
Modifies the component responsible (time-picker widget) to include the Id which was being passed already.
Fixes #233
=> Adds missing Id parameter to time picker widget

app/router.js, app/routes/events/view/sessions/index.js, app/routes/events/view/sessions/list.js, app/templates/events/view/sessions.hbs, app/templates/events/view/sessions/list.hbs, tests/unit/routes/events/view/sessions/list-test.js
added subroutes
splits events/<event-id>/sessions into proper pages
demo- https://open-event-frontend-branch3.herokuapp.com/events/963d3ba5/sessions
Fixes #215
=> splits events/<event-id>/sessions into proper pages

app/templates/components/tabbed-navigation.hbs
On mobile devices, it doesn't make sense for the menu to be pointing and also the menu doesn't close after selecting a route on it
- Menu is no longer pointing on mobile devices
- The menu now closes while switching routes
Fixes #252
=> Enhances tabbed navigation user experience

app/router.js, app/routes/events/view/speakers/index.js, app/routes/events/view/speakers/list.js, app/templates/events/view/speakers.hbs, app/templates/events/view/speakers/list.hbs, tests/unit/routes/events/view/speakers/list-test.js
splits events//sessions into proper pages
demo- https://open-event-frontend-branch4.herokuapp.com/events/963d3ba5/speakers/rejected
Fixes #245
=> splits events/<event-id>/speakers into proper pages

app/components/n-times.js, app/templates/admin/permissions/event-roles.hbs, app/templates/components/n-times.hbs, tests/integration/components/n-times-test.js
visiting `admin/permissions/event-roles` resulted in a same id assertion error because of same id being used for multiple checkboxes.
- Adds the n-times component.
- make the id's (changed to names for better form handling) unique
- make their name more logical, similar to the ones used in orga server 
Fixes #265
=> Fixes same id assertion error on admin/permissions

app/routes/events/list.js
subroutes of events now have titles depending on the page selected
demo- https://open-event-frontend-branch5.herokuapp.com/events/past
Fixes #288
=> adds dynamic title to events sub routes

app/components/forms/wizard/basic-details-step.js, app/components/modals/tax-info-modal.js, app/components/settings/password-section.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/modals/tax-info-modal.hbs
The form validation variables of the files which were missed while previous refactoring are converted to camelcase.
- refactor password section and tax Modal
- rename `isTaxModelOpen` to `isTaxModalOpen`
- Add missing validation to some fields of tax Modal
Since two minor but separate things are being solved by this PR I have split it into two commits.
Fixes #309
=> Refactor taxModal,password section to camelcase, add missing validation to tax Modal

app/routes/events/list.js
Adds redirection to events overview if the route is not live, past, draft.
Fixes #305 
@fossasia/open-event-frontend Please review
Deployment link:
https://open-event-frontend-app2.herokuapp.com
=> Fixes redirection to events/<id>

app/templates/components/nav-bar.hbs
Nav bar overflow on tablet Devices
**Before:**
**After:**
Fixes #314
=> Fix navbar overflow for tablets

app/components/modals/event-delete-modal.js, app/controllers/events/view.js, app/templates/components/modals/event-delete-modal.hbs, app/templates/events/view.hbs, tests/integration/components/modals/event-delete-modal-test.js, tests/unit/controllers/events/view-test.js
Adds the confirm delete modal before deleting an event on event overview page.
Fixes #299
=> Adds confirm modal before deleting event

app/templates/components/footer-main.hbs
Fixes the footer overflow on tablets 
Fixes #318
=> Fixes footer overflow on tablets

app/templates/components/events/view/overview/event-sponsors.hbs
This PR resolves the issue of pop-up overflowing in the sponsors' block under event overview page.
Deployment Link: https://open-event-frontend-harshita.herokuapp.com/events/963d3ba5
Fixes #325
=> resolve: overflow of popup on event overview page

app/components/event-card.js, app/components/smart-overflow.js, app/styles/partials/event-card.scss, app/templates/components/event-card.hbs, app/templates/components/smart-overflow.hbs, tests/integration/components/smart-overflow-test.js
This PR revolves around resolving the text overflow in the event card for smaller screens of mobile and tablet. 
- I've added 2 conditions for mobile and tablet respectively which do the same styling thing because I could not find the substitution for "OR" condition for helper classes.
- I have not added styling for entire div because it makes no sense to ellipsise the text for larger screens. This issue is only on mobile and tablet devices both in landscape and portrait modes.
Fixes #228 
@niranjan94 @geekyd @CosmicCoder96 @anu-007 @sumedh123 @utkarshnath  Please review 
Deployment Link : https://open-event-frontend-harshita.herokuapp.com/
=> resolve: text overflow in event card

app/components/modals/modal-base.js
Removes `classNames` from base modal as they are already present in `semantic-ui-ember/components/ui-modal` which the base modal extends.
The class will appear only once as it is supposed to after this.
Fixes #362
=> Remove classNames from modal-base

app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/forms/wizard/sponsors-step.hbs
This PR resolves the slider box's label going to next line for all the screens lesser than laptop.
Removing the column size and letting the label take whatever the require width is. 
Fixes #366 
Deployment Link: https://open-event-frontend-harshita.herokuapp.com/events/963d3ba5/edit/sponsors
=> resolve: sliderbox label overflowing to next line

app/styles/partials/overrides.scss, app/templates/components/widgets/forms/ticket-input.hbs
In the event create wizard, the move ticket up/down buttons are floated to the right, it works out fine for the mobile, because the grid is stackable, however in tablets for both horizontal and landscape mode, it creates a buggy diamond shaped layout.
Make the buttons float to the right only if the screen is larger than portrait tablet
Fixes #384
=> Make move ticket up/down buttons in create event wizard non floating for tablets

app/templates/events/view/tickets.hbs, app/templates/events/view/tickets/access-codes/list.hbs
moving on subroutes of access-codes will not remove its active class on sidebar
-resolves active class issue
-convert access code url (a field in access code table) as a link.
demo- https://open-event-frontend-branch3.herokuapp.com/events/963d3ba5/tickets/access-codes
Fixes #390
=> resolves : loss of active class of side bar on subroutes of /access-code

app/components/widgets/steps-indicator.js
This PR resolves the issue of wrong tab highlighted in nav bar at /events/event_id/edit page
Added add `this.notifyPropertyChange('autoSteps');` to `didInsertElement()` of `components/widgets/steps-indicator.js`
Fixes #386 
@niranjan94 @geekyd @CosmicCoder96 Please review. Thanks
=> resolve: wrong tab highlighted in nav bar at /events/event_id/edit page

app/templates/components/forms/wizard/sessions-speakers-step.hbs
Adds spacing between fields in mobile view.
Proposed design
Fixes #383 
Deployment link: 
https://open-event-frontend-app.herokuapp.com/login
=> Adds spacing between fields for mobile in session-speaker form

app/components/event-card.js, app/controllers/index.js, app/models/discount-code.js, app/routes/index.js, app/serializers/event-topic.js, app/serializers/event.js, app/templates/components/event-card.hbs, package-lock.json, package.json
Refactors the models and app to display events on public page via new API.
- Lock ember data to 2.13.2
- temporarily disable speakersCall
- Refactor to display events on public page via new API
=> Refactor to display events on public page via New API

app/templates/admin/permissions/system-roles.hbs, app/templates/components/forms/admin/settings/system-form.hbs
Hides divider in settings/system & permissions/system-roles form.
Fixes #410
=> Hides divider in settings/system & permissions/system-roles

app/styles/partials/wizard.scss, app/templates/components/forms/wizard/sponsors-step.hbs
Makes the UI of sponsors in event wizard responisve
- Prevent buttons overflow
- Give space between fields for mobile
- Make rich text editor accommodate for tablets
Fixes #371
=> Make UI of sponsors in event wizard responsive

app/templates/components/widgets/forms/location-input.hbs
Fixes overflowing location-input for mobile devices.
Fixes #414 
Deployment link : https://open-event-frontend-app.herokuapp.com/
=> Adds responsiveness to location-input by hiding label in mobile device

app/templates/components/forms/wizard/basic-details-step.hbs
make event creation wizard time field tablet responsive
before :
After:
Fixes #425
=> make event creation wizard time field tablet responsive

app/components/modals/cropper-modal.js
resolves button overflow
resolves overflow of image upload widget (for mobile devices) on the profile page
-remove width from boundary so that it can take the width of the current viewport
-reduce the height of the boundary so that buttons and zoom control does not overlap
-reduce the height and width of the viewport (maintaining same aspect ratio)
demo- http://open-event-frontend-branch6.herokuapp.com/profile
Fixes #424
=> Prevents image upload widget overflow on profile page

app/services/device.js
Currently there are more than 3 screen sizes which are bigger than the tablet,Computer, Large Monitor and Wide Screen
In order to specify an element common to all of them multiple boolean conditions have to be used, also the portrait and landscape tablet sizes are differentiated via isTablet and isComputer respectively, however a similar distinction is not possible for portrait and landscape mobile screens.
- Add isGreaterThanTablet breakpoint
- ~Add isPortraitMobile breakpoint~
- ~Add isLandscapeMobile breakpoint~
Fixes #441
=> Enhance device service add more breakpoints

app/components/explore/side-bar.js, app/templates/components/explore/side-bar.hbs
It was not possible for the user to enter the dates in the custom date filter, as the menu closed the field on clicking it.
Fixes #438
=> Enable user to enter values in explore route custom date filter

app/styles/partials/utils.scss, app/templates/events/view/tickets/attendees.hbs, app/templates/events/view/tickets/attendees/list.hbs
This PR resolves the issue of navigation bar overflowing and label misalignment for tablet sized devices.
Fixes #400 
Deployment Link : 
https://open-event-frontend-harshita.herokuapp.com/events/ebaf2dbe/tickets/attendees
@niranjan94 @CosmicCoder96 @geekyd Please review :+1:
=> make nav bar scrollable and added margin to label to attendees page

app/components/modals/add-system-role-modal.js, app/controllers/admin/permissions/system-roles.js, app/templates/admin/permissions/system-roles.hbs, app/templates/components/modals/add-system-role-modal.hbs, tests/integration/components/modals/add-system-role-modal-test.js, tests/unit/controllers/admin/permissions/system-roles-test.js
Adds the add system role modal to admin/permission/system-roles
Fixes #379
=> Create modal for add system role on admin/permissions

app/templates/components/events/view/overview/event-setup-checklist.hbs, app/templates/components/events/view/overview/event-sponsors.hbs, app/templates/events/view/tickets/access-codes.hbs, app/templates/events/view/tickets/discount-codes.hbs, app/templates/events/view/tickets/index.hbs
adds links to buttons under events/<event-id>/
demo- https://open-event-frontend-branch4.herokuapp.com/events/963d3ba5
Fixes #346
=> adds links to buttons under events/<event-id>/

app/components/public/ticket-list.js, app/styles/partials/overrides.scss, app/templates/components/public/ticket-list.hbs
Adds the missing promotional code text field on event page
Fixes #434
=> Add promotional code text field on event page

app/templates/components/forms/events/view/create-access-code.hbs, app/templates/events/view/tickets/access-codes.hbs
adds tabbed navigation to `events/<event-id>/tickets/access-codes/`
-adds tabbed navigation with links to dynamic segments 
-removed cancel button on create access-code page as requested [here](https://github.com/fossasia/open-event-frontend/pull/313#discussion_r126005778)
demo- http://open-event-frontend-branch3.herokuapp.com/events/ebaf2dbe/tickets/access-codes
Fixes #455
=> adds tabbed navigation to /access-code

app/styles/pages/public-event.scss, app/styles/partials/footer.scss, app/styles/vars.scss, app/templates/public.hbs
maintained the aspect ratio of the image and the content container as it scales.
-created a Sass mixin to maintain the aspect ratio of the image and the container 
-used 16:9 as default aspect ratio works fine with higher resolution image but a little bit of overflow still there for low-resolution image
-the height of the content changes according to the height of the content container
demo-http://open-event-frontend-branch5.herokuapp.com/e/963d3ba5
Fixes #328
=> prevents content overflow the event image on public event page

app/mixins/form.js
Fixes the bug where enter key didn't submit the form.
Modify form mixin
Reference for changes : https://stackoverflow.com/questions/11811426/why-does-the-tagname-dom-property-return-an-uppercase-value
Fixes #476
=> Fix enter key not submitting forms bug

app/controllers/register.js
Breaks loading state of registration form on pressing back button after successful completion which was earlier stuck in loading state.
make the loading state false, after successful registration
Fixes #484
=> Break loading state of registration form on pressing back button after successful completion

app/styles/partials/nav-bar.scss
It resolves the css styling specified in `.nav-bar-prompt` class being overridden, due to missing `!important`
Add !important to nav bar search box css class
Fixes #499
=> Add !important to nav bar search box css class

app/components/public/copyright-item.js, app/routes/public.js, app/templates/components/public/copyright-item.hbs, app/templates/public/index.hbs, tests/integration/components/public/copyright-item-test.js
Implements event-copyright API on public event page
Use event model to fetch copyright data instead.
Fixes #487
=> Implement event-copyright API on public event page

app/components/public/speaker-item.js, app/models/event.js, app/models/speaker.js, app/routes/public/index.js, app/templates/components/public/speaker-item.hbs, app/templates/public/index.hbs, tests/integration/components/public/featured-speaker-list-test.js, tests/integration/components/public/speaker-item-test.js, tests/integration/components/public/speaker-list-test.js, tests/unit/models/event-test.js, tests/unit/models/speaker-test.js, tests/unit/serializers/event-test.js
Implements Speaker API on public event page and add Speaker Model
Load speakers from the API instead of dummy data.
Fixes #503
=> Implement Speaker API on public event page and add Speaker Model

app/routes/events/view/edit.js, app/routes/events/view/edit/basic-details.js, app/routes/events/view/edit/sessions-speakers.js, app/routes/events/view/edit/sponsors.js, app/routes/public/cfs.js, app/routes/public/index.js, app/routes/public/schedule.js, app/routes/public/sessions.js, package-lock.json, package.json, testem.js
We have been using `this._super(...arguments)` call in a lot of routes to get the model of the parent route. The right way of doing it is by using [`modelFor`](https://www.emberjs.com/api/ember/2.14/classes/Ember.Route/methods/modelFor?anchor=modelFor). This PR refactors all `_super` usages to use `modelFor`.
> Also, in this PR. Did some updates of a few packages after local testing.
=> Use modelFor instead of a _super call

app/templates/events/view/tickets/access-codes.hbs, app/templates/events/view/tickets/discount-codes.hbs
This PR resolves the distortion of Create an access code and Create a discount code button in access code and discount code tabs respectively under Tickets tab.
Changed the if condition from mobile to tablet device because due to fluid it won't help much in mobile so changed it for tablet and other large screens.
Fixes #543 
@fossasia/open-event-frontend Please review.
=> Refractoring if condition in access and discount codes tabs under tickets tabs

app/templates/components/notification-dropdown.hbs
Make count label not appear when 0 new notifications
Fixes #563
=> Make count label not appear when there are no new notifications

app/components/forms/wizard/sponsors-step.js, app/components/widgets/forms/link-input.js, app/mixins/event-wizard.js, app/routes/events/view.js, app/routes/events/view/edit/sponsors.js, app/templates/components/forms/wizard/sponsors-step.hbs, tests/integration/components/forms/wizard/sponsors-step-test.js, tests/unit/serializers/user-test.js
- Integrates sponsors API to sponsors route
- Modifies link-input for valid urls
Fixes #579
=> Integrates sponsors API to sponsors route

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
Makes ticket buyer and holder same by default and also, when there is a single ticket holder, it considers it as a special case and makes the fields not appear unless the user specifically selects that the holder is not the same as the buyer.
Makes ticket buyer holder same by default for single tickets
- separate case for a single buyer.
- checkbox is there only for the first ticket holder of a given ticket
Fixes #562
=> Make ticket buyer and holder same by default

app/components/forms/wizard/sponsors-step.js, app/templates/components/forms/wizard/sponsors-step.hbs
Fixes the sponsors delete functionality in sponsor step, as currently the sponsors don't actually get deleted, they reappear on page refresh.
- To retain the intended functionality i.e. on pressing delete button the sponsor should disappear but the changes should persist only after the user has pressed delete, I have made use of `isDeleted` attribute of sponsor.
- `removeObject` has been removed as that was preventing the model from sending out a **DELETE** request.
Fixes #606
=> Fix the sponsors delete functionality in sponsor step

app/models/speakers-call.js, app/routes/public/cfs.js, app/templates/components/public/call-for-speakers.hbs, app/templates/public/cfs.hbs
Refactor public event page to use speakers call API
Fixes #556 
Deployment Link: https://open-event-frontend-harshita.herokuapp.com/e/82e5dff3/cfs
=> Refactor code to use speakers call API to the public event page

app/templates/components/public/call-for-speakers.hbs
Hides submit proposal button  for closed Call for Speakers
Fixes #680
=> Hide submit proposal button  for closed Call for Speakers

app/routes/events/view/tickets/index.js, app/templates/events/view/tickets/index.hbs
The PR integrated the order statistics API at events/view/tickets route.
Fixes #671 
@fossasia/open-event-frontend Please review!
=> Integrate order statistics API at tickets route

app/templates/components/modals/event-delete-modal.hbs
- Make deleteEvent as the default action so that user can submit the form by pressing the `return` key
Fixes #852
=> Make deleteEvent as submit action of event-delete-modal

app/templates/notifications/all.hbs
The tick appears only on the read notifications 
Fixes #876
=> Remove the check-mark icon from unread notification

app/styles/partials/utils.scss
It changes the behaviour of the mouse from **pointer** to how it is supposed to be (**type**) when it hovers over certain texts like the "Copyright" text in the footer and the other headings in the footer as they are not links to anything else.
The cursor behaviour has been changed in the above-mentioned regions and it now behaves as **type** instead of the **pointer** as those texts are not hyperlinks.
This Pull Request is in continuation of the PR #929 which is closed.
Fixes #921
=> Change cursor behaviour for some texts in footer

app/routes/notifications.js, app/routes/notifications/index.js, app/templates/notifications.hbs
- Hides "mark all as read" button when there are no notifications."
Fixes #934
=> Hide 'Mark all as read' button when no notifications around

app/components/events/view/overview/event-sponsors.js, app/templates/components/events/view/overview/event-sponsors.hbs, app/templates/components/ui-table/cell/cell-sponsor-options.hbs, tests/integration/components/ui-table/cell/cell-sponsor-options-test.js
It add the functionality to delete button.
- The sponsor added in the event overview section to the table gets deleted on clicking the delete button in the options.
Fixes #972
=> Add delete functionality to button in Event overview for sponsors

app/controllers/events/view/index.js, app/templates/components/events/view/overview/event-sponsors.hbs, app/templates/components/ui-table/cell/cell-sponsor-options.hbs, app/templates/events/view/index.hbs, tests/integration/components/ui-table/cell/cell-sponsor-options-test.js
When the edit button in the sponsor in the event overview section is clicked it then helps to edit the sponsors.
-It adds functionality to the edit button in the event overview section.
Fixes #977
=> Add edit functionality to button in Event overview for sponsors

app/controllers/events/view/sessions/list.js, app/models/session.js
This adds the value to the Last Modified At field in sessions table.
-The missing field 'Last Modified At' is added to sessions model
Fixes #985
=> Add missing 'Last Modified At' to sessions model

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs
session-speaker-form.hbs: add condition and user data
This change add user data as default for the speaker detail
Fixes #773
=> add user detail as default in call for speaker form

.travis.yml
fixes #995 .
The dev frontend is live on https://open-event-frontend-dev.herokuapp.com/ using https://open-event-api-dev.herokuapp.com/ as its server.
@mariobehling While this PR stops the automatic deploys to gcloud, nextgen.eventyay.com is currently up and it has to be manually shut down by someone with gloud access
=> Stop automatic deploy to gcloud

app/templates/index.hbs
Home Page: show 'No Upcoming Events Found' if no events present
Fixes #1037 
cc: @fossasia/open-event-frontend
=> Home Page: show 'No Upcoming Events Found' if no events present

app/router.js, app/routes/my-sessions/view.js, app/templates/components/session-card.hbs, app/templates/my-sessions.hbs, app/templates/my-sessions/view.hbs, tests/unit/routes/my-sessions/view-test.js
There was no route to properly view a session.
- Create a route my-sessions/<session_id> to view the sessions.
Fixes #1028
=> Create UI for view route in sessions

app/templates/public/sessions/list.hbs
Adds helper text when the sessions of a particular track do not exist.
- Helper text added to this route.
Fixes #1040
=> Add helper text to the route e/{event_identifier}/sessions/{track_id}

app/components/explore/side-bar.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
The field to add the start and the end date in custom dates in the explore routes is missing.
- Adds the field to add the start and the end date in custom dates.
Fixes #1046
=> Show custom dates accordion

app/controllers/events/view/sessions/list.js, app/templates/components/ui-table/cell/cell-simple-buttons.hbs, app/templates/events/view/sessions/list.hbs, tests/integration/components/ui-table/cell/cell-simple-buttons-test.js
When the view button is clicked sessions content is visible.
- Functionality added to the view button on this route.
Fixes #1022
=> Add view functionality to events/{event_identifier}/sessions

app/templates/public/sessions/index.hbs
There was no text stating that a session for some track did not exist.
- Helper text is added.
Fixes #1051
=> Add helper text if session for a track does not exists

app/routes/settings/contact-info.js, app/routes/settings/email-preferences.js, app/routes/settings/password.js
/settings route was accessible without login.
- Users are redirected to login if they are not logged in before accessing /settings route.
Fixes #1096
=> Add authentication security to /settings route

app/controllers/my-sessions/view.js, app/templates/my-sessions/view.hbs, tests/unit/controllers/my-sessions/view-test.js
The withdraw session proposal button appears even for past sessions.
- Remove button "Withdraw Session Proposal" for the sessions which are over.
Fixes #1113
=> Remove button "Withdraw Session Proposal" for past sessions

app/templates/components/modals/cfs-proposal-modal.hbs
Removes the button to  Add/Edit Session Proposal from 'cfs modal' till Speaker Details are added
- The session proposal can not be added or edited till you add the speaker details in the 'call for speaker modal'
Fixes #1130
=> Remove Add/Edit Session Proposal from cfs modal till Speaker Details are added

app/controllers/events/view/speakers/list.js, app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs, app/templates/events/view/speakers/list.hbs
The action button in the route events/{event_identifier}/speakers/all to delete the speakers currently doesn't work.
- The delete action button in the route events/{event_identifier}/speakers/all when clicked now deletes that particular speaker.
Fixes #1146
=> Add functionality to the delete  action button in the route to list speakers

app/components/modals/proposal-delete-modal.js, app/controllers/my-sessions/view.js, app/templates/components/modals/proposal-delete-modal.hbs, app/templates/my-sessions/view.hbs
Currently Withdraw proposal button in /my-sessions is not functional.
- Adds a confirmation modal for confirming proposal withdraw before actually deleting it.
- Makes withdraw proposal button functional.
Fixes #1143
=> Make Withdraw proposal button functional

app/controllers/my-sessions/view.js, app/routes/my-sessions/view.js, app/templates/my-sessions/view.hbs
Adds functionality to the Edit Session Proposal in the route to view a session.
- The edit session proposal button when clicked redirects to the edit session route.
Fixes #1060
=> Add functionality to Edit Session Proposal Button

app/models/event.js
Adds port to locally generated URL for Event.
URL is a computed property of the Event model. For local setup, adds the port number to the url.
Fixes #1162
=> fix: Add port to locally generated url for Event

README.md, docs/installation/Publish-to-GitHub-Pages.md, docs/installation/local.md
Adds instructions to publish the project to github pages.
Fixes #1150
=> chore: Add instructions to publish it to GitHub Pages

.env.example
use 127.0.0.1 in example file, instead of localhost to match the CSP.
Fixes #1178
=> use 127.0.0.1 as API_HOST in .env.example

app/controllers/admin/sessions/list.js, app/templates/components/ui-table/cell/cell-date.hbs
All the date columns in the admin/sessions route use the same template and the starts at and ends at columns show the starting and ending date of the session.
- Use of same template for the dates in admin/sessions
- Updated columns Starts At and Ends At.
Fixes #1188
=> Update columns Starts At, Ends At, Submitted At of the route admin/sessions

app/controllers/admin/events/list.js
The admin/events route has a common column for the starting and ending date of event further the template being used to display the information is not the common date template.
- The Starts At and Ends At columns created.
- The common template for dates is now used here.
Fixes #1193
=> Update columns Starts At and Ends At in admin/events

app/templates/components/ui-table/cell/admin/users/cell-actions.hbs
The delete and edit action buttons appear for the Super Admin too.
- Only view action button should appear for a super admin.
Fixes #1201
=> Update column Actions for admin/users

app/controllers/admin/sessions/list.js, app/templates/components/ui-table/cell/cell-simple-buttons.hbs
When the edit action button is clicked in the route admin/sessions it redirects to the public new-session form.
- The edit button when clicked in the given route now redirects to the edit session form in the route /sessions/edit/<session_id>
Fixes #1195
=> Add functionality to edit button in admin/sessions

app/components/modals/admin/content/new-event-sub-topic-modal.js, app/components/modals/admin/content/new-event-topic-modal.js, app/components/modals/admin/content/new-event-type-modal.js, app/controllers/admin/content/events.js, app/models/event-sub-topic.js, app/router.js, app/routes/admin/content/events.js, app/templates/admin/content.hbs, app/templates/admin/content/events.hbs, app/templates/components/modals/admin/content/new-event-sub-topic-modal.hbs, app/templates/components/modals/admin/content/new-event-topic-modal.hbs, app/templates/components/modals/admin/content/new-event-type-modal.hbs, tests/integration/components/modals/new-event-sub-topic-modal-test.js, tests/integration/components/modals/new-event-topic-modal-test.js, tests/integration/components/modals/new-event-type-modal-test.js
Currently there is not option to add event types and topic for admins. This causes problem while creating events as we are not able to select types and topics of events. This PR fixes this.
Fixes #1153
=> Add option to add event type and event topic to admin panel

app/components/events/view/overview/manage-roles.js, app/controllers/events/view/index.js
When we delete a sponsor in the event overview screen, the sponsor deleted successfully message is shown but the list stays the same.
Moreover in the Role Invites section, we delete the record from the data before the api call. It can cause problems when due to any error, the entry is not deleted from the server. In that case the list won't show the role invite but it would appear again on reload.
1.The sponsor's list gets updated automatically upon successful deletion.
2. The role invite object is deleted from the list after the successful deletion from the server.
Fixes #1209
=> fix: Update sponsors list upon deletion, Delete role-invites after deletion from server

app/controllers/create.js
The tickets weren't created from the wizard. The problem was that we set a default value of 10 for the max order in the model. If the organizer sets the value of quantity to be less than 10, then the server throws HTTP 422. 
Now we set the maxOrder to be the min of itself and the quantity.
Fixes #1207
=> fix: Set ticket maxOrder to be always less than quantity

app/controllers/events/view/sessions/create.js
Right now, when the create session/speaker fails, no error message is shown which leads to confusions.
The error message is shown if there is something wrong with the creation of a session but it isn't shown if something went wrong for the speaker.
- Show error message for speaker creation as well.
Fixes #1221
=> fix: Show error message for speakers creation

app/controllers/events/view/edit/sponsors.js, app/templates/components/forms/wizard/basic-details-step.hbs
Corrects the spelling error in `canPayByPaypal`
Fixes #1236
=> fix: Correct spelling mistake in "canPayByPaypal"

app/templates/components/public/ticket-list.hbs, app/templates/components/widgets/forms/ticket-input.hbs
Currently ticket list at public route shows description of tickets irrespective of whether it is set to hidden or visible.
Ticket input widget does not show description hence organizer is unable ti edit the description.
- Hide the description if organizer has set it to hidden at public routes.
- Enables description edits.
Fixes #1233
=> Hide ticket description if it is set to hidden 

app/components/widgets/forms/file-upload.js, app/utils/file.js
Currently in session creation file upload widget does not allow upload of pdf, ppt and mp4 files for slides. It throws file type not supported error.
- Added respective file codes to utils/file.js so that it does not consider such files as unknown.
Fixes #1223
=> Enable uploading of pdf ppt and mp4 files in sessions

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs
Checks if the call for speakers is public or private.
Displays only if it is public.
- Add a variable to hold the result of the above condition check
Fixes #1239
=> fix: Display only if public, call for speakers, on the event website

app/controllers/my-sessions/view.js, app/templates/my-sessions/view.hbs
In view sessions the Edit Speaker Details button has no functionality.
- In view sessions the Edit Speaker Details button redirects to edit speakers form.
Fixes #1253
=> Add functionality to Edit Speaker Details in view sessions

app/components/events/view/export/download-common.js, app/templates/components/events/view/export/download-common.hbs, app/templates/events/view/export.hbs
Makes the download as iCal button functional in the Export tab
Fixes #1211
=> feat: Make download as iCal functional

app/components/events/view/export/download-common.js
The build is failing due to a variable being imported but never being used.
- Remove ENV from the component file to fix the build.
Fixes #1263
=> Fix travis build

app/mixins/event-wizard.js
Call for speakers doesn't load right after we create an event.(Make sure to not reload the web application). It is because we aren't setting the record on the event.
- Setting record on event in getOrCreate method of EventWizard.
Fixes #1260
=> fix: set record on event in getOrCreate of EventWizard

app/components/forms/session-speaker-form.js, app/controllers/events/view/sessions/list.js, app/models/session.js, app/routes/events/view/sessions/create.js, app/routes/events/view/sessions/list.js, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/events/view/sessions/list.hbs
Currently aceept/reject proposal buttons on sessions route do not work. This PR makes necessary additions and deletions to make it functional.
- Defines new actions that allow organizer to accept or reject a proposal with an option to notify user via mail or not.
Fixes #1094
=> Make accept/reject proposal button for sessions functional

app/controllers/events/view/speakers/list.js, app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs, app/templates/events/view/speakers/list.hbs
The view button in speakers ember table currently doesn't work.
- When the view action button is clicked in the speakers table it redirects to the speakers form.
Fixes #1257
=> Add functionality to view action button in speakers

app/components/forms/wizard/basic-details-step.js, app/initializers/blanket.js, app/routes/application.js, app/services/settings.js, app/templates/components/forms/wizard/basic-details-step.hbs
Hide Stripe and Paypal payment options if they are disabled by the admin.
- Check the settings if these payment options are enabled or disabled.
Fixes #1245
=> fix: Hide payment options if disabled(Paypal and Stripe)

app/components/forms/wizard/basic-details-step.js, app/controllers/create.js, app/controllers/events/view/edit/basic-details.js, app/models/event.js, app/models/stripe-authorization.js, app/routes/create.js, app/routes/events/view.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/torii-providers/stripe.js, package.json, yarn.lock
Currently in event creation wizard organizer do not have support to add their stripe account to enable payments. This PR makes connect to stripe button functional.
- Adds a new library torii which makes OAuth implementation simpler.
- Defines new functions and methods to make stripe button functional.
Fixes #1180
=> Make Stripe OAuth functional in event wizard

app/templates/components/forms/wizard/basic-details-step.hbs
Hides discount code temporarily from event wizard till we get this feature ready to apply discount code on events.
This was discussed during event wizard meeting.
- Comments the discount code part.
Fixes #1240
=> Hide discount code temporarily from event wizard

app/router.js, app/routes/public/cfs/index.js
Add a route for private CFS link
- Re-direct to the cfs page if the hash in the url is correct.
Fixes #1244 
@niranjan94 There is one flaw in this which was there from before. The public cfs route doesn't check the privacy. So directly accessing `/cfs` from the address bar works irrespective of the privacy. I don't know how to handle this efficiently. I can add a check in the public route and define the whole private route but that would involve code repetition. Maybe we can pass an additional variable to the public route which would signify if the hash was correct or not in case of a private cfs.
```javascript
if(cfs.privacy === 'public' || (cfs.privacy === 'private' && isVerified === true)) {
// go ahead
}
``` 
But I am not really sure about the second method. How should I approach …
=> fix: Private CFS not working

app/templates/components/modals/login-signup-modal.hbs
In the modal in the route e/{event_identifier}/cfs when the user used to click submit proposal without logging in an absurd statement used to come in the modal.
- A meaningful statement for the modal is added.
Fixes #1300
=> Change modal message for call for speakers

app/routes/events/view/speakers/list.js
The list of the speakers was not getting filtered. The list would appear same for all tabs like pending, accepted.
- The filtering function is added to the list of speakers
Fixes #1287
=> Filter speakers list according to session's state

app/models/tax.js
Currently event creation throws error as server returns 404 for some event properties.
Directly use model properties to save models.
=> update tax model to match latest server changes

app/controllers/events/view.js
Now clicking 'Publish' with no event location won't turn the button to 'Unpublish', will show error message: "Your event must have a location before it can be published."
- Adds a check for the location of an event before publishing
Fixes #1308
=> fix: require event location before publishing event

app/controllers/events/view/sessions/create.js, app/serializers/application.js
Now the speaker and his corresponding session are linked together.
- First save the speaker to the database so that it gets an ID.
- Now add this speaker to the session.speakers relationship
- Save both again
Fixes #1277
=> fix: Speaker-Session not being linked

app/routes/admin/users/list.js
The users presently are not getting filtered in active and deleted routes.
- The all users route now shows all users including the deleted ones.
- The routes /users/active and /users/deleted now filter the users.
Fixes #1157
=> Filter users into active and deleted in admin/users

app/components/widgets/forms/file-upload.js, app/services/loader.js, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/widgets/forms/file-upload.hbs
Fix uploading slides field
- Do not add `Content-Type` header while uploading multipart-form as we cannot find the boundary used by the browser.
- The browser automatically generates the required header if it is not added. Refer to this answer https://stackoverflow.com/a/39281156/6870128
- Make the input field for file upload read-only.
Fixes #1290
=> fix: Upload slides in session create form

app/components/modals/admin/content/new-event-sub-topic-modal.js, app/controllers/admin/content/events.js, app/templates/admin/content/events.hbs, app/templates/components/modals/admin/content/new-event-sub-topic-modal.hbs
Disable add event sub-topic button until a topic is selected
- Disable add event sub-topic button until a topic is selected
- Lock the selected topic when adding the sub-topic in the modal
Fixes #1325
=> fix: Disable add event sub-topic button until a topic is selected

app/routes/events/view/speakers.js, app/templates/events/view/sessions.hbs, app/templates/events/view/speakers.hbs
If the session-speaker part is deactivated by the event organizer then the speaker table and the add speaker button should not appear in event/{event_identifier}/speakers route.
- The add speaker button and the speaker table should appear only if the session-speaker is enabled by the event organizer.
Else this should come:
Fixes #1349
=> Hide Add speaker button till session-speaker part is deactivated

app/controllers/admin/settings/images.js
Adds functionality to the the save button in admin/settings/images
- The save button when clicked changes the values of different attributes of the image size model accordingly. 
Fixes #1344
=> Add functionality to save button in admin/settings/images

app/components/forms/events/view/create-access-code.js, app/controllers/events/view/tickets/access-codes/create.js, app/controllers/events/view/tickets/access-codes/list.js, app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.hbs, app/templates/events/view/tickets/access-codes/create.hbs, app/templates/events/view/tickets/access-codes/list.hbs
Currently delete and toggle status button of access code are not functional.
- Add necessary actions to make those buttons functional.
Related to #1362
=> Make delete and toggling status of access code functional

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs
Show the new speaker form only if the new speaker option is checked, hide otherwise :
- Add a computed property `shouldShowNewSpeakerDetails` which does the check and returns true or false
- The check is as follows - `this.get('newSpeakerSelected') && !this.get('speakerDetails');`
Fixes #1375
=> fix: New speaker form shown even if it is unselected

app/components/forms/events/view/create-access-code.js, app/components/forms/events/view/create-discount-code.js, app/routes/events/view/tickets/discount-codes/create.js, app/templates/components/forms/events/view/create-access-code.hbs, app/templates/components/forms/events/view/create-discount-code.hbs
Currently "select all tickets" checkbox is visible even when no tickets are available to select from.
- Add proper checks to hide the ticket.
Fixes #1376
=> Hide 'select all' checkbox when no suitable tickets available

app/helpers/header-date.js, app/templates/components/public/ticket-list.hbs, app/templates/public.hbs
- Currently event header shows short forms of month and days. As discussed in meeting we should change it to what other platforms like eventbrite use. Since they use full forms with time zone mentioned, so we are modifying it.
- Ticket sales end date/time column does not include sales end time currently. This PR adds sales end time to that column.
- change date formats.
- add sales end time to tickets list.
Fixes #1341
=> Fix date formats and add end time to tickets sales end date/time column

app/controllers/public/cfs/edit-speaker.js, app/router.js, app/routes/public/cfs/edit-speaker.js, app/routes/public/cfs/index.js, app/templates/components/modals/cfs-proposal-modal.hbs, app/templates/components/public/call-for-speakers.hbs, app/templates/components/public/side-menu.hbs, app/templates/public/cfs/edit-speaker.hbs
Fixes all the bugs with the add and edit speaker details in cfs
- Add speaker button comes in the cfs modal if the logged in user has not added himself as a speaker of that event.
- Edit speaker details button comes if he exists in the list of speakers.
- The route for add speaker contains a form with the name and email of the logged in user as in v1.
- The route for edit speaker contains a form with the previously saved information of that user.
Fixes #1381
=> Fix bugs with speaker details and add edit route for cfs

app/controllers/admin/events/list.js, app/templates/components/ui-table/cell/cell-event-state.hbs
The state column is missing in admin/events
- Adds the state column to admin/events
Fixes #1358
=> Add state column to admin/events

app/components/errors/forbidden-error.js, app/templates/components/errors/forbidden-error.hbs, app/templates/error.hbs, tests/integration/components/errors/forbidden-error-test.js
Adds error handling for 403 HTTP status for forbidden routes
- Create 403 error component
- Integrate it with errors route
Fixes #1327
=> Add error handling for 403 HTTP status for forbidden routes

app/components/errors/generic-error.js, app/templates/components/errors/generic-error.hbs, app/templates/error.hbs, tests/integration/components/errors/generic-error-test.js
Currently, even for non server related errors, 500 error status is displayed.
- This will enable to show a generic error page, when the type of the error is not identifiable.
Fixes #1197
=> Implement a generic error page

app/routes/admin/sessions/list.js
The deleted tab never showed any sessions.
- The all tab shows all the active sessions
- Rejected, accepted, pending tabs show rejected, accepted, pending sessions respectively.
- Deleted tab shows the sessions which were deleted or the sessions of the event which was deleted.
Fixes #1394
=> Add filtering to admin/sessions

app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
paidVia is null until we actually pay for the order. So we should change paymentMethod to paidVia in orders list and attendees table which will be correct use of what we want to show.
- Modify the attendees and orders table accordingly.
Fixes #1399
=> Modify orders & attendees table to use paidVia instead of paymentMethod

app/templates/components/ui-table/cell/events/view/speakers/cell-simple-sessions.hbs
A session is deleted the speakers table shows it in the sessions column.
- Remove deleted sessions from the speakers table.
Fixes #1404
=> Update the sessions column for speakers table

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs
Makes the date filters in explore route just like v1.
- Restore the UI of v1
- Implement all the date range types
Fixes #1383
=> fix: Make date filters in explore route as v1

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs
- In the add speaker form if there are no sessions for the event helper text should come.
- In the create session form if there are no speakers for the event helper text should come.
Fixes #1406
=> Add helper text to add session/speaker form

app/components/forms/session-speaker-form.js, app/controllers/events/view/speakers/list.js, app/routes/events/view/sessions/create.js, app/routes/public/cfs/new-session.js, app/routes/public/cfs/new-speaker.js
- Most of the time if we create a from speaker and then go to /events/view/session or speaker without saving the cfs speaker it shows a blank entry.
- If user has not filled his first name and last name it comes as `null null` in text field.
- For the same route we have two `createRecord` instances the second on present in session-speaker-form component is not required.
- Add necessary code to fix above issues.
Fixes #1410
=> Fix minor bugs with cfs speaker and session creation

app/templates/components/ui-table/cell/admin/users/cell-system-roles.hbs
The column for system roles was missing in admin/users
- Shows info of the system role of the user, i.e. if the user is admin, super admin or a verified user.
Fixes #1413
=> Add system roles column to admin/users

app/components/forms/events/view/create-discount-code.js
Currently we can select free tickets also for discount code which does not makes sense.
- Filter tickets based on its type and select only paid tickets.
Fixes #1417
=> Allow only paid tickets to be selected for discount code

package.json, yarn.lock
Reverts fossasia/open-event-frontend#1401
Most of the collaborators working on this project are facing a similar error. Error popping out is given below. Maybe we can revert this PR and then manually update it when it appears to be fixed.
We tried running yarn but it seems updating dependencies but still error pops up.
```
Missing yarn packages: 
Package: ember-data
* Specified: ~3.3.0
* Installed: 3.2.0
Run `yarn` to install missing dependencies.
Stack Trace and Error Report: /tmp/error.dump.2c22997b231a0119f3b5c1e762d813f7.log
An error occurred in the constructor for ember-cli-dependency-checker at /home/rs/Pradeep/github/open-event-frontend/node_modules/ember-cli-dependency-checker
```
=> Revert "Update ember-data to the latest version 🚀"

.travis.yml
Fix failing Travis by following this solution https://github.com/greenkeeperio/greenkeeper-lockfile/issues/185.
- Change `before_install` to this : 
```yml
before_install:
- export PATH="$(yarn global bin):$PATH"
- yarn global add greenkeeper-lockfile@1
```
Fixes #1426
=> fix: Fix failing Travis by adding global path for yarn

app/routes/application.js
Right now when the user logs in, he/she is redirected back to the public page.
Redirect to previous route after login
Fixes #1294
=> feat: Redirect to previous route after login

app/components/forms/login-form.js, app/templates/components/forms/login-form.hbs
Retrieve redirect URL from the server for facebook login.
- Make a call to `v1/auth/oauth/facebook` to get the redirect url
- Created a success notifier just for testing purposes and will be removed in the next PR
Fixes #1429
=> feat: Retrieve redirect URL from the server for facebook login

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs, app/utils/validators.js
URL and Email fields aren't validated in the session/speaker form.
Add validation to those fields.
Fixes #1430 
Fixes #1326
=> feat: Add URL and Email validations in speaker-session form

app/components/modals/edit-user-modal.js, app/controllers/admin/users/list.js, app/templates/admin/users/list.hbs, app/templates/components/modals/edit-user-modal.hbs, app/templates/components/ui-table/cell/admin/users/cell-actions.hbs, tests/integration/components/modals/edit-user-modal-test.js, tests/integration/components/ui-table/cell/admin/users/cell-actions-test.js
Adds UI for the edit system roles modal.
- When the edit action button in admin/users is clicked a modal appears.
- UI for the modal is added
- Will do the API integration after https://github.com/fossasia/open-event-server/issues/5142 is solved.
Fixes #1432
=> Add UI for the edit button for admin/users

app/components/forms/orders/order-form.js, app/components/forms/session-speaker-form.js, app/utils/validators.js
Right now the session-speaker form accepts https://twitter.com as a valid twitter account url. Although this is a valid twitter url but it is not an account URL. Similar cases exist for other social media URL fields.
Added checks for them.
Fixes #1443
=> feat: Check for valid social media profiles in session-speaker form

app/components/forms/orders/order-form.js, app/models/order.js, app/routes/orders/expired.js, app/templates/components/forms/orders/order-form.hbs
Add timer to orders form to indicate time remaining for order to expire.
- Add necessary variables and function to achieve the functionality.
Fixes #1450 
Part of #750
=> Add timer to orders form to indicate time remaining to complete registration

app/components/public/ticket-list.js, app/routes/public/index.js, app/templates/components/modals/login-signup-modal.hbs, app/templates/components/public/ticket-list.hbs
Currently if user is not logged in before ordering tickets then it throws an error.
- Force user to be logged in before ordering tickets.
- Render login signup modal before if user is not logged in.
Fixes #1355
=> Display login signup modal if user is not logged in before ordering tickets

app/components/forms/login-form.js, app/torii-providers/facebook.js
Integrates the facebook login feature with the FE.
- Use torii and the endpoint `/oauth/login/<provider>/<auth_code>/` to login a user via facebook
Fixes #1449
=> feat: Complete the integration of Facebook login

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs
Currently all the side menu tabs are displayed when they are enabled by organizer even if they do not contain any information. Purpose of this PR is to display tabs only if they contain some data inside them. This was discussed during recent open event wizard meeting. 
- Hides tabs if no data is present.
- CFS is enabled only if it has a announcement with it.
Fixes #650
=> Hide side menu tabs on public routes if no data is present

app/components/footer-main.js, tests/integration/components/footer-main-test.js
Currently event types and event locations on home page are not sorted. This looks weird.
Sort them alphabetically.
Fixes #1488
=> Sort event types and event locations alphabetically on footer of homepage

app/controllers/admin/users.js, app/controllers/admin/users/view/settings/contact-info.js, app/router.js, app/routes/admin/users/view/settings.js, app/routes/admin/users/view/settings/applications.js, app/routes/admin/users/view/settings/contact-info.js, app/routes/admin/users/view/settings/email-preferences.js, app/templates/admin/users/view/settings.hbs, app/templates/admin/users/view/settings/applications.hbs, app/templates/admin/users/view/settings/contact-info.hbs, app/templates/admin/users/view/settings/email-preferences.hbs, app/templates/components/ui-table/cell/admin/users/cell-user-links.hbs
The settings user link in the admin/users was not working
- Make the settings user-link to redirect to the info about the user.
- Add routes for the settings user link displaying contact-info, notifications of the user in the row.
Fixes #1293
=> Add settings user link to admin/users

app/controllers/events/view/speakers/list.js, app/templates/components/public/featured-speaker-list.hbs, app/templates/components/ui-table/cell/events/view/speakers/cell-is-featured.hbs, app/templates/events/view/speakers/list.hbs
Allows organizers to make a speaker featured.
- Adds a checkbox in the speakers' tab.
Fixes #1498
=> Allows organizers to make a speaker featured

app/components/forms/reset-password-form.js
This PR fixes the error code check which results in displaying a more specific error message when an email is not found in the server while resetting its password:
Fixes #1516
=> Show proper error message for invalid email while resetting password

app/controllers/admin/events/list.js, app/controllers/admin/sessions/list.js, app/controllers/admin/users/list.js
Corrects the time format in sessions, users, and events tabs of the admin panel.
- Changes 24-hour format to 12-hour format.
Screenshot:
Fixes #1520
=> Corrects the time format in different tabs of admin panel

app/controllers/orders/new.js, app/models/event.js, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs
Currently only payment options supported in orders form are paypal and stripe.
- Add bank, cheque and onsite as payment options if organizer has enabled them
- Add if else conditions to check if a payment option is supported.
Fixes #1524
=> Add bank,cheque and onsite as payment options in order from

app/controllers/admin/messages.js, app/controllers/admin/messages/list.js, app/router.js, app/routes/admin/messages/index.js, app/routes/admin/messages/list.js, app/templates/admin/messages.hbs, app/templates/admin/messages/list.hbs
Adds the feature to update options column in admin -> messages table.
- Add a save button
- Move the table to a file called list.hbs according to the practice followed in the project.
- Link the save button with a patch request to the endpoint provided by the server to update options.
Fixes #1526
=> feat: Add feature to update options in Admin -> Messages

app/routes/events/view/speakers/edit.js, app/templates/events/view/speakers.hbs
- Removes the model.get console error in the edit speaker form.
- Removes the options to filter the speakers included for the list from the create speaker and edit speaker form.
Fixes #1531
=> Remove errors in the edit and create speakers forms.

app/components/ui-table/cell/events/view/tickets/cell-add-order-quantity.js, app/components/ui-table/cell/events/view/tickets/cell-add-order-total.js, app/controllers/events/view/tickets/add-order.js, app/routes/events/view/tickets/add-order.js, app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-quantity.hbs, app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-total.hbs, app/templates/events/view/tickets/add-order.hbs
Currently organizer is unable to add an order from add order section of tickets tab.
- Fix tickets selection table.
Part of #1292
=> Add Order Page: Step 1: Fix Add order form and allow proper selection of tickets

app/templates/components/forms/orders/attendee-list.hbs
Shows payment modes in attendee list only when enabled.
- Adds if condition to check if payment mode is enabled.
Fixes #1547
=> Shows payment modes in attendee list only when enabled

app/components/settings/application-section.js, app/models/user.js, app/routes/settings/applications.js, app/templates/components/forms/login-form.hbs, app/templates/components/settings/application-section.hbs, app/templates/settings/applications.hbs
Adds Facebook connect option to user -> settings. Removes unsupported auths from login and settings page
Fixes #1556
=> fix: Add fb auth to settings and remove non-supported auths

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
Right now we use the hardcoded 10 minutes set as the order expiry time. We should now use the order expiry time set by the event organizer.
- Change hardcoded value to orderExpiryTime.
Fixes #1540
=> Use the events order expiry time instead of hardcoded 10 minutes

app/components/modals/add-system-role-modal.js, app/controllers/admin/permissions/event-roles.js, app/models/event-role-permission.js, app/models/service.js, app/routes/admin/permissions/event-roles.js, app/templates/admin/permissions/event-roles.hbs, app/templates/admin/permissions/system-roles.hbs, app/templates/components/modals/add-system-role-modal.hbs
Integrates event roles API in admin permissions tab.
- Integrate event-role-permissions and service APIs.
Fixes #1329
=> Integrates event roles API in admin permissions tab

app/routes/admin/settings/images.js
Properly highlight tabs in admin -> settings.
- Fix the improper method used to rollback attributes in `willTransition()` method of admin->settings->images route.
Fixes #1589
=> fix: Tabs in admin->settings part is not correctly highlighted

app/components/public/ticket-list.js, app/models/access-code.js, app/models/order.js, app/routes/public.js, app/templates/components/public/ticket-list.hbs
Currently users cannot apply discount codes and access codes to their orders.
- As step 1 of this functionality allow users to apply access codes.
Part of #1558
=> Promotional Codes: Step 1: Allow users to apply access code to orders

app/components/widgets/forms/file-upload.js, app/templates/components/forms/events/view/edit-session.hbs, app/templates/components/widgets/forms/file-upload.hbs
Adds the file-upload widget to edit-session form.
- Adds the file-upload widget to edit-session form similar to create session-speaker form.
Fixes #1536
=> Adds file-upload widget to edit-session form

app/models/notification-action.js
Notification action button doesn't appear for view sessions.
It's visible and working now.
Fixes #1602
=> fix: Button title not showing for Sessions

app/controllers/orders/view.js, app/templates/orders/view.hbs
Add button to confirmed orders page to download invoice for attendees
- Add buttons to confirmed orders page to download invoice and tickets for attendees.
Fixes #1457
=> Allow users to download order invoice

app/components/modals/edit-user-modal.js, app/templates/components/modals/edit-user-modal.hbs
The edit user modal currently does not work.
- Integrates the attributes sales admin, admin, marketer to gthe edit user modal.
Fixes #1491
=> Integrate API to the edit user modal

app/controllers/notifications/all.js, app/templates/notifications/all.hbs
Mark all as read button appears on unread notifications route having no unread notifications
Add a computed property in the controller and hide the button.
Fixes #1619
=> fix: Hide mark_all_as_read button in Notification panel when there are no unread notifications

app/mixins/event-wizard.js
Shows notify error when Speaker Call start or end date is after Event end date.
Fixes #1156
=> fix: Disallow speaker call start, end dates after event end date

app/mixins/notifications.js, app/templates/notifications/all.hbs
Right now, nothing happens when we click on the "mark all as read" button in the notification panel. It should work
Added action in the notifications mixin to mark all the notifications as read.
Fixes #1611
=> feat: Add functionality to mark all as read button

app/components/modals/add-system-role-modal.js, app/controllers/admin/permissions/system-roles.js, app/models/custom-system-role.js, app/models/panel-permission.js, app/routes/admin/permissions/system-roles.js, app/templates/admin/permissions/system-roles.hbs, app/templates/components/modals/add-system-role-modal.hbs, tests/integration/components/modals/add-system-role-modal-test.js
Integrates system role API in permissions tab.
- Integrated the API for custom system-role.
Status:
The relationship for `panel-permission` needs to be added to custom-system-role API on the server, integration would be done here once it is done on the server.
Fixes #1597
=> [Fixes #1597]Integrates system role API in permissions tab

app/components/orders/order-summary.js, app/components/public/ticket-list.js, app/routes/public/index.js, app/templates/components/orders/order-summary.hbs, app/templates/components/public/ticket-list.hbs, tests/integration/components/orders/order-summary-test.js, tests/integration/components/public/ticket-list-test.js
Currently we cannot apply discount codes to avail discount in tickets.
- Make discount codes applicable to orders
Fixes #1558
=> feat: Make discount codes applicable to orders

app/templates/components/forms/admin/settings/system-form.hbs
Add a radio button in the settings form to select between flask(implemented) and elastic search(coming soon) feature. Currently, both the fields are disabled and flask is checked by default as elastic search is yet to be implemented properly.
Fixes #1634
=> feat: Provide option to switch between flask filters and elastic search

app/torii-providers/stripe.js
Stripe redirect uri produces error when re-editing an event
Fixes the stripe redirect uri
Fixes #1637
=> fix: stripe connect redirect uri works when re-editing an event

app/utils/computed-helpers.js
Currently, on the event creation page, the end date is always the today's date.
This PR changes the date of the end date to be the next date of the start date until the start date is set.
Fixes #1690
=> Update end date of event automatically when start date is selected.

app/styles/partials/form.scss
Earlier, the links on `Login`/`Register`/`Forget Password` doesn't change its style when hovered. 
- I have added relevant css to fix the style change on hover of links
Fixes #1684
=> Fixed style of links on hover

app/controllers/public/index.js, app/routes/public/index.js, app/serializers/order.js
Adds attendees to orders API POST request manually to fix the order placement wizard.
- Modify the serializer of orders to manually add missing attendees relationship
Fixes #  1751
=> Temporary fix: Adds attendees to orders API POST request manually

app/models/event.js
Adds a default value (`moment(0)`)for schedulePublishedOn in the event model.
=>  Add a default value for schedulePublishedOn in event model

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
Fixes erratic disabling of new order text fields by introducing two new computed properties.
Fixes #1755
=> Fix erratic disabling of new order text fields

app/controllers/events/view/scheduler.js
Handle null values for _schedulePublishedOn_ attribute of the event, to deal with legacy data.
=> Scheduler: Handle null values for schedulePublishedOn attribute

app/controllers/events/view.js
Currently if we publish or unpublish the event and it fails then also it shows transformed state in UI. 
- If state change is unsuccessful then it should revert back.
=> Revert back to original state if event publish/unpublish fails

app/components/orders/order-summary.js, app/helpers/ticket-attendees.js, app/templates/components/orders/order-summary.hbs
- Move the order summary calculations to a helper to return only the attendees which are related to the order.
Fixes #1789
=> Fix: Inconsistent order summary values

app/templates/components/public/session-item.hbs, app/templates/components/ui-table/row.hbs
Formats the text according to html tags returned in the server side data, instead of rendering the actual tags.
Fixes #1795
=> Render serverside html after sanitizing in ember model tables

app/templates/components/orders/order-summary.hbs, app/templates/components/public/ticket-list.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs, app/templates/events/view/tickets/attendees/list.hbs, app/templates/events/view/tickets/orders/list.hbs, app/templates/orders/expired.hbs, app/templates/orders/new.hbs, app/templates/orders/placed.hbs, app/templates/orders/view.hbs, app/templates/public/index.hbs, tests/integration/components/public/ticket-list-test.js, tests/integration/components/ui-table/cell/events/view/tickets/attendees/cell-price-test.js, tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-amount-test.js
- Show currency corresponding to the event on the public event page
- Show currency corresponding to the event on the order dashboard
- Show currency corresponding to the event for attendees
- Show currency corresponding to the event for orders on event dashboard
Fixes #1850
=> Enforce display of event currency across the app.

app/components/orders/order-summary.js
Currently, on the orders summary page, all the tickets amount is reduced even if the discount was applied to only a few of them. Although the final order of the amount is determined correctly, the break up does not add up due to incorrectly applied discounts.
=> Order summary: Add discount to discounted tickets only

app/routes/public/index.js, app/routes/public/speakers.js
Fixes the issue of all the speakers not showing up on the public event page.
=> Avoid pagination of speakers on public pages

app/components/public/ticket-list.js, app/templates/components/public/ticket-list.hbs
- Corrects the wrong URL generated while pressing enter
- Removes and sets the query param in the URL when a promotional code is applied.
Fixes #1903
=> Handle default action of Enter key for Promotional Codes

app/helpers/header-date.js, app/templates/public.hbs
- Display the time on event public page in it's own timezone.
Fixes #1829
=> Event Public Page: Display event time in it's own timezone

app/helpers/session-color.js, app/templates/components/ui-table/cell/events/view/speakers/cell-simple-sessions.hbs
Adds a label with the session name in the speakers table.
Fixes #1942
=> Add a label in front of Sessions in the Speaker table

app/routes/my-tickets/list.js
It makes sure that only tickets with statuses of ``completed`` and ``placed`` are show in the my-tickets section
- Using ``or`` condition to show only completed and placed orders
Fixes #1979
=> Improving filter for my-tickets

app/components/modals/login-signup-modal.js, app/components/public/ticket-list.js, app/controllers/public/index.js, app/templates/components/modals/login-signup-modal.hbs, app/templates/components/public/ticket-list.hbs, app/templates/components/unverified-user-message.hbs, app/templates/public/index.hbs, tests/integration/components/public/ticket-list-test.js, tests/integration/components/unverified-user-message-test.js
1. Modifies the pop up asking non-logged in users to log in or sign up, to instead ask for an email.
2. Functionality to handle pre-registered users who are simply not logged in will be handled in a separate issue.
3. Enables order now button for unverified users.
4. Generates a random password, and along with the entered user create a new user on the server.
5. Fetches user id from the server, and authenticate the session with him.
6. Posts successful authentication, persist the session with the new user itself.
7. Ensures, that after persisting the current user in the session, the initial session which is about to get invalidated does not cause the app to redirect new user to home page. Keep him on the order page itself.
8. Moves the placeOrder action into the controller of the route …
=> Orders: Make flow similar to eventyay Phase - 1

app/templates/components/public/copyright-item.hbs
Shows the copyright badges only when `logoUrl` is present. I adopted this method because i could not find a badge for All Rights Reserved which is free to use
- Using `logoUrl` as a condition for presence of the logo image
Fixes #1991
=> Show copyright logo only if `logoUrl` is present

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs
If  the user has not published the schedule the schedule link would not be visible.
Fixes #1798
=> schedule link is only visible when schedule is published

app/templates/events/view/scheduler.hbs
All sessions shown in scheduler changed to only accepted and confirmed sessions
-Only accepted and confirmed sessions will be shown in scheduler
Fixes #1985
=> Show accepted and confirmed sessions in event scheduler

app/controllers/events/view/tickets/orders/list.js
…tickets
Cancelled orders now show up under Cancelled tab in Orders tab of Tickets as soon as we cancel the order.
-
-
-
Fixes #2037
=> Display cancelled orders under Cancelled tab in Orders tab of Tickets

app/routes/public/sessions/list.js
It makes sure that `confirmed` sessions are shown in public page of an event instead of `accepted` ones
- Using `confirmed` instead of `accepted` as required state
After the filter change:
Fixes #2053
=> Modifying event sessions filters

app/routes/public/speakers.js
Makes sure that confirmed speakers are displayed in the event speakers section 
- Changing query value from `accepted` to `confirmed`
Screenshot :
(Speaker details can be find in issue) 
Fixes #2059
=> Changing query from accepted to confirmed

app/styles/components/ui-table.scss
A zero value should not have a unit suffix.
=> Remove SCSS lint warning

app/routes/create.js, app/templates/components/forms/wizard/basic-details-step.hbs
Earlier, if the ticketing was disabled from Admin, the `Create Event` section still showed `Ticketing` section.
- Passed `module` in `create` route
- Disabled Ticketing if it is disabled from Admin 
Fixes #1907
=> Hides ticketing section in Create Event section, if disabled from Admin

app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
It makes sure every ticket order has an email id to go with it
- Modifying `record.user.email` to `record.order.user.email`
Fixes #2070
=> Making sure order's user email is displayed

app/adapters/event.js
Adds a check in the adapter, to ensure adapter options are accessed only when they have been defined.
Fixes #2103
=> Fix: Broken event update

app/templates/components/forms/events/view/create-discount-code.hbs
It makes sure that event's payment currency is being used instead of default USD in add discount code sections
- Using event's payment currency instead of default USD
Fixes #2101
=> Using Event's payment currency in Add Discount Code form

app/controllers/events/view/tickets/access-codes/list.js, app/controllers/events/view/tickets/discount-codes/list.js, app/routes/events/view/tickets/access-codes/list.js, app/routes/events/view/tickets/discount-codes/list.js
Reload active and inactive tabs in Access and Discount codes when it is toggled.
Fixes #2107
=> Reload active and inactive tabs in Access and Discount codes when it is toggled

app/components/ui-table-server.js
Currently null values are ignored, and anything with null for a column like name is not displayed at all.
Fixes #2112
=> Improve customGlobalFilter in ember tables: include null values by default

app/routes/admin/users/list.js
Currently the non deleted users are being shown in Active tab , additional filter is required for utilising last accessed status  
- Using `last-accessed-at` as a query parameter
Fixes #2134
=> Fix : Improving filter for admin/user active list

app/controllers/admin/events/list.js, app/routes/admin/events/list.js, app/templates/admin/events/list.hbs, app/templates/components/ui-table/cell/cell-buttons.hbs
This PR resolves the issue of  restore button was still shown for deleted buttons in admin events
Fixes #2157
=> Display restore event button on admin event-all route

app/controllers/index.js
It makes sure that private call for speakers are no longer listed in the index page
- Adding `privacyState` conditional in CFS display
Before : 
After: 
Fixes #2176
=> Private CFS no longer being shown in index

app/routes/admin/users/list.js, app/templates/admin/users.hbs
This adds an `Inactive User` tab in Admin/Users
- Creating new parameter for inactive users
Fixes #2174
=> Adding 'Inactive User' Tab in Admin/Users

app/templates/components/ui-table/cell/cell-tickets.hbs
It uses completed order statistics instead of initially used total order statistics
- Using `completed` orders instead of `total` orders
Fixes #2187
=> Using completed orders instead of total orders

app/templates/my-sessions/view.hbs
- In my-sessions the edit speaker button only appears if the user is a speaker of that session (as in v1).
- All the speakers are listed in a line under the session title instead of coming as individual headings.
Fixes #2149
=> Improve the edit speaker functionality in my-sessions

app/templates/components/ui-table.hbs, app/themes/semantic.js
This makes the tablet screen view responsive by adding an x-scroll to table for `events/live` page.
- add the `x-scrollable` class to the table and make table not `tablet stackable`.
Fixes #2209
=> responsive events table view for tablet screens.

app/components/forms/admin/settings/system-form.js
Fixes: #2238
This makes the username and password field in the SMTP host server settings optional.
- make username and password optional in SMTP host settings.
=> make SMTP username and password field optional.

app/routes/admin/users/view/tickets/list.js, app/templates/admin/users/view/tickets.hbs
saved events column is removed from user tickets page
Fixes #2252
=> saved events column removed from user tickets page

app/routes/my-sessions/list.js
Adds a new tab which shows all the sessions of the concerned user by setting the filter to `[ ]` for that `token` 
- Add a new tab in my-sessions
- Add corresponding route
Fixes #2262
=> enh : modify sessions filter to shows all states

app/templates/components/modals/event-share-modal.hbs
As google plus will shut down on April 2, 2019, it is no longer needed in 'share events'
Fixes #2299
=> Remove google plus from share events

app/components/explore/side-bar.js
after this commit, `event_location` can be cleared by clear filter option
- use `location` as a filter disabling factor
Fixes #2332
=> fix : add location removal in explore filter

app/controllers/events/view/tickets/access-codes/list.js, app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-url.hbs
Currently, the `Access Code URL` column in `Access Codes` of `Tickets` section in Manage Events is not a link. It is simply a text
- Makes values of Access Code URL in Tickets section a link
Fixes #2329
=> Manage Events: Makes values of Access Code URL in Tickets section a link

app/templates/admin/content/system-images/list.hbs
Align System Images as two per row
Fixes #2321
=> Align System Images as two per row

app/templates/my-sessions/view.hbs
Currently, the start timestamp for any scheduled session is incorrect.
Also, if the session is not scheduled, it shows `From Invalid date to Invalid date`
- For accepted session, the timestamp should be correct.
- For session which is not scheduled, it should show Session Not Yet Scheduled
_Pending Session_
_Accepted Session_
Fixes #2349
=> My Session: Fixes timestamp of accepted and pending sessions

app/controllers/events/view/speakers/list.js, app/templates/components/ui-table/cell/events/view/speakers/speaker-mobile.hbs
- Sorting in not disabled for speakers-logo
- If Phone Number is not present, null should be removed
- Sorting disabled on Speakers Logo
- If mobile is not present, `null` is removed
Fixes #2342
=> Speaker Table:Disable sorting on speaker-logo and remove null on mobile

app/templates/components/public/social-links.hbs, app/templates/public.hbs, tests/integration/components/public/social-links-test.js
- Currently the External Event URL on the main page of event i.e. public, is having wrong link. It should have external link but it has same link as that of the public page
- Also, the General Info of event is not having Exteral event URL. It only has Social Media Links.
- Fixed URL on event's public route
- Included External event URL on General Info of event
Fixes #2334
=> External event URL fixed on public and event's general info

app/routes/public/sessions/list.js
Currently, `accepted` sessions are not visible in `Sessions` tab of public route e.g. on `/e/<event id>/sessions/s/all`.
- `accepted` sessions made visible
Fixes #2359
=> fix: make accepted sessions visible on public route

app/styles/partials/colors.scss
Currently, social media links in `public` route is not applicable due to incorrect scss code.
- fixed scss code
- added github color code
_Featured Speakers_
_Sessions_
Fixes #2357
=> fix: social media color in public route

app/components/public/session-item.js, app/templates/components/public/session-item.hbs
Duplicate images appearing in `session-item`.
- When the user click on the session the image on the top disappears and image should be above speaker description.
Fixes #2361
=> Redesigns the session-item on public route

app/routes/explore.js
Prevents the explore route from making separate network requests to event-topic, sub-topic, and types APIs and thus 404s for non-defined objects are handled automatically.
=> Explore route: Pre-fetch event-topics, sub-topics, event-types

app/templates/components/events/view/overview/general-info.hbs
It adds a breakdown of speakers along the lines of breakdown of number of sesssions
- using newly revamped event-statistics for the task
Fixes #2388
=> add speaker state breakdown in general info tab of event overview

app/routes/public.js
Prefetches the speakers call on the public event route so that an uncaught 404 is not generated.
#2424
=> Public event page: prefetch speakers-call

app/routes/events/view/tickets/discount-codes/create.js
sets the default `validTill` value to the end of the event instead of the start.
Fixes #2425
=> Fix discount code creation for ongoing events

app/components/public/side-menu.js
Fixes the uncaught exception generated due to referencing of a null speakers-call on the public page.
Fixes #2421
=> Public side menu: Avoid referencing null speakers-call

app/components/public/side-menu.js
Makes sure that `toISOString()` is not called on a null string.
Fixes #2435
=> Fix: Side Menu - invalid operation on null string

app/templates/create.hbs
An unverified User warning is now displayed on the Create Event page as well as unverified Users are not allowed to create an event. 
Fixes #2312
=> Display unverified user message on create event page

app/templates/admin/sales/locations.hbs
We can't use paymentCurrency of an event based on location because on a location, different events with different  currencies maybe present and they can't be displayed under a single tab using a single payment Currency unless standardised.
- Use USD as default rendering currency
Fixes #2402
=> using default USD currency in admin/sales location

app/templates/components/unverified-user-message.hbs, tests/integration/components/unverified-user-message-test.js
Incorrect message has been displayed to the user while verifying their acoount .
- corrected the popout message
Fixes #2437 
Please see the commit
=> Fixes the incorrect message popped to the unverified users

app/components/event-card.js, app/templates/components/event-card.hbs, app/templates/explore.hbs
Follow up for PR #2183 
Removes redundant computed properties by leveraging prefetching of these values introduced in PR #2371
@shreyanshdwivedi that's why it wasn't working before -- they were never fetched while executing.
=> Code optimization : Explore route :: Remove redundant computed properties

app/templates/components/widgets/forms/file-upload.hbs
It corrects the storage message on the create session page during file-upload
- update `file-upload.hbs`.
Fixes #2456
=> Fixes the incorrect storage instruction during file upload

app/templates/components/ui-table.hbs
There was a typo in the enclosing `div` `classes` of the pagination component. By resolving those typos, the margin of pagination line is fixed in manage events page.
- Fix typo of wrapper divs.
Fixes: #2490
=> Fix pagination line margin in manage events page.

app/templates/components/widgets/forms/image-upload.hbs
Resolves the UI defect during image -upload
- Added icon for re-crop option
Fixes #2479 
BEFORE
AFTER
=> Changes the icon for re-crop option

app/templates/components/forms/wizard/basic-details-step.hbs
This hides the payment section when a paid ticket was added but later ticketing was disabled.
- Modify the payment section if condition.
Fixes: #2506
=> Show payment section in events only when a paid ticket is added along with ticketing enabled.

app/templates/events/view/speakers.hbs
Fix mobile UI bug of speakers page. Make the export CSV button and Add speaker button in the same line as in Sessions page in mobile view
Before Changes (Mobile View):
Before Changes (Web View):
After changes (mobile view):
After Changes (Web View):
Fixes #2494
=> Fix mobile UI bug of speakers page

app/controllers/admin/events/list.js, app/controllers/events/list.js, app/routes/events/list.js
Refreshes dashboard after deletion of event.
- Added *refreshRoute* after success of deletion of event
Fixes #2483
=> Adding refresh of dashboard after deletion of event

app/controllers/settings/password.js
This PR fixes the error shown to the user when incorrect current password is entered during password reset process.
The if block checking for if error is returned by the server was checking for wrong attribute. The attribute received from server is `errors` while `error` was being checked in the frontend code. I fixed the attribute checked in `if` block and displayed the error along with added extra custom error message.
Fixes: #2546
=> Fix current password error in password reset settings.

app/routes/admin/users/list.js
When logged in as an admin, in the users tab under inactive users, deleted user is shown along with inactive user
- fixed the `filterOptions` for `Inactive` users
Fixes #2455
=> admin users:removes deleted users from inactive user filter

app/routes/events/view/scheduler.js
Avoid implicit pagination carried out by the server restricting the sessions received in the query.
Fixes #2555
=> Scheduler: Load all sessions, avoid pagination

app/templates/components/forms/wizard/sponsors-step.hbs
This PR fixes the sponsor button text when all sponsors are removed.
- Add if condition to check for sponsor length for button to be rendered.
Fixes: #2532
=> Fix add another sponsor button text when all sponsors are removed.

app/routes/events/view/scheduler.js, app/templates/events/view/scheduler.hbs
Ensure all values are always displayed and stored in UTC while viewing or scheduling through the scheduler.
Fixes #2559
=> Scheduler: standardize timezone to UTC

app/components/settings/contact-info-section.js, app/utils/validators.js
Reference Link for the regex:
https://stackoverflow.com/a/29835355
https://regexr.com/38pvb
This regex doesn't checks for helpline number like `1800-MY-APPLE`.
I guess we need to assume to some extent the kind of phone number to be entered.
This adds phone number field validation using regex.
- Add regex for phone number field validation.
Fixes: #2345
=> Add phone number field validation using regex.

app/templates/components/forms/wizard/sponsors-step.hbs
It sets equal widths to both the components enhancing the UI of sponsor page
- Update `sponsor-step.hbs` 
Fixes #2522
=> Fixes the width of both the components

app/templates/components/forms/wizard/basic-details-step.hbs
Make the event type, subtopic and topic dropdowns similar in design to Event Copyright
- use `selected` attribute in dropdown 
- change DefaultText conditions
Fixes #2626
=> Change default text styles for Event type dropdowns

app/templates/components/ui-table/cell/cell-sessions.hbs
this fixes the variable typo in sessionsSubmitted present in ui-table/cell-sessions
- fix spelling of sessionsSubmitted
Fixes #2610
=> Fix typo in ui-table/cell/cell-sessions

app/templates/notifications/all.hbs
Clicking on View Session in notification panel now redirects to correct location
Fixes #2607
=> Fixed Clicking on View Session in notification panel redirects to Not defined

app/templates/components/ui-table/cell/admin/users/cell-actions.hbs
Edit button removed if user is deleted
Fixes #2573
=> Remove the edit button if the user is deleted

app/models/user.js
The current implementation prevents even an admin from making someone else an admin. This change will enable an admin to make other users admin.
=> make isAdmin attribute of user modifiable by admin

app/templates/components/forms/orders/order-form.hbs
Adds a flag icon infront of the country name in the drop-down to select a country in the order-form.
Fixes #2672
=> Add the country's flag infront of it's name in the drop-down in order-form

app/routes/index.js
Preload 18 events in once, at index page.
=> Change default page size to 18 events on landing page

app/templates/components/modals/edit-user-modal.hbs
- Add hidden divider to make a space between modal and button
Makes sure that user.isAdmin is being reflected in radio buttons and the save buttton and modal has some space
Fixes #2761
=> initialise user system role modal using user.isAdmin

app/templates/components/events/view/overview/general-info.hbs, app/templates/components/forms/wizard/basic-details-step.hbs
When clicking on the option to add social links, it takes us to that part of the page.
Fixes #2627
=> Add fragment identifier to scroll to links part of page

app/templates/components/widgets/forms/rich-text-editor.hbs
Currently the editor tools split in different lines for mobile view. This PR makes the editor tools inline for mobile view.
- Use `compact` semantic ui class for buttons in mobile view.
Fixes: #2755
=> Inline editing tools in responsive view.

app/components/settings/password-section.js
=> Changing Allowed Password Length in 'Settings/Password' from 6 to 8

app/templates/components/forms/admin/settings/ticket-fees-form.hbs
There is a typo in fee removal modal, it asks for remove this ticket instead of fee.
- Fix typo
Fixes: #2781
=> Fix typo in fee removal modal prompt.

app/routes/admin/reports/system-logs/activity-logs.js, app/routes/admin/reports/system-logs/mail-logs.js, app/routes/admin/reports/system-logs/notification-logs.js
In the Admin Section in the Logs, it shows the oldest entries first.
- fixed sorting of logs in admin reports section
Fixes #2679
=> fix: sorting of logs in admin reports section

app/templates/components/settings/application-section.hbs
I have removed the div with class `ui action fluid input` as it wasn't needed.
This fixes the visibility of facebook icon in connect with facebook button.
- Add inverted class
Fixes: #2779
=> Fix inconsistency in visibility of facebook icon in connect with facebook button.

app/components/forms/session-speaker-form.js, app/models/speaker.js, app/templates/components/forms/session-speaker-form.hbs
This adds a link-input field for website field in speaker details form.
- Add link input field.
Fixes: #2428
=> Add link input field for website and twitter in speaker details form.

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
Currently the sales end date of tickets doesn't change when the start date of the event is changed to a time earlier than the current time.
- Add an action which makes the sales end date to the event start date when the event is preponed.
Fix/es: #2649
=> Change salesEndDate on event start date change.

app/templates/components/ui-table/cell/cell-roles.hbs
Fixes - #2770
Remove ordering error caused due to hardcoded numbering
- Use sematic UI ordered list class
- Remove hardcoded numbering
=> Fix numerical ordering in user roles in event table

app/templates/admin/content/system-images/list.hbs
Fix Bug in System Images in Admin. Before a blank page appears if a new event topic was created without event subtopic as system images are only for subtopics. Now a text "No records to show" appears.
Fixes #2690
=> Add default text in System Images when no image is present in Admin Panel

app/routes/public/schedule.js, app/templates/public/schedule.hbs
Ensures scheduler view is independent of the timezone it is being viewed from.
=> standardize timezone to UTC on public schedule

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
remove save as draft button from published events
Fixes #2865
=> fix: Remove draft button in published events

app/components/forms/wizard/basic-details-step.js
fixes - #2834
This makes sure that the event's start and end timings are correctly stored
Since the date and time pickers use `startAtDate` and `startAtTime` etc, concatenate them and then set them as startsAt and endsAt attribute
=> updateDates function refactored to apply timezone correctly

app/templates/components/widgets/forms/image-upload.hbs
Makes the user profile form columns begin at the same height.
See discussion in #2513
=> fix: remove unnecessary hidden divider from upload image widget

app/components/widgets/forms/image-upload.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/widgets/forms/image-upload.hbs
Adds a conditional divider between image pickers in mobile mode
Fixes #2513
=> Adds hidden divider between image inputs

app/controllers/admin/content/translations.js, app/controllers/orders/view.js
Fixes the bug which led to files having an inconsistent format while downloading in production.
Fixes #2914
=> Refactor: Use createObjectURL for saving blob as file

app/components/ui-table/cell/events/view/tickets/orders/cell-date.js, app/controllers/events/view/tickets/orders/list.js, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs
Fixes #2938 
It is important for organizers to view tickets according to the date. The Date Column in the Orders and Attendees table is missing though.
- Adds date and time  column to organizer dashboard
- Displays `completedAt` attribute. If its missing `createdAt` attribute is displayed
=> fix: adds date and time column to organizer dashboard ticket section

app/models/event.js
Fixes #2967 
Omits venue if the multiple fields of locations are present else prints the entire address so, city and country is always displayed.
=> fix: Event location display on landing page

app/mixins/custom-form.js, app/models/custom-form.js
Fixes #2981 
Adds instagram and address fields to custom-forms model **[Only for the events created henceforth]**
=> feat: Add instagram & address fields to speaker custom-forms

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #2985 
Ensures empty tax record does not replace the actual tax of the event.
=> fix: display of pre-existing event tax details in edit wizard

app/controllers/public/index.js, app/models/event.js
Sync relationships have the advantage of not returning a proxy object when needed, but then ember expects the tax to be included every time an event record is supplied.
=> enh: Avoid using sync relationship for event-tax

app/templates/public/cfs/edit-session.hbs
Fixes #2991 
Ensures that custom forms are used on edit route of CFS proposal so that the form fields are consistent across the app.
=> Make use of custom forms to edit session proposals on CFS route

app/helpers/order-color.js, app/templates/components/order-card.hbs, app/templates/components/orders/order-summary.hbs, tests/integration/helpers/order-color-test.js
Adds a helper with tests, to compute the colors according to the status of orders to make the color control centralized.
Fixes #3004
=>  feat: create a helper for order status-color

app/components/paypal-button.js
Fixes #2999 
switches functions to arrow functions to retain `this` of the component.
=> Fix: Broken paypal button fixed

app/routes/my-tickets/upcoming/list.js
Fixes #3001 
Adds pending and initializing orders to open orders tab of my-tickets route
=> fix: Show pending orders in my tickets section

package.json, yarn.lock
This dependency was missed in the refactor.
=> Upgrade ember-full-calendar to 1.8.0

app/controllers/events/view/scheduler.js
Fixes #3025 
The scheduler was broken because it required a global jQuery selector.
=> fix:  broken scheduler

app/templates/orders/pending.hbs
Fixes #3037 
Use event currency to determine payment currency.
=> feat: Show appropriate currency in stripe checkout

app/routes/public/cfs/edit-session.js
Fixes #3056 
When user edit the session for proposal, sessions and tracks are not loaded so that user cannot change it
- Adds `tracks` and `sessionTypes` to `edit-session` route
=> fix: tracks and sessionTypes loads on editing session

app/routes/events/view/tickets/discount-codes/edit.js, app/templates/events/view/tickets/discount-codes/edit.hbs
Fixes #3065  
- Removes RSVP hash from the route model
- Fixes the discount code issue
=> fix: pre-fetch event currency to render on edit discount code route

app/templates/components/public/session-item.hbs
Fixes: #3061
This shows the speaker image in the session card in event listing.
- Fix the image url reference.
=> fix: Show speaker image in session card.

app/models/session.js
Fixes: #3071
This fixes the wrong submitted time in sessions
- Correct default value of submitted at in session model.
=> fix: Fix wrong submit time in sessions.

app/templates/components/forms/admin/settings/system-form.hbs
Fixes #3088 
Fixes the UI bug for which the production environment value does not get updated on switching from one environment to another.
- Added `onChange` action
=> fix: Fixed environment switch bug

app/templates/components/public/speaker-item.hbs
Fixes #3043 
Session of the Speaker are not getting listed under Its Heading on Public Pages due to :
- `html-safe` not a helper error
- removes `html-safe` helper
- adds a condition to add a subheading `Microlocation` on speaker-item to increase the understanding.
=> fix: ensures sessions are listed in public/speakers by handling errors

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
- This avoid name changes in the nav bar because the name has been pre loaded
Fixes #2707
This utilises computed property to make sure that user name doesn't change during filling of forms.
=> fix: Refactor buyer name fields in order-form

app/templates/components/event-card.hbs, app/templates/index.hbs
Fixes #3099 
On the front page in the call for speakers section please direct the listed events in that section directly to the "Call for Speakers" page of the event.
=> fix: redirect to event cfs page if clicked on event-card in cfs section

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #2482 , Related to #2920 
The option "use ticketing system" is a nice feature to add events of external websites. The options has been abused though to add spam events. 
- Comments option `use ticketing system`
=> fix: hides 'use ticketing system' to prevent spam

app/templates/components/forms/admin/settings/system/mail-settings.hbs
Fixes #3105 
Ensures that smtp encryptions settings persist, the field was previously not linked to the model.
=> fix: Admin wizard: Persist smtp encryption settings

app/templates/public.hbs
Fixes #2694 
Extra space in Event View Page after External Event Url.
=> Extra space in Event View Page

app/templates/components/settings/danger-zone.hbs
Related to https://github.com/fossasia/open-event-frontend/pull/2924#issuecomment-501006598
Currently, the text displayed when user's account is not deletable is a little vague. 
Updates the text displayed on danzer zone if user's account is not deletable
=> fix: update text if user's account is not deletable

app/templates/components/modals/tax-info-modal.hbs
Fixes #3115 
The tax invoice data of a registered company can only be added if the field "Send Tax Invoice.." is ticked. 
- Made it possible to enter the data even if the field is not ticked.
=> feat: company data possible to be added without ticking 'Send tax invoice'

app/components/explore/side-bar.js, app/templates/components/explore/side-bar.hbs
Fixes #3136 
- Add component level logic for hiding/showing filters
- Toggle filters in small devices.
Two mobile views of the implementation, with and without the filters
=> feat: toggle filters in mobile devices 

app/routes/public/role-invites.js
Fixes #2771 
- Fix transition syntax after the refactor
=> fix: Restructure and update role-invite flow 

app/components/widgets/forms/location-input.js, app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #3149 
Ensures that `searchableLocationName` is populated, when event location is being saved. The data from this field will be later used to list the most common cities.
=> feat: Populate searchableLocationName with event location:

package.json, yarn.lock
Fixes #275 
Uses the latest version (master branch), since the last release was in 2018, a newer one hasn't been released yet.
Please open more specific follow up issues if some buggy scroll behavior is still present.
=> Use latest version (Master branch)  for ember-router-scroll

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
Reference: #3098
This PR adds an additional filter to filter events by ticket type i.e `free` or `paid`.
- Add an accordion in sidebar of explore route with free and paid as options.
- In the js of sidebar, implement action to set `ticket_type` variable.
- In the route of explore, add an `if` block  to check for ticket type params.
=> feat: Add filter to filter events by ticket type.

app/components/ui-table/cell/events/view/sessions/cell-rating.js, app/controllers/events/view/sessions/list.js, app/models/feedback.js, app/models/session.js, app/routes/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs, app/templates/events/view/sessions/list.hbs
Related to #2959 
Implement ratings of sessions by event organizer
- Adds `Rating` column to events/view/sessions table
=> feat: adds star rating to events/view/sessions

app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/widgets/forms/ticket-input.hbs
Fixes #3174 
- The following at least displays ticket price properly in full width of the screen.
- The following is still not a valid solution if width< 786px, For this, we have to make two fields rather than accommodating both inputs in single `Two Fields Div` , But it would break design that's why didn't follow it
=> fix: Increasing Column Width of Price Section

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #3183 
- Made `Ticket Buttons` inline
=> fix: Making Ticket Buttons Inline

app/templates/components/public/ticket-list.hbs
Fixes #3204 
- Removed extra repetition of `Ticket Price`
=> fix: Orientation of Ticket Input

app/components/modals/tax-info-modal.js, app/templates/components/modals/tax-info-modal.hbs
Fixes #3164 
- Introducing Scrolling to disable Overflow caused by `UI Modal`
=> fix: Preventing Overflow 

app/controllers/admin/users.js, app/templates/admin/users/view/account.hbs, app/templates/components/ui-table/cell/admin/users/cell-user-links.hbs
Fixes #3181 
Wrong route is defined for Accounts Link in admin panel of users
Defined the route properly so that admin can see user details
=> fix: Wrong route defined in user accounts for admin

app/templates/components/side-bar.hbs
Fixes #
- Rename Profile to Accounts in User Dropdown for Mobile View #3203
=> mobile view profile changes to account

app/components/modals/tax-info-modal.js, app/templates/components/modals/tax-info-modal.hbs
Fixes #3236 
- After removing `Company Details Tickbox`, We forgot to make these fields optional
=> enh: Making company details optional in tax modal

app/components/tables/headers/sort.js, app/controllers/events/list.js
Fixes #3242 
- initializes sorts beforehand to avoid making params accidentally null.
- Adds date sort support for ember-tables.
=> fix: Date sort support + avoid null sorts comparison

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
Reference: #3098
This adds a new search filter to sidebar of explore route.
- Add a new filter accordion with `open` and `closed` options in sidebar.
- Add a query for cfs.
=> feat: Add CFS filter to sidebar filters in explore route.

app/templates/index.hbs
Fixes #3249 
- Wrong `Query Param` was used for querying , Changed it
=> fix: `Show More Call For Speaker` button fixed

app/components/forms/wizard/basic-details-step.js, app/components/public/ticket-list.js, app/components/widgets/forms/ticket-input.js, app/models/ticket.js, app/templates/components/public/ticket-list.hbs, app/templates/components/widgets/forms/ticket-input.hbs
Fixes #3184 
**When organizer tries to add tickets worth of 0 value**
_________________
**Min max validation checks**
________________
**When the ticket buyer tries to add zero valued donation tickets**
Does not allow donation tickets worth of 0 value to be purchased & adds quantity support
- Added quantity support for donation tickets
- Removed duplicate code segment to prevent price repitition
- Added check to allow donations to be limited to a pre-specified price range (`minPrice` and `maxPrice`)
- Fixed the price update bug by adding price to watchable properties
=> fix: Added quantity, min/max price validations & fixed donations bugs

app/models/ticket.js
**Screenshot**
*22% tax rate (separate fee on top of price)*
_______
Fixes #3259
Resolves the issue with the resultant negative tax popping up due to the non-updation of the ticket price in the computed property
- Added price as a watchable property to update the computed property
=> fix: Fix tax on donation tickets

docs/installation/local.md
=> docs: Get-Text linking error

app/templates/components/forms/orders/order-form.hbs
Fixes #3291
Adds a billing information header to indicate what are the extra fields for.
=> enh: add billing info header to avoid confusion

app/components/forms/login-form.js, tests/acceptance/login-test.js
Fixes #3300 
Refactors the login form according to flask jwt extended related refactor on the server to fix the tests,
and update the syntax in general.
=> fix: Refactor login-form according to flask jwt extended changes

app/components/public/ticket-list.js, app/templates/components/public/ticket-list.hbs
Fixes #3292 
Not sure, why this was broken in the first place, a very obvious fix.
=> fix: Resolve broken discount codes for tax inclusive tickets

app/components/events/view/export/download-zip.js, app/templates/components/events/view/export/download-zip.hbs
Fixes #3293 
Fixes event exports with the help of loader service
Related Server fix:
- Implemented an action to fix downloads & file serving
- Modified component template logic
=> fix: Fix export events module(URL fetch logic)

app/templates/components/forms/orders/order-form.hbs
Fixes #3307 
- Fixing the rendering of `if` clause for gender fields
=> fix: rendering of gender field

app/utils/validators.js
Fixes #3324 
- GitHub Profile allows a single hyphen in the profile.
=> fix: Update GitHub URL Validator

app/controllers/admin/content/translations.js
Fixes #3355
Fixes the URL endpoint which is being hit when downloading the translations
- Restructure code according to ES6 style
- Use `/admin/content/translations/all/` to download files
=> fix: use correct URL to download translations

app/controllers/public/cfs/new-session.js, app/routes/public/cfs/new-session.js, app/templates/components/forms/session-speaker-form.hbs
=> fix: infinite loader on sessions page

app/components/forms/wizard/basic-details-step.js
Fixes #3322 
Adds support for decimal prices for tickets. 
Related server PR for price check:
- Changed validation rule
=> fix: allow decimal values for ticket prices

app/controllers/event-invoice/review.js, app/router.js, app/routes/event-invoice/review.js, app/templates/event-invoice/review.hbs
Fixes #3312
This PR aids in reviewing the invoice before the payment. It includes billing info & related  invoice details .
- Added review routes, controller & templates 
- Added corresponding billing info
=> feat: Implementation of review route for event invoice payment

app/routes/public/role-invites.js
Fixes #3348 
Fixes #3347 
Fixes #3306 
Moves the logic to afterModel, as fastboot doesn't fully support the transition in the beforeModel hook.
=>  fix: prevent fastboot to crash for role-invites acceptance

app/controllers/events/view/sessions/create.js, app/controllers/events/view/sessions/edit.js, app/controllers/events/view/speakers/create.js, app/controllers/events/view/speakers/edit.js, app/models/speaker.js, app/templates/components/forms/session-speaker-form.hbs
Fixes #2953
When a speaker registers they have to enter an email. It must be possible to override this requirement for organizers/admins
- Adds a checkbox to override email while creating speaker from event dashboard
=> feat: Implement a tick box for organizers/admin to override Email

app/components/forms/admin/settings/payment-gateway-form.js, app/models/setting.js, app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Fixes #3364
- Adds stripe test keys to the payment-gateway-form
_Test Keys_
_Live Keys_
=> enh: add stripe test keys to admin payment-gateway-form

app/components/widgets/forms/image-upload.js, app/templates/components/forms/user-profile-form.hbs
Fixes #3360 
Fixes profile picture removal
- Update avatarUrl to None on the model level when the picture gets deleted.
=> fix: profile picture link to null when removed

app/controllers/events/view/sessions/list.js, app/models/user.js, app/routes/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-is-mail-sent.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs, app/templates/events/view/sessions/list.hbs
Fixes #3195 
Adds columns - `| Rating | Avg Rating | No. of ratings |`
- Modified `updateRating` function
- Introduced 2 new columns - `Avg Rating` and `No. of ratings`
=> feat: introduce new columns for session ratings & switch to ember table

app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Fixes #3384 
Blocker: https://github.com/fossasia/open-event-server/pull/6357
This helps in saving the attribute to the DB. This also requires a server change.
=> fix: fix isPaytmActivated attribute save

app/controllers/events/view/tickets/orders/list.js, app/routes/events/view/tickets/orders/list.js, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-date.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs, app/templates/events/view/tickets/orders/list.hbs, tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-amount-test.js, tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
=> feat: implement ember table for tickets/orders table

app/controllers/account/billing/invoices/list.js, app/routes/account/billing/invoices/index.js, app/templates/components/ui-table/cell/events/cell-amount.hbs
Fixes #3393 
Event invoices aren't visible for `all` filter and there are few places to refactor
- fix column fetch for `all` filter
- changed `id` to `identifier` and `Name` to `Event Name`
- display amount alongwith currency
=> fix: event invoice table 'all' filter displays invoices

app/controllers/events/view/tickets/attendees/list.js, app/routes/events/view/tickets/attendees/list.js, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-action.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs, app/templates/events/view/tickets/attendees/list.hbs, tests/integration/components/ui-table/cell/events/view/tickets/attendees/cell-order-test.js, tests/integration/components/ui-table/cell/events/view/tickets/attendees/cell-price-test.js
=> feat: use ember table for tickets/attendees

app/controllers/events/view/tickets/access-codes/list.js, app/controllers/events/view/tickets/discount-codes/list.js, app/routes/events/view/tickets/access-codes/list.js, app/routes/events/view/tickets/discount-codes/list.js, app/templates/components/ui-table/cell/cell-label.hbs, app/templates/components/ui-table/cell/cell-validity.hbs, app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.hbs, app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-url.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-status.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-url.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.hbs, app/templates/events/view/tickets/access-codes/list.hbs, app/templates/events/view/tickets/discount-codes/list.hbs, tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions-test.js
=> feat: access-code & discount-code ember tables

app/routes/event-invoice/paid.js, app/routes/event-invoice/review.js, app/templates/event-invoice/review.hbs
Fixes #3411
Currently, we use filter to get a particular event invoice. Also we are not redirecting request from review to paid even if it is paid
- fix event invoice query
- fix redirection of event invoice
- made minor changes to review page
=> fix: event invoice fetched correctly in review route

app/components/forms/events/view/create-discount-code.js, app/components/forms/wizard/basic-details-step.js, app/components/forms/wizard/sessions-speakers-step.js, app/components/widgets/forms/date-picker.js, app/components/widgets/forms/time-picker.js, app/models/access-code.js, app/models/discount-code.js, app/models/event.js, app/models/session.js, app/models/speakers-call.js, app/models/ticket.js, app/routes/events/view/tickets/discount-codes/create.js, app/templates/components/forms/events/view/create-discount-code.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/widgets/forms/date-picker.hbs, app/templates/components/widgets/forms/time-picker.hbs, app/utils/computed-helpers.js, app/utils/dictionary/date-time.js
Fixes #3020
Fixes #3382 
Fixes #2077
Fixes #2366 
Fixes #2972
=> fix: resolve whack-a-mole behavior of time/date pickers & add validations to date-time

app/components/paypal-button.js, app/templates/event-invoice/review.hbs, app/templates/orders/pending.hbs
Fixes #3313 
Server PR: https://github.com/fossasia/open-event-server/pull/6296
Integrates the paypal payment component with event invoice workflow. 
https://drive.google.com/file/d/14Je8183BW4wgToQJCihp7C_k0MScbBjA/view?usp=sharing
- Replaces semantic UI button with existing PayPal-component with logic
- Refactors component to work with event invoices
=> feat: integrated payment component for event invoice

app/controllers/events/view/sessions/list.js, app/routes/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-rating.hbs, app/templates/events/view/sessions/list.hbs
Fixes #3436 
Currently pagination, sorting, searching weren't working.
- Fixes pagination, sorting and searching issue
- This PR will be default fix any other issues mentioned in the issue description
=> fix: pagination, searching, sorting in events/session table

app/controllers/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-session-title.hbs
Fixes #3449  
Sometimes, while viewing/editing/deleting a session, unexpected entries are passed as params. Fix it using extraRecords
=> fix: uses refreshModel to refresh session table after an action

app/models/setting.js
=> fix: Saving stripe client test id

app/components/modals/paytm-otp.js, app/components/modals/paytm-payment-options.js, app/controllers/orders/pending.js, app/templates/components/modals/paytm-otp.hbs, app/templates/components/modals/paytm-payment-options.hbs, app/templates/orders/pending.hbs
Fixes #3446
Add PayTM modal designs. 
(actions will be linked once server PR has been completed)
- PayTM payment options modal created
- OTP entering modal prepared simultaneously
=> feat: Design PayTM gateway modals

app/components/forms/wizard/basic-details-step.js, app/controllers/orders/pending.js, app/models/event.js, app/models/setting.js, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/orders/pending.hbs
Fixes #3464 
Due to computed properties which were named incorrectly, the alipay workflow was buggy. Now, it functions as expected.
- Fixed naming conventions for controller actions to make it compatible with server schema
=> fix: Fixed alipay workflow & naming

app/templates/components/forms/orders/order-form.hbs
=> fix: omise image optimisation

tests/integration/components/modals/paytm-otp-test.js, tests/integration/components/modals/paytm-payment-options-test.js
Fixes #3468 
Add integration tests for paytm modals\
=> test: add integration tests for paytm modals

.env.example
Fixes #3530 
The link to the open-event-server (API_HOST) is updated to connect to the server at heroku.
API_HOST in .env.example updated from http://localhost:5000 --> https://open-event-api-dev.herokuapp.com/
=> fix: update .env.example to run server on heroku

app/controllers/events/view/tickets/attendees/list.js
Fixes #3477 
- Now the overlapping problem is solved in the Event Dashboard.
=> fix: Fix overlapping columns in event dashboard

app/controllers/events/view/speakers/list.js
Fixes #3483
Added sort button to speakers Table
=> fix:add sort options to Speakers Table

.travis.yml
=> fix: CodeCov for the repository

app/templates/components/public/ticket-list.hbs
=> fix: Hotfix for non-rendering paymentCurrencies

docs/installation/local.md
Fixes #3560
Updates the documentation to reflect the change to the default `.env.example` file which now points to Heroku and not localhost.
- Update Local.md doc to reflect changes to default config
-
-
=> docs: Update Docs to Reflect Change to .env.example

app/utils/validators.js
Fixes #3528 
RegExp for URLs improved to allow acceptance of localhost or 127.0.0.1 URLs in Admin settings.
=> fix: Improve RegExp for URLs in Admin settings

app/routes/public/cfs/new-speaker.js
Fixes #3585 
In total, all custom fields related to an event  (speaker custom fields + session custom fields + attendee custom fields) can have a size of 55, while we only fetch 50, which causes us to lose some fields rendering from server.
- Changed it to 0, to render all custom fields associated with that event.
=> fix: Increase page[size] to render all form fields.

app/templates/components/ui-table/cell/cell-simple-buttons.hbs
Fixes #3578 
- Changing view of button vertical for mobile view and horizontal for desktop.
=> fix : improving arrangement of button in table

app/templates/components/explore/side-bar.hbs, app/templates/components/forms/admin/settings/system/mail-settings/test-email-form.hbs
Fixes #3574 
previosly it was showing like this - 
after fixing the issue it is -
for mobile device -
for pc -
=> fix : Send test email box is showing properly  in mobile also

app/controllers/index.js
Fixes #3544
There was a reference to an undefined variable "event_name" in app/templates/index.hbs which this PR fixes it by assigning a value of null to it in "app/controllers/index.js"
The variable "name" in app/controllers/index.js was changed to "event_name" for a better reference
-
-
-
=> fix: changed variable "name" to "event_name"

app/components/forms/wizard/basic-details-step.js
Start date & time should be before End date and time
Fixes #3568
previously message was showing "Start date & time should be after End date and time" so i chage it to Start date & time should be before End date and time .
=> fix : error message in crete event date section
