app/controllers/orders/new.js
Fixes #2945
- add a order.user.save() method to save the user model
=> fix: Save user details in order confirmation step

app/components/forms/events/view/create-discount-code.js, app/routes/events/view/tickets/discount-codes/create.js, app/templates/components/events/view/overview/event-tickets.hbs, app/templates/components/forms/events/view/create-discount-code.hbs, app/templates/events/view/tickets/discount-codes/create.hbs, tests/integration/components/events/view/overview/event-tickets-test.js
=> Refactor: Update model hooks and parse event currency where required.

app/controllers/public/index.js, app/models/event.js, app/routes/orders/new.js, app/routes/orders/placed.js, app/routes/orders/view.js, app/templates/components/orders/order-summary.hbs
=> fix: amend broken order tax flow

app/components/ui-table/cell/cell-event-general.js, app/controllers/events/list.js, app/templates/components/ui-table/cell/cell-event-general.hbs, app/templates/events/list.hbs, tests/integration/components/ui-table/cell/cell-event-general-test.js
Fixes #2947
Places the action buttons in the front row in horizontal alignment and improved logic as requested.
=> fix: realign event list action buttons 

app/routes/orders/pending.js
This file was deleted in the refactor during #2946
=> Restore pending order route file

app/components/ui-table-server.js
Fixes #2996 
Fix all the tables broken after refactor in #2946
=> Fix: Restore search,sorting,pagination in ember-tables after refactor

app/templates/admin.hbs, app/templates/events.hbs, app/templates/events/view.hbs
=> UI: Reduce excessive use of containers :: admin,events,overview

package.json, yarn.lock
Fixes #3006 
Restores live-reload functionality of the app.
=> chore: Restore livereload in app

app/utils/computed-helpers.js
=> fix: Disabling the addition of one extra day in EndAtDate

app/routes/public/cfs/index.js
Fixes #3016 
- Changed the access method to `transition.params`
=> fix: Speakers Call Page fix

app/routes/public/cfs/index.js
Reverts fossasia/open-event-frontend#3029
=> Revert "fix: Speakers Call Page fix"

app/components/forms/wizard/basic-details-step.js, app/mixins/event-wizard.js
=> Fix stripe

app/routes/public/cfs/index.js
Access params in CFS Correctly.
=> Fix CFS : define params

app/components/explore/side-bar.js, app/templates/components/explore/side-bar.hbs
Fixes #2171 
- This replaces the static google map with an updatable one, along with a location change handler. 
- Added `onLocationChangeHandler`
- Passed dynamic longitudes and latitudes
=> fix: Replaced a static Google Map component with a dynamic one

app/components/create-session-message.js
Fixes #3039
This resolves the issue for rejected promises occurring due to the access to cfs page for a given event.
=> fix: fixed rejected promise for cfs(unauthenticated users)

app/routes/verify.js
Partially Fixes #3026 and fixes fossasia/open-event-server#5969
This fixes the token access of the verify route.
=> fix: update beforeModel transitions

app/components/forms/events/view/create-access-code.js, app/components/forms/events/view/create-discount-code.js
Fixes #3062 
Similar to scheduler, we were using imported jquery and thus the validation form wasn't working.
- use global jquery
=> fix: use global jquery for form validation

app/controllers/orders/new.js, app/controllers/orders/pending.js, app/helpers/payment-icon.js, app/templates/components/orders/ticket-holder.hbs, app/templates/orders/new.hbs, app/templates/orders/pending.hbs, app/templates/orders/view.hbs
Fixes #2912 
- Show card details if payment is via stripe
- Show Paypal Transaction details if payment is via Paypal
- Add loading state
- Change the location of download invoice and tickets buttons
=> feat: Order wizard refactor -- Smoothen the process, introduce loading state

app/templates/components/forms/session-speaker-form.hbs
=> fix: Required Fields in Session-Speaker Form

app/routes/notifications/all.js, app/templates/notifications/all.hbs
Fixes #2976 
Adds pagination to notifications.
=> feat: Implement pagination on notifications route

app/templates/events/view/scheduler.hbs
Fixes #2600
**Before :-**
**After :-**
=> fix: Fixing Scheduler View in Small Screens

app/routes/my-tickets/past.js, app/routes/my-tickets/upcoming/list.js, app/templates/my-tickets/past.hbs, app/templates/my-tickets/upcoming/list.hbs
Fixes #2584 
Implements pagination(via lazy load on all routes of my tickets section)
=> Add pagination on my-tickets route

app/controllers/orders/pending.js, app/templates/orders/pending.hbs
Fixes #2859 
Provides a basic mechanism for dealing with omise payments.
Note : server to frontend redirection is missing
=> feat: add initial mechanism for omise

app/routes/my-sessions/list.js, app/templates/my-sessions/list.hbs
Fixes #3084 
- Implemented Infinity Model on My Sessions Page.
- Fixed the missing of `Past Sessions` due to query order
=> feat: Infinity Lazy Loading on My Sessions Page

app/templates/components/forms/admin/settings/system/storage-option.hbs
Fixes #1803 
Resolves the issue where the server did not respect the user's choice while selecting storage.
=> fix: Make storage location names compatible with server

app/components/order-card.js, app/templates/components/order-card.hbs, tests/integration/components/order-card-test.js
Fixes #3027 
There is no way to see if a ticket is checked in or not. 
- Shows tickets as status "Checked In" on the my-ticket page
=> feat: Mark checked in ticket as 'Checked In' on my-ticket page

app/components/forms/session-speaker-form.js, app/models/speaker.js, app/templates/components/forms/session-speaker-form.hbs
Fixes #3106 
- Added URL Trimming for twitter URL, As before speaker was needed to enter full Profile URL with https protocal
=> feat: URL Trimming for Twitter URL

app/templates/components/events/view/overview/event-tickets.hbs, app/templates/components/events/view/overview/manage-roles.hbs, app/templates/events.hbs, app/templates/events/view/tickets/index.hbs, app/themes/semantic.js
Partially Fixes #697 and #2927 
1.)For Table Space :- 
2.)For Irresponsive Tables :-
=> fix: Less Table Space Consumption and Fixing Loose Tables on Small Screen

tests/helpers/custom-helpers.js
Fixes #3022
**Passing builds:**
- https://travis-ci.org/fossasia/open-event-frontend/builds/546310835
- https://travis-ci.org/fossasia/open-event-frontend/builds/546324539
- https://travis-ci.org/fossasia/open-event-frontend/builds/546324530
=> fix: Wait for the app to settle after login and logout.

app/components/events/view/overview/event-tickets.js, app/templates/components/events/view/overview/event-tickets.hbs, tests/integration/components/events/view/overview/event-tickets-test.js
Fixes #3070 
- Modify component to minimize template level logic
=> fix: add placed orders in tickets overview 

app/components/forms/admin/settings/system/mail-settings/test-email-form.js, app/templates/components/forms/admin/settings/system/mail-settings.hbs, app/templates/components/forms/admin/settings/system/mail-settings/test-email-form.hbs, tests/integration/components/forms/admin/settings/system/mail-settings/test-email-form-test.js
=> Add test mail functionality in admin settings

app/routes/account/billing-info.js, tests/acceptance/billing-info-test.js, tests/acceptance/invoices-test.js, tests/acceptance/payment-info-test.js
Fixes #3166 
Fixes the route access bug for billing info in account settings.
- Implemented `AuthenticatedRouteMixin` for billing route
- Added Title Token
=> fix: Title Token & Implemented mixin for billing route

app/templates/components/events/view/overview/event-setup-checklist.hbs
Fixes #3175 and #3188 
- adds attendee form to the event checklist
=> feat: Add attendee form step in event checklist

app/templates/components/forms/wizard/attendee-step.hbs
Fixes #3189 
- Added `Description` about `Attendee Form`
=> feat: Adding general description of attendee form

app/templates/components/forms/orders/attendee-list.hbs
=> fix: Unmute order details text

app/templates/components/public/ticket-list.hbs
Fixes #3238
- Made it compatible for mobile view
=> fix: Making Ticket List compatible with mobile view

app/templates/components/forms/orders/order-form.hbs
=> feat: make billing fields mandatory for paid orders

package.json, yarn.lock
=> chore: Gettext fix

app/components/forms/wizard/basic-details-step.js
Fixes #3254 
- Showing `Payment Information` in case for `Donation Tickets` too.
=> fix: Showing `Payment Options` for `Donations` 

tests/integration/components/forms/login-form-test.js, tests/integration/components/forms/register-form-test.js, tests/integration/components/forms/reset-password-form-test.js, tests/integration/components/forms/user-payment-info-form-test.js, tests/integration/components/forms/user-profile-form-test.js
Fixes #3282 
Adds multiple integration tests for forms
=> test: Add integration tests for multiple forms

app/adapters/discount-code.js
=> feat: Add adapter for discount codes to fetch them by event ID

app/components/forms/admin/settings/billing.js, app/controllers/admin/events/list.js, app/controllers/admin/users/list.js, app/controllers/admin/users/view/events/list.js, app/templates/admin/users/view/events.hbs, app/templates/components/forms/admin/settings/billing.hbs
Fixes #3315 
- Added missing labels.
- Added missing validations.
- Fix the resizing of tables
- Removed Extra Spaces in code file
=> enh: Minor bugs and enhancements in admin area

app/templates/public/index.hbs
=> fix: Pass event object to ticket list correctly

app/adapters/access-code.js, app/components/public/ticket-list.js
=> feat: Add adapter for access codes to fetch them by event ID

app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
=> fix: Remove not-ready-to-use relationship calls in admin users

app/components/forms/session-speaker-form.js, app/models/custom-form.js, app/models/session.js, app/models/speaker.js, app/templates/components/forms/session-speaker-form.hbs
Fixes #3332 
Fixes #2552 
Declutters custom forms to some extent, 
reintroduces some validations, and smoothens the flow.
=> fix: Revamp session-speaker custom forms, fix URLs

app/components/forms/session-speaker-form.js, app/models/custom-form.js, app/models/session.js, app/models/speaker.js, app/templates/components/explore/side-bar.hbs, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/public/event-map.hbs, app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs, app/utils/validators.js
Contains hot fixes for session-speaker forms.
=> Release v1.2.2

app/templates/orders/pending.hbs
Fixes #3343
- Remove duplicate buttons
- Change button positions for Alipay, Omise
=> fix: change button positions and take out repeating buttons

app/templates/components/forms/orders/order-form.hbs
=> fix: Added missing validation for country

package.json, yarn.lock
=> fix: fix broken google analytics in fastboot

app/utils/dictionary/payment.js
Fixes #3380 
- Add PayTM currency inclusion status
=> feat: add paytm accepted currencies

app/controllers/account/billing/invoices/list.js, app/templates/components/ui-table/cell/events/cell-action.hbs
Fixes #3401
- Add action column in invoice table
=> feat: link invoices to respective pages

app/routes/application.js
=> feat: add try catch block to await in application route

app/components/forms/user-payment-info-form.js
=> fix: avoid multiple success message in accounts

app/components/forms/admin/settings/billing.js
=> Fix: multiple success message in admin/billing

app/controllers/event-invoice/paid.js
Fixes #3408 
Paid event invoice page's download invoice button has been made functional.
**Demonstration GIF** :
=> feat: add invoice download action

app/controllers/events/view/edit/attendee.js, app/controllers/events/view/edit/sessions-speakers.js, app/controllers/events/view/edit/sponsors.js, app/mixins/event-wizard.js
Fixes #3409 
- add 'tickets' property to be fetched if not present
=> fix: tickets fetched at each step of wizard

app/controllers/admin/sessions/list.js
=> fix: add sort options to admin sessions

app/components/forms/admin/settings/system-form.js, app/models/setting.js, app/templates/components/forms/admin/settings/system-form.hbs
=> feat: add static domain fields to admin settings

app/templates/events/view/tickets/index.hbs
=> fix: Solving Ticket Sales ambiguity

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: Problem with time selector after TimeZone

app/controllers/account/billing/invoices/list.js, app/routes/account/billing/invoices/list.js, app/templates/account/billing/invoices/list.hbs
Fixes #3472 
The pagination/searching/sorting in event invoice table in billing info isn't working
- change searching to `status` attribute as there is no other searchable attribute
- add sort options to status and amount
- fix pagination by passing correct data in the list template
=> fix: pagination/searching/sorting in billing invoice table

app/templates/components/side-bar.hbs
Fixes #3526 
Profile Tab on mobile now opens the required Profile page.
=> fix: Nav Bar - Profile Tab works in Mobile View

app/templates/components/ui-table.hbs
Fixes #2797 
The dropdown is not bounded by the ticket table.
=> fix: Dropdown in Add Order section Fixed

app/templates/orders/view.hbs
=> chore(ui): Rename and changing icon for print invoice

yarn.lock
=> chore(deps): Updating caniuse and related dependecnies

app/components/forms/admin/settings/billing.js, app/components/forms/user-payment-info-form.js, app/controllers/my-sessions/view.js, app/controllers/my-tickets/past.js, app/controllers/my-tickets/upcoming.js
=> chore: Migrate my-session, ticket and billing forms to ES6

README.md
Fixes #3623
Fixed front end deployment link in README.md.
=> fix: front-end deployment link

app/templates/events/view.hbs
Reverts fossasia/open-event-frontend#3601
=> Revert "fix: fixing weird vertical shift in event dashboard"

app/routes/admin/events/index.js, app/templates/admin/events.hbs
=> fix: Changing tab order and routes

app/models/event.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/public/index.hbs
=> fix: Removing isTicketingEnabled from events

app/helpers/is-input-field.js
Reverts fossasia/open-event-frontend#3567
Fixes #3674
=> Revert "fix: added check for required-fields and rendering gender"

app/controllers/orders/pending.js
=> fix: Displaying more informative error on Stripe Failure

app/components/forms/orders/attendee-list.js, app/templates/orders/view.hbs
=> fix: Removing Billing Info if not filled from the Order Dashboard

app/routes/my-sessions/list.js
=> fix: Past sessions rendering multiple times

app/templates/components/forms/wizard/sessions-speakers-step.hbs
=> chore: reveal the custom widget form

app/templates/components/nav-bar.hbs
=> fix: appname for mobile screen

app/routes/public/cfs/new-session.js
=> fix: Track field not rendering due to page size limit

app/controllers/events/view/edit/attendee.js, app/controllers/events/view/edit/basic-details.js, app/controllers/events/view/edit/sessions-speakers.js, app/controllers/events/view/edit/sponsors.js
=> hotfix: Reverting forms controller to ES5

app/templates/components/forms/session-speaker-form.hbs
=> fix: Remove email-override condition model hook for organiser

app/templates/components/forms/session-speaker-form.hbs, app/templates/events/view/sessions/create.hbs, app/templates/events/view/speakers/create.hbs
=> fix: Speaker & Sessions can be added from dashboard

app/components/forms/wizard/basic-details-step.js, app/templates/public/index.hbs, app/torii-providers/stripe.js
=> fix: Stripe working on test & development mode

app/templates/events/view/sessions/edit.hbs, app/templates/events/view/speakers/edit.hbs
=> fix: defining event hook in edit speaker/session route

app/utils/file.js
=> fix: Updating file signatures for extended jpeg support

app/routes/events/view/sessions/create.js, app/routes/events/view/sessions/edit.js, app/routes/events/view/speakers/create.js, app/routes/events/view/speakers/edit.js, app/routes/public/cfs/edit-session.js, app/routes/public/cfs/edit-speaker.js
=> fix: Missing fields in session/speaker cluster

app/components/forms/orders/order-form.js, app/components/widgets/forms/billing-info.js, app/routes/events/view/sessions/create.js, app/routes/events/view/sessions/edit.js, app/routes/events/view/speakers/create.js, app/routes/events/view/speakers/edit.js, app/routes/public/cfs/edit-session.js, app/routes/public/cfs/edit-speaker.js, app/utils/file.js
- Solving the Speaker & Sessions fields disappearance.
=> chore: Release 1.8.1

app/templates/components/forms/session-speaker-form.hbs
Refers #3739 
- One of the reason for submission error can be links getting submitted to server without the protocol of website .
=> fix: URL Fields are segmented without protocol

app/models/custom-form.js, app/models/speaker.js
=> fix: Introducing Instagram URL in speaker model

app/templates/components/forms/session-speaker-form.hbs
Fixes #3799 
reference :https://semantic-ui.com/modules/dropdown.html#selection
=> fix: validation working for gender and country

app/templates/account.hbs, app/templates/account/profile.hbs
=> fix: Place unverified user message above the segment in account route

.gitignore
=> chore: Ignore the OS-X Trash

app/components/forms/events/view/create-access-code.js
=> fix: AccessURL generated is fixed

app/controllers/admin/events/list.js
=> fix: Send refreshModel after deletion of event

app/components/forms/orders/order-form.js
=> fix: country rendering in attendee form

app/controllers/public/index.js, app/routes/public/index.js, app/templates/public/index.hbs
=> fix: Fetch only featured speakers on event public page

app/routes/public/speakers.js, app/templates/public/speakers.hbs
=> fix: Implement infinityLoader for event speakers

package.json, yarn.lock
=> chore: Remove ember-cli-geo

config/targets.js
Blocking all dependency PRs like https://github.com/fossasia/open-event-frontend/pull/3859 due to https://github.com/babel/ember-cli-babel/issues/316
=> chore: Update brower targets

package.json, yarn.lock
Reverts fossasia/open-event-frontend#3872
=> Revert "chore(deps-dev): bump semantic-ui-ember from 3.0.3 to 3.0.4"

config/environment.js
=> fix: Add omise cdn in CSP

package.json, yarn.lock
=> chore: Pin semantic-ui-ember to 3.0.3

app/services/l10n.js, config/environment.js, package.json, yarn.lock
=> fix: Revert ember-l10n to 3.2.1

.travis.yml, scripts/test_fastboot.sh
=> chore: Add basic test for fastboot

package.json, yarn.lock
Reverts fossasia/open-event-frontend#3950
Fixes #3986
=> Revert "chore(deps-dev): bump ember-data from 3.14.1 to 3.16.0"

tests/integration/helpers/payment-icon-test.js
=> test: Addition of paymentIcon Helpers Test

app/templates/events/view/settings.hbs, app/templates/events/view/tickets/index.hbs
=> feat: Improving layout of Event Settings Page

app/controllers/admin/users/view/events/list.js
=> fix: Event Identifier getting shown in Admin/User/Event

app/templates/components/account/danger-zone.hbs
=> enh: improved danger-zone layout

app/templates/events/view/tickets/index.hbs
=> fix: adding tickets-type field in table

app/templates/components/forms/events/view/create-access-code.hbs, app/templates/components/forms/events/view/create-discount-code.hbs
Fixes #4050 
reference : https://www.npmjs.com/package/ember-cli-clipboard/#actions
```
The following clipboard.js custom events are sent as actions
success sent on successful copy
error sent on failed copy
```
=> fix: fixed create discount page

app/templates/components/public/session-item.hbs, app/templates/components/public/speaker-item.hbs
Refers #3650
- Removing Microlocation and additional details which can be covered in session item
=> fix: Removing microlocation from speaker item

app/controllers/events/import.js, app/routes/events/import.js, app/templates/components/events/imports-history-section.hbs, app/templates/events/import.hbs
=> feat: Restoring import events section

ember-cli-build.js
Signed-off-by: kushthedude <kushthedude@gmail.com>
Fixes #4119
=> fix: Make app compatible with latest auto-prefixer

app/templates/orders/view.hbs
=> fix: order buttons alignment on small screens

package.json, yarn.lock
Reverts fossasia/open-event-frontend#4157
See https://github.com/emberjs/data/issues/7074
=> Revert "chore(deps-dev): bump ember-data from 3.14.1 to 3.16.2"

app/mixins/event-wizard.js
=> fix: Handle error on event save property null

app/templates/components/orders/organizer-info.hbs, app/templates/components/public/side-menu.hbs
=> fix: Organizer Heading in Ticketing Page

translations/fr.po
Fixes #
- completed the french translation
-
-
=> chore: Complete french translation

README.md
=> chore(README): fix minor typo and URL

config/environment.js, package.json, yarn.lock
=> chore: Disable CSP

app/templates/application.hbs
=> chore: Use defaultClass instead of classPrefix

app/templates/account/billing/invoices/list.hbs
=> revert: Angle bracket syntax for table

config/environment.js, package.json, yarn.lock
Related https://github.com/fossasia/open-event-theme/commit/a132b4d2448cce5eb11585700cb509978371b90f
=> chore: Use new theme package and npm

config/environment.js, config/optional-features.json, ember-cli-build.js, package.json, yarn.lock
See #3872 #3902 
#3901 and #3935 are issue with core semantic UI
They moved some icons to brand icons, and just "forgot" to add CSS for them. Let me see if it is fixed in fomantic UI or not. Else, it'll need to be fixed manually
=> chore: Upgrade semantic-ui-ember to 3.0.4

package.json, yarn.lock
=> chore(deps): Remove resolutions

ember-cli-build.js, package.json, yarn.lock
=> chore: Remove remaining bower packages

docs/installation/local.md
=> docs(installation): fix typo

docs/installation/local.md
I was update the installation link of Watchman page. because that is not found in old file.
=> fix: Update in local installation file

app/components/forms/wizard/basic-details-step.js, app/mixins/event-wizard.js
=> fix: Support adding tax to created events

app/components/public/ticket-list.js, app/controllers/public/index.js, app/templates/components/public/ticket-list.hbs
=> feat: use new create-order API

app/models/order.js
=> fix: Make discount code ID read only

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs
=> fix: Empty session added on toggling add session

app/routes/events/view/edit.js
=> fix: remove module from event edit route

app/templates/components/footer-main.hbs
Fixes #4612
Improved footer as per issue description
=> feat: improve footer

app/templates/events/view.hbs
=> feat: make event dashboard buttons colorful

app/mixins/event-wizard.js
Fixes bug in #4692 
More details in https://github.com/fossasia/open-event-frontend/issues/4608#issuecomment-669168129
=> fix: Handle absence of deleted tickets in mixin

app/controllers/orders/new.js, app/controllers/orders/view.js, app/controllers/public/cfs/edit-session.js, app/controllers/public/cfs/edit-speaker.js, app/controllers/public/cfs/new-session.js, app/controllers/public/cfs/new-speaker.js, app/mixins/notifications.js
=> chore: Add more console errors

app/routes/events/view/scheduler.js
Fixes #4729 
FullCalendar threw errors for single day events
seg is undefined for single day events as i > seg.length due to some logical error
=> fix: Patch FullCalendar to show single day events

app/controllers/events/view/scheduler.js, app/routes/events/view/scheduler.js, app/templates/events/view/scheduler.hbs, app/utils/text.ts
=> feat: Add filtering option to unscheduled sessions

app/components/schedule.ts, app/components/scheduler/unscheduled-session.js, app/utils/color.ts
=> feat: Change text color based on session color lightness

app/components/public/session-item.js, app/helpers/general-date.js, app/templates/components/public/session-item.hbs
=> fix: Session list date format with timezone

app/routes/public/schedule.js
=> fix: Show all sessions in public section

app/styles/pages/public-event.scss, app/templates/components/public/sponsor-item.hbs
=> fix: show sponsors logo in same size

app/routes/public/speakers.js, app/templates/components/public/speaker-item.hbs
=> fix: Filter deletion sessions from speaker list

app/routes/public/cfs/index.js
=> fix: Remove CFS transition from fastboot

app/components/forms/wizard/basic-details-step.js
=> fix: Prefill ticket fields in wizard

app/styles/components/extras.scss, app/templates/public.hbs
=> fix: Enhance filter opacity and color

app/templates/components/public/side-menu.hbs, app/templates/public/index.hbs
=> feat: Add menu tab Sponsors

package.json, yarn.lock
=> fix: Revert ember-source to 3.20.3

app/components/forms/wizard/attendee-step.js, app/templates/components/forms/wizard/attendee-step.hbs, app/templates/components/forms/wizard/custom-forms/table.hbs
=> feat: Separate required and optional attendee fields

app/router.js, app/templates/components/public/side-menu.hbs
=> feat: change session to schedule & schedule to calendar in URL

app/templates/components/events/view/overview/event-setup-checklist.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4936
add wizard step 2 to event checklist
=> feat: show addition information step in event checklist

app/components/forms/wizard/other-details-step.js, app/components/widgets/forms/link-input.js, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/components/widgets/forms/link-input.hbs, app/utils/computed-helpers.js
=> fix: Revert LinkInput changes

app/templates/components/footer-main.hbs
**Description**
Fixed links in Footer Column - Plan Events
Fixes #4961 
Updated the links in "Plan Events" of the footer column.
=> fix: Links in Footer Column - Plan Events

app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: adding allowClear to make fields null again

app/adapters/event.js, app/controllers/index.js, app/routes/index.js, app/templates/index.hbs
=> fix: Add more constraints for upcoming events

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs, app/templates/public/index.hbs
Reverts fossasia/open-event-frontend#4883
=> Revert "fix: page scroll with URL hash redirection."

app/templates/components/forms/wizard/basic-details-step.hbs
=> chore: Stripe authentication message in basic-details step

app/components/widgets/forms/rich-text-editor.js, app/templates/components/widgets/forms/rich-text-editor.hbs
=> fix: adding line break for formating error 

app/styles/components/track-item.scss, app/templates/public/sessions.hbs
=> feat: add verticle timeline

app/templates/pricing.hbs
Fixes #5004 
Add more details to pricing table.
=> chore: Add more details to pricing and fix spelling

app/styles/components/track-item.scss, app/templates/public/sessions.hbs
Reverts fossasia/open-event-frontend#5002
=> Revert "feat: add verticle timeline"

app/templates/pricing.hbs
=> Adding missing table rows

app/components/widgets/forms/rich-text-editor.js, app/controllers/admin/content/pages.js, app/routes/pages.js
=> fix: Admin Pages Content

app/templates/components/forms/wizard/sessions-speakers-step.hbs
=> chore: Change "Microlocations" to "Microlocations or Virtual Online Rooms"

app/templates/components/public/ticket-list.hbs
Refers https://github.com/fossasia/open-event-frontend/issues/5036
Related API PR-> https://github.com/fossasia/open-event-server/pull/7254
=> fix: show refund policy button only if its present

app/templates/components/public/sponsor-list.hbs, tests/integration/components/public/sponsor-list-test.js
=> fix: Remove sponsor header from list

app/helpers/payment-icon.js, tests/integration/helpers/payment-icon-test.js
=> fix: Display card image correctly

app/controllers/public/cfs/edit-session.js
=> fix: Redirect to session details after edit

app/models/setting.js, app/templates/components/forms/admin/content/social-links-form.hbs
=> fix: Convert gitter and telegram links to normal input

app/components/schedule.ts
=> fix: Remove timeline day from calendar

app/templates/pricing.hbs
=> chore: Update fee percentage

app/templates/components/public/social-links.hbs
=> fix: Social link icon indentation

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes # -Discussed in the meeting
=> fix: start date in event wizard causing error

app/templates/components/widgets/forms/ticket-input.hbs
=> fix: fixing error with the price of donation ticket

app/templates/components/widgets/forms/ticket-input.hbs
Reverts fossasia/open-event-frontend#5148
Fixes #5169
=> Revert "fix: fixing error with the price of donation ticket"

app/mixins/event-wizard.js
=> fix: Deleted ticket publish prevention logic

app/mixins/event-wizard.js
=> fix: Return false if no deleted ticket

app/controllers/account/billing/invoices/list.js, app/models/event-invoice.js, app/routes/account/billing/invoices/list.js, app/templates/components/event-invoice/invoice-summary.hbs, app/templates/event-invoice/review.hbs
For https://github.com/fossasia/open-event-frontend/issues/5127
=> fix: Use issued-at for event invoice

app/components/forms/wizard/sessions-speakers-step.js
=> fix: listing privacy shows error in wizard

app/templates/event-invoice/paid.hbs, app/templates/event-invoice/review.hbs
=> fix: change print invoice to download invoice

package.json, yarn.lock
=> fix: Revert to ember 3.20.3

app/components/ui-table/cell/admin/sales/invoice-user.hbs, app/controllers/account/billing/invoices/list.js, app/controllers/admin/sales/invoices.js, app/routes/account/billing/invoices/list.js
=> feat: Allow admin to see any user's invoice

app/templates/components/forms/wizard/sessions-speakers-step.hbs
on changing time it was showing error like wizard step 1 previously. 
on updating -
=> fix: time error fix in wizard step 5

app/templates/components/modals/add-user-role-modal.hbs
=> fix: can send more than one invite

app/models/event.js
=> fix: Don't check authCode for stripe connection

package.json
=> chore: Pin node version to 12.x

translations/hi.po
Currently translated at 6.5% (97 of 1479 strings)
Translation: Open Event/Open Event Frontend
Translate-URL: https://hosted.weblate.org/projects/open-event/frontend/hi/
=> chore: Translated using Weblate (Hindi)

translations/de.po
Currently translated at 24.6% (364 of 1479 strings)
Translation: Open Event/Open Event Frontend
Translate-URL: https://hosted.weblate.org/projects/open-event/frontend/de/
=> chore: Translated using Weblate (German)

app/routes/public/cfs/index.js
=> fix: Recursively look for route params for private CFS

app/services/l10n.js, app/utils/loader.ts, config/environment.js, ember-cli-build.js
=> fix: Set moment locale according to chosen language

app/controllers/events/view.js, app/controllers/events/view/index.js, app/controllers/events/view/scheduler.js, app/controllers/events/view/sessions.js, app/controllers/events/view/sessions/create.js, app/controllers/events/view/sessions/edit.js, app/controllers/events/view/settings.js, app/controllers/events/view/speakers.js, app/controllers/events/view/speakers/create.js, app/controllers/events/view/speakers/edit.js, app/controllers/events/view/speakers/list.js, app/controllers/events/view/tickets/access-codes/list.js, app/controllers/events/view/tickets/attendees.js, app/controllers/events/view/tickets/attendees/list.js, app/controllers/events/view/tickets/discount-codes/list.js, app/controllers/events/view/tickets/order-form.js, app/controllers/events/view/tickets/orders.js, app/controllers/events/view/tickets/orders/list.js
related https://github.com/fossasia/open-event-frontend/issues/4174
=> chore: console log more errors

.travis.yml, Dockerfile, netlify.toml, package.json
=> chore: Upgrade to node 14.x

app/services/l10n.js
=> fix: Correctly load detected moment locales

app/routes/events/view/tickets/attendees/list.js
Fixes #5548 
Organizer can search attendee information on the basis of first name, last name and email.
=> fix: attendee page search

ember-cli-build.js
=> chore: Disable CSS sourcemaps in prod

app/components/public/sponsor-list.hbs
The intermediate simple solution is not good enough
=> fix: Keep number of sponsor columns constant

app/templates/components/forms/orders/order-form.hbs
Fixes #5645 
change the billing information icon which same as ticket icon see in he screenshot for the better understanding
=> fix: change the billing information icon

app/components/account/contact-info-section.js, app/components/account/password-section.js, app/components/forms/admin/content/pages-form.js, app/components/forms/admin/content/social-links-form.js, app/components/forms/admin/settings/analytics-form.js, app/components/forms/admin/settings/images-form.js, app/components/forms/admin/settings/microservices-form.js, app/components/forms/admin/settings/payment-gateway-form.js, app/components/forms/admin/settings/system-form.js, app/components/forms/events/view/create-access-code.js, app/components/forms/events/view/create-discount-code.js, app/components/forms/events/view/edit-session.js, app/components/forms/orders/order-form.js, app/components/forms/register-form.js, app/components/forms/session-speaker-form.js, app/components/modals/add-system-role-modal.js, app/components/modals/add-user-role-modal.js, app/components/modals/admin/content/new-event-sub-topic-modal.js, app/components/modals/admin/content/new-event-topic-modal.js, app/components/modals/admin/content/new-event-type-modal.js, app/components/modals/confirm-event-transfer-modal.js
Fixes #1519 
Removes sendAction() for various components.
=> chore: remove deprecated sendAction()

docs/installation/docker.md
Fixes #5580 
Linked the installation of server using docker-compose.
=> chore: Link server docker installation steps

app/templates/components/forms/orders/order-form.hbs
Fixes #5693 
The payment method icons changes see in the screenshot for the better understanding
=> fix: Payment method icons need to change

app/components/forms/wizard/sessions-speakers-step.js, app/mixins/event-wizard.js, app/templates/components/forms/wizard/sessions-speakers-step.hbs
Fixes removing custom-form field of Session & Speaker Step
=> fix: Add option to remove custom field in session speaker step

app/routes/events/view/index.js
=> fix: show selected number of sponsor in sponsor-box

app/routes/events/view/edit/sponsors.js, app/routes/public/index.js
=> fix: Show all sponsors on sponsors edit and public page

app/components/tables/default.js, app/controllers/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/events/view/sessions/list.hbs
Reverts fossasia/open-event-frontend#5766
Fixes #5834
=> Revert "fix: Dropdown menu results in internal scroll bar"

app/components/forms/orders/order-form.js
=> fix: Use .get on buyer in order form

.github/workflows/scripts.yml
=> chore: Add branch check action

app/controllers/events/view/speakers/create.js
=> fix: remove continuous loading of create speaker page

app/components/public/session-item.hbs, app/styles/libs/_helpers.scss
=> fix: Unwrap and align Join Video button

app/routes/events/view/speakers/list.js, app/templates/events/view/speakers.hbs
Fixes #5871 
Added 'Withdrawn' and 'canceled' tab in view Speakers page.
**Screenshot** -
=> fix: withdrawn & canceled tab added in speaker page

app/templates/components/ui-table/cell/cell-sponsor-image.hbs
=> fix: Sponsors logo size reduced to 40px

app/templates/components/ui-table/cell/cell-sponsor-image.hbs
Reverts fossasia/open-event-frontend#5898
=> Revert "fix: Sponsors logo size reduced to 40px"

app/controllers/events/view/tickets/orders/list.js
Fixes https://github.com/fossasia/open-event-frontend/issues/4237
=> fix: sort Organizer Event Ticket Order Overview by date

app/models/setting.js, app/templates/components/forms/admin/settings/billing.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4958
server side - https://github.com/fossasia/open-event-server/pull/7502
=> feat: allow admin to add logo to invoice

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
=> feat: Add Past filter to Explore page

app/controllers/public/session/view.js, app/models/social-link.js, app/routes/public/index.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5051
=> fix: Do not allow "Withdraw" session after session was held

app/templates/components/events/view/overview/general-info.hbs, app/templates/components/ui-table/cell/cell-event-date.hbs
=> fix: Event Dashboard: long date format added

app/components/events/view/export/download-zip.js, app/services/loader.js
=> fix: Zip export download link not working

app/components/events/view/overview/speaker-session.js, app/routes/events/view/index.js, app/templates/components/events/view/overview/general-info.hbs, app/templates/components/events/view/overview/speaker-session.hbs, app/templates/events/view/index.hbs
=> feat: Implement Dashboard Box "Sessions and Speakers"

app/templates/events/view/index.hbs
=> fix: Event Dashboard: Only show Sessions and Speakers Box if options are active

app/controllers/events/view/speakers/create.js, app/routes/events/view/speakers/create.js
=> fix: non-saved speaker appear in speakers list

app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: Change between location, online options etc. moves to top of page

app/templates/events/view/team/permissions.hbs
Fixes #5794 
Adds translation to Teams permission page
T-var add in permission.title
=> chore: Make team area translatable (add t-var)

app/components/events/view/overview/manage-roles.js, app/templates/components/events/view/overview/manage-roles.hbs
Fixes #5416 
require https://github.com/fossasia/open-event-server/pull/7522
=> feat: Enable Organizer to resend invitation

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
Fixes #5921 
- location part is done.
=> fix: enhance location filter options at explore page

.env.example, app/components/forms/register-form.js, app/components/forms/reset-password-form.js, app/templates/components/forms/register-form.hbs, app/templates/components/forms/reset-password-form.hbs, config/environment.js, package.json, yarn.lock
Fixes https://github.com/fossasia/open-event-frontend/issues/6086
=> feat: add hcaptcha to register and forgot password

app/components/tables/headers/sort.js, app/controllers/events/view/tickets/attendees/list.js, app/mixins/ember-table-route.js, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs, app/utils/text.ts
=> feat: Implement sorting on attendee overview page

app/components/forms/login-form.js, app/templates/components/forms/login-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6086
=> feat: add hcaptcha when user clicks more than two times to to login

app/routes/explore.js
=> fix: Prevent "Private Events" from being searched

app/components/forms/orders/order-form.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6129
=> fix: Order expire page redirection out of no where

app/components/events/view/overview/manage-roles.js, app/components/modals/add-user-role-modal.js, app/templates/components/events/view/overview/manage-roles.hbs
=> fix: Disable Role edit in Teams Page

app/components/public/event-date-time.hbs, app/components/public/event-venue.hbs, app/templates/components/event-card.hbs, app/templates/components/order-card.hbs
Fixes #6138
Show all basic data
-from to time and date
-Online event or location 
Add links
-Link event name to event page
-Order number of order
=> fix: enhance my ticket page

app/components/modals/session-notify-modal.hbs, app/components/modals/session-notify-modal.js
Fixes #5309 
required https://github.com/fossasia/open-event-server/pull/7529
=> feat: show email address and add CC in session notify modal

app/styles/pages/public-event.scss
=> fix: logo overlapping fixed

app/components/public/side-menu-outer.js, app/controllers/public.js
=> chore: Make areas translatable

app/components/forms/wizard/wizard-footer.hbs
Provides proper allignment to buttons in mobile view
Fixes #6146 
Provides proper alignment to button in the mobile view
- [✓ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [✓ ] My branch is up-to-date with the Upstream `development` branch.
- [✓ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [✓ ] I have added tests that prove my fix is effective or that my feature works
- [✓] I have added necessary documentation (if appropriate)
=> fix: Improve responsiveness of event wizard

app/components/public/stream/jitsi-stream.hbs, app/components/public/stream/jitsi-stream.ts, app/components/public/stream/video-stream.hbs, app/components/public/stream/video-stream.ts
=> feat: Add bbb iframe integration

app/templates/components/public/ticket-list.hbs
Fixes #5915
Removed the obvious headings of table for mobile view. 
Screenshot -
=> fix: Tickets: mobile ticket view

.sass-lint.yml, app/components/public/session-item.js, app/components/public/side-menu.js, app/components/public/stream/join-video.hbs, app/components/public/stream/side-panel.hbs, app/components/public/stream/side-panel.ts, app/controllers/public.js, app/controllers/public/sessions.js, app/services/loader.js, app/services/loader.ts, app/styles/components/stream.scss, app/templates/public.hbs, app/templates/public/sessions.hbs, app/utils/event.ts, tsconfig.json
=> feat: Add stream side panel to public event page

app/routes/public.js
=> fix: Set side_panel null on controller reset

app/router.js
=> chore: Change videoroom URL to video

app/services/auth-manager.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6185
list in my-tickets section is now showing correctly on reload or anything.
=> fix: disable caching for user 

app/styles/partials/colors.scss, app/styles/partials/form.scss, app/styles/partials/text.scss
=> fix: Change light gray font to dark gray

app/components/modals/simple-modal.hbs, app/components/modals/simple-modal.js, app/components/public/stream/side-panel.ts, app/controllers/public.js, app/routes/public/stream/view.ts, app/templates/public.hbs
=> feat: Redirect logged out or non attendee video stream to event page

app/components/forms/wizard/custom-forms/table.hbs, app/mixins/custom-form.js, app/models/custom-form.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5100
server : https://github.com/fossasia/open-event-server/pull/7524
=> feat: introduce is_public in session-speaker wizard

app/templates/components/nav-bar.hbs, app/templates/components/widgets/twitter-timeline.hbs
Fixes #6227 
self-explanatory
-
-
-
=> fix: hide "create event" on wizard pages for mobile view

app/components/forms/session-section.js, app/components/forms/speaker-section.js, app/templates/components/forms/session-section.hbs, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/forms/speaker-section.hbs
=> fix: Implement abstraction layer in add session-speaker form

app/controllers/events/view/edit/attendee.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6232
=> fix: read custom prop of undefined attendee step

app/components/forms/wizard/basic-details-step.js
Fixes #6237 
This was the mistake done by me on the PR #6144.
Previously , it was not able to create a multiple day event with same starting and ending time. [Check the date]
But the error should come for the single day event - [Check the date]
=> fix: Different day time check mistake of #6144

app/components/public/side-menu.js, app/components/public/stream/side-panel.hbs, app/components/public/stream/side-panel.ts, app/controllers/events/view/scheduler.js, app/controllers/public/schedule.js, app/models/event.js, app/templates/components/public/side-menu.hbs, app/templates/events/view/scheduler.hbs, app/templates/public/schedule.hbs
=> feat: Only show rooms with published sessions in side panel

app/components/public/stream/video-stream.hbs, app/styles/components/stream.scss
Fixes #6270 
Fixes the scrollbar in video meeting.
=> fix: scroll in video meeting

app/models/access-code.js, app/routes/events/view/tickets/access-codes/list.js, app/templates/components/forms/events/view/create-access-code.hbs, app/templates/events/view/tickets/access-codes/create.hbs
Fixes #5857
Making access form similar to discount form
=> fix: Simplify Access code

app/utils/dictionary/social-media.ts
For #6298 
Sort social links alphabetically in wizard step 2
=> fix: Sort social links alphabetically

app/components/public/stream/join-video.hbs, app/components/public/stream/join-video.ts, app/components/public/stream/stream-info.hbs, app/templates/components/modals/confirm-modal.hbs, app/templates/public.hbs, app/templates/public/index.hbs
=> feat: Add Join Event button

app/templates/components/country-dropdown.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6302
=> fix: Wizard Step 1 Tax information country field opens

app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: Billing Info checkbox

app/routes/index.js
Fixes https://github.com/fossasia/open-event-frontend/issues/4963
=> fix: isDemoted cfs fix for admin

app/styles/components/ticket-list.scss, app/templates/components/public/ticket-list.hbs
Fixes #6305 
It resolves the unoderd alignment of ticket list.
=> fix: alignment of ticket-list columns

app/styles/libs/_helpers.scss, app/templates/public.hbs
Fixes #6292
links added to logo and event heading
=> fix: Public Event Pages: Link event logo and text to event start page top 

app/controllers/events/view/speakers/create.js
=> fix: Allow speaker to be created without session

app/routes/public/role-invites.js
=> fix: Use event identifier in role invite page

app/templates/components/welcome-header.hbs
Fixes #6327 
tagline updated
- updated the tagline to The open source event solution for virtual and in-person events.
=> fix: updated tagline

app/components/modals/event-delete-modal.js, app/controllers/admin/events/list.js, app/templates/admin/events/list.hbs, app/templates/components/ui-table/cell/cell-event.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6324
the problem is due to space around the names of events.
=> fix: admin not able to delete events

app/components/forms/events/view/videoroom-form.hbs, app/templates/components/side-bar.hbs
Fixes #6242 
Added cancel button to get back to previous work
- Added cancel button
Screenshot
=> fix: Video Room Need further enhancement

app/templates/components/public/social-links.hbs, translations/bn.po, translations/de.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> chore: Update translations

app/components/forms/wizard/basic-details-step.js, app/templates/components/widgets/twitter-timeline.hbs
=> fix: Limit Time of Event Duration to Maximum 20 days to limit spam events

app/templates/components/events/view/overview/manage-roles.hbs, app/templates/components/modals/add-system-role-modal.hbs, app/templates/components/modals/add-user-role-modal.hbs
Fixes #6365 
- Change Add Role" or "Edit Role" to"Add Team Member" or "Edit Team Member"
-
-
=> fix: Team Member: Fix button text and enable translation

app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: Access Code Functionality

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
Fixes #6404 
Fixes #6405 
1) Previously the ticket buing form or new route gets reloaded on hitting enter key and all fields get reset , now it is resolved.
2) Errors was getting out of the sight of the users , now its resolved
=> fix: reset of ticket buying form & scrolling error

app/utils/computed-helpers.js
=> fix: Copy all time components

app/styles/libs/stripe_connect.scss, app/templates/orders/pending.hbs
Fixes #6406 
- Extended the button width
Screenshot
=> fix: Order Form Stripe Payment: Increase button size

app/components/forms/orders/order-form.js, app/mixins/custom-form.js, app/models/attendee.js, app/models/custom-form.js, app/utils/validators.js
Fixes #6402 
- Added Instagram and Linkedin into Attendee Form
-
-
=> fix: Attendee Form: Added Instagram and Linkedin

app/controllers/public.js, app/controllers/public/cfs/edit-speaker.js, app/controllers/public/cfs/new-speaker.js, app/controllers/public/cfs/view-speaker.js, app/router.js, app/routes/public/cfs/view-speaker.js, app/templates/components/events/view/overview/speaker-view.hbs, app/templates/public.hbs, app/templates/public/cfs/view-speaker.hbs
=> feat: Add "view-speaker" page for cfs

app/components/public/stream/stream-info.hbs, app/styles/libs/_helpers.scss, app/templates/components/orders/after-order-message.hbs
=> fix: Show after order message with whitespace preserved

app/components/nav-bar.js, app/styles/pages/events.scss, app/templates/components/nav-bar.hbs
=> fix: search bar enhancement and working

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: Ticket sorting logic in event wizard

app/components/public/add-to-calender.ts
=> feat: Add event link, event description and organizer message

app/templates/components/forms/session-section.hbs, app/templates/components/forms/speaker-section.hbs
=> fix: CfS: Add private/public badge into edit form

app/routes/my-tickets/upcoming/list.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6498
=> fix: Sort ticket list by event date

app/components/account/danger-zone.js, app/routes/account/danger-zone.js, app/templates/components/order-card.hbs, app/templates/my-tickets/past.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6497
=> fix: don't cancel ticket in past

app/components/public/ticket-list.js
=> fix: Loads availability of ticket and remove error from console at add order page

app/utils/computed-helpers.js
Fixes #6500 
Fixes #6259 
Fixes #6150
=> fix: Timezone issue in cfs

app/components/modals/session-notify-modal.js
Fixes #6531 
This PR makes speaker email in the form of "Some name <email>"
=> fix: added <> around emails

app/components/public/stream/side-panel.hbs, app/styles/components/stream.scss, app/styles/partials/utils.scss
Fixes #6510 
self-explanatory
-
-
-
=> fix: Online Event Sidebar Align text and buttons

app/controllers/public.js, app/templates/components/public/speaker-item.hbs
=> fix: Speaker event_id crash and moment warning

app/routes/public/speakers.js
=> fix: Load less speakers in one go

app/templates/components/nav-bar.hbs
=> chore: Hide groups nav item

app/controllers/events/view/sessions/list.js
And make all possible fields sortable
Fixes #6516
=> fix: Sort sessions by submitted date

app/components/widgets/forms/link-field.ts, app/templates/components/events/view/overview/speaker-view.hbs, tests/integration/components/widgets/forms/link-field-test.ts
Fixes https://github.com/fossasia/open-event-frontend/issues/6546
=> fix: don't show links if field was empty

app/templates/components/forms/speaker-section.hbs
=> fix: Gender value set to random string

app/templates/components/forms/wizard/sessions-speakers-step.hbs
Reverts fossasia/open-event-frontend#6289
=> Revert "fix: Standardize Microlocations or Virtual Online Rooms Requirement"

app/templates/components/public/speaker-item.hbs, app/templates/public/speakers.hbs
=> fix: Pass event as prop to speaker item to make link

app/styles/pages/public-event.scss, app/styles/pages/public.scss, app/styles/partials/footer.scss, app/templates/public.hbs
Fixes #6534
The left sidebar was not sticky which was due to a parent container with class "footer-pusher" having overflow-x as hidden.
I have removed this property of the above class as it is already inherited from the body of the page. This fixes the bug and no functionality/UI is hampered.
-
-
-
=> fix: Left Sidebar Not moving down

app/controllers/public/cfs/new-session.js, app/routes/public/cfs/new-session.js
Fixes #6593 
required for #https://github.com/fossasia/open-event-server/pull/7711
=> feat: enhance cfs mail

app/styles/pages/public-event.scss, app/styles/pages/public.scss, app/styles/partials/footer.scss, app/templates/public.hbs
Reverts fossasia/open-event-frontend#6582
Fixes #6603
=> Revert "fix: Left Sidebar Not moving down"

app/controllers/orders/view.js, app/templates/components/forms/orders/cancel-order.hbs, app/templates/orders/view.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6489
=> feat: add ticket cancellation box 

app/controllers/admin/settings/social-media.js, app/router.js, app/routes/admin/settings/social-media.js, app/templates/admin/settings.hbs, app/templates/admin/settings/social-media.hbs, app/templates/components/forms/admin/settings/system-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6459
=> fix: move social media to other tab in admin section

app/controllers/public/cfs/new-session.js, app/routes/public/cfs/new-session.js
Reverts fossasia/open-event-frontend#6602
Fixes #6613
=> Revert "feat: enhance cfs mail"

app/templates/components/forms/session-section.hbs, app/templates/components/forms/speaker-section.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6627
=> fix: session/speaker form section

app/routes/public/session/view.js, app/templates/components/public/speaker-item.hbs
=> fix: Hide sessions from speaker item when schedule is not published

app/controllers/public/sessions.js
=> fix: Store frozen date array for sessions page

app/components/modals/session-notify-modal.hbs, app/components/modals/session-notify-modal.js, app/routes/events/view/sessions/list.js
=> feat: Add "Reply-to" to organizers in session notify

app/components/modals/session-notify-modal.hbs
=> fix: make reply-to readable in session notify modal

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/components/public/stream/video-stream.hbs, app/components/public/stream/video-stream.ts, app/models/video-channel.ts, app/styles/components/extras.scss
Fixes https://github.com/fossasia/open-event-frontend/issues/6479
=> feat: adding youtube & vimeo

app/routes/events/view/sessions/list.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6655
=> fix: organizer search by track, speaker, session

package.json, yarn.lock
Reverts fossasia/open-event-frontend#6673
=> Revert "chore(deps-dev): bump ember-source from 3.20.3 to 3.25.1"

app/components/public/session-item.hbs, app/components/public/session-item.js, app/models/session.js, app/models/user-favourite-session.ts, app/models/user.js, app/routes/public/sessions.js, tests/unit/models/user-favourite-session-test.ts
Related to https://github.com/fossasia/open-event-frontend/issues/5763
=> feat: Add user favourite session

app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/orders/after-order-message.hbs
Fixes #6659
requires - fossasia/open-event-server#7731
Sanitization added for Organizer msg in Wizard Step 1
=> feat: Organizer Msg: Add Sanitization

app/components/public/stream/video-stream.ts, app/controllers/public/sessions.js, app/routes/public/sessions.js, app/templates/public.hbs, app/templates/public/sessions.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5763
=> feat: my schedule filter

app/components/modals/session-notify-modal.hbs, app/components/modals/session-notify-modal.js
=> fix: Only allow one email address of "event owner" in the Reply-to email

app/styles/partials/utils.scss, app/templates/components/widgets/twitter-timeline.hbs, app/templates/public/exhibition/view.hbs
=> feat: Exhibitor Page: Add Twitter Widget

app/components/forms/wizard/custom-form-input.hbs, app/components/public/stream/video-stream.ts, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5832
=> fix: Implement "Short Answer" and "Paragraph"

app/components/public/session-item.hbs, app/helpers/prevent-bubbling.js
Fixes #6695
https://user-images.githubusercontent.com/61330148/108095140-8f3d3500-70a5-11eb-8e66-b19148f4c124.mp4
=> fix: Prevent session accordion expansion on icon click

app/components/modals/add-to-calendar.js, app/components/public/add-to-calender.hbs, app/components/public/add-to-calender.ts, app/templates/components/modals/add-to-calendar.hbs
discussed in monday meeting
Previously there was two button "add event" and "add sessions".
this PR make a single button "add to calendar" that has dropdown for "add event" and "add session".
they lead to a dialog containing list of supported calendar.
=> feat: Add single "add to calendar" button.

app/components/footer-main.js, app/styles/partials/utils.scss
=> fix: Add top margin to footer

app/components/forms/events/view/exhibitors/exhibitor-form.hbs, app/components/forms/events/view/exhibitors/exhibitor-form.ts, app/controllers/public/exhibition/view.js, app/models/exhibitor.ts, app/templates/components/public/social-links.hbs, app/templates/public/exhibition/view.hbs
=> feat: Exhibitor: Add extra social links

app/components/public/session-item.hbs, app/components/public/session-item.js
fixes #5788 icon part.
this PR implement circle Checkbox icon in session card instead of star icon. This is discussed in meeting.
=> fix: Add checkbox in session card

app/routes/events/view/exhibitors/list.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6768
=> fix: exhibitor page search 

app/templates/public/sessions.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6774
=> fix: invalid date to not yet scheduled

app/templates/components/public/side-menu.hbs, app/templates/public/exhibition/index.hbs, app/templates/public/speakers.hbs
=> fix: Mobile Event Pages: Spacing and icon for event pages 

app/models/exhibitor.ts, app/templates/components/public/exhibitor-item.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6767
=> fix: Exhibitors Pages thumbnail image

app/styles/partials/utils.scss, app/templates/public/schedule.hbs, app/templates/public/sessions.hbs
=> fix: Schedule: Add list and calendar button to schedule page

app/models/exhibitor.ts, app/models/session.js, app/routes/public/session/view.js, app/templates/public/session/view.hbs
=> feat: Add user favourite avatars on session page

app/components/public/stream/join-video.ts, app/controllers/public.js, app/templates/public.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6322
https://user-images.githubusercontent.com/56407566/108744972-94482b80-7560-11eb-914e-a75d690529f2.mp4
=> fix: Join event panel opening

app/components/public/add-to-calender.hbs, app/components/public/social-links.js, app/styles/partials/utils.scss, app/templates/components/public/social-links.hbs, app/templates/public.hbs
=> fix: Public Event Page: Right hand side

app/templates/public/exhibition/view.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6830  https://github.com/fossasia/open-event-frontend/issues/6830#issuecomment-786662222
=> fix: move exhibitor slides down to video

app/styles/app.scss, app/styles/libs/_helpers.scss, app/templates/public/sessions.hbs
Fixes #6852
https://user-images.githubusercontent.com/61330148/109396188-64c96280-7956-11eb-98f2-69cead3ec590.mp4
=> fix: Public Schedule: Date filters text not in middle, get rid of empty space

app/templates/components/public/side-menu.hbs
Fixes #6800 
**Changed the order of left side menu**
The new order :
- Info
- Tickets
- Schedule
- Speakers
- Calendar
- Sponsors
- Exhibition
- Organizer
- Call for Speakers
- Getting here
- Code of Conduct
=> Changed order of left side menu

app/controllers/public/schedule.js, app/templates/public/schedule.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6812
=> fix: full screen for calendar view

app/components/public/session-item.hbs, app/components/public/speaker-item.js, app/templates/components/public/speaker-item.hbs
=> fix: Public Speaker Page/Schedule Website links of speaker missing

app/controllers/public/speakers.js, app/routes/public/speakers.js, app/templates/public/speakers.hbs
Fixes #6753
https://user-images.githubusercontent.com/61330148/109559250-6fbff680-7b00-11eb-891b-4650a6fe796e.mp4
=> feat: Public Speakers Page: Add search box to search for a speaker name

app/components/public/session-item.hbs, app/components/public/stream/video-stream.hbs, app/templates/public/exhibition/view.hbs
Fixes #6883
| After | Before |
| ------------- | ------------- |
| ![Screenshot from 2021-03-02 14-30-59](https://user-images.githubusercontent.com/61330148/109624367-22757080-7b64-11eb-92b1-8c0923b5951c.png) | ![Screenshot from 2021-03-02 14-30-33](https://user-images.githubusercontent.com/61330148/109624413-328d5000-7b64-11eb-8a52-a8b130c93ccb.png) |
| ![Screenshot from 2021-03-02 14-24-59](https://user-images.githubusercontent.com/61330148/109624462-4042d580-7b64-11eb-97f9-3fae56b554f3.png) | ![Screenshot from 2021-03-02 14-26-32](https://user-images.githubusercontent.com/61330148/109624784-9b74c800-7b64-11eb-90c9-9006c9c82da1.png) |
=> fix: Youtube: Always implement modest branding

app/controllers/orders/new.js, app/templates/components/forms/orders/order-form.hbs
=> fix: Make order form email readonly

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/components/public/stream/video-stream.hbs, app/models/video-stream.ts
Fixes #6882
server reqd : fossasia/open-event-server#7795
https://user-images.githubusercontent.com/61330148/109807841-6ba0ef80-7c4c-11eb-8f9e-8dbb8ed6c103.mp4
=> feat: Youtube and Vimeo: allow looping videos

app/components/public/session-item.hbs, app/components/public/session-item.js, app/controllers/public/sessions.js, app/models/session.js, app/styles/app.scss, app/templates/public/sessions.hbs
=> feat: Add favourite count and sort by popularity

app/styles/components/scheduler.scss, app/templates/events/view/scheduler.hbs
Fixes #6711 
- Navbar equal to calendar.
=> fix: Side Navbar made equal to calendar

app/styles/components/scheduler.scss, app/templates/events/view/scheduler.hbs
Reverts fossasia/open-event-frontend#6807
=> Revert "fix: Side Navbar made equal to calendar"

app/templates/components/public/ticket-list.hbs
=> fix: Public Event Page: Improve ticket box

app/templates/components/public/side-menu.hbs
Fixes #6918
schedule without a filter or search result displayed.
https://user-images.githubusercontent.com/61330148/110113206-c6ffe880-7dd8-11eb-954c-72f383fcd1f9.mp4
=> fix: Public Schedule & Speakers: Reset filters on navigation

app/templates/components/public/speaker-item.hbs
Fixes #6904 
https://www.loom.com/share/652b7fc46d364712a9928f858e9ae2e0
=> fix : Public Speakers Page: Session links missing

app/routes/events/view/videoroom/create.js, app/routes/events/view/videoroom/edit.js
Fixes #6914 
https://user-images.githubusercontent.com/72552281/110082014-cf452d00-7db2-11eb-838a-15df3505f32c.mp4
=> fix: unload microlocation video-room

app/templates/public.hbs
=> fix: Schedule: Always show heading "Session Types" on top of filter

app/templates/public/sessions.hbs
=> fix: Public Schedule Add a pop-up message to the central Filter

app/templates/public/exhibition/view.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6946
@mariobehling this one - 
or
=> fix: change position exhibition video & add heading above contact

app/components/public/stream/side-panel.hbs, app/styles/components/stream.scss, app/templates/public.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6826
=> fix: change sidepanel style

app/controllers/public/exhibition/view.js, app/routes/public/exhibition/view.js, app/templates/public/exhibition/view.hbs
Fixes #6792 
https://user-images.githubusercontent.com/61330148/109708054-e58b9700-7bc0-11eb-9ec3-9522769f62e4.mp4
=> feat: Virtual Exhibition: Add a "< previous | next >" option 

app/components/public/stream/side-panel.ts
Fixes remaining part of https://github.com/fossasia/open-event-frontend/pull/6966#issuecomment-794587032
=> fix: Show all video streams in side panel

app/components/public/stream/side-panel.hbs, app/styles/components/stream.scss
=> fix: scroll video stream side panel

app/controllers/public/schedule.js, app/templates/public/schedule.hbs
=> fix: Public Schedule Calendar View still showing hidden rooms

app/routes/public/chat.ts
Fixes #6985
https://user-images.githubusercontent.com/61330148/110866013-83cadb80-82ea-11eb-8e4d-bd4e0866b721.mp4
=> fix: Virtual Event Chat: Accessing page when not logged in shows error

app/templates/components/public/exhibition-view.hbs
=> fix: Put exhibitor logo above Name and make it larger.

app/templates/components/modals/event-share-modal.hbs
=> fix: Align copy button in event share modal.

app/components/public/stream/side-panel.ts, app/controllers/events/view/chat.js, app/models/event.js, app/router.js, app/routes/events/view/chat.js, app/templates/events/view.hbs, app/templates/events/view/chat.hbs
Related to : #7044
requires : fossasia/open-event-server#7848
Toggle chat page added in organizer menu
=> feat: Allow Chat Toggle

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/models/video-stream.ts
This PR add record, autoStartRecording, muteOnStart Features to BBB video-stream
require https://github.com/fossasia/open-event-server/pull/7835
=> feat: add record, autoStartMeeting, muteOnStart parameters to bbb

app/templates/events.hbs, app/templates/events/view/settings/export.hbs
=> fix: hiding import section, and export is in alpha stage

docs/installation/local.md
=> docs: watchman installation step removed

app/components/events/view/overview/manage-roles.js
Fixes #discussion
required https://github.com/fossasia/open-event-server/pull/7861
https://user-images.githubusercontent.com/56407566/113180019-e2420480-926d-11eb-918e-218d38b02036.mp4
=> fix: handle error on duplicate invite

app/templates/events.hbs
Fixes #show import section to admin
=> fix: show import section to admin in event list

app/components/public/session-item.hbs
Display session language in session item.
=> feat: Display session language in session item

app/templates/events/view/chat.hbs
=> fix: Additional info for chat on/off

app/components/public/stream/chat.ts, app/models/event.js, app/templates/public/chat.hbs
Fixes #7044
requires: fossasia/open-event-server#7853
=> feat: Create private chat room per event

app/router.js, app/routes/admin/sales/index.js, app/templates/admin.hbs, app/templates/admin/sales.hbs, app/templates/admin/sales/index.hbs, tests/acceptance/admin-sales-accessibility-test.js
partially Fixes https://github.com/fossasia/open-event-frontend/issues/5256
fixes point 2.
```Dropdown filter:
Events with
Live Events (pre-selected default view)
Draft Events
Past Event
```
=> feat: dropdown filter for live, past, all events in admin-sales

app/controllers/admin/messages.js, app/models/message-setting.js, app/templates/components/ui-table/cell/admin/messages/cell-options.hbs, app/templates/components/ui-table/cell/cell-title-message.hbs
=> feat: Restructure email settings

app/components/forms/wizard/sessions-speakers-step.js, app/models/speakers-call.js, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/public/call-for-speakers.hbs
Fixes #6408 
Add soft closing date for submissions to wizard CfS page
=> feat: Add soft closing date for submissions to wizard CfS page

app/components/forms/events/view/videoroom-form.js
=> fix: Video extra null check

app/components/forms/events/view/videoroom-form.js, app/templates/public.hbs
=> fix: Side panel not opening

app/utils/dictionary/genders.ts
Fixes #7129 
Made gender question more inclusive
=> chore: Add gender fields

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/templates/components/ui-table/cell/events/view/videoroom/cell-video-recording.hbs
this PR add bbb recording table in video edit page.
=> feat: add bbb recording table in video edit page

app/templates/components/widgets/forms/file-upload.hbs
Add message for slide upload in CFS form
=> fix: Add message for slide upload in CFS form

app/controllers/public.js
Reverts fossasia/open-event-frontend#7226
=> Revert "fix: Show event link if event is online event in "Location Field" in calenders(other than ical)"

app/templates/admin.hbs
Fixes #7183 
Rename  video-channels to video in admin.
=> fix: Admin: Renamed video-channels to video 

app/components/public/add-to-calender.ts
=> fix: Show event link if event is online event in "Location Field"

package.json, yarn.lock
Fixes #paypal checkout issue
https://user-images.githubusercontent.com/56407566/118998756-51eb8a80-b9a7-11eb-88b4-0e5f772bb28e.mp4
@sachinchauhan2889 is there anything else in issue?
=> fix: paypal version downgrade

app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/speaker-section.hbs, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/components/widgets/forms/billing-info.hbs
=> chore: Add t-var for translations

app/templates/components/widgets/forms/rich-text-editor.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7319
fixes mobile view of linkify button
=> fix: linkify button ui for mobile

app/components/forms/events/view/videoroom-form.js, app/components/ui-table/cell/cell-duration.hbs, app/components/ui-table/cell/cell-duration.js, app/models/video-recording.ts, app/models/video-stream.ts
=> fix: remove edit video page error

.github/workflows/ci.yml, .github/workflows/scripts.yml, .travis.yml
=> chore: run tests for testing branch

app/components/forms/events/view/videoroom-form.hbs, app/styles/libs/_helpers.scss
As discussed in the meeting ask moderators to get a ticket for the event.
=> fix: ask moderators to order a ticket for the event.

app/routes/groups/edit.js, app/templates/groups/edit.hbs
Fixes #7377 
add infinity loader for events at edit group page
=> feat: add infinity loader for events at edit group page

app/templates/components/tabbed-navigation.hbs, app/templates/events/view/team.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7384
fixes the team page by adding dropdown icon & text changed to team members.
=> fix: Dropdown icon to the event creation steps to make it more user friendly.

app/templates/components/widgets/forms/file-upload.hbs
Reverts fossasia/open-event-frontend#7321
=> Revert "fix: Session and Exhibitor Form Simplify Slide Form Element"

app/components/ui-table/cell/admin/users/cell-user-actions.hbs, app/controllers/admin/users/list.js
=> feature: send reset mail and resend verification via admin section

app/styles/libs/_helpers.scss, app/templates/public/sessions.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5919
I have aligned everything in a line for mobile view. This way it is not more complicated than it should, and it look better. Some changes from issue are not resolved as same, I have to compromise them, there were 2 PRs on that isue and they both were complicated and time taking.
=> fix: simplyfing schedule page

package.json, yarn.lock
Reverts fossasia/open-event-frontend#7509
=> Revert "chore(deps-dev): bump ember-cli-deprecation-workflow from 1.0.1 to 2.0.0"

app/templates/components/modals/confirm-event-transfer-modal.hbs, app/templates/components/modals/event-transfer-modal.hbs
=> fix: add owner downgrade to organzier popup message

app/components/forms/document-upload.hbs, app/components/forms/events/view/exhibitors/exhibitor-form.hbs, app/models/setting.js, app/templates/components/forms/admin/settings/billing.hbs, app/templates/components/forms/admin/settings/system-form.hbs, app/templates/components/forms/events/view/edit-session.hbs, app/templates/components/forms/session-section.hbs, app/templates/components/forms/speaker-section.hbs, app/templates/components/forms/user-profile-form.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/forms/wizard/sponsors-step.hbs, app/templates/components/modals/change-image-modal.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7529
require https://github.com/fossasia/open-event-server/pull/8092
=> feat: Make upload size dynamic.

app/components/forms/events/view/videoroom-form.js
Implement check before update bbb video if user restore previous configs.
=> fix: Implement check before update bbb video

app/controllers/admin/groups/list.js, app/models/group.js, app/routes/admin/groups/list.js
=> feat: enhance admin group table

app/models/group.js, app/templates/components/forms/group/group-settings-form.hbs, app/templates/components/forms/group/group-view.hbs, app/templates/components/group-card.hbs, app/templates/groups/view.hbs
Fixes #7528 
**Group View Page -**
**Group Settings -** 
**Groups Tab (My groups/Following) -**
=> feat: Add group banner and logo

app/styles/pages/public-event.scss
=> chore: fix sass warning & future deprecation

app/components/group-card.js, app/templates/components/group-card.hbs
=> fix: Group Card: Slice long about text

app/components/forms/wizard/basic-details-step.js, app/models/event.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/public/index.hbs
=> fix: remove live stream and webinar link

app/templates/components/group-card.hbs
=> feat: Add a View button for groups on the "My Groups" tab

app/templates/components/group-nav.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7586
=> fix: adding view button in grop edit page

app/templates/components/side-bar.hbs
=> fix: mobile view: add group tab in sidebar

app/components/public/session-item.hbs, app/templates/public/sessions.hbs
=> fix(icons): made icons more intuitive on schedule page

app/controllers/admin/index.js, app/templates/admin/index.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7538
=> fix: show frontend and server version on admin index page

app/templates/components/forms/group/group-view.hbs
Fixes #7619
Centered button and changed color.
=> fix: center contact button on group page

app/routes/create.js
Fixes #7483 
Screen Capture:
https://user-images.githubusercontent.com/56963647/127100571-1cc1a551-9c2e-436c-9b74-e71c2e8f5e24.mp4
=> fix: redirect to /create after login

app/templates/components/forms/group/group-view.hbs
Fixes #7619
Changed color to blue
=> fix: changed contact button color in group to blue

app/controllers/admin/index.js, app/templates/admin/index.hbs
=> feat: show testing deployment version on admin page

app/models/group.js, app/styles/partials/text.scss, app/templates/components/forms/group/group-view.hbs, app/templates/components/group-card.hbs, app/templates/public.hbs
requires https://github.com/fossasia/open-event-server/pull/8132
fixes https://github.com/fossasia/open-event-frontend/issues/7630
=> feat: Group: add followers count

.github/workflows/docker-hub.yml
Just a copy of https://github.com/fossasia/open-event-server/pull/8137, with repo rename, so it should work.
=> GitHub action to build and push Docker image

app/components/forms/events/view/videoroom-form.hbs, app/controllers/events/view/videoroom/list.js, app/templates/events/view/videoroom/list.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7673
=> fix: make areas translatable

app/controllers/admin/sales/index.js
follow up https://github.com/fossasia/open-event-frontend/pull/7642
=> apply default sorting on admin sales

app/controllers/public/index.js
fix env variable for authentication.
It fix the error while logging in from modal on event public page.
=> fix env variable for authentication

app/templates/components/group-nav.hbs
=> fix: view group button

app/templates/components/group-nav.hbs
=> fix: remove view button from create group page

app/templates/components/group-header.hbs
=> chore: add alpha stage banner in group

app/templates/components/group-nav.hbs, app/templates/groups/edit/followers.hbs, app/templates/groups/team.hbs
Fixes #7664 
Now, user should be able to access all other tabs while present on any tab.
=> fix: group edit tabs

app/templates/public/index.hbs
=>  fix:  Show correct tax for registration tickets #7799

app/models/order.js
=> fix: Calculate Tax Properly

app/models/order.js
=> fix: Tax Issue Completed

.env.example
=> fix: change api host to test server

app/controllers/events/view/tickets/index.js
Fixes #7861
Before | After
------- | -----------
=> fix: Organizer Ticket Overview Page: Missing Currency for Sales

app/routes/public/index.js
=> fix: preselect ticket if only one ticket in ocs event

app/components/forms/events/view/videoroom-form.js
=> fix: not able to add video rooms other than bbb

app/components/orders/order-summary.js, app/models/group.js
=> fix: unconditionally show subtotal

app/templates/public/index.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7912
=> fix: Menu Link not working for Registration

app/templates/components/events/view/overview/general-info.hbs
=> fix: location & online info in event dashboard

app/templates/public/index.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7928
=> fix: screen froze on user login at time of ticket buying

app/routes/group-public.js
Fixes https://github.com/fossasia/open-event-frontend/issues/8006
=> fix: make anonymous user see public group

translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> chore: updated and added tranlatable strings

app/controllers/account/billing/invoices/list.js, app/templates/components/events/view/overview/general-info.hbs, app/templates/components/forms/group/group-settings-form.hbs, app/templates/components/forms/orders/order-form.hbs, app/templates/events/view/chat.hbs, app/templates/events/view/documents.hbs, app/templates/events/view/videoroom/list.hbs, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> fix: make strings translatable

app/components/forms/session-speaker-form.js, app/components/public/session-item.hbs, app/components/public/session-item.js, app/models/speaker.js
Fixes https://github.com/fossasia/open-event-frontend/issues/7904
required https://github.com/fossasia/open-event-server/pull/8355
=> feat: adding speaker sorting

app/components/public/session-item.js
related https://github.com/fossasia/open-event-frontend/pull/8040
=> fix: handled edge case in sorted speaker show

app/templates/components/public/featured-speaker-list.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/8039
=> fix: speaker section responsiveness

app/templates/components/modals/add-user-role-modal.hbs
=> fix: make role translatable & capitalize

app/components/forms/orders/attendee-list.js, app/templates/components/forms/orders/attendee-list.hbs
Reverts fossasia/open-event-frontend#7948
For more info please find details here https://github.com/fossasia/open-event-frontend/pull/7948#issuecomment-965349686
=> Revert "feat: make ticket holder info editable"

app/templates/components/group-card.hbs
=> fix: explore groups now shows all groups as expected

app/controllers/events/view/exhibitors/list.js, app/controllers/events/view/sessions/list.js, app/templates/components/event-invoice/payee-info.hbs, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/order-card.hbs, app/templates/components/orders/ticket-holder.hbs, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> chore: make strings translatable

app/components/forms/orders/order-form.js, app/templates/components/forms/group/group-view.hbs, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> fix: missing punctuations

app/routes/index.js
=> fix: promoted groups now visible on frontpage as expected

app/components/forms/group/group-view.js, app/components/public/ticket-list.js, app/controllers/public.js, app/controllers/public/index.js, app/routes/group-public.js, app/routes/index.js, app/routes/public.js, app/templates/public.hbs, app/templates/public/index.hbs, package.json, translations/de.po, yarn.lock
=> Merge Dev to Master

app/components/paypal-button.js, app/controllers/orders/pending.js
Fixes #8166 
A small edge case was left during implementation causing this error.
=> fix(payments): error message on stripe checkout button

app/utils/dictionary/event.ts, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
=> fix: make event-topic/subtopic/type dropdown translatable

app/components/public/stream/video-stream.ts
=> chatmosphere working now

app/components/public/stream/side-panel.ts
=> fix: loading icon on side panel

app/components/public/stream/video-stream.ts
=> add chatmosphere to iframe

app/components/public/stream/side-panel.ts, app/components/public/stream/video-stream.ts, package.json, yarn.lock
=> Merging Dev to Master

app/components/public/stream/side-panel.ts
=> fix: microlocations sorted by position in side-panel

app/components/public/stream/side-panel.ts, app/components/public/stream/video-stream.hbs, app/components/public/stream/video-stream.ts
=> Dev to master

app/styles/pages/events.scss, app/templates/public/index.hbs
=> fix: change class name for iframe

app/controllers/public/index.js, app/models/event.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/public/index.hbs
=> feat: allow loop and autoplay to public youtube stream

app/controllers/public/index.js
Fixes #8478 
Autoplay is now working.
=> fix: make autoplay work

README.md
=> Update README.md to latest test URL

package.json, yarn.lock
Reverts fossasia/open-event-frontend#8725
=> Revert "chore(deps-dev): bump ember-simple-auth-token from 5.3.0 to 5.3.2"

package.json, yarn.lock
Reverts fossasia/open-event-frontend#8749
=> Revert "chore(deps-dev): bump ember-resolver from 8.0.3 to 8.1.0"

package.json, yarn.lock
Reverts fossasia/open-event-frontend#8745
=> Revert "chore(deps-dev): bump ember-leaflet from 5.0.1 to 5.0.2"

package.json, yarn.lock
Reverts fossasia/open-event-frontend#8729
=> Revert "chore(deps-dev): bump @sentry/tracing from 6.19.7 to 7.53.0"

app/components/forms/wizard/custom-form-input.hbs, app/styles/pages/events.scss, app/templates/components/forms/orders/order-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/8783
- Add type rich text links custom from field
- Add type rich text links custom from field
=> feature-8783:Add type rich text links custom from field

app/components/forms/wizard/custom-form-input.hbs, app/styles/pages/events.scss, app/templates/components/forms/orders/order-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/8782
- Add type Yes/No custom from field
- Add type Yes/No custom from field
=> feature-8782:Add type Yes/No custom from field

app/components/forms/wizard/custom-form-input.hbs, app/components/forms/wizard/custom-form-input.ts, app/components/forms/wizard/custom-forms/table.hbs, app/models/custom-form.js, app/styles/pages/events.scss, app/templates/components/forms/orders/order-form.hbs
Fixes #8785
Implement dropdown with a number in custom forms
- Define range for the type number of the custom form.
=> feature-8785:Implement dropdown with a number in custom forms

app/components/forms/orders/order-form.js, app/components/forms/wizard/custom-form-input.hbs, app/styles/pages/events.scss, app/templates/components/forms/orders/order-form.hbs, app/utils/dictionary/year-list.ts
Fixes https://github.com/fossasia/open-event-frontend/issues/8784
- Add type year drop down custom from field
- Add type year drop down custom from field
=> feature-8784:Add type year drop down custom from field

app/components/forms/orders/order-form.js
Fix default text for refund policy
=> Correct text for refundPolicy

app/templates/components/footer-main.hbs
=> Change footer to Maintained by FOSSASIA

package.json, yarn.lock
Reverts fossasia/open-event-frontend#8803
=> Revert "chore(deps-dev): bump @sentry/tracing from 6.19.7 to 7.56.0"

app/components/forms/orders/order-form.js, app/components/forms/wizard/custom-form-input.ts, app/mixins/custom-form.js, app/models/attendee.js, app/models/custom-form.js, app/templates/components/footer-main.hbs, app/templates/components/forms/orders/order-form.hbs, app/utils/dictionary/wiki-scholarship.ts, package.json, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po, yarn.lock
=> Merge development into master

README.md
=> Update installation video in readme

app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs, yarn.lock
Fixes #8831 
- Changed `TextArea` input instead of `Widgets::Forms::RichTextEditor` in `app/templates/components/forms/orders/order-form.hbs`
- Added `<span>` tag for showing the `paragraph` in `app/templates/components/forms/orders/attendee-list.hbs`
- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ x] My branch is up-to-date with the Upstream `development` branch.
- [ x] The acceptance, integration, unit tests and linter pass locally with my changes
=> Add Paragraph field, text area

app/components/orders/order-summary.js
Fix #8137 
Referencing from https://github.com/fossasia/open-event-frontend/pull/8628
=> fix #8137 Orders Pages show wrong total amount of order

app/components/forms/orders/attendee-list.js, app/components/forms/orders/order-form.js, app/components/forms/wizard/custom-form-input-translation.hbs, app/components/forms/wizard/custom-form-input.hbs, app/components/forms/wizard/custom-form-rich-text.hbs, app/components/forms/wizard/custom-form-rich-text.ts, app/components/forms/wizard/custom-forms/table.hbs, app/components/forms/wizard/custom-forms/table.ts, app/components/widgets/forms/rich-text-link.js, app/styles/pages/events.scss, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/wizard/custom-form-ticket.hbs, app/templates/components/widgets/forms/rich-text-link.hbs, app/utils/dictionary/translate-language.ts
Fixes #8783
Implement rich text links in custom forms
- Implement rich text links in custom forms
- Fix issue not show field
=> feature 8783: Implement rich text links in custom forms

app/routes/events/view/tickets/index.js
=> Fix ticket list (another)

app/components/forms/orders/attendee-list.js, app/components/forms/orders/order-form.js, app/components/forms/wizard/custom-form-input-translation.hbs, app/components/forms/wizard/custom-form-input.hbs, app/components/forms/wizard/custom-form-rich-text.hbs, app/components/forms/wizard/custom-form-rich-text.ts, app/components/forms/wizard/custom-forms/table.hbs, app/components/forms/wizard/custom-forms/table.ts, app/components/widgets/forms/rich-text-link.js, app/helpers/rich-text-link.js, app/styles/pages/events.scss, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/wizard/custom-form-ticket.hbs, app/templates/components/widgets/forms/rich-text-link.hbs, app/utils/dictionary/translate-language.ts
Fixes #8783
Implement rich text links in custom forms
- Implement rich text links in custom forms
=> feature 8783:Implement rich text links in custom forms

app/routes/events/view/edit/attendee.js, app/routes/events/view/edit/badge.js, app/routes/events/view/index.js, app/routes/events/view/scheduler.js, app/routes/events/view/session/edit.js, app/routes/events/view/sessions/create.js
Maybe fixes https://github.com/fossasia/open-event-frontend/issues/8989
=> Fix various places where more than 20 items could be

app/components/forms/wizard/badge-forms/badge-setting.js
Fixes #8984 
- fix issue Backgroud images disappeared when select color and cancel
- add condition when remove image from badge
=> feature-8984: Background images disappeared when select color and cancel

app/components/forms/orders/order-form.js
Fixes #8878
- Can't read errors related to unfilled fields in the form
- Can't read errors related to unfilled fields in the form
=> feature-8878: Can't read errors related to unfilled fields in the form

app/components/public/session-item.js, app/controllers/events/view/tickets/attendees.js, app/controllers/events/view/tickets/orders.js
Fixes #9018
- Error when trying to export attendees
- Error when trying to export attendees
=> fix-9018: Error when trying to export attendees

app/components/public/add-to-calender.hbs, app/styles/pages/public-event.scss, app/templates/components/public/social-links.hbs
Fixes #8986
Missing spacing in some areas like button of calendar 
- Missing spacing in some areas like button of calendar
=> feature-8986:Missing spacing in some areas like button of calendar

app/controllers/events/view/edit/sessions-speakers.js
Fixes #9014 
- Cannot add rooms or microlocations
- Cannot add rooms or microlocations
=> fix-9014: Cannot add rooms or microlocations

app/components/public/stream/side-panel.hbs, app/styles/components/stream.scss, app/styles/pages/public-event.scss
Fixes #9007
Increase spacing below last video room on sidepanel
-Increase spacing below last video room on sidepanel
=> feature-9007:Increase spacing below last video room on sidepanel

app/components/public/stream/side-panel.hbs
=> Fix language dropdown margin left

app/components/forms/wizard/badge-field-form.js, app/components/public/side-menu.js, app/components/side-bar.js, app/routes/public.js, app/services/event.ts, app/styles/components/explore/side-bar.scss, app/templates/components/public/side-menu.hbs, app/templates/components/side-bar.hbs, app/templates/public.hbs
Fixes #8752
- Redesign Burger Menu for Mobile Views
- Redesign Burger Menu for Mobile Views
=> feature-8752: Redesign Burger Menu for Mobile Views

app/styles/components/stream.scss
Fixes #9045 
I have changed the width to 75% and enable scrollbar if content overflows
=> Fix: sidebar width and scrolling

app/components/public/stream/side-panel.hbs, app/components/public/stream/side-panel.ts
=> Fix #9056 include dropdown of languages

app/components/public/stream/side-panel.hbs, app/components/public/stream/side-panel.ts
=> Fix #9053 #9046 display in sequence rooms

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/components/forms/wizard/badge-field-form.js, app/styles/components/extras.scss
Fixes #9034
- Fix organizer translation issues
- Fix organizer translation issues
=> feature-9034: Fix organizer translation issues

app/components/public/session-item.js, app/templates/components/public/schedule-menu-filter.hbs
Fixes #9008 
- Select Session Type button hits the browser border
- Select Session Type button hits the browser border
=> feature-9008: Select Session Type button hits the browser border

app/components/orders/event-info.js, app/controllers/orders/view.js, app/templates/components/orders/event-info.hbs, app/templates/orders/view.hbs
Fixes #9015
Change and link text on overview order page to event page
- Change and link text on overview order page to event page.
=> feature-9015:Change and link text on overview order page to event page

app/components/forms/wizard/sessions-speakers-step.js, app/components/public/schedule-menu-filter.js, app/models/session-type.js, app/models/track.js, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/public/schedule-menu-filter.hbs
Fixes #9049
- Make tracks and session types sortable similar to microlocations
- Make tracks and session types sortable similar to microlocations
=> feature-9049: Make tracks and session types sortable similar to microlocations

app/components/forms/wizard/attendee-step.js, app/components/forms/wizard/badge-step.js, app/components/forms/wizard/sessions-speakers-step.js, app/components/forms/wizard/wizard-footer.hbs, app/components/nav-bar.js
Fixes #9077 
- Row has been duplicated when edit badge of an existing event
- Row has been duplicated when edit badge of an existing event
=> fix-9077: Row has been duplicated when edit badge of an existing event

app/components/public/stream/side-panel.ts
=> fix #9053 display video rooms in order

app/components/public/add-to-calender-join-video.hbs, app/components/public/add-to-calender-join-video.ts, app/components/public/side-menu.js, app/styles/partials/utils.scss, app/templates/public.hbs, app/utils/file.js
Fixes #9075
- Reduce complexity of mobile screens and minimize white spaces
- Reduce complexity of mobile screens and minimize white spaces
=> feature-9075: Reduce complexity of mobile screens and minimize white spaces

app/components/side-bar.js, app/templates/application.hbs, app/templates/components/side-bar.hbs
Fixes #9013
Remove Search Box on Mobile Event Pages Menu
-Remove Search Box on Mobile Event Pages Menu
=> feature-9103: Remove Search Box on Mobile Event Pages Menu

translations/ar.po, translations/es.po, translations/fr.po, translations/hi.po, translations/ja.po, translations/ko.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/zh_Hant.po
Fixes #9050
- Arabic Translation hook error 
- Arabic Translation hook error 
- Fix similar errors for other languages during language generation.
- Resolve code file conflict for the Thai language file
=> feature-9050: Arabic Translation hook error 

app/components/forms/wizard/sessions-speakers-step.js, app/components/nav-bar.js, app/components/public/side-menu.js, app/components/side-bar.js, app/controllers/application.js, app/routes/public.js, app/services/event.ts, app/styles/pages/public.scss, app/styles/partials/nav-bar.scss, app/templates/application.hbs, app/templates/components/nav-bar.hbs, app/templates/components/side-bar.hbs, app/templates/public/sessions.hbs
Fixes #9069
Improve mobile top menu and add calendar icon
-Improve mobile top menu and add calendar icon
=> feature 9069:Improve mobile top menu and add calendar icon

app/components/side-bar.js, app/styles/partials/utils.scss
Fixes #9132
- Dropdown list is hidden when passing the header table
- Dropdown list is hidden when passing the header table
=> fix-9132: Dropdown list is hidden when passing the header table

app/components/public/add-to-calender-join-video.hbs
Fixes #9114
- Mobile screen: Add to Calendar button changing height
- Mobile screen: Add to Calendar button changing height
=> fix-9114: Mobile screen: Add to Calendar button changing height

app/mixins/ember-table-route.js
Fixes #9080
- There was no result for searching with Ticket price "0.0"
- There was no result for searching with Ticket price "0.0"
=> fix-9080: There was no result for searching with Ticket price "0.0"

app/controllers/events/view/tickets/attendees.js, app/controllers/events/view/tickets/orders.js, app/mixins/ember-table-route.js, app/routes/events/view/tickets/attendees/list.js, app/routes/events/view/tickets/orders/list.js, app/routes/public/cfs/edit-speaker.js, app/styles/components/ticket-list.scss, app/styles/partials/utils.scss, app/templates/components/widgets/forms/date-picker.hbs, app/templates/events/view/tickets/attendees.hbs, app/templates/events/view/tickets/orders.hbs
Fixes #9020
- Filter options for orders and attendees not working
- Filter options for orders and attendees not working
=> feature-9020: Filter options for orders and attendees not working

app/controllers/events/view/tickets/attendees/list.js, app/routes/events/view/tickets/attendees/list.js
Fixes #https://github.com/fossasia/open-event-server/issues/9127
- Add the unique ticket code into the downlad CSV file
- Add the unique ticket code into the downlad CSV file
=> Fix-9127: Add the unique ticket code into the downlad CSV file
