- app/components/public/featured-speaker-list.js
- app/components/public/speaker-item.js
- app/controllers/public/index.js
- app/styles/pages/public-event.scss
- app/styles/partials/speaker.scss
- app/templates/components/public/featured-speaker-list.hbs
- app/templates/components/public/speaker-item.hbs
- app/templates/public/index.hbs
- tests/integration/components/public/featured-speaker-list-test.js
- tests/integration/components/public/speaker-list-test.js
Adds the layout for featured speakers to the public event page.
- Adds featured speakers layout for event page.
Fixes #12 
@niranjan94 Please review this.
> Adds featured speakers layout to public events

- app/components/forms/user-profile-form.js
- app/router.js
- app/routes/profile.js
- app/templates/components/forms/user-profile-form.hbs
- app/templates/profile.hbs
- tests/integration/components/forms/user-profile-form-test.js
It creates the profile page (UI only)
Fixes #29
> Adds Profile page UI only

- app/components/events/event-import-section.js
- app/components/events/imports-history-section.js
- app/styles/pages/all.scss
- app/styles/pages/events.scss
- app/styles/partials/colors.scss
- app/templates/components/events/event-import-section.hbs
- app/templates/components/events/imports-history-section.hbs
- app/templates/events/import.hbs
- tests/integration/components/events/event-import-section.js
- tests/integration/components/events/imports-history-section.js
Adds import event and pending events list to the events/import.
Fixes #38 
@niranjan94 Please review. Thanks
> Adds event listing on import page

- app/templates/components/events/events-table.hbs
- app/templates/components/public/side-menu.hbs
- app/templates/components/public/social-links.hbs
- app/templates/components/widgets/twitter-timeline.hbs
Adds missing translation helper to events-table & side-menu handlebars.
Fixes #47 
@niranjan94 Please review
> Adds missing translation helper in hbs files

- app/components/public/sponsor-item.js
- app/components/public/sponsor-list.js
- app/controllers/public/index.js
- app/styles/pages/public-event.scss
- app/templates/components/public/speaker-list.hbs
- app/templates/components/public/sponsor-item.hbs
- app/templates/components/public/sponsor-list.hbs
- app/templates/public/index.hbs
- tests/integration/components/public/sponsor-item-test.js
- tests/integration/components/public/sponsor-list-test.js
- Adds layout for sponsors to the public events page
####Screenshot
Fixes #49 
@niranjan94 Please review. Thanks
> Adds sponsors layout to public events

- app/components/public/call-for-speakers.js
- app/templates/components/public/call-for-speakers.hbs
- app/templates/public/cfs.hbs
- tests/integration/components/public/call-for-speakers-test.js
Adds the public call for speaker component (UI Only)
Fixes #54
> Adds public event CFS component (UI only)

- app/components/nav-bar.js
- app/components/notification-dropdown.js
- app/controllers/application.js
- app/styles/components/all.scss
- app/styles/components/notification-dropdown.scss
- app/templates/application.hbs
- app/templates/components/nav-bar.hbs
- app/templates/components/notification-dropdown.hbs
- app/templates/components/public/ticket-list.hbs
- tests/integration/components/notification-dropdown-test.js
Adds notification dropdown to the navbar
Fixes #10
> Add notification dropdown to navbar

- app/templates/components/events/imports-history-section.hbs
> Fixes orientation overflow on event imports page.

- app/components/quick-filter.js
- app/templates/components/quick-filter.hbs
- app/templates/index.hbs
- tests/integration/components/quick-filter-test.js
> added filter option

- .env.example
- .gitignore
- .template-lintrc.js
- app/components/explore/side-bar.js
- app/controllers/explore.js
- app/router.js
- app/routes/explore.js
- app/styles/components/all.scss
- app/styles/components/explore/side-bar.scss
- app/styles/partials/event-card.scss
- app/templates/components/event-card.hbs
- app/templates/components/explore/side-bar.hbs
- app/templates/explore.hbs
- app/utils/dictionary/filters.js
- package.json
- tests/integration/components/event-card-test.js
- tests/integration/components/explore/side-bar-test.js
- tests/unit/controllers/explore-test.js
- tests/unit/routes/explore-test.js
Implements the search UI page at `/explore/`. Please see inline comments.
UI preview:
Fixes #69
> Implements the UI of search page

- app/templates/components/public/side-menu.hbs
- app/templates/public/index.hbs
- package.json
Adds scroll-to library & implements auto scroll on public events page.
Fixes #74 
@niranjan94 Please review.
> Adds auto scroll to public events

- app/styles/components/explore/side-bar.scss
- app/templates/components/explore/side-bar.hbs
Adds auto fill location input in explore page.
Fixes #86 
@niranjan94 Please review.
> Adds auto fill location input to explore page

- app/styles/partials/event-card.scss
> Improve image display of event card

- app/templates/components/quick-filter.hbs
- app/templates/components/side-bar.hbs
- tests/integration/components/quick-filter-test.js
- tests/integration/components/side-bar-test.js
> Make quick-filter component responsive and remove sidebar search for mobile

- app/router.js
- app/routes/events/view/sessions.js
- app/templates/events/view/sessions.hbs
- tests/unit/routes/events/view/sessions-test.js
Added the UI for the sessions page to the event route (events/<event_id>/sessions)
Fixes #79
> feat: added sessions to event route (UI)

- app/controllers/my-tickets/index.js
- app/router.js
- app/routes/my-tickets.js
- app/routes/my-tickets/index.js
- app/routes/my-tickets/past.js
- app/routes/my-tickets/saved.js
- app/templates/components/event-card.hbs
- app/templates/my-tickets.hbs
- app/templates/my-tickets/index.hbs
- app/templates/my-tickets/past.hbs
- app/templates/my-tickets/saved.hbs
- tests/unit/controllers/my-tickets/index-test.js
- tests/unit/routes/my-tickets-test.js
- tests/unit/routes/my-tickets/index-test.js
- tests/unit/routes/my-tickets/past-test.js
- tests/unit/routes/my-tickets/saved-test.js
Creates the UI for my-tickets and it's sub Routes
Fixes #98
> UI for my-tickets and it's sub routes created

- app/routes/events.js
- app/routes/events/draft.js
- app/routes/events/import.js
- app/routes/events/live.js
- app/routes/events/past.js
- app/routes/events/view/export.js
- app/routes/explore.js
- app/routes/profile.js
- app/routes/register.js
- app/templates/components/explore/side-bar.hbs
- app/templates/components/public/copyright-item.hbs
- app/templates/components/quick-filter.hbs
- app/templates/components/widgets/forms/image-upload.hbs
- app/templates/events/view/sessions.hbs
- app/templates/public/sessions.hbs
Some titles were missing on routes, it adds them and adds missing translation helpers for routes as well as templates.
Translation helpers and titles are added where necessary.
Fixes #103
> Adds missing translation helpers, titles to routes and templates

- app/router.js
- app/routes/notifications.js
- app/routes/notifications/all.js
- app/routes/notifications/index.js
- app/templates/components/notification-dropdown.hbs
- app/templates/notifications.hbs
- app/templates/notifications/all.hbs
- tests/unit/routes/notifications-test.js
- tests/unit/routes/notifications/all-test.js
- tests/unit/routes/notifications/index-test.js
Added routes for notifications
Fixes #99
> added routes for notifications

- app/templates/components/settings/application-section.hbs
- tests/integration/components/settings/application-page-test.js
Adds UI for settings/applications.
**Screenshot**
Fixes #128
> Adds UI for settings/applications

- app/router.js
- app/routes/events/view/tickets/orders.js
- app/templates/events/view/tickets/orders.hbs
- tests/unit/routes/events/view/tickets/orders-test.js
Adds the `tickets/order` route UI
Fixes #113
> Adds UI for tickets/order route

- app/templates/events/view/tickets.hbs
Changes the width of the tickets route to 100% of the viewport.
**BEFORE**
**AFTER**
Fixes #135
> Changes width of tickets route to 100%

- app/templates/components/side-bar.hbs
It resolves the lack of  links in the sidebar component due to which buttons were not linked to their respective routes in the mobile navbar which uses sidebar component.
Currently Admin and My sessions route don't exist yet and hence will have to be added later.
Updates the sidebar component which is used in mobile navbar to link the buttons with their respective routes (available ones)
Fixes #139
> Link routes with respective buttons in sidebar component (mobile navbar)

- app/templates/components/nav-bar.hbs
Link My tickets, settings in navbar to respective routes
Fixes #138
> Link My tickets, settings in navbar to respective routes

- app/templates/events/view.hbs
- app/templates/events/view/index.hbs
Fixes #133 
@niranjan94 plz review
> fix: removed divider from events/view.hbs

- app/router.js
- app/routes/events/view/tickets/attendees.js
- app/templates/events/view/tickets/attendees.hbs
- tests/unit/routes/events/view/tickets/attendees-test.js
Adds attendees sub route
Fixes #117
> feat:adds attendees sub route

- app/router.js
- app/routes/events/view/speakers.js
- app/templates/events/view.hbs
- app/templates/events/view/speakers.hbs
- tests/unit/routes/events/view/speakers-test.js
Fixes #125 
https://hidden-badlands-35601.herokuapp.com/events/963d3ba5/speakers
@niranjan94 @geekyd @CosmicCoder96 plz review
> feat: added speakers to events route

- app/controllers/application.js
- app/controllers/events/live.js
- app/controllers/public/index.js
- app/controllers/public/sessions.js
- app/routes/application.js
- app/routes/events/live.js
- app/routes/public/index.js
- app/routes/public/sessions.js
- app/templates/components/ui-table.hbs
- app/templates/events/live.hbs
- app/templates/public/index.hbs
Moves all the dummy data from controllers to route's model method.
Fixes #147
> Moves dummy data to models method of routes

- app/controllers/events/view/tickets/add-order.js
- app/router.js
- app/routes/events/view/tickets/add-order.js
- app/templates/events/view/tickets.hbs
- app/templates/events/view/tickets/add-order.hbs
- tests/unit/controllers/events/view/tickets/add-order-test.js
- tests/unit/routes/events/view/tickets/add-order-test.js
> feat: Add add-order to tickets route

- app/templates/events.hbs
- app/templates/my-tickets.hbs
- app/templates/settings.hbs
Replaces all the tabs with tabbed-navigation, for better UI on mobile devices. 
Deployment link:
https://open-event-frontend-app2.herokuapp.com/
Fixes #163
> Replaces all the tabs with tabbed-navigation

- app/templates/components/nav-bar.hbs
The navbar admin button didn't work
Admin button of the navbar is now linked to admin route
Fixes #166
> Links admin route in the navbar

- app/templates/events/view/tickets.hbs
It links buttons like Overview, Attendees, Order in tickets to their respective routes
Fixes #169
> link buttons in tickets to their respective routes

- app/templates/components/tabbed-navigation.hbs
- app/templates/events/view/tickets.hbs
Makes the event overview vertical menu responsive
Modiefies the `tabbed-navigation` component to accommodate vertical menu as well. 
Fixes #173
> Makes events overview menu responsive

- app/templates/components/nav-bar.hbs
- app/templates/components/side-bar.hbs
Fixes the navbar repetition bug of settings and updates sidebar
* remove repeat option of `settings`
* update sidebar to incorportate changes of #165 and #166 
Fixes #168
> Fixes navbar repetition bug and update sidebar

- app/routes/admin.js
- app/routes/admin/content.js
- app/routes/admin/events.js
- app/routes/admin/messages.js
- app/routes/admin/modules.js
- app/routes/admin/permissions.js
- app/routes/admin/reports.js
- app/routes/admin/sales.js
- app/routes/admin/sessions.js
- app/routes/admin/settings.js
> fix:added titleToken to admin and its sub routes

- app/templates/components/settings/email-preferences-section.hbs
Adds action helper to checkboxes in settings/email-preferences for manipulation value of it.
Fixes #190 
@niranjan94 @CosmicCoder96 Please review. Thanks
> Adds action helper to checkboxes in settings/email-preferences

- app/routes/admin/modules.js
- app/templates/admin/modules.hbs
Adds ui for modules sub-route in admin route.
Deployment link: https://open-event-frontend-app2.herokuapp.com/admin/modules
Fixes #184 
@niranjan94 @CosmicCoder96 Please review. Thanks
> Adds ui for admin/modules

- app/components/ui-table-select.js
- app/components/ui-table-server.js
- app/components/ui-table.js
- app/components/ui-table/cell/cell-link.js
- app/controllers/events/live.js
- app/routes/events/live.js
- app/styles/components/all.scss
- app/styles/components/ui-table.scss
- app/templates/components/ui-table-select.hbs
- app/templates/components/ui-table.hbs
- app/templates/components/ui-table/cell/cell-date.hbs
- app/templates/components/ui-table/cell/cell-link.hbs
- app/templates/components/ui-table/cell/cell-roles.hbs
- app/templates/components/ui-table/cell/cell-sessions.hbs
- app/templates/components/ui-table/cell/cell-tickets.hbs
- app/templates/components/ui-table/component-footer.hbs
- app/templates/components/ui-table/global-filter.hbs
- app/templates/components/ui-table/numeric-pagination.hbs
- app/templates/components/ui-table/page-size.hbs
- app/templates/events/live.hbs
- tests/integration/components/ui-table/cell/cell-link-test.js
- tests/integration/components/ui-table/cell/cell-roles-test.js
- tests/integration/components/ui-table/cell/cell-sessions-test.js
- tests/integration/components/ui-table/cell/cell-tickets-test.js
Improves the ui-table layout & cell templates to render the dummy data.
- Improves the layout of the ui-table to follow semantic-ui as specified [here](https://github.com/fossasia/open-event-frontend/issues/161#issuecomment-306864069)
- Improves the dummy data & the cell-templates to render the dummy data
- Dummy data now mimics the API response
Deployment link : https://open-event-frontend-app.herokuapp.com/events/live
Fixes #161
> Improves layout of ui-table & cell templates. 

- app/components/forms/admin/settings/system-form.js
- app/mixins/form.js
- app/templates/components/forms/admin/settings/system-form.hbs
- app/templates/components/forms/admin/settings/system/mail-settings.hbs
- app/templates/components/forms/admin/settings/system/storage-option.hbs
Adds the form validation to `admin/settings/` system form
Fixes #192
> Adds form validation to admin settings system form

- app/routes/admin/users.js
- app/templates/admin/users.hbs
Added added admin/users route
Fixes #158
https://young-wildwood-91762.herokuapp.com/admin/users
@niranjan94 @geekyd plz review
> feat: added admin/users route

- app/router.js
- app/routes/events/view/tickets/access.js
- app/templates/events/view/tickets.hbs
- app/templates/events/view/tickets/access.hbs
- tests/unit/routes/events/view/tickets/access-test.js
> feat: Add access codes to event tickets route

- app/router.js
- app/routes/events/view/tickets/discount-codes.js
- app/templates/events/view/tickets.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- tests/unit/controllers/events/view/tickets/discount-codes-test.js
adds discount sub route
Fixes #116
> feat:adds discounts sub route

- app/components/forms/admin/settings/system-form.js
- app/templates/components/forms/admin/settings/system-form.hbs
- app/templates/components/forms/admin/settings/system/mail-settings.hbs
- app/templates/components/forms/admin/settings/system/storage-option.hbs
* fixes the broken validation for admin settings system form 
* remove `required=true` from each of the input fields which is causing the bug
* Adds form validation to from name and from email fields which were missing it.
Fixes #211
> Fixes: Broken validation  admin settings system form

- app/routes/admin/sessions.js
- app/templates/admin/sessions.hbs
Fixes #160 
https://young-wildwood-91762.herokuapp.com/admin/sessions
> feat:add sessions route to admin

- app/components/forms/admin/settings/payment-gateway-form.js
- app/components/forms/admin/settings/ticket-fees-form.js
- app/helpers/currency-name.js
- app/helpers/currency-symbol.js
- app/routes/admin/settings/ticket-fees.js
- app/templates/admin/settings/payment-gateway.hbs
- app/templates/admin/settings/ticket-fees.hbs
- app/templates/components/forms/admin/settings/payment-gateway-form.hbs
- app/templates/components/forms/admin/settings/ticket-fees-form.hbs
- tests/integration/components/forms/admin/settings/payment-gateway-form-test.js
- tests/integration/components/forms/admin/settings/ticket-fees-form-test.js
- tests/integration/helpers/currency-name-test.js
- tests/integration/helpers/currency-symbol-test.js
Adds UI for the routes : 
* `admin/settings/ticket-fees`
* `admin/settings/payment-gateway`
Two commits for two separate tabs.
Fixes #199
> Adds UI for admin settings - payment gateways and ticket fees

- app/templates/events/view/tickets/access.hbs
- app/templates/events/view/tickets/add-order.hbs
- Uses common header tag for all the subroutes of `tickets`.
- Removes extra padding of header in `tickets/add-order` route
Fixes #219 
Deployment link: https://open-event-frontend-app2.herokuapp.com/
> Fixes header & padding for subroutes of tickets

- app/templates/events/view/tickets/access.hbs
- app/templates/events/view/tickets/attendees.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/orders.hbs
Makes UI of tables across ticket route uniform
- Corrects the status label of access codes
- Adds compact classes to the tables to prevent overflow
- Implements counting via loop index wherever it was missing
Only visible change: 
Rest are code related
Fixes #223
> Makes UI of tables across tickets route uniform

- app/components/forms/admin/settings/images-form.js
- app/routes/admin/settings/images.js
- app/templates/admin/settings/images.hbs
- app/templates/components/forms/admin/settings/images-form.hbs
- tests/integration/components/forms/admin/settings/images-form-test.js
- Adds UI for admin/settings/images
- Adds form validation for image form in admin/settings/images.
Fixes #203 
Deployment link: https://open-event-frontend-app.herokuapp.com/
> Adds ui for admin/settings/images

- app/components/forms/admin/settings/analytics-form.js
- app/components/forms/admin/settings/microservices-form.js
- app/templates/admin/settings/analytics.hbs
- app/templates/admin/settings/microservices.hbs
- app/templates/components/forms/admin/settings/analytics-form.hbs
- app/templates/components/forms/admin/settings/microservices-form.hbs
- tests/integration/components/forms/admin/settings/analytics-form-test.js
- tests/integration/components/forms/admin/settings/microservices-form-test.js
Adds UI for : 
* `admin/settings/microservices`
* `admin/settings/analytics`
Two commits for two separate routes
Fixes #202
> Adds UI for admin settings: microservices and analytics

- app/components/forms/register-form.js
Removes the redundant condition check in registeration form component
The condition check for incorrect credentials in registration form is removed.
Fixes #226
> Removes redundant check from register form

- app/components/forms/admin/content/social-links-form.js
- app/components/forms/admin/settings/images-form.js
- app/components/forms/admin/settings/microservices-form.js
- app/components/forms/admin/settings/payment-gateway-form.js
- app/components/forms/admin/settings/system-form.js
- app/components/forms/orders/order-form.js
- app/components/forms/register-form.js
- app/components/forms/wizard/basic-details-step.js
All the form validation variables were previously in snake case, not in accordance with the style guide.
- Makes all form validation variables in codebase camelCase
- Adds identifier for form validation where missing
Fixes #
> Makes all form validation variables in codebase camelCase

- app/templates/admin/permissions/system-roles.hbs
- app/templates/admin/sessions/list.hbs
- app/templates/admin/users.hbs
- app/templates/events/view/sessions.hbs
- app/templates/events/view/speakers.hbs
- app/templates/events/view/tickets/access.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/orders.hbs
> feat: Change tooltip to left center

- app/routes/admin/messages.js
- app/templates/admin/messages.hbs
Fixes #221 
https://hidden-badlands-35601.herokuapp.com/admin/messages
> feat:added admin/messages route

- package.json
> chore: pin ember-data to 2.13.1

- app/templates/events/view/tickets/attendees.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/index.hbs
- app/templates/events/view/tickets/orders.hbs
Adds number-format helper to all the routes in the application.
Fixes #258 
@niranjan94 @sumedh123 @CosmicCoder96 @anu-007 @harshitagupta30 @utkarshnath Please review. Thanks!
> Adds missing number-format helper

- app/controllers/admin/sales/marketer.js
- app/routes/admin/sales/marketer.js
- app/templates/admin/sales/marketer.hbs
- tests/unit/controllers/admin/sales/marketer-test.js
This PR adds the UI for the admin/sales/marketer page/
Fixes #243 
Deployment Link: https://open-event-frontend-harshita.herokuapp.com/admin/sales/marketer
@niranjan94 @CosmicCoder96 @geekyd @sumedh123 @utkarshnath @anu-007 Please Review :+1:
> feat: UI for admin/sales/marketer page

- app/router.js
- app/routes/admin/events/import.js
- app/routes/admin/events/index.js
- app/routes/admin/events/list.js
- app/templates/admin.hbs
- app/templates/admin/events.hbs
- app/templates/admin/events/import.hbs
- app/templates/admin/events/list.hbs
- tests/unit/routes/admin/events/import-test.js
- tests/unit/routes/admin/events/list-test.js
Fixes #157 
https://young-wildwood-91762.herokuapp.com/admin/events
> feat:add admin/event route

- app/templates/admin/events/list.hbs
- app/templates/admin/sessions/list.hbs
- [] I have added tests that prove my fix is effective or that my feature works
Adds correct input to moment-format helper in admin/events & admin/sessions 
Fixes #267
> Adds correct input to moment-format helper

- app/controllers/admin/sales/fees.js
- app/routes/admin/sales/fees.js
- app/templates/admin/sales/fees.hbs
- tests/unit/controllers/admin/sales/fees-test.js
Adds UI for `admin/sales/fees`
Fixes #244
> Adds UI for admin sales : fees route

- app/controllers/admin/sales/locations.js
- app/routes/admin/sales/locations.js
- app/templates/admin/sales/locations.hbs
- tests/unit/controllers/admin/sales/locations-test.js
> add admin/sales/locations UI

- app/templates/admin/sales/index.hbs
- app/templates/admin/sales/marketer.hbs
Replaces header tags in sub-routes of admin/sales from h1 to h2.
Fixes #270 
@niranjan94 @anu-007 @CosmicCoder96 @harshitagupta30 @utkarshnath @sumedh123 please review.
> Changes header tag from h1 to h2 in subroutes of sales

- app/controllers/admin/sales/index.js
- app/routes/admin/sales/index.js
- app/templates/admin/sales/index.hbs
- tests/unit/controllers/admin/sales/index-test.js
Adds the missing total row of `admin/sales/index` table
Fixes #248
> Adds total row to table at admin/sales/ index route

- app/controllers/admin/sales/organizers.js
- app/routes/admin/sales/organizers.js
- app/templates/admin/sales/organizers.hbs
- tests/unit/controllers/admin/sales/organizers-test.js
Fixes #260
@geekyd @CosmicCoder96 @sumedh123 @anu-007 @harshitagupta30  Plz review
https://hidden-badlands-35601.herokuapp.com/admin/sales/organizers
> feat:add UI for admin/sales/organizers

- app/routes/admin/sales/status.js
- app/templates/admin/sales/fees.hbs
- app/templates/admin/sales/status.hbs
This PR adds the UI for the admin/sales/status page.
Fixes #261 
Deployment Link: https://open-event-frontend-harshita.herokuapp.com/admin/sales/status
@geekyd @CosmicCoder96 @anu-007 @sumedh123 @utkarshnath Please review :+1:
> feat: UI for admin/sales/status page

- app/templates/admin/sales/status.hbs
> Right align the amount column in invoices tab.

- .travis.yml
> Test new travis image

- app/controllers/admin/sales/discounted-events.js
- app/routes/admin/sales/discounted-events.js
- app/templates/admin/sales/discounted-events.hbs
- tests/unit/controllers/admin/sales/discounted-events-test.js
Adds UI of route `admin/sales/discount-codes`
Fixes #262
> Add UI of admin sales : discount codes

- app/routes/events/view/sessions/list.js
- app/templates/events/view/sessions/list.hbs
Adds correct date variable in events/view/sessions. Replaces `speaker.submittedAt` with `session.submissionDate` from the model function of route.
Fixes #307 
@fossasia/open-event-frontend Please review. Thanks
> Adds correct date variable in events/view/sessions

- app/components/events/view/overview/event-apps.js
- app/components/events/view/overview/event-tickets.js
- app/templates/components/events/view/overview/event-apps.hbs
- app/templates/components/events/view/overview/event-tickets.hbs
- app/templates/events/view/index.hbs
- tests/integration/components/events/view/overview/event-apps-test.js
- tests/integration/components/events/view/overview/event-tickets-test.js
- Adds tickets card to events overview
- Adds apps card to events overview
Fixes #297
Deployment link:
https://open-event-frontend-app2.herokuapp.com/
@niranjan94 @CosmicCoder96 @anu-007 @utkarshnath @harshitagupta30 @sumedh123 Please review.
> Adds tickets & apps card to events overview

- app/styles/partials/all.scss
- app/styles/partials/utils.scss
- app/templates/admin.hbs
This PR resolves the menu overflow on the admin page.
-Made the horizontal overflow auto 
Fixes #284 
@niranjan94 @CosmicCoder96 @geekyd @sumedh123  Please review.
> resolve: menu overflow on admin page

- app/templates/components/forms/admin/settings/payment-gateway-form.hbs
> Fix typo in payment-gateway-info form

- app/routes/events/view/speakers.js
Fixes #327
https://hidden-badlands-35601.herokuapp.com/events/963d3ba5/speakers/
@geekyd @CosmicCoder96  plz review
> fix:removed redundant model from events/view/speakers.js

- package.json
> chore(package): update loader.js to version 4.5.1

- app/services/device.js
- Use js breakpoints instead of depending on css. Should be fine on all the popular browsers
> Use js breakpoints to get device size

- app/components/forms/admin/content/pages-form.js
- app/components/forms/admin/content/translation-form.js
- app/controllers/admin/content/pages.js
- app/routes/admin/content/pages.js
- app/routes/admin/content/translations.js
- app/templates/admin/content.hbs
- app/templates/admin/content/pages.hbs
- app/templates/admin/content/translations.hbs
- app/templates/components/forms/admin/content/pages-form.hbs
- app/templates/components/forms/admin/content/translation-form.hbs
- tests/integration/components/forms/admin/content/pages-form-test.js
- tests/integration/components/forms/admin/content/translation-form-test.js
- tests/unit/controllers/admin/content/pages-test.js
Adds ui for translation & pages in admin/content. Adds functional ui for admin/content/pages along with a pages-form with validation.
Fixes #242 
Deployment Link: https://open-event-frontend-app.herokuapp.com
> Adds ui for translation & pages in admin/content

- package.json
Changes the node version in package.json.
Fixes #352
> Changes node version in package.json

- app/templates/components/events/view/overview/manage-roles.hbs
Fixes the alignment of content within the manage roles component in event overview
Make the buttons center aligned
Fixes #354
> Fix alignment of buttons in manage roles event overview

- app/router.js
- app/routes/events/view/tickets/discount-codes.js
- app/routes/events/view/tickets/discount-codes/index.js
- app/routes/events/view/tickets/discount-codes/list.js
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/discount-codes/list.hbs
- tests/unit/routes/events/view/tickets/discount-codes/list-test.js
splits events/<event-id>/tickets/discount-codes into proper pages
splits events/<event-id>/tickets/discount-codes into-
-`events/<event-id>/tickets/discount-codes`
-`events/<event-id>/tickets/discount-codes/active`
-`events/<event-id>/tickets/discount-codes/inactive`
demo- https://open-event-frontend-branch3.herokuapp.com/events/963d3ba5/tickets/discount-codes
Fixes #291
> splits events/<event-id>/tickets/discount-codes into proper pages

- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- app/templates/components/forms/wizard/sponsors-step.hbs
Changes label of radio button from `turn` to `Turn`.
Fixes #364 
@fossasia/open-event-frontend Please review.
> Changes label text in edits/sponsors & sessions-speakers

- app/components/events/view/overview/manage-roles.js
- app/components/modals/add-user-role-modal.js
- app/templates/components/events/view/overview/manage-roles.hbs
- app/templates/components/modals/add-user-role-modal.hbs
- tests/integration/components/modals/add-user-role-modal-test.js
Adds the add user role modal
Fixes #302
> Adds Modal for add user role in event overview

- app/templates/admin/content/pages.hbs
> fix:change color of button from teal to blue at admin/content/pages

- app/templates/components/public/session-item.hbs
> move icon to front of information in the session-card at '<event_id>/sessions'.

- app/styles/partials/utils.scss
- app/templates/components/modals/tax-info-modal.hbs
This PR resolves the tax modal overflow on edit event page.
Fixes #373
> resolve: tax modal overflow on edit event page

- app/components/forms/register-form.js
- app/controllers/register.js
- app/routes/register.js
- app/serializers/user.js
- app/templates/components/forms/register-form.hbs
- app/templates/register.hbs
- tests/unit/controllers/register-test.js
- tests/unit/serializers/user-test.js
Enables registration using the new API. 
- Adds user serializer for filtering the request.
- Post calls are now handled in the controller.
> Adds register feature using API

- app/templates/admin/sales/discounted-events.hbs
- app/templates/admin/sales/fees.hbs
- app/templates/admin/sales/index.hbs
- app/templates/admin/sales/locations.hbs
- app/templates/admin/sales/marketer.hbs
- app/templates/admin/sales/organizers.hbs
- app/templates/admin/sales/status.hbs
- app/templates/admin/sessions/list.hbs
Fixes #403 
@fossasia/open-event-frontend plz review
> add missing compact class in admin/sales

- app/controllers/index.js
- app/models/speakers-call.js
- app/routes/index.js
- app/serializers/event.js
Enables the speakers call which were previously disabled
- Enable speakers call
- remove the snake case variables in index router
> Refactor public event page to enable speakers call

- package.json
> chore(package): update ember-source to version 2.14.0

- package.json
Reverts fossasia/open-event-frontend#421
> Revert "chore(package): update ember-source to version 2.14.0"

- app/routes/public.js
- app/serializers/event.js
- app/templates/public.hbs
Refactor public page of event to make use on new API for existing fields
Update the components which were using old API to fetch any kind of data
- image 
- date 
- URL
> Refactor public page of event to make use on new API for existing fields

- app/templates/events/view/tickets/add-order.hbs
- app/templates/events/view/tickets/attendees/list.hbs
- app/templates/events/view/tickets/discount-codes/list.hbs
- app/templates/events/view/tickets/orders/list.hbs
> right align quantity, prices of tickets in some routes

- app/templates/components/forms/admin/settings/images-form.hbs
Fixes #435 
@fossasia/open-event-frontend plz review
> fix:set min value to input box in admin/settings/images

- app/templates/components/settings/application-section.hbs
Replaces text with icons in settings/application for all the connect buttons.
Fixes #443
> Enhances connect buttons in settings/application

- app/components/tabbed-navigation.js
- app/templates/components/tabbed-navigation.hbs
- Adds support for dynamic routing pages to tabbed-navigation. `currentRoute` now updates properly in the dynamic routes & the items remain centre aligned.
Fixes #432 
Deployment link : https://open-event-frontend-app.herokuapp.com
> Adds support for dynamic routes for tabbed-navigation

- app/templates/components/forms/wizard/basic-details-step.hbs
- app/templates/components/widgets/forms/ticket-input.hbs
Enhances UI responsiveness of event creation basic step
- fix date field for tablet landscape mode
- make the button sizes same for various steps on mobile
- make ticket code group field fluid for mobile 
- make redeem button responsive for mobile
Fixes #449
> Enhance UI responsiveness of event creation basic step

- app/templates/components/forms/wizard/sponsors-step.hbs
Adds mmin value to levels input in sponsors-step form.
Fixes #375
> Adds min value to levels in sponsors-step form

- app/components/events/event-import-section.js
- app/components/forms/admin/content/translation-form.js
- app/templates/components/events/event-import-section.hbs
adds validation to file before uploading
-added validations to uploaded file format
demo-https://open-event-frontend-branch6.herokuapp.com/events/import
Fixes #436
> adds validation to file before uploading

- app/controllers/register.js
- app/mixins/form.js
- app/models/event.js
- app/models/session.js
- app/serializers/user.js
- tests/unit/controllers/register-test.js
Fixes the failing test for visiting register and registering with existing user
> fix test for registering with existing user

- app/components/forms/wizard/basic-details-step.js
- app/mixins/event-wizard.js
- app/routes/create.js
- app/routes/events/list.js
- app/routes/events/view/edit/basic-details.js
- app/templates/components/forms/wizard/basic-details-step.hbs
- tests/integration/components/forms/wizard/basic-details-step-test.js
- tests/integration/components/modals/tax-info-modal-test.js
- tests/unit/models/event-topic-test.js
- tests/unit/serializers/event-test.js
- tests/unit/serializers/event-topic-test.js
Refactors event-wizard & basic details form for integration of API
> Refactors event-wizard & basic-details form

- app/models/event.js
Fixes Time picker in basic-details form.
Fixes #465 
Deployment link: https://open-event-frontend-app2.herokuapp.com/
> Refactors event model to fix time-picker in basic-details form

- app/controllers/register.js
Fixes info message position for user registration 
Deployment link https://cc96-opev-frontend.herokuapp.com/register
Fixes #463
> Restores info message for new user registration on login dialog

- app/routes/index.js
Changes the filter string to lower case in model() of index.js for events retrieval 
Fixes #473
> Changes filter string to lower case in index.js

- app/components/forms/events/view/create-access-code.js
- app/templates/components/forms/events/view/create-access-code.hbs
> fix:Correct reference to ticketNumber in create-access-code form

- app/adapters/application.js
- app/components/public/ticket-list.js
- app/models/event.js
- app/routes/public/index.js
- app/templates/components/public/ticket-list.hbs
- app/templates/public/index.hbs
- package-lock.json
- package.json
- tests/integration/components/public/ticket-list-test.js
Refactorw public event page to use tickets API
Remlove dummy data for tickets and use API
Fixes #460
> Refactor public event page to use tickets API

- app/components/forms/events/view/create-discount-code.js
- app/router.js
- app/routes/events/view/tickets/discount-codes/create.js
- app/templates/components/forms/events/view/create-discount-code.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/discount-codes/create.hbs
- tests/integration/components/forms/events/view/create-discount-code-test.js
- tests/unit/routes/events/view/tickets/discount-codes/create-test.js
I have added two separate commits one for UI and other for form validation
https://hidden-badlands-35601.herokuapp.com/events/963d3ba5/tickets/discount-codes/create
Fixes #326 
@geekyd @CosmicCoder96 @anu-007 @sumedh123 @harshitagupta30 plz review
> UI for create discount code form

- app/templates/public/index.hbs
Hides the tickets section if not ticket details is available for the event.
Hides if :
- No tickets are available and no ticket URL is available
Deployment Link: https://open-event-frontend-app.herokuapp.com
Fixes #489
> Hides tickets section from public/index if details are not present

- app/styles/partials/overrides.scss
- app/templates/components/errors/not-found.hbs
- app/templates/components/errors/server-error.hbs
- app/templates/components/events/view/export/download-zip.hbs
- app/templates/components/footer-main.hbs
- app/templates/components/forms/forgot-password-form.hbs
- app/templates/components/forms/login-form.hbs
- app/templates/components/forms/register-form.hbs
- app/templates/components/public/session-item.hbs
- app/templates/components/public/ticket-list.hbs
- app/templates/components/widgets/forms/ticket-input.hbs
Resolves logical conflicts with 'less' css class
Redefine the classes and refactor the entire codebase to adjust according to them.
Fixes #501
> Resolve logical conflicts with 'less' css class

- app/styles/pages/public-event.scss
- Increases font size of the event details
- Removes redundant code from public-event.scss
Deployment link: https://open-event-frontend-app2.herokuapp.com/
Fixes #493
> Increases font size of event details in public/index

- app/templates/components/forms/wizard/basic-details-step.hbs
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- app/templates/components/forms/wizard/sponsors-step.hbs
Fixes #490 
https://young-wildwood-91762.herokuapp.com/create
> fix:alignment of buttons in basic-details route

- app/templates/components/footer-main.hbs
- app/templates/components/forms/login-form.hbs
- app/templates/components/public/session-filter.hbs
Adds missing translation helper to templates
Fixes #516
> Adds missing translation helper to templates

- app/components/modals/change-image-modal.js
- app/components/modals/cropper-modal.js
- app/controllers/admin/content/system-images/list.js
- app/router.js
- app/routes/admin/content/system-images.js
- app/routes/admin/content/system-images/list.js
- app/templates/admin/content/system-images.hbs
- app/templates/admin/content/system-images/list.hbs
- app/templates/components/modals/change-image-modal.hbs
- app/templates/components/widgets/forms/image-upload.hbs
- tests/integration/components/modals/change-image-modal-test.js
- tests/unit/controllers/admin/content/system-images/list-test.js
- tests/unit/routes/admin/content/system-images/list-test.js
> Add UI for system-images

- app/components/forms/user-profile-form.js
- app/components/widgets/forms/image-upload.js
- app/controllers/profile.js
- app/models/user.js
- app/routes/profile.js
- app/serializers/user.js
- app/templates/components/forms/user-profile-form.hbs
- app/templates/profile.hbs
- tests/integration/components/forms/user-profile-form-test.js
- tests/unit/controllers/profile-test.js
- Adds user API to profile page
- Improves tests for profile form
Deployment link: https://open-event-frontend-app.herokuapp.com/
Fixes #488
> Integrates user API to profile route

- app/templates/components/forms/admin/content/translation-form.hbs
- app/templates/components/modals/add-system-role-modal.hbs
- app/templates/components/widgets/forms/link-input.hbs
- app/templates/components/widgets/forms/ticket-input.hbs
- app/templates/events/view.hbs
Refactor double quotes to single one in helpers
Fixes #535 
@fossasia/open-event-frontend Please review. Thanks
> refactor double quotes to single in helpers

- app/controllers/admin/modules.js
- app/models/module.js
- app/routes/admin/modules.js
- app/templates/admin/modules.hbs
- tests/unit/controllers/admin/modules-test.js
- tests/unit/models/module-test.js
- Adds modules model
- Implements modules API to admin/modules
Fixes #524
> Adds modules model & implements modules API to admin/modules

- app/models/activity.js
- app/routes/admin/reports/system-logs/activity-logs.js
- tests/unit/models/activity-test.js
- Add activity Model
- Implement activity API on `admin/reports/system-logs/activity-logs`
Fixes #530
> Add activity model & implement activity API on admin/reports/system-logs/activity-logs

- app/components/forms/admin/settings/payment-gateway-form.js
- app/controllers/admin/settings/payment-gateway.js
- app/templates/admin/settings/payment-gateway.hbs
- app/templates/components/forms/admin/settings/payment-gateway-form.hbs
- tests/integration/components/forms/admin/settings/payment-gateway-form-test.js
- tests/unit/controllers/admin/settings/payment-gateway-test.js
- Implement settings API on admin settings payment-gateway
Fixes #529
> Implement settings API on admin settings payment-gateway

- app/templates/public/index.hbs
Hides sponsors section if no sponsors data is available
Fixes #546
> Hides sponsors section if no sponsors data is available

- app/components/settings/contact-info-section.js
- app/controllers/settings/contact-info.js
- app/routes/settings/contact-info.js
- app/serializers/user.js
- app/templates/components/settings/contact-info-section.hbs
- app/templates/settings/contact-info.hbs
- tests/integration/components/settings/contact-info-test.js
- tests/unit/controllers/settings/contact-info-test.js
> feat: add user API for settings/contact-info

- app/components/forms/admin/content/social-links-form.js
- app/components/widgets/forms/link-input.js
- app/controllers/admin/content/index.js
- app/models/setting.js
- app/routes/admin/content/index.js
- app/templates/admin/content/index.hbs
- app/templates/components/forms/admin/content/social-links-form.hbs
- tests/unit/controllers/admin/content/index-test.js
I have split it into two commits as, im trying to achieve two different tasks here. 
- Integrates settings api to content/index
- improves form validation in social-links form
Fixes #539 
Deployment link:
https://open-event-frontend-app.herokuapp.com
> Integrates settings api to content/index & improves form validation in social-links form

- app/controllers/profile.js
- app/controllers/settings/contact-info.js
> Add translation helper to the notification messages

- app/components/forms/wizard/basic-details-step.js
- app/models/event.js
- app/routes/create.js
- app/routes/events/view.js
- app/routes/events/view/edit.js
- app/serializers/application.js
- app/templates/components/forms/wizard/basic-details-step.hbs
[Work In Progress]
- Adds event creation API to basic-details form
Fixes #554
> Adds event API to basic-details form

- app/components/forms/admin/settings/analytics-form.js
- app/components/forms/admin/settings/microservices-form.js
- app/controllers/admin/settings/analytics.js
- app/controllers/admin/settings/microservices.js
- app/models/setting.js
- app/templates/admin/settings/analytics.hbs
- app/templates/admin/settings/microservices.hbs
- app/templates/components/forms/admin/settings/analytics-form.hbs
- app/templates/components/forms/admin/settings/microservices-form.hbs
- app/utils/validators.js
- tests/unit/controllers/admin/settings/analytics-test.js
- tests/unit/controllers/admin/settings/microservices-test.js
- Implement settings API on admin/settings/microservices
- Implement settings API on admin/settings/analytics
Fixes #527
> Implement settings API on admin/settings/microservices & admin/settings/analytics

- app/templates/admin/permissions/event-roles.hbs
- app/templates/admin/permissions/system-roles.hbs
> Replaces <br> tags in system-roles and event-roles with hidden divider

- app/templates/admin/permissions/event-roles.hbs
- app/templates/admin/permissions/system-roles.hbs
Reverts fossasia/open-event-frontend#572
> Revert "Replaces <br> tags in system-roles and event-roles with hidden divider"

- app/routes/my-tickets/past.js
- app/routes/my-tickets/saved.js
- app/templates/my-sessions/past.hbs
- app/templates/my-tickets/index.hbs
- app/templates/my-tickets/past.hbs
- app/templates/my-tickets/saved.hbs
Adding user awareness text if no data available for my-sessions route.
Deployment link: https://gentle-taiga-30801.herokuapp.com/my-sessions
Fixes #396 
@fossasia/open-event-frontend Please Review. Thanks.
> Adding user awareness text if no data available in my sessions

- app/styles/pages/public-event.scss
Fixes title size on the public event page
Fixes #567 
Deployment link: https://open-event-frontend-app2.herokuapp.com/
> Fixes title size on the public event page

- app/components/forms/admin/settings/images-form.js
- app/controllers/admin/settings/images.js
- app/models/image-size.js
- app/routes/admin/settings/images.js
- app/templates/admin/settings/images.hbs
- app/templates/components/forms/admin/settings/images-form.hbs
- tests/unit/controllers/admin/settings/images-test.js
- tests/unit/models/image-size-test.js
- Adds image-size model
- Integrates image-size API to admin/settings/image
Fixes #525
> Integrates image-size API to admin/settings/image

- app/templates/events/view/speakers.hbs
This PR adds compact and tiny class to the button to resolve button misalignment in events/event_id/speakers view.
Added compact and tiny classes to the buttons
Deployment link: https://open-event-frontend-harshita.herokuapp.com/events/3d07e4f5/speakers
Fixes #519 
@fossasia/open-event-frontend Please review! Thanks.
> Adding compact class to buttons for removing misalignment

- app/controllers/admin/permissions/system-roles.js
- app/models/user-permission.js
- app/routes/admin/permissions/system-roles.js
- app/templates/admin/permissions/system-roles.hbs
- tests/unit/models/user-permission-test.js
Implement user-permission API on admin permissions
- Add user-permission model
- Implement user-permission API on admin permissions
- Remove verified user column from the table
Fixes #549
> Implement user-permission API on admin permissions & add user-permission model

- .travis.yml
- scripts/pr_deploy.sh
> Auto deploy to surge on every PR

- app/routes/admin/content/index.js
- app/routes/admin/settings/analytics.js
- app/routes/admin/settings/images.js
- app/routes/admin/settings/index.js
- app/routes/admin/settings/microservices.js
- app/routes/admin/settings/payment-gateway.js
- app/routes/admin/settings/ticket-fees.js
Adds rollback of attributes on transition of all admin routes
Fixes #585
> Add rollback attributes on transition of all admin routes

- app/components/forms/admin/content/social-links-form.js
Adds missing URL validation to admin content social-settings
Fixes #582
> Add missing URL validation to admin content social-settings

- app/components/events/events-table.js
- app/components/ui-table-server.js
- app/components/ui-table/cell/cell-buttons.js
- app/controllers/events/list.js
- app/models/event.js
- app/routes/events/list.js
- app/templates/components/ui-table-select.hbs
- app/templates/components/ui-table.hbs
- app/templates/components/ui-table/cell/cell-buttons.hbs
- app/templates/components/ui-table/cell/cell-date.hbs
- app/templates/components/ui-table/cell/cell-event.hbs
- app/templates/components/ui-table/cell/cell-sessions.hbs
- app/templates/components/ui-table/cell/cell-tickets.hbs
- app/templates/events/list.hbs
- tests/integration/components/ui-table/cell/cell-sessions-test.js
- Adds JSON API support to ember-models-table
- Adds events API to events/list route
Fixes #551 
Deployment link : https://open-event-frontend-app.herokuapp.com/
> Adds JSON API support to ember-models-table & integrates events API to events/list route

- app/templates/components/public/event-map.hbs
- app/templates/public/index.hbs
- Display map using isMapShown
- Hides description if no data is available
Fixes #587
> Display map using isMapShown & hide description if no data is available

- app/controllers/public/sessions.js
- app/router.js
- app/routes/public/sessions.js
- app/routes/public/sessions/index.js
- app/routes/public/sessions/list.js
- app/templates/public/sessions.hbs
- app/templates/public/sessions/index.hbs
- app/templates/public/sessions/list.hbs
- tests/acceptance/public/sessions-test.js
- tests/unit/routes/public/sessions/index-test.js
- tests/unit/routes/public/sessions/list-test.js
Fixes #502 
https://young-wildwood-91762.herokuapp.com/e/3d07e4f5/sessions
@niranjan94 plz suggest changes
> Implement sessions API on public/sessions page

- app/routes/admin/reports/system-logs/activity-logs.js
- app/routes/admin/settings/ticket-fees.js
Replaces empty query call with findAll in models
Fixes #596
> Replace empty query call with findAll in models

- app/components/explore/side-bar.js
- app/routes/explore.js
- app/templates/components/explore/side-bar.hbs
- app/templates/explore.hbs
-  Implement event topic API to sidebar on explore route
-  Implement event sub topic API to sidebar on explore route
-  Implement event type API to sidebar on explore route
Fixes #553
> Implement event-topic,sub-topic,type API on explore route

- app/styles/partials/overrides.scss
Fixes less margin css classes
- correct less top margin
- correct less bottom margin 
Fixes #602
> Fix less margin css classes

- app/routes/index.js
Events on the index route are now sorted by the time of start.
Fixes #608
> Adds sorting of events by starts-at in index route

- app/templates/components/forms/wizard/basic-details-step.hbs
Fixes event type,topic,subtopic dropdowns in event wizard
Fixes #604
> Fix event type,topic,subtopic dropdowns in event wizard

- app/routes/events/list.js
Fixes filters for live and past events
- Categorise the ongoing events as live 
Fixes #611
> Fix filters for live and past events

- app/components/scheduler/external-event-list.js
- app/controllers/events/view/scheduler.js
- app/router.js
- app/routes/events/view/scheduler.js
- app/styles/components/all.scss
- app/styles/components/scheduler.scss
- app/templates/components/scheduler/external-event-list.hbs
- app/templates/events/view.hbs
- app/templates/events/view/scheduler.hbs
- config/environment.js
- package-lock.json
- package.json
- tests/integration/components/scheduler/external-event-list-test.js
- tests/unit/controllers/events/view/scheduler-test.js
- tests/unit/routes/events/view/scheduler-test.js
https://cc96-opev-frontend.herokuapp.com/events/3d07e4f5/scheduler
Fixes #83
> Add scheduler to events/<event:id>/scheduler [UI only]

- app/routes/explore.js
- tests/acceptance/public/schedule-test.js
> Sort the events at /explore in ascending order

- README.md
Before this change:
After this change:
- Updated README to fix markdown for proper doc generation
Fixes #620
> Fixes #620 Add four space indentation according to commonmark

- README.md
- app/styles/partials/overrides.scss
> fixes #619 grammatical changes in README.md

- app/components/nav-bar.js
- app/components/notification-dropdown.js
- app/controllers/application.js
- app/models/notification.js
- app/models/user.js
- app/routes/application.js
- app/routes/notifications.js
- app/routes/notifications/all.js
- app/routes/notifications/index.js
- app/styles/components/notification-dropdown.scss
- app/templates/application.hbs
- app/templates/components/nav-bar.hbs
- app/templates/components/notification-dropdown.hbs
- app/templates/notifications.hbs
- app/templates/notifications/all.hbs
- tests/integration/components/notification-dropdown-test.js
- tests/unit/models/notification-test.js
- tests/unit/models/user-test.js
> Implement notifications api at '/' route

- app/routes/index.js
Fixes event filter in index route for live events, index route now shows ongoing events as well as upcoming events.
Fixes #616
> Fixes event filter in index route for live events

- app/components/forms/wizard/sponsors-step.js
- app/controllers/events/view/edit/sponsors.js
- app/routes/events/view.js
- app/routes/events/view/edit/sponsors.js
- app/templates/components/forms/wizard/sponsors-step.hbs
- app/templates/events/view/edit/sponsors.hbs
- tests/integration/components/forms/wizard/sponsors-step-test.js
- tests/unit/controllers/events/view/edit/sponsors-test.js
- Moves API logic from sponsors route to controller
Fixes #614
> Moves API logic from sponsors route to controller

- app/components/ui-table-server.js
- app/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-for.js
- app/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-time.js
- app/controllers/admin/reports/system-logs/notification-logs.js
- app/routes/admin/reports/system-logs/notification-logs.js
- app/templates/admin/reports/system-logs/notification-logs.hbs
- app/templates/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-for.hbs
- app/templates/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-time.hbs
- tests/integration/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-for-test.js
- tests/integration/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-time-test.js
- tests/unit/controllers/admin/reports/system-logs/notification-logs-test.js
Integrate notification api via ember-model-table on notification-logs
Fixes #623
> Integrate notification api via ember-model-table on notification-logs

- app/components/ui-table/cell/admin/reports/system-logs/activity-logs/cell-time.js
- app/controllers/admin/reports/system-logs/activity-logs.js
- app/routes/admin/reports/system-logs/activity-logs.js
- app/templates/admin/reports/system-logs/activity-logs.hbs
- app/templates/components/ui-table/cell/admin/reports/system-logs/activity-logs/cell-time.hbs
- tests/integration/components/ui-table/cell/admin/reports/system-logs/activity-logs/cell-time-test.js
- tests/unit/controllers/admin/reports/system-logs/activity-logs-test.js
Converts admin activity logs table to ember-model-table
Fixes #629
> Convert admin activity logs table to ember-model-table

- app/components/forms/wizard/sessions-speakers-step.js
- app/controllers/events/view/edit/sessions-speakers.js
- app/mixins/event-wizard.js
- app/models/speakers-call.js
- app/routes/events/view.js
- app/routes/events/view/edit/sessions-speakers.js
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- app/templates/events/view/edit/sessions-speakers.hbs
- tests/unit/controllers/events/view/edit/sessions-speakers-test.js
- Adds tracks,microlocations & session-types API to sessions-speakers
Fixes #594
> Integrates API to sessions-speakers

- app/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions.js
- app/components/ui-table/cell/events/view/tickets/discount-codes/cell-status.js
- app/components/ui-table/cell/events/view/tickets/discount-codes/cell-url.js
- app/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.js
- app/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.js
- app/controllers/events/view/tickets/discount-codes/list.js
- app/models/discount-code.js
- app/routes/events/view/tickets/discount-codes/index.js
- app/routes/events/view/tickets/discount-codes/list.js
- app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions.hbs
- app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-status.hbs
- app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-url.hbs
- app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs
- app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-value.hbs
- app/templates/events/view/tickets/discount-codes.hbs
- app/templates/events/view/tickets/discount-codes/list.hbs
- tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-actions-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-status-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-url-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/discount-codes/cell-value-test.js
- tests/unit/controllers/events/view/tickets/discount-codes/list-test.js
- Integrate discount-codes API on tickets/discount-codes
-  Add missing URL field to discount code model
- ~Add a temp fix to allow hasMany queries in ui-server~ Will be handled later
Fixes #635
> Integrate discount-codes API on tickets/discount-codes

- app/components/ui-table/cell/admin/sales/status/cell-amount.js
- app/components/ui-table/cell/admin/sales/status/cell-dated.js
- app/controllers/admin/sales/status.js
- app/models/event-invoice.js
- app/models/event.js
- app/models/user.js
- app/routes/admin/sales/status.js
- app/templates/admin/sales/status.hbs
- app/templates/components/ui-table/cell/admin/sales/status/cell-amount.hbs
- app/templates/components/ui-table/cell/admin/sales/status/cell-dated.hbs
- tests/integration/components/ui-table/cell/admin/sales/status/cell-amount-test.js
- tests/integration/components/ui-table/cell/admin/sales/status/cell-dated-test.js
- tests/unit/controllers/admin/sales/status-test.js
- tests/unit/models/event-invoice-test.js
- tests/unit/serializers/application-test.js
- tests/unit/serializers/event-test.js
- tests/unit/serializers/user-test.js
- Add event-invoice model 
- Add missing  notification model to user serializer test to prevent build from failing (hence in this PR, separate commit) 
- Implement event-invoice on admin/sales/status
Fixes #647
> Implement event-invoice API on admin/sales/status

- app/components/ui-table/cell/cell-image.js
- app/components/ui-table/cell/cell-sponsor-options.js
- app/controllers/events/view/index.js
- app/routes/events/view/index.js
- app/templates/components/events/view/overview/event-sponsors.hbs
- app/templates/components/ui-table/cell/cell-image.hbs
- app/templates/components/ui-table/cell/cell-sponsor-options.hbs
- app/templates/events/view/index.hbs
- tests/integration/components/events/view/overview/event-sponsors-test.js
- tests/integration/components/ui-table/cell/cell-image-test.js
- tests/integration/components/ui-table/cell/cell-sponsor-options-test.js
- tests/unit/controllers/events/view/index-test.js
Proposed changes in this PR
- Integrates sponsors API to events/view route
Fixes #550
> Adds sponsors API to events/view route

- app/components/ui-table/cell/admin/reports/system-logs/mail-logs/cell-mail-message.js
- app/controllers/admin/reports/system-logs/mail-logs.js
- app/models/mail.js
- app/routes/admin/reports/system-logs/mail-logs.js
- app/templates/admin/reports/system-logs/mail-logs.hbs
- app/templates/components/ui-table/cell/admin/reports/system-logs/mail-logs/cell-mail-message.hbs
- tests/integration/components/ui-table/cell/admin/reports/system-logs/mail-logs/cell-mail-message-test.js
- tests/unit/controllers/admin/reports/system-logs/mail-logs-test.js
- tests/unit/models/event-test.js
- tests/unit/models/mail-test.js
- tests/unit/models/user-test.js
- Adds mail model
- Adds mails API to mail-logs route
- Adds event-invoice to user & event model test
Fixes #652
> Implements mails API to mail-logs route

- app/templates/components/ui-table/numeric-pagination.hbs
Fixes ember-model-table pagination
Fixes #655
> Fix ember-model-table pagination

- app/controllers/admin/events/list.js
- app/controllers/events/list.js
> Add a missing column name to the tables at '/events' and '/admin/events'

- app/templates/components/widgets/twitter-timeline.hbs
- Adds scrolling to tweet section in public route
Fixes #662
> Adds scrolling to tweet section in public route

- app/components/widgets/forms/rich-text-editor.js
Fixes bold functionality of rich text editor
Fixes #664
> Fix bold functionality of rich text editor

- app/adapters/admin-statistics-event.js
- app/adapters/admin-statistics-user.js
- app/models/admin-statistics-event.js
- app/models/admin-statistics-user.js
- app/routes/admin/index.js
- app/templates/admin/index.hbs
- tests/unit/adapters/admin-statistics-event-test.js
- tests/unit/adapters/admin-statistics-user-test.js
- tests/unit/models/admin-statistics-event-test.js
- tests/unit/models/admin-statistics-user-test.js
- Implements events & users API to admin/index route
- Adds admin-statistics-event model
- Adds admin-statistics-user model
Fixes #668
> Integrates events & users API to admin/index route

- app/adapters/admin-statistics-mail.js
- app/adapters/admin-statistics-session.js
- app/models/admin-statistics-mail.js
- app/models/admin-statistics-session.js
- app/routes/admin/index.js
- app/templates/admin/index.hbs
- tests/unit/adapters/admin-statistics-mail-test.js
- tests/unit/adapters/admin-statistics-session-test.js
- tests/unit/models/admin-statistics-mail-test.js
- tests/unit/models/admin-statistics-session-test.js
- tests/unit/serializers/application-test.js
- Add admin-statistics-mail model
- Add admin-statistics-session model
- Implement admin-statistics mail & session API
Fixes #667
> Implement admin-statistics mail & session API

- app/components/ui-table/cell/cell-code-buttons.js
- app/components/ui-table/cell/cell-label.js
- app/components/ui-table/cell/cell-validity.js
- app/controllers/events/view/tickets/access-codes/list.js
- app/models/access-code.js
- app/models/event.js
- app/routes/events/view/tickets/access-codes/index.js
- app/routes/events/view/tickets/access-codes/list.js
- app/templates/components/ui-table/cell/cell-code-buttons.hbs
- app/templates/components/ui-table/cell/cell-label.hbs
- app/templates/components/ui-table/cell/cell-validity.hbs
- app/templates/events/view/tickets/access-codes.hbs
- app/templates/events/view/tickets/access-codes/list.hbs
- tests/integration/components/ui-table/cell/cell-code-buttons-test.js
- tests/integration/components/ui-table/cell/cell-label-test.js
- tests/integration/components/ui-table/cell/cell-validity-test.js
- tests/unit/controllers/events/view/tickets/access-codes/list-test.js
- tests/unit/models/access-code-test.js
- tests/unit/models/event-test.js
- tests/unit/serializers/application-test.js
- tests/unit/serializers/event-test.js
> feat: Integrate the access codes API at '/tickets/access-codes' route.

- app/styles/partials/utils.scss
- app/templates/events/view/tickets/index.hbs
- Adds pointer cursor to all the links in tickets/index route
Fixes #677
> Adds pointer cursor to all the links in tickets/index route

- app/components/forms/wizard/sessions-speakers-step.js
- app/controllers/events/view/edit/sessions-speakers.js
- app/mixins/custom-form.js
- app/mixins/event-wizard.js
- app/models/custom-form.js
- app/models/event.js
- app/routes/events/view/edit/sessions-speakers.js
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- tests/unit/models/custom-form-test.js
- tests/unit/models/event-test.js
- tests/unit/serializers/event-test.js
Implements custom-forms API to sessions-speakers
Fixes #672
> Implements custom-forms API on sessions-speakers

- app/templates/components/nav-bar.hbs
- app/templates/components/side-bar.hbs
- tests/unit/serializers/application-test.js
Hides admin menu for non-admin users
Fixes #704
> Hides admin menu for non-admin users

- app/templates/components/forms/wizard/sessions-speakers-step.hbs
> Make the copy link display completely

- app/templates/components/nav-bar.hbs
This PR resolves the issue of changing the sequence of browse event and notification in nav bar to make it same as eventyay.
Fixes #689 
@fossasia/open-event-frontend Please Review.
> Changing sequence of browse event and notification in nav bar

- app/templates/components/events/view/overview/event-setup-checklist.hbs
- app/templates/events/view/index.hbs
- Changes the UI of the event-setup-checklist from steps to segments
- Integrates API to event-setup-checklist component
Fixes #712
> Implements API to event-setup-checklist

- app/components/ui-table/cell/events/view/tickets/orders/cell-action.js
- app/components/ui-table/cell/events/view/tickets/orders/cell-actions.js
- app/components/ui-table/cell/events/view/tickets/orders/cell-amount.js
- app/components/ui-table/cell/events/view/tickets/orders/cell-order.js
- app/controllers/events/view/tickets/orders/list.js
- app/models/discount-code.js
- app/models/event.js
- app/models/order.js
- app/models/ticket.js
- app/models/user.js
- app/routes/events/view/tickets/orders/index.js
- app/routes/events/view/tickets/orders/list.js
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-actions.hbs
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
- app/templates/events/view/tickets/orders.hbs
- app/templates/events/view/tickets/orders/list.hbs
- tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-actions-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-amount-test.js
- tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
- tests/unit/controllers/events/view/tickets/orders/list-test.js
- tests/unit/models/discount-code-test.js
- tests/unit/models/event-test.js
- tests/unit/models/order-test.js
- tests/unit/models/ticket-test.js
- tests/unit/models/user-test.js
- tests/unit/serializers/application-test.js
- tests/unit/serializers/event-test.js
- tests/unit/serializers/user-test.js
Implements Orders API on tickets route
Fixes #660
> Implement Orders API on tickets route

- app/routes/events/list.js
Changes API for events/list route from `events` to `user/<id>/events`
Fixes #687
> Changes API for events/list route

- app/components/forms/wizard/basic-details-step.js
- app/controllers/create.js
- app/controllers/events/view/edit/basic-details.js
- app/mixins/event-wizard.js
- app/models/ticket.js
- app/routes/create.js
- app/templates/components/forms/wizard/basic-details-step.hbs
- app/templates/components/widgets/forms/rich-text-editor.hbs
- app/templates/components/widgets/forms/ticket-input.hbs
- app/templates/create.hbs
- app/templates/events/view/edit/basic-details.hbs
- app/utils/dictionary/licenses.js
- tests/integration/components/forms/wizard/basic-details-step-test.js
- tests/unit/controllers/create-test.js
- tests/unit/controllers/events/view/edit/basic-details-test.js
- Adds missing API to basic-details & create route
- Removes route actions
Fixes #593 , #709 , #685
> Implements API to create & basic-details routes

- app/models/event.js
- app/models/order-statistics-event.js
- app/models/order-statistics-ticket.js
- app/models/ticket.js
- app/routes/events/view/index.js
- app/serializers/event.js
- app/templates/components/events/view/overview/event-tickets.hbs
- app/templates/events/view/index.hbs
- tests/unit/models/order-statistics-event-test.js
- tests/unit/models/order-statistics-ticket-test.js
- tests/unit/serializers/application-test.js
- tests/unit/serializers/event-test.js
Integrates order-statistics API to event/view/index route
Fixes #676
> Integrates order-statistics API to event/view/index route

- app/templates/components/public/event-map.hbs
Changes the zoom value for maps in public/index
Fixes #747
> Changes the zoom value for maps in public/index

- app/controllers/events/view.js
- app/templates/components/modals/event-delete-modal.hbs
- app/templates/events/view.hbs
Makes delete button in event overview functional
Fixes #752
> Integrate api on delete event button in event overview

- app/controllers/events/view.js
- app/templates/components/events/view/overview/general-info.hbs
- app/templates/events/view.hbs
Makes event view page buttons functional other than the copy button.
Fixes #749
> Make event view page buttons functional and improve layout

- app/templates/components/notification-dropdown.hbs
- app/templates/notifications/all.hbs
> Render the html properly returned by server in the notification dropdown

- tests/unit/serializers/event-sub-topic-test.js
Adds event model to event-sub-topic serializer test
Fixes #759
> Adds event model to event-sub-topic serializer test

- app/controllers/events/view/export.js
- app/services/loader.js
- app/templates/components/events/view/export/download-zip.hbs
- app/templates/events/view/export.hbs
- tests/integration/components/events/view/export/download-zip-test.js
- tests/unit/controllers/events/view/export-test.js
- tests/unit/serializers/user-test.js
> feat: Integrates event export api at event/export route.

- app/controllers/admin/permissions/system-roles.js
- app/models/role.js
- app/routes/admin/permissions/system-roles.js
- app/templates/admin/permissions/system-roles.hbs
- app/templates/components/modals/add-system-role-modal.hbs
- tests/unit/models/role-test.js
Implements roles api for creating roles on admin system-roles
[Creation Only]
Fixes #727
> Implement roles api for creating roles on admin system-roles

- app/components/notification-dropdown.js
- app/templates/components/nav-bar.hbs
- app/templates/components/notification-dropdown.hbs
- Makes notifications accessible by click tab in nav-bar
- Fixes UI for the notification pop-up
Fixes #763
> Makes notifications accessible by click tab in nav-bar

- app/services/loader.js
- bower.json
- ember-cli-build.js
- package-lock.json
> Add multipart file-upload support to loader

- app/components/forms/admin/content/pages-form.js
- app/controllers/admin/content/pages.js
- app/models/page.js
- app/routes/admin/content/pages.js
- app/templates/admin/content/pages.hbs
- app/templates/components/forms/admin/content/pages-form.hbs
- tests/unit/models/page-test.js
> Integrating Pages API on content/pages route under admin

- app/components/modals/cfs-proposal-modal.js
- app/components/public/call-for-speakers.js
- app/templates/components/modals/cfs-proposal-modal.hbs
- app/templates/components/public/call-for-speakers.hbs
- tests/integration/components/modals/cfs-proposal-modal-test.js
> feat: Add the Submit proposal modal for Call for Speakers(UI only)

- app/components/events/events-table.js
- app/components/modals/event-delete-modal.js
- app/components/ui-table/cell/cell-buttons.js
- app/controllers/admin/events/list.js
- app/controllers/events/list.js
- app/templates/admin/events/list.hbs
- app/templates/components/ui-table/cell/cell-buttons.hbs
- app/templates/events/list.hbs
Adds delete functionality to events and admin/events
Fixes #768
> Add delete functionality to events and admin/events

- app/controllers/admin/permissions/system-roles.js
- app/routes/admin/permissions/system-roles.js
- app/templates/admin/permissions/system-roles.hbs
- app/templates/components/modals/add-system-role-modal.hbs
Adds delete & update feature to admin/system-roles route
Fixes #766
> Adds delete & update feature to admin/system-roles route

- app/templates/components/widgets/forms/ticket-input.hbs
Adds min value to ticket price & quantity
Fixes #467
> Adds min value to ticket price & quantity

- app/components/events/view/overview/manage-roles.js
- app/models/event.js
- app/models/role-invite.js
- app/models/role.js
- app/routes/events/view/index.js
- app/templates/components/events/view/overview/manage-roles.hbs
- app/templates/components/modals/add-user-role-modal.hbs
- app/templates/events/view/index.hbs
- tests/integration/components/events/view/overview/manage-roles-test.js
- tests/unit/models/event-test.js
- tests/unit/models/role-invite-test.js
- tests/unit/serializers/application-test.js
- tests/unit/serializers/event-test.js
> List role invites in manage roles in events overview

- app/controllers/events/view.js
- app/templates/events/view.hbs
- tests/acceptance/index-test.js
> feat: Integrate the events copy API to create a similar event

- app/components/settings/password-section.js
- app/controllers/settings/password.js
- app/services/loader.js
- app/templates/components/settings/password-section.hbs
- app/templates/settings/password.hbs
- tests/unit/controllers/settings/password-test.js
> feat: Integrate the change password API at settings/password route

- app/components/forms/wizard/basic-details-step.js
- app/components/public/ticket-list.js
- app/templates/components/forms/wizard/basic-details-step.hbs
- app/templates/public/index.hbs
- Use position attribute of tickets while creating
- Use position attribute of tickets while listing
Fixes #790
> Use position attribute of tickets while creating/listing

- app/controllers/admin/content/index.js
- app/controllers/admin/modules.js
- app/controllers/admin/permissions/system-roles.js
- app/controllers/admin/settings/analytics.js
- app/controllers/admin/settings/images.js
- app/controllers/admin/settings/index.js
- app/controllers/admin/settings/microservices.js
- app/controllers/admin/settings/payment-gateway.js
- app/controllers/admin/settings/ticket-fees.js
- app/controllers/events/list.js
- app/controllers/events/view.js
- app/controllers/events/view/export.js
- app/controllers/profile.js
- app/controllers/register.js
- app/controllers/settings/contact-info.js
> Refactor code to remove redundancy while setting loader to false

- app/controllers/create.js
- app/controllers/events/view/edit/basic-details.js
- app/controllers/events/view/edit/sessions-speakers.js
- app/controllers/events/view/edit/sponsors.js
- app/templates/components/forms/wizard/basic-details-step.hbs
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- app/templates/components/forms/wizard/sponsors-step.hbs
- app/templates/create.hbs
- app/templates/events/view/edit/basic-details.hbs
- app/templates/events/view/edit/sessions-speakers.hbs
- app/templates/events/view/edit/sponsors.hbs
Adds loaders to event creation/edit forms
Fixes #789
> Adds loaders to event creation/edit forms

- app/components/forms/session-speaker-form.js
- app/mixins/custom-form.js
- app/models/custom-form.js
- app/router.js
- app/routes/events/list.js
- app/routes/events/view/sessions/create.js
- app/routes/events/view/sessions/index.js
- app/serializers/event.js
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- app/templates/events/view/sessions.hbs
- app/templates/events/view/sessions/create.hbs
- tests/integration/components/forms/session-speaker-form-test.js
- tests/unit/routes/events/view/sessions/create-test.js
- Adds sessions/create route & session, speaker form
Fixes #757, #359
> Adds sessions/create route & session, speaker form

- app/components/tabbed-navigation.js
This PR resolves the misalignment in tabbed navigation for dynamic routing in admin routes.
Fixes #775
> Misalignment in tabbed navigation for dynamic routing resolved

- app/components/events/view/overview/manage-roles.js
- app/components/modals/add-user-role-modal.js
- app/routes/events/view/index.js
- app/templates/components/events/view/overview/manage-roles.hbs
- app/templates/components/modals/add-user-role-modal.hbs
- app/templates/events/view/index.hbs
- tests/integration/components/events/view/overview/manage-roles-test.js
Adds role Invite creation in event overview
Fixes #796
> Add role Invite creation,edit &delete in event overview

- app/routes/application.js
- app/routes/notifications/all.js
- Sort notifications by `receivedAt`
Fixes #806
> Show most recent notifications at top

- app/router.js
- app/routes/public/coc.js
- app/templates/components/public/side-menu.hbs
- app/templates/public/coc.hbs
- tests/unit/routes/public/coc-test.js
> Add CoC route for public event page

- app/templates/components/nav-bar.hbs
Adds safe-image in nav-bar in place of img tag
Fixes #809
> Adds safe-image in nav-bar

- app/components/forms/admin/settings/system-form.js
- app/models/setting.js
- app/templates/components/forms/admin/settings/system/mail-settings.hbs
Adds missing frontend Url to settings model and form
Fixes #811
> Add missing frontend Url to settings model and form

- app/controllers/events/view/export.js
> Stop the loader when request to task_url is failed in export event

- app/components/forms/wizard/basic-details-step.js
- app/controllers/events/view/edit/sponsors.js
Fixes default dates for tickets
Fixes #822
> Fixes default dates for tickets

- app/components/forms/forgot-password-form.js
- app/templates/components/forms/forgot-password-form.hbs
Implements change password api on forgot password page
- Implement change password api on forgot password page
- Add a success notification to the tempalte
Fixes #827
> Implement change password api on forgot password page

- app/controllers/admin/events/list.js
- app/models/event.js
- app/routes/admin/events/list.js
- app/routes/events/list.js
- app/serializers/ticket.js
- app/templates/components/ui-table/cell/cell-roles.hbs
- app/templates/components/ui-table/cell/cell-sessions.hbs
- app/templates/components/ui-table/cell/cell-tickets.hbs
- tests/integration/components/ui-table/cell/cell-roles-test.js
- tests/integration/components/ui-table/cell/cell-sessions-test.js
- tests/unit/serializers/ticket-test.js
Adds ticket serializer & ticket details to cell-ticket
Fixes #808
> Adds ticket serializer & ticket details to cell-ticket

- app/templates/components/ui-table/cell/cell-buttons.hbs
> Left align the tooltip in the popups at events/list

- app/components/events/events-table.js
- app/components/ui-table/cell/cell-buttons.js
- app/templates/admin/events/list.hbs
- app/templates/components/ui-table/cell/cell-buttons.hbs
- app/templates/events/list.hbs
- tests/integration/components/ui-table/cell/cell-buttons-test.js
- Switch to closure actions for events ember model table
Fixes #843
> Switch to closure actions for events ember model table

- README.md
Adds communication channels to documentation
Fixes #846
> Adds communication channels to documentation

- app/controllers/admin/sessions/list.js
- app/templates/admin/sessions/list.hbs
- app/templates/components/ui-table/cell/cell-simple-buttons.hbs
- tests/integration/components/ui-table/cell/cell-simple-buttons-test.js
Adds delete functionality to admin/sessions
Partially Fixe(s) #835
> Add delete functionality to admin/sessions

- app/routes/application.js
- app/templates/application.hbs
- app/templates/components/footer-main.hbs
Implements settings api on application route for social links
Fixes #855
> Implement settings api on application route for social links

- app/models/user.js
- app/templates/components/ui-table/cell/admin/users/cell-status.hbs
> Add a computed property called 'status' to indicate users status

- package-lock.json
- package.json
> Greenkeeper/ember data 2.15.0

- app/templates/components/footer-main.hbs
Fixes youtube link in footer
Fixes #865
> Fix youtube link in footer

- app/templates/components/nav-bar.hbs
> Fix UI of notification icon for mobile

- app/components/widgets/forms/file-upload.js
- app/routes/events/view/sessions/create.js
- app/styles/partials/utils.scss
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/components/widgets/forms/file-upload.hbs
- app/utils/file.js
- tests/integration/components/widgets/forms/file-upload-test.js
Adds file-upload component
Fixes #849
> Adds file-upload component

- app/templates/components/notification-dropdown.hbs
> Reduce font-weight of notification description

- app/controllers/admin/events/list.js
- app/controllers/admin/reports/system-logs/activity-logs.js
- app/controllers/admin/reports/system-logs/mail-logs.js
- app/controllers/admin/reports/system-logs/notification-logs.js
- app/controllers/admin/sessions/list.js
- app/controllers/events/list.js
- app/controllers/events/view/tickets/access-codes/list.js
- app/controllers/events/view/tickets/attendees/list.js
- app/controllers/events/view/tickets/discount-codes/list.js
- app/controllers/events/view/tickets/orders/list.js
Refactor:  Add  'Actions' heading to buttons column in all tables.
Fixes #878
> Refactor: Add Actions heading to button column in all the tables

- app/styles/partials/nav-bar.scss
- app/templates/components/nav-bar.hbs
This pull request fixes the issue #701 .The screenshots for the same are included. I have provided the min-width to the drop-down for consistent UI also have included the logout icon in the menu item.  
When user has a very short email:
When user has a large email:
- Provides Minimum width to the user information drop-down menu for consistent UI.
- Adds the previously implemented log out icon to the menu item.
Fixes #701
> FIX for dropdown width and logout icon

- app/controllers/events/view/sessions/create.js
- app/controllers/events/view/sessions/list.js
- app/models/session.js
- app/routes/events/view/sessions/create.js
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/events/view/sessions.hbs
- app/templates/events/view/sessions/create.hbs
- app/templates/events/view/sessions/list.hbs
- app/templates/events/view/speakers.hbs
- tests/unit/controllers/events/view/sessions/create-test.js
- Adds speaker & session creation from event panel
- Adds deletion of sessions from events panel
Fixes #792
> Adds creation & deletion of sessions

- README.md
Corrects grammatical mistakes present in the README file.
Fixes #884
> Correct grammatical mistakes in README

- app/templates/notifications/all.hbs
> Add helper text to notifications page

- app/templates/components/events/view/overview/manage-roles.hbs
Helper text appears in the manage roles. 
Fixes #893
> Add helper text to manage roles in event overview

- app/models/custom-form.js
Fixes typo 
Replace Ssubtitle with Subtitle
Fixes #906
> Fix typo in subtitle

- app/styles/partials/welcome.scss
- app/templates/index.hbs
Resolves the change of color of heading on welcome page. (#690)
- Add a class "main-heading" to the heading
- Add a style for the heading in welcome.scss
Fixes a part of #690
> Changed color of heading on welcome page

- README.md
Resolves  README.md missing docs link by adding links to the API docs and the test install on heroku.
- Add links to README.md
Fixes #926
> Add links to the API docs to the README.md

- package-lock.json
- package.json
> Greenkeeper/ember l10n 0.4.1

- app/controllers/events/view/sessions/create.js
- app/routes/events/view/sessions/create.js
- Fixes the session & speaker relationship while creation in create.js controller
Fixes #931
> Fixes session & speaker relationships in session-speaker form

- ubuntu-install-script.sh
This would be a quick way to install open-event-frontend on ubuntu/debian
-Creates a new shell script where deploying the project is easier
Fixes #956
> Create shell file to deploy quickly.

- README.md
- Implied the style which is currently used in `open-event-api-server` **repo**.
- Added `Project Title` :heart:
- Fixed improper `github-badges`.
- Removed strings and Linked the `LICENSE.md` to `README.md` :heart:
- Bullet pointed `Communication` & Highlighted, Quoted URL(s)
- Fixed many typo(s) and used *italics*, **bold** to prettify the `README.md`
> Beautified `README.md` & Themed docs like `open-event-api-server`

- tests/acceptance/events-test.js
- tests/acceptance/my-sessions-test.js
- tests/acceptance/my-tickets-test.js
- tests/acceptance/notifications-test.js
- tests/acceptance/profile-test.js
- tests/acceptance/settings-test.js
Add test for routes to increase code coverage.
Partially Fixes issue #958
> Add test for routes

- app/styles/partials/nav-bar.scss
- app/templates/components/nav-bar.hbs
Fixes the logout text and icon alignment
Fixes #962
> Fix logout icon and text alignment

- app/components/forms/forgot-password-form.js
Adds detailed info message to reset password form
-
Fixes #971
> Add detailed info message to reset password form

- app/components/events/view/overview/event-sponsors.js
- app/controllers/events/view/index.js
- app/templates/components/events/view/overview/event-sponsors.hbs
- app/templates/events/view/index.hbs
Moves the sponsor delete action to the controller for event overview
Fixes #980
> Move the sponsor delete action to controller for event overview

- .github/CONTRIBUTING.md
- README.md
- app/components/ui-table-server.js
- app/templates/components/forms/admin/settings/system/storage-option.hbs
- app/utils/validators.js
- tests/integration/components/public/copyright-item-test.js
- tests/integration/components/public/featured-speaker-list-test.js
- tests/integration/components/public/speaker-item-test.js
- tests/integration/components/public/speaker-list-test.js
- tests/integration/components/public/sponsor-item-test.js
- tests/integration/components/public/sponsor-list-test.js
Previous serving of website links on 'http'
- Migrating the website links that were serving on 'http' to serve on 'https'
-
-
Fixes #987
> Fixes #987: 'Few links still serve on 'http''

- app/components/forms/reset-password-form.js
- app/controllers/reset-password.js
- app/services/loader.js
- app/templates/components/forms/reset-password-form.hbs
- app/templates/reset-password.hbs
- tests/unit/controllers/reset-password-test.js
- Make reset password via token functional
- Add **PATCH** request support to *loader* service
Fixes #1007
>  Make reset password via token functional

- README.md
Updates installation instruction, and adds information for solving error when facing error while installation.
- Updated README.md for installation instruction.
Fixes #1010
> Fixed #1010: 'Check-Node-Version tracks npm: 5.3<=npm<6 and README.md states node.js(with NPM v5.2x)'

- docs/Integrate-local-deployment.md
Adds instruction in documentation for integrating open-event-frontend and open-event-server locally
- Added Instructions for integrated local deployment
-
-
Fixes #992
> Fixed #992: 'Add instructions in documentation to run Open event frontend with open event server local deployment'

- app/controllers/events/view/sessions/list.js
- app/templates/components/ui-table/cell/cell-simple-buttons.hbs
- app/templates/events/view/sessions/list.hbs
- tests/integration/components/ui-table/cell/cell-simple-buttons-test.js
The session can be edited after the edit button is clicked.
- The edit button works on this route.
Fixes #1014
> Add edit functionality to events/{event_identifier}/sessions

- app/templates/explore.hbs
Adds helper text to the explore route.
Fixes #1018
> Add helper text to explore route

- app/controllers/admin/sessions/list.js
- app/templates/admin/sessions/list.hbs
The edit button when clicked helps to edit the session of an event.
- The functionality of the edit button is added in the route admin/sessions
Fixes #835
> Add edit functionality to admin/sessions

- app/components/forms/events/view/create-discount-code.js
- app/controllers/events/view/tickets/discount-codes/create.js
- app/models/discount-code.js
- app/routes/events/view/tickets/discount-codes/create.js
- app/templates/components/forms/events/view/create-discount-code.hbs
- app/templates/events/view/tickets/discount-codes/create.hbs
- tests/unit/controllers/events/view/tickets/discount-codes/create-test.js
Implements discount-code API to the route tickets/discount-codes/create.
- Discount codes are finally being created for the tickets of different events.
Fixes #798
> Implement Discount Code API

- app/controllers/admin/sessions/list.js
- app/templates/admin/sessions/list.hbs
The view button on the route admin/sessions should work.
- The view button on the route admin/sessions should redirect to the path to view a session.
Fixes #1053
> Add view functionality to admin/sessions

- .github/ISSUE_TEMPLATE.md
Added Screenshot and "Would you like to work on it" section in the issue template.
Fixes #1033
> Updated Issue template

- app/components/forms/wizard/sessions-speakers-step.js
- app/templates/components/forms/wizard/sessions-speakers-step.hbs
- Added validations in session-speaker route
Partially Fixes #882
> Fixes#882 Adds validations in session-speaker route

- app/routes/my-sessions.js
- app/routes/my-sessions/index.js
- app/routes/my-sessions/list.js
- app/routes/my-sessions/view.js
- tests/acceptance/my-sessions-test.js
> My sessions error

- README.md
`gloabl` => `global`
Fix a typo in README
> Fix REAMDE typo

- .env.example
- README.md
Setting environment variables `API_HOST` and that in `.env.example`
- Setting environment variables `API_HOST` and that in `.env.example`
-
-
Fixes #1101 Set API_HOST env and cp .env.example to .env
> Fixes #1101 Set API_HOST env and cp .env.example to .env

- .gitignore
Adds `.idea` to gitignore
- Add `.idea` folder to gitignore
Fixes #1098
> fix: Update gitignore to ignore the .idea folder

- app/routes/public/cfs/new-session.js
The title for the new session route was New Speaker.
-  title for the route /e/{event_identifier}/cfs/new-session is added.
Fixes #1108
> Add title for the route /e/{event_identifier}/cfs/new-session

- tests/acceptance/settings-test.js
Add tests for /settings route
Fixes #1103
> Add acceptance tests for settings routes

- app/templates/my-sessions.hbs
Upcoming is spelled as Upcomming in my-sessions route.
- Fixes the type in my-sessions route.
Fixes #1115
> Fix upcoming typo in the my-sessions route

- app/templates/components/event-card.hbs
- app/utils/file.js
Currently uploading an image on any page shows File type not supported error although everything is in correct format. This PR fixes this issue.
- Fixes image uploading n every page.
Fixes #1120
> Fix image uploading on all pages

- app/templates/components/widgets/forms/date-picker.hbs
- app/templates/components/widgets/forms/ticket-input.hbs
- app/templates/components/widgets/forms/time-picker.hbs
Now the `ticket-input` module works for multiple tickets at the same time
- Replace `id` tags with `name` tag to avoid the conflict of two items having the same id.
Fixes #1118
> fix: Second ticket onwards "Maximum Order" stops working

- config/environment.js
- tests/helpers/custom-helpers.js
Currently the frontend is using master branch of the server (deployed at open-event-api.herokuapp.com), it should be using development branch where the development is going on (deployed at open-event-api-dev.herokuapp.com)
Fixes #1140
> Switch to development branch of server for testing and deployment

- package.json
- yarn.lock
> Greenkeeper/ember fetch 4.0.1

- app/controllers/events/view/speakers/list.js
- app/routes/events/view/speakers/index.js
- app/routes/events/view/speakers/list.js
- app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
- app/templates/components/ui-table/cell/events/view/speakers/cell-simple-sessions.hbs
- app/templates/events/view/speakers.hbs
- app/templates/events/view/speakers/list.hbs
Converts the Speakers table into an ember model table and integrates it with the speakers API.
- The speakers table is still not a proper ember table. This PR converts it into that and integrates it with the speakers API.
Fixes #638
> Convert speakers table to ember table and integrate Speakers API on it

- config/environment.js
Fixes the Content Security Policy Voilation
- Added the local host url as a source in config/environment.js
Fixes #1154
> fix: Content Security Policy voilation

- app/components/forms/events/view/create-access-code.js
- app/components/forms/events/view/create-discount-code.js
Fixes access code and discount code URL
Fixes #1166
> Fix generation of access code & discount code url

- app/templates/components/forms/wizard/sessions-speakers-step.hbs
Converted Microlocation floor field to take integer input.
Same as above.
Fixes #1174
> fix: Convert microlocation floor input type to number

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Comments out hints in the issue templates
-Comments out hints in the issue templates
Fixes #1181
> chore: Comment out hints in the issue templates

- app/controllers/events/view/sessions/list.js
- app/templates/components/ui-table/cell/cell-simple-date.hbs
Updates the column Last Modified At in the route /events/{event_identifier}/sessions
- Currently the dates in the columns Last Modified At and Submission Date are same.
- When the session is edited the last modified at column's value should change.
Fixes #1168
> Update the column Last Modified At in the route /events/{event_identifier}/sessions

- app/templates/components/forms/wizard/basic-details-step.hbs
Ticket payment description like paypal email, onsite payment description, cheque payment description and onsite payment description are not saved when saving event.
- These details are not saved.
Fixes #1205
> Fix: Ticket payment description not getting saved

- app/templates/components/widgets/forms/ticket-input.hbs
Inconsistencies: 
1. ticket.descriptionVisible - template but ticket.isDescriptionVisible in model.
2. ticket.ticketHidden - template but ticket.isTicketHidden in model.
3. ticket.absorbFees - template but ticket.isAbsorbFees in model.
Fixes the above ones.
Fixes #1226
> fix: Inconsistency in the ticket-input form and the Ticket model

- app/controllers/admin/users/list.js
- app/templates/components/ui-table/cell/admin/users/cell-last-accessed-at.hbs
The last accessed at column in version1 shows the date of the recent login by the user.
- The common date template is used for this column.
Fixes #1231
> Update Last Accessed At in admin/users

- app/components/unverified-user-message.js
- app/templates/components/unverified-user-message.hbs
- app/templates/events.hbs
- app/templates/events/view.hbs
- app/templates/my-sessions.hbs
- app/templates/profile.hbs
Show alert message on certain routes as per v1 to users whose email is unverified.
- Added message alert box on certain routes.
Fixes #1151
> Show alert message when user's email is unverified

- app/templates/admin/index.hbs
The value of pending sessions in the admin dashboard showed 0 even if pending sessions existed.
- Correct value is shown
Fixes #1230
> Update pending sessions in admin dashboard

- .travis.yml
- config/environment.js
Adds automatic deployment to GitHub pages
- Added a script to automatically deploy the repo to GitHub pages
- Executing this script in the `after-script` section of Travis
Fixes #1218
> chore: Add automatic deployment to Github pages

- app/controllers/events/view/edit/sessions-speakers.js
- app/controllers/events/view/edit/sponsors.js
- app/templates/components/unverified-user-message.hbs
There were some template linting errors and some ES6 syntax errors on JavaScript files.
- Added relevant code to fix the template and ES6 errors.
Fixes #1247
> Fix template linting and ES6 errors

- app/templates/components/nav-bar.hbs
Link browse events to explore route
- Link browse events to explore route
Fixes #1295
> fix: Link "Browse Events" to explore route

- app/components/forms/events/view/create-access-code.js
- app/models/access-code.js
- app/models/user.js
- app/routes/events/view/tickets/access-codes/create.js
- app/templates/components/forms/events/view/create-access-code.hbs
Implements access code API to /tickets/access-codes/create
Implements the access code creation.
Add access codes relationship in user model
Fixes #797
> Implement Access-code API

- Dockerfile
- README.md
- docker-compose.yml
- docs/installation/docker.md
Adds a `docker-compose` and a `dockerfile` for automatic deployment
-
-
-
Fixes #983
> Docker compose

- app/controllers/events/view/tickets/attendees.js
- app/templates/events/view/tickets/attendees.hbs
Make export attendees as CSV and PDF in tickets section of manage events functional
- Make a request to the endpoint provided by the server
Fixes #1338 , Fixes #1337
> feat: Make export attendees as csv and pdf functional

- app/controllers/events/view/sessions/create.js
- app/routes/events/view/sessions/create.js
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/events/view/sessions/create.hbs
The speaker details should have two parts. One where an existing speaker can be chosen or one where a new speaker can be added.
As discussed in the meeting the part in the create session form to add speaker details should have the options to choose a speaker from the existing list of speakers or add a new speaker.
Fixes #1356
> Update Create session form

- app/components/modals/add-user-role-modal.js
Fixes cancel button of dialog creating empty records.
Unloads created record
Fixes #1320
> fix: cancel role invite should not add record

- app/components/public/ticket-list.js
- app/controllers/public/index.js
- app/models/attendee.js
- app/models/order.js
- app/models/ticket.js
- app/router.js
- app/routes/public/index.js
- app/serializers/application.js
- app/templates/components/public/ticket-list.hbs
- app/templates/public/index.hbs
Currently user cannot select tickets and place a order. This PR allows user to select tickets for which he wants to place order and redirect them to orders page (Orders page is not dynamic now. That will be done after this PR is merged)
- Add new actions to select tickets and save order.
- Modify models where ever necessary.
Part of #750
> Allow selecting tickets to place order and redirect to orders page - Part 1

- app/components/forms/events/view/create-access-code.js
- app/controllers/events/view/tickets/access-codes/edit.js
- app/controllers/events/view/tickets/access-codes/list.js
- app/router.js
- app/routes/events/view/tickets/access-codes/create.js
- app/routes/events/view/tickets/access-codes/edit.js
- app/templates/components/ui-table/cell/events/view/tickets/access-codes/cell-actions.hbs
- app/templates/events/view/tickets/access-codes.hbs
- app/templates/events/view/tickets/access-codes/edit.hbs
- app/templates/events/view/tickets/access-codes/list.hbs
Add edit route to access codes, thus allowing organizer to edit a access code.
- Add necessary routes and actions to edit a access code.
Fixes #1362
> Add edit access code route to organizer's dashboard

- config/environment.js
This allows open-event to run in more enviroments. Without compromising default security for EventYAY
-Add a condition that checks if the flag exist
-Sets the csp to a more permissive value
Fixes #1365
> Add CSP flag in order to be more permissive

- app/routes/admin/events/list.js
Even if you delete an event the deleted tab showed no events
- Add proper filtering to admin/events
Fixes #1387
> Add filtering to admin/events

- app/components/explore/side-bar.js
- app/components/widgets/forms/date-picker.js
- app/controllers/explore.js
- app/routes/explore.js
- app/templates/components/explore/side-bar.hbs
- app/templates/components/widgets/forms/date-picker.hbs
- app/templates/explore.hbs
Fixes the date filters in the explore route
- Give the user option of selecting dates manually instead of providing options like Today, yesterday etc.
Fixes #1296
> fix: Fix the Date filters in explore route

- app/components/unverified-user-message.js
- app/templates/components/unverified-user-message.hbs
Implement resend confirmation mail end point and add missing translation helpers.
Fixes #1385
> Implement resend confirmation mail endpoint

- app/templates/components/forms/events/view/create-access-code.hbs
- app/templates/components/forms/events/view/create-discount-code.hbs
- app/templates/components/forms/session-speaker-form.hbs
> Add a few missing translation helpers & fix formatting

- app/controllers/events/view/tickets/orders/list.js
- app/helpers/can-modify-order.js
- app/models/order.js
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-actions.hbs
- app/templates/events/view/tickets/orders/list.hbs
- tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-actions-test.js
Currently action buttons in order list are not functional.
- Adds necessary actions to make them functional.
Fixes #1379
> make action buttons in orders list functional

- app/controllers/public/cfs/edit-session.js
- app/controllers/public/cfs/new-session.js
- app/router.js
- app/routes/public/cfs/edit-session.js
- app/routes/public/cfs/index.js
- app/routes/public/cfs/new-session.js
- app/templates/components/modals/cfs-proposal-modal.hbs
- app/templates/components/public/side-menu.hbs
- app/templates/public/cfs/edit-session.hbs
- app/templates/public/cfs/new-session.hbs
This resolves the bugs related to session details in cfs and adds a route to edit session details for the public session proposals
- Adds a route to edit session proposals entered through the cfs modal.
- Allows the user to enter multiple session proposals 
- Allows the user to edit the session proposals he has submitted
- Sets the user as the speaker for the session proposals he submits through the cfs modal.
Fixes #1402
> Fix bugs related to session details and a route to edit session for cfs

- app/controllers/events/view/speakers.js
- app/templates/events/view/sessions.hbs
- app/templates/events/view/speakers.hbs
Makes exporting sessions and speakers as CSV functional using the endpoint provided by the server.
- Make a GET request to the endpoints `/v1/events/{event_identifier}/export/speakers/csv` and `/v1/events/{event_identifier}/export/sessions/csv` respectively.
Fixes #1408
> feat: Make export as CSV - sessions and speakers functional

- app/components/order-card.js
- app/models/order.js
- app/routes/my-tickets/list.js
- app/templates/components/order-card.hbs
- app/templates/my-tickets/list.hbs
- tests/integration/components/order-card-test.js
Implement My tickets tab.
- Added a new order-card component.
Fixes #1347
> feat: Implement My Tickets tab

- app/controllers/explore.js
- app/routes/explore.js
- app/templates/components/explore/side-bar.hbs
- app/templates/explore.hbs
Implement location filter in the explore route
- Add `location` to the list of query params.
- Use `ilike` operation from https://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html
Fixes #1409
> feat: Implement location filter in the explore route

- app/models/user.js
- app/routes/admin/users/list.js
- app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
It adds information to event role column in admin/users table
- Adds relevant information to the column event roles
Fixes #1298
> Add Event Roles column in admin/users

- app/routes/public/cfs/new-session.js
Adds title to the public form of sessions
Fixes #1434
> Add title to the public session form

- app/controllers/my-sessions/view.js
- app/templates/my-sessions/view.hbs
- The edit session details button works.
- The edit speaker details button works.
- The speakers now are listed below the session.
Fixes #1438
> Fix bugs in the view session route

- app/routes/admin/users/view/events/list.js
admin/users/user_id/events/live is loaded without any error message
Fixes #1436
> remove error message from admin/users/user_id/events/live

- app/models/event-location.js
- app/models/event.js
Adds the location models on the frontend
-Add the models
Fixes #1328
> Add location model

- app/mixins/custom-form.js
- app/models/custom-form.js
- app/router.js
- app/routes/events/view/tickets/order-form.js
- app/templates/events/view/tickets.hbs
- app/templates/events/view/tickets/order-form.hbs
Step one of implementation of the attendee form builder.
Implement custom form builder for attendee
Add forms in the custom-form model
Create them in CustomFormMixin
Fixes #1453
> feat: Implement custom form builder for attendee - Step one.

- app/components/modals/edit-user-modal.js
- app/controllers/admin/users/list.js
- app/templates/admin/users/list.hbs
- app/templates/components/modals/edit-user-modal.hbs
- app/templates/components/ui-table/cell/admin/users/cell-actions.hbs
- Allows super admin to change the admin role of other users
- Will implement the functionality for sales admin and marketer after https://github.com/fossasia/open-event-server/issues/5170 is solved
Fixes #1465
> Add functionality to the edit user modal

- app/models/user.js
Updates the model for users
- Adds missing attributes in users model.
Fixes #1468
> Update user model

- app/adapters/application.js
- app/mixins/event-wizard.js
Notify the user with a proper error message.
Fixes #1478
> fix: Display proper error message during event creation

- app/controllers/public/speakers.js
- app/router.js
- app/routes/public/speakers.js
- app/templates/components/public/side-menu.hbs
- app/templates/components/public/speaker-item.hbs
- app/templates/public/speakers.hbs
Adds speakers page on the public section of the project with the layout a bit similar to the web app.
- Added a separate page for speakers.
- Screenshot:
Fixes #1471
> Adds speakers page on public section

- app/controllers/admin/sessions/list.js
- app/templates/admin/sessions/list.hbs
Adds state of sessions column in the admin panel similar to the events section.
- Adds a column for the state of any session.
Fixes #1494
> Adds state of sessions column in admin panel

- app/controllers/orders/placed.js
- app/routes/orders/new.js
- app/routes/orders/placed.js
- app/routes/orders/view.js
Charge user after receiving stripe token.
- Add process stripe token method.
Fixes #1460 
Parent issue #750
> Stripe Payment: Charge user after receiving stripe token

- app/models/attendee.js
- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-action.hbs
- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
Attendee table in organizer dashboard has some missing fields.
- Add missing fields.
Part of #1497
> Fix attendees table to match version 1

- app/torii-providers/stripe.js
Change redirect url to support ghpages deployment.
- Fix redirect uri.
Fixes #1505
> Fix stripe redirect uri for ghpages deployment

- app/controllers/events/view/tickets/order-form.js
- app/models/event.js
- app/templates/events/view/tickets/order-form.hbs
Now that the event organizer can decide on what information to collect from each user, we should also allow them to set custom order expiry time.
Refactored the UI for the order form and allowed setting custom order expiry time.
Fixes #1492
> feat: Refactor Order form UI and allow setting custom expiry time

- app/services/loader.js
Fixes #1462
This PR fixes the `Bad Request` error for password reset. More importantly, it fixes the `PATCH` functionality that earlier used to incorrectly assign patch body request as query string!
> Fix error for password reset

- app/components/events/view/overview/manage-roles.js
After cancelling modal multiple times after clicks to `Add People` button in Overview -> Manage Roles,  used to stop working.
Fixes #1512
> fix: 'Add People' button stops working after a few clicks

- app/components/forms/events/view/order-form.js
- app/controllers/events/view/tickets/order-form.js
- app/routes/events/view/tickets/order-form.js
- app/templates/components/forms/events/view/order-form.hbs
- app/templates/events/view/tickets/order-form.hbs
- tests/integration/components/forms/events/view/order-form-test.js
Right now the event organizer can have any integer as the order expiry time. time should not be allowed to be negative as it doesn't make sense. Moreover we should also set an upper limit to the expiry time.
- Extract order-form to a component.
- Add validations.
Fixes #1510
> feat: Extract order-form to a component and add validations

- app/styles/partials/footer.scss
Prevents main container from collapsing, fixes loader position
Adds min-height to main container, margin to loader
Fixes #1537
> fix: Prevent main container from collapsing, correct loader position

- app/controllers/events/view/tickets/add-order.js
- app/templates/events/view/tickets/add-order.hbs
Add order button in add order page of organizer dashboard is not functional.
- Add proper actions to allow creating an order.
Fixes #1292
> Add Order: Step 2: Add actions to create an order

- app/components/forms/orders/attendee-list.js
- app/controllers/orders/placed.js
- app/routes/orders/placed.js
- app/routes/orders/view.js
- app/templates/components/forms/orders/attendee-list.hbs
- app/templates/orders/placed.hbs
- app/templates/orders/view.hbs
Implements the new custom attendee form in the attendee-list.
Fixes #1552
> feat: Implement new custom attendee form in attendee-list

- tests/integration/helpers/can-modify-order-test.js
- Add test for can-modify-orders helper.
Related issue #1554
> Add test for can-modify-order helper

- app/templates/components/ui-table-select.hbs
> fix: Add label to quantity dropdown for Events list

- app/components/quick-filter.js
- app/controllers/index.js
- app/routes/index.js
- app/templates/components/nav-bar.hbs
- app/templates/components/quick-filter.hbs
- app/templates/index.hbs
Implements searching functionality on the home page using flask filtering provided by the server.
- Implement search using event name, location, and date range
- Add a clear filters button to clear all the filters
Fixes #1561
> feat: Implement search on the home page using flask filters

- app/models/notification-action.js
- app/models/notification.js
- app/routes/notifications.js
- app/routes/notifications/all.js
The Notification model needs to be updated according to the recent changes in the model on the server. A new model named Notification action should be added as well.
Added Notification action model.
Added relationships with Notification model.
Modified the requests to include actions as well.
Fixes #1559
> feat: Add NotificationAction model and add proper relationships with Notification model

- app/controllers/verify.js
- app/router.js
- app/routes/verify.js
- app/templates/verify.hbs
This PR adds user email verification via front-end. Here is the screenshot after successful email verification:
Fixes #1528
> Implement user email verification on FE

- app/controllers/admin/messages.js
Show a proper message when the save button is pressed in Admin -> Messages route
- Wrap the code in a try-catch block
- Use notify for showing the message
Fixes #1566
> fix: Show proper message when save button is pressed in Admin -> Messages

- app/components/explore/side-bar.js
- app/templates/components/explore/side-bar.hbs
Adds a clear filter button on the explore route
- Add a clear filter button on the explore route
- Implement action to clear all filters
Fixes #1565
> feat: Add clear filter button to explore route

- package.json
- yarn.lock
This reverts commit 1d7943e43c7409ea265dbfc9424ef9910231d8d5.
Reverts PR #1546 
Fixes #1578
> Revert "Update ember-link-action to the latest version 🚀 (#1546)"

- app/models/notification-action.js
- app/models/notification.js
- app/routes/notifications.js
- app/routes/notifications/all.js
- app/templates/notifications/all.hbs
Display buttons in the notifications panel according to Notification actions.
Show them.
Fixes #1576
> feat: Show action buttons in notification panel according to Notification actions.

- app/controllers/notifications/index.js
- app/models/notification.js
- app/router.js
- app/routes/notifications.js
- app/routes/notifications/all.js
- app/routes/notifications/index.js
- app/templates/notifications.hbs
- app/templates/notifications/all.hbs
- tests/acceptance/notifications-test.js
There are some major issues with the notification panel.
1. The mark as read button errors out.
2. The navigation isn't working.
3. Unread notification section also contains the read notifications.
Fixed them.
Fixes #1610
> fix: Major issues with the notification panel

- app/routes/events/view/scheduler.js
- app/templates/components/scheduler/unscheduled-list.hbs
This PR adds code to display microlocations in the event scheduler.
Fixes #1600
> feat: Display microlocations in scheduler

- app/components/public/ticket-list.js
Adds Error message when an invalid promotional code is applied in order wizard.
Fixes #1617
> Adds Error message for invalid promotional code

- app/templates/components/forms/login-form.hbs
- Improves the UI of the login page.
Fixes #1620
> Update UI for the login page

- app/routes/events/view/scheduler.js
This PR adds code to display scheduled sessions on the event scheduler.
Fixes #1606
> feat: display scheduled sessions on scheduler

- app/mixins/event-wizard.js
Reverts fossasia/open-event-frontend#1628
> Revert "fix: Disallow speaker call start, end dates after event end date"

- app/components/public/ticket-list.js
- app/controllers/public/index.js
- app/templates/components/public/ticket-list.hbs
- app/templates/components/unverified-user-message.hbs
- app/templates/public.hbs
Display the appropriate error message to the user as returned by the server.
Fixes #1616
> fix: Display unverified user error message while placing an order.

- package.json
- yarn.lock
Reverts fossasia/open-event-frontend#1641
> Revert "Update ember-cli-babel to the latest version 🚀"

- app/controllers/events/view/tickets/discount-codes/edit.js
> Fix a typo in discount-codes/edit.js

- docs/installation/local.md
Fixes #1663 
Adds a note in the local installation docs that one should clone from a fork to contribute.
added a note in docs as follows:
> Fixes #1663 Add note about contributing from fork in local install docs

- app/controllers/application.js
- app/initializers/blanket.js
- package.json
- yarn.lock
Remove the previous cookie handling which was not compatible with fastboot.
- Adds the ember-cookie package
- Makes cookie handling compatible with fastboot
Fixes #1670
> Make cookie handling compatible with fastboot

- package.json
- yarn.lock
> Greenkeeper/paypal checkout 4.0.223

- package.json
- yarn.lock
> Greenkeeper/sanitize html 1.19.1

- app/routes/events/view/sessions/create.js
- app/transforms/moment.js
Modifies the creation of sessions to ensure that new unscheduled sessions don't have a start and end date.
> Make start and end date null for unscheduled sessions

- app/controllers/events/view/scheduler.js
- app/routes/events/view/scheduler.js
- app/styles/components/scheduler.scss
- app/templates/events/view/scheduler.hbs
Adds ability to unschedule events on the scheduler
> Add ability to unschedule events on scheduler

- app/components/scheduler/unscheduled-session.js
- app/styles/components/scheduler.scss
- app/templates/components/scheduler/unscheduled-session.hbs
- app/templates/events/view/scheduler.hbs
> Add styling to unscheduled sessions

- app/controllers/events/view/scheduler.js
- app/models/event.js
- app/routes/events/view/scheduler.js
- app/templates/events/view/scheduler.hbs
Adds a functional publish/unpublish button to the scheduler
>  Add publish/unpublish schedule button in scheduler

- app/controllers/events/view/scheduler.js
- app/templates/events/view/scheduler.hbs
> Optimize code for publish/unpublish actions in scheduler

- app/models/attendee.js
- app/routes/events/view/tickets/attendees/list.js
- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
> Make attendees table display order details properly

- tests/integration/components/order-card-test.js
- Added test for order-card component
Related issue #1554
> Added test for order-card component

- app/components/forms/login-form.js
- app/components/forms/register-form.js
- app/templates/components/forms/login-form.hbs
- app/templates/components/forms/register-form.hbs
This PR adds show/hide functionality for password in login and register form
Fixes #1681
> Added show/hide functionality for password

- app/serializers/attendee.js
Make attendees use originalId of order for requests
Fixes #1757
> Fix: Order wizard payment flow

- app/templates/components/ui-table.hbs
- app/templates/components/ui-table/simple-pagination.hbs
> Add number of entries summary to pagination

- package.json
> fix: pin ember-router-scroll to 1.0.1

- .dockerignore
> fix: Remove .env from .dockerignore

- app/templates/orders/placed.hbs
It fixes UI of Pay with card button to pay for tickets through stripe
- Added class to `Pay with Card` button
**Earlier**
**Now**
Fixes #1569
> Fixes UI of Pay with card button to pay for tickets through stripe

- Dockerfile
> fix: Make docker builder lean and lite

- app/templates/components/ui-table/cell/cell-buttons.hbs
- Placed `view icon` on the top in events table
Fixes #1811
> Placed view icon on top in events table

- app/templates/components/ui-table/cell/cell-sessions.hbs
- app/templates/components/ui-table/cell/cell-tickets.hbs
- Removed Number and bullets from events table by changing class of cell
Fixes #1809
> Number and bullets removed from events table

- app/routes/my-tickets/list.js
- app/templates/components/order-card.hbs
- app/templates/my-tickets.hbs
- tests/acceptance/my-tickets-test.js
-  Removes saved events sub-route for my-tickets
-  Optimizes order card
Fixes #1801
>  Remove saved events sub-route for my-tickets & optimize order card

- app/utils/dictionary/payment.js
Added Clear Currency Info
-Added Clear Currency Info
Fixes #1828
> Added Clear Currency Info

- app/templates/components/public/side-menu.hbs
- Adds side menu component to the public pages of sessions and speakers.
Fixes #1799
> Add sidebar to public sessions and speakers page

- app/templates/components/orders/event-info.hbs
- Ticket Page shows correct time
Fixes #1847 
@mariobehling  @CosmicCoder96  Please review.
> Ticket Page shows correct time

- app/templates/components/public/speaker-item.hbs
> Render the html for speakers after sanitization

- app/templates/components/ui-table/cell/cell-event.hbs
> Show the event name below it's logo in tables

- app/controllers/events/view/sessions/edit.js
- app/helpers/custom-related-field.js
- app/routes/events/view/sessions/edit.js
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/events/view/sessions/edit.hbs
> Add custom forms to the session edit page

- app/utils/validators.js
Enhances the regex used to include the possibility of URL containing 'www'
Fixes #1859
> Fix social media validations on speaker page

- app/templates/components/footer-main.hbs
- Category Filters Fielding Results
Fixes #1821
> Fix Category Filters Fielding Results

- app/templates/components/forms/orders/order-form.hbs
> Put payment method in separate section for orders page

- app/templates/events/view/scheduler.hbs
> Make it easier to enter short sessions on scheduler

- Dockerfile
Generates all the missing translation files while deploying.
Fixes #1806
> Generate translation files for l10n

- app/templates/components/forms/orders/order-form.hbs
> Fix Bug: Broken stripe payment gateway

- app/components/forms/events/view/create-discount-code.js
- app/components/public/ticket-list.js
- app/controllers/public/index.js
- app/routes/events/view/tickets/discount-codes/create.js
- app/templates/components/forms/events/view/create-discount-code.hbs
- app/templates/public/index.hbs
- Adds default values when the creation of a discount code is triggered so that the PATCH/POST request to the server doesn't fail.
- Modify the query parameter in discount code routes to match that of the legacy server.
- Fix the issue with date picker rendering all date values as invalid.
- Modify the existing components and actions to make discount code URLs functional
This PR effectively allows the creation, editing, and application of discount codes.
> Fix: Creation, Editing and Application of Discount Codes

- app/styles/partials/text.scss
- app/templates/components/public/ticket-list.hbs
> Strike through original price to show discounts

- app/components/ui-table-server.js
- app/templates/components/ui-table-select.hbs
Added Show  100, 250, All
-
-
-
Fixes #1906
> Added Show  100, 250, All

- app/templates/components/public/speaker-item.hbs
Make use of speaker thumbnail images for speaker-item.
Fixes #1916
> Optimize images on speaker route and for featured speakers

- app/controllers/events/view/speakers/list.js
- app/templates/components/ui-table/cell/events/view/speakers/speaker-logo.hbs
- Adds the speaker logo to the Speakers Table
Fixes #1816
> Add speaker logo to the Speakers Table

- app/components/quick-filter.js
- app/templates/components/quick-filter.hbs
Adding Enter key functionality to search events on homepage
-Adding Enter key functionality to search events on homepage
-
-
Fixes #1893
> Adding Enter key functionality to search events on homepage

- app/components/ui-table-server.js
- app/templates/admin/events/list.hbs
- app/templates/admin/sessions/list.hbs
- app/templates/admin/users/list.hbs
- app/templates/events/view/sessions/list.hbs
- app/templates/events/view/speakers/list.hbs
- app/templates/events/view/tickets/access-codes/list.hbs
- app/templates/events/view/tickets/attendees/list.hbs
- app/templates/events/view/tickets/discount-codes/list.hbs
- Overrides default behavior of ember server paginated table.
- Ember Model Table: Adds support for a custom global filter
- Adds a functional global filter to admin-events
- Adds a functional global filter to admin-users
- Adds a functional global filter to admin-sessions
- Events: Adds search for sessions
- Events: Adds search for speakers
- Events: Adds search for access codes
- Events: Adds search for attendees
- Events: Adds search for discount codes
Fixes #1933
> Implement a customised global search across tables in Open Event Frontend

- app/initializers/blanket.js
- app/routes/index.js
- app/styles/components/all.scss
- app/styles/components/infinity-loader.scss
- app/templates/index.hbs
- package.json
- yarn.lock
- Add ember-infinity-model
- Introduce it as a service
- Integrate it on the index route for the time being
Fixes #1940
> Implement a lazy loading solution for components

- app/components/forms/session-speaker-form.js
- app/controllers/events/view/sessions/create.js
- app/controllers/events/view/sessions/edit.js
- app/routes/events/view/sessions/create.js
- app/routes/events/view/sessions/edit.js
- app/templates/components/forms/session-speaker-form.hbs
- app/templates/events/view/sessions/create.hbs
- app/templates/events/view/sessions/edit.hbs
- List all the speakers of the event in the list of existing speakers for create/edit routes.
- Session edit and create: add option to add/remove speakers.
Fixes #1888
> Sessions: Edit and Create routes revamped

- app/templates/components/forms/session-speaker-form.hbs
` {{speakersDetails}}` should not be present.
> remove debugging text from session-speaker form

- app/templates/components/public/session-item.hbs
- tests/integration/components/public/session-item-test.js
- Removes console errors for the public page of sessions.
Fixes #1927
> Remove 404 console error for public/sessions

- docs/installation/docker.md
Updates the docker installation instructions of the project.
Fixes #1972
> Update Docker Instructions

- app/templates/components/order-card.hbs
After this, the images in the tickets will be linked to the ticket page.
- changing `href` of the images
Fixes #1978
> Linking images to ticket details

- app/templates/components/forms/login-form.hbs
- app/templates/components/forms/register-form.hbs
password is no longer visible , when we pressed enter the button was triggered , now it is not triggered.
Fixes #1974
> password not visibe on pressing enter

- app/components/forms/reset-password-form.js
- Redirecting Users to Login
Fixes #1899
> Redirecting Users to Login

- app/styles/partials/nav-bar.scss
Take out  JS effects on menu
- Take out  JS effects on menu
Fixes #1992
> Take out  JS effects on menu

- app/controllers/events/view/sessions/list.js
- Adds functionality to the view button for sessions, as in v1
Fixes #1950
> Add functionality to the view button for sessions

- app/controllers/events/view/sessions/list.js
- app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
- app/templates/events/view/sessions/list.hbs
- Adds a button to confirm a session proposal with or without a mail.
Fixes #1861
> Add confirm speaker action to sessions table

- app/helpers/session-color.js
- app/templates/components/session-card.hbs
- app/templates/components/ui-table/cell/events/view/sessions/cell-session-state.hbs
- app/templates/my-sessions/view.hbs
- Adds correct colors to all the labels of sessions.
Fixes #2006
> Add correct labels to different sessions

- translations/bn.po
- translations/de.po
- translations/en.po
- translations/es.po
- translations/fr.po
- translations/hi.po
- translations/id.po
- translations/ja.po
- translations/ko.po
- translations/messages.pot
- translations/pl.po
- translations/ru.po
- translations/th.po
- translations/vi.po
- translations/zh.po
- translations/zh_Hans.po
- translations/zh_Hant.po
Regenerate .po files to account for the new strings introduced since 2017.
> Update translation files

- app/components/ui-table/cell/events/view/tickets/cell-add-order-price.js
- app/controllers/events/view/tickets/add-order.js
- app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-price.hbs
- app/templates/events/view/tickets/add-order.hbs
- tests/integration/components/ui-table/cell/events/view/tickets/cell-add-order-price-test.js
Add order section ticket will parse currency correctly
-Added new component cell-add-order-price
-Added the test case for the same
Fixes #2048
> Add cell-add-order-price component and its test

- app/styles/components/events/view/export.scss
- app/templates/components/events/view/export/api-response.hbs
Added vertical scroll to response in Export
Fixes #2049
> Add vertical scroll to response in Export

- app/components/ui-table-server.js
- app/templates/components/ui-table/header-row-sorting.hbs
This PR resolves the broken sorting in all the ember model tables is broken. 
Fixes #2063
> Fix sorting across the app

- app/templates/components/events/view/overview/event-tickets.hbs
Display Available tickets and Total tickets separately in Ticket Summary
Fixes #2061
> Display Available tickets and Total tickets separately in Ticket Summary

- app/routes/events/view/edit.js
After this PR, the newly added changes for `basic-details-step` can be reflected in the `edit-form` steps too which was earlier not handled
- Included module model in `events.view.edit`
Fixes #2098
> Adding module in event edits

- app/templates/components/public/session-item.hbs
Fixes: #2074
The orientation of date in sessions card was not proper. This PR fixes the orientation of the date in the sessions card.
- Fixed the alignment of the date in sessions card.
> Fix date alignment in the session card.

- app/controllers/events/view/tickets/attendees/list.js
- app/models/attendee.js
- app/routes/events/view/tickets/attendees/list.js
Adds attendee check-in time to the request.
Fixes #2111
> Fix 422 error on attendee checkin

- app/components/ui-table-server.js
Please revert if any other inconsistency occurs due to this fix.
Fixes #1814
> Trial: Fix flickering in tables

- tests/acceptance/admin-sales-accessibility-test.js
- Added admin sales accessibility blocking for unauthenticated users
- Added acceptance test
> Admin-sales test for unauthenticated users

- app/templates/components/order-card.hbs
- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
- Display dates based on order status
- Fixes the invalid date appearing on my tickets page.
Fixes #2084
> Fix order date display across the app

- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs
- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs
> Show discount code while listing orders, if applied

- app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-action.hbs
- The text of the button no more splits into two lines.
Fixes #2132
> Improve the UI of the Check-In button

- app/controllers/index.js
It makes sure that the events with sessions and speakers enabled produces cfs on the index page. 
- Adding `sessionSpeakers` as a conditional
Fixes #2136
> Adding sessionSpeakers as a conditional

- app/models/user.js
- app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
- Adds event role relationships to user model
- Optimizes Admin/users route
- Improves UI/UX
Fixes #2138
> Optimize Admin/users route

- app/routes/events/view/scheduler.js
- app/templates/events/view/scheduler.hbs
- For 1 day view rooms are now on top (agendaView) earlier rooms were on 1st column (timelineView):
- For multi day view rooms are visible now:
Fixes #1864 
Fixes #1865
> Refactor Scheduler views

- app/models/speaker.js
- app/models/user.js
Several image fields in both the models were missing.
> Add missing fields to speaker & user  models

- app/components/forms/orders/guest-order-form.js
- app/components/modals/login-signup-modal.js
- app/templates/components/forms/orders/guest-order-form.hbs
- app/templates/components/modals/login-signup-modal.hbs
- tests/integration/components/forms/orders/guest-order-form-test.js
- Creates a proper form component for the email-password form
- The enter keypress event is handled automatically, previously it incorrectly added the email as a query parameter and tried to submit the form.
> Enhance non logged in user order checkout experience

- app/templates/components/footer-main.hbs
- Events getting filtered on the basis of locations in the filter.
Fixes #2164
> Filter events on the basis of locations in the footer

- app/templates/components/forms/events/view/create-discount-code.hbs
Reverts fossasia/open-event-frontend#2102
Fixes #2197
> Revert "Using Event's payment currency in Add Discount Code form"

- app/templates/components/forms/wizard/basic-details-step.hbs
Using `sanitize` helper to remove HTML character
- Using sanitize to remove html stubs from server
Fixes #2022
> Using sanitize to remove html elements

- app/components/forms/register-form.js
A follow on to the API min pass length change
- Update min pass length to 8
Fixes #2200
> Update min pass length to 8

- app/routes/index.js
It makes  sure that only public events are being listed in the index page
- adding privacy check in filter
Fixes #2211
> adding privacy check in filter

- app/models/admin-sales-by-organizer.js
- app/templates/admin/sales/organizers.hbs
This fixes the `admin-sales-organiser`  model and the corresponding template in the admin section.
- fix the syntax error in the template
- Adding email to be shown in case the profile contains no name
Fixes fossasia/open-event-server#5621
> adding email in admin-sales-organiser model

- app/components/forms/orders/attendee-list.js
- app/components/orders/event-info.js
- app/components/orders/ticket-holder.js
- app/templates/components/forms/orders/attendee-list.hbs
- app/templates/components/forms/orders/order-form.hbs
- app/templates/components/orders/event-info.hbs
- app/templates/components/orders/order-summary.hbs
- app/templates/components/orders/organizer-info.hbs
- app/templates/components/orders/ticket-holder.hbs
- app/templates/orders/new.hbs
- app/templates/orders/placed.hbs
- app/templates/orders/view.hbs
This PR redesigns the placed order Preview page along the lines of 
- Phase 1
- Redesigning the event information component
- Realignment of Payment tabs and swapping the positions of event information and order summary
- Elaborating the Organiser details  and relocating it
- Phase 2
- Breaking down Ticket Holder-information into Payee Info and Attendee Info
- Removing `input_fields` and using placeholders instead
- Creation of new ticket-holder component to hold Payee Info
- Phase 3
- Adding Details Row in the ticket-holder section
- Removing Payment information from billing section
- Making Billing Information section visibility toggle enabled
Now : Fix build and work on reviews
Fixes #1867
> Redesigning the Placed Order Preview Page

- app/templates/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-for.hbs
- tests/integration/components/ui-table/cell/admin/reports/system-logs/notification-logs/cell-for-test.js
- adding email of recipient in the For section 
- sending an appropriate message whenever the user name is not available
Fixes #2229
> fix : improve "For" cell in admin/reports | notification

- app/components/forms/wizard/basic-details-step.js
Fix bugs in Basic Details
Fixes #2222
> Fix bugs in Basic Details

- app/templates/components/forms/wizard/sessions-speakers-step.hbs
Indicates required element in the session-speaker-form
- adding required class in labels
Fixes #2240
> enh : add required label on session fields

- app/components/events/view/overview/general-info.js
- app/components/modals/event-revision.js
- app/components/range-slider.js
- app/templates/components/events/view/overview/general-info.hbs
- app/templates/components/modals/event-revision.hbs
- package.json
- yarn.lock
This adds a UI for the modal of event revisions.
- Add a UI for event revisions modal.
Screenshots:
Fixes: #2192
> Create UI for events revision dialog modal.

- app/routes/admin/users/view/tickets/list.js
Upcoming and past events are now visible. 
Fixes #2257
> filter added to separate upcoming and past events on user ticket route

- docs/installation/local.md
The given API link in docs shows CSP violation 
Fixes #2281
> Correct API link in docs.

- app/components/forms/wizard/basic-details-step.js
> use destroyRecord instead of deleteRecord while deleting tickets

- app/templates/events/list.hbs
It makes sure that Global Filter uses event name to filter results
- add a `custom-global-filter` in `events` table
Fixes #2220
> fix : apply global filter in manage event

- app/routes/admin/users/view/sessions/list.js
This makes sure that all the sessions of a user are being shown regardless of any time cosntraints
- filter events similar to my-session route
Fixes #2290
> filter events similar to my-session route

- app/templates/events/view/tickets/attendees.hbs
- app/templates/events/view/tickets/orders.hbs
Fix UI bug in filter by in Orders and attendees under Tickets Section
Fixes #2320
> Fix UI bug in filter by in Orders and attendees under Tickets Section

- app/routes/public/index.js
- app/routes/public/speakers.js
speakers are visible if session is confirmed
Fixes #2339
> speakers are visible if session is confirmed

- app/templates/admin/reports/system-logs/activity-logs.hbs
- app/templates/admin/reports/system-logs/mail-logs.hbs
Makes sure that 2 out of 3 filters are working
- add `customGlobalFilter` in mail-logs and activity-logs
Fixes #2331
> fix: Add custom global filters in report tabs

- app/models/admin-sales-by-event.js
- app/models/admin-sales-discounted.js
- app/templates/admin/sales/discounted-events.hbs
- app/templates/admin/sales/fees.hbs
- app/templates/admin/sales/index.hbs
- app/templates/admin/sales/locations.hbs
- app/templates/admin/sales/marketer.hbs
- app/templates/admin/sales/organizers.hbs
_By Events_
_Fees_
- Removes `Total` from Admin Sales 
- Removes hard-coded currency
Fixes #2316
> Removed Total and added event's paymentCurrency in Admin Sales

- tests/acceptance/explore-test.js
- Added acceptance test for explore route
Fixes #1774
> Adds acceptance test for explore route

- app/templates/components/forms/admin/settings/system-form.hbs
> Remove 'Coming Soon' for elastic search in Admin settings 

- app/templates/components/forms/admin/settings/images-form.hbs
> Move 'Found in' to newline in Admin's image settings

- app/templates/components/public/ticket-list.hbs
Increases the number of order-able tickets by 1
- use math helper to increase the number of order able tickets by 1 in the dropdown
Fixes #2404
> Increasing the number of order-able tickets by 1

- app/serializers/event-statistics-general.js
Makes sure that speaker component loads up correctly
- update serializer and the payload
Fixes #2380
> Update serialise to deal with snake_case in event-statistic-general 

- app/templates/components/forms/register-form.hbs
Solves toggle switch icon for hide/show Password
- Added a condition to check on eye-icon
Fixes #2450
> Add Toggle Eye

- app/styles/components/events/view/export.scss
- app/templates/components/events/view/export/api-response.hbs
Follow up PR for PR #2086 
Optimizes code.
> Code optimization: API Response URL - Remove CSS

- app/templates/components/widgets/forms/file-upload.hbs
- app/templates/components/widgets/forms/image-upload.hbs
Fixes the typo ..(See commit)
- Update `image-upload.hbs`
Fixes #2466
> Fixes incorrect image storage instruction

- app/templates/components/orders/order-summary.hbs
Fixed the typo in order summary
- Corrected the spelling and the Reference given for events link
Fixes #2464
> Correcting typo in order summary

- app/models/user.js
Changes inactivity period from year to month
Fixes fossasia/open-event-server#5739
> Change route filter according to User's status

- app/templates/components/public/copyright-item.hbs
Fixes #2498
-  [x] I have added tests that prove my fix is effective or that my feature works
Checks for license url and displays 'Not under any license' if not present
- Added check for license
> License check

- .github/ISSUE_TEMPLATE/bug_report.md
> Correcting typo in 'Bug_Report' template

- tests/integration/helpers/session-color-test.js
Adds an integration test for session-color helper
- uses default and specialised case for testing
Fixes #2527
> add session color integration tests

- app/templates/admin/modules.hbs
This PR makes it possible to save the changes by clicking on toggle buttons present in modules section in admin settings.
- Pass the submit action in onchange of inputs along with the input name.
- In controller check for input changed and set its value.
- Save the changes.
Fixes: #2485
> Save changes on clicking toggle input in admin modules settings.

- app/services/loader.js
Adds a download file method to the loader service.
> Loader service: Add a downloadFile method

- app/templates/components/events/view/overview/general-info.hbs
-  [x] The acceptance, integration, unit tests and linter pass locally with my changes 
Adding muted coming soon and removing the link to demo slide bar .
Fixes #2526
> Adding coming soon for no of revision

- app/routes/admin/users/list.js
- fixed inactive user filterOptions in Admin Users' section
Fixes #2455
> fixes inactive user filter in Admin Users

- app/routes/admin/users/list.js
Reverts fossasia/open-event-frontend#2551
> Revert "fixes inactive user filter in Admin Users"

- app/templates/components/forms/wizard/sessions-speakers-step.hbs
Fixes the typo.
- Update `sessions-speakers-step.hbs`
Fixes #2535
> Fixes the typo in the Sessions-speakers page

- app/templates/components/ui-table/cell/events/view/tickets/orders/cell-actions.hbs
Remove cancel action from expired orders
Fixes #2496
> Remove cancel action from expired orders

- app/templates/admin/users/view/tickets.hbs
User ticket list UI improved on users tickets page
Fixes #2595
> User ticket list UI improved on users tickets page

- app/templates/components/settings/contact-info-section.hbs
Added asterisk after label on settings/contact-info
Fixes #2592
> Added asterisk after label on settings/contact-info

- app/components/forms/session-speaker-form.js
mobile number validated on speaker create page
Fixes #2574
> mobile number validated on speaker create page

- app/models/user.js
- app/templates/components/ui-table/cell/admin/users/cell-status.hbs
The status of deleted users is either `Active` or `Inactive`. It never shows `Deleted`.
- Introduced `Deleted` status for deleted users
Fixes #2550
> fix:status of deleted users set to Deleted

- app/templates/public/index.hbs
I am using model.event to access ticketUrl for the event
-  use model.event to call ticketUrl
Fixes #2622
> Fix usage of ticketUrl on index

- app/templates/components/settings/password-section.hbs
- Adding Class required to password section
Fixes #2637
> Adding Class required to password

- app/templates/components/session-card.hbs
Event image is visible on my session page
Fixes #2589
> Event image visible on my session page

- tests/integration/helpers/header-date-test.js
Created header date integration test
- Using moment data to create a known timezone test
Fixes #2655
> test: header-date integration test

- app/controllers/admin/events/list.js
Addition of Speaker Breakdown in *Admin/Event/*
Fixes #2630
> Adding speaker section breakdown in 'Admin/Event'

- app/templates/components/events/view/overview/event-sponsors.hbs
Adding customGlobalFilter in sponsor component of event/sponsor
Fixes #2642
> add customGlobalFilter for sponsor component

- app/components/tabbed-navigation.js
- app/templates/components/tabbed-navigation.hbs
Reverts fossasia/open-event-frontend#2489
> Revert "Add a down arrow in tabbed navigation to indicate button as a dropdown in mobile devices."

- app/components/forms/wizard/sponsors-step.js
- app/templates/components/forms/wizard/sponsors-step.hbs
The validation rules are now applied to sponsors URLs
Fixes #2639
> Make URL validation work on sponsors step

- app/controllers/admin/sessions/list.js
- app/models/session.js
- app/routes/admin/sessions/list.js
- app/templates/components/ui-table/cell/events/view/sessions/cell-session-state.hbs
_`Admin > Sessions`_
- The `All` filter is not showing deleted sessions too
- The deleted sessions is having `Deleted` state.
Fixes #2603
> fix: session UI bugs in Admin and Manage Events section

- app/templates/components/forms/orders/order-form.hbs
Add search to country dropdown in enable billing information in ticket order.
Fixes #2634
> Add search to country dropdown

- app/templates/components/forms/login-form.hbs
Reverts fossasia/open-event-frontend#2510
> Revert "Comment out login with Facebook which is not working"

- app/templates/components/forms/admin/content/pages-form.hbs
Allow user to search in Language field of Create Page in Admin
Fixes #2688
> Allow user to search in Language field of Create Page in Admin

- app/templates/components/forms/admin/settings/system-form.hbs
Fixes the typo in the system-form
- Update `system-form.hbs`
Fixes #2587
> fixes typo in system form

- app/templates/components/event-card.hbs
> Removing hardcoded S

- app/templates/components/forms/user-profile-form.hbs
It enhances the UI of the user profile page by introducing hidden divider.
- Update `user-profile-form.hbs`
Fixes #2591
> Enhancing the UI of user-profile form

- app/components/ui-table-server.js
Makes sure that ember model table doesn't execute it's own query hook, if route model already takes care of it.
> Fix: Remove Extra network requests on initial ember table load

- app/components/forms/wizard/sponsors-step.js
- app/templates/components/forms/wizard/sponsors-step.hbs
Reverts fossasia/open-event-frontend#2665
> Revert "Make URL validation work on sponsors step"

- app/components/forms/admin/content/social-links-form.js
- app/components/forms/orders/order-form.js
- app/components/forms/session-speaker-form.js
- app/models/custom-form.js
- app/templates/components/footer-main.hbs
- app/templates/components/forms/admin/content/social-links-form.hbs
- app/templates/components/public/session-item.hbs
This capitalise the `h` in `GitHub` as per the GitHub standards.
-  Capitalise the`h`
Fixes: #2735
> Capitalise the h in GitHub for the frontend.

- app/components/forms/orders/guest-order-form.js
> remove unnecessary scroll from order form

- app/templates/components/footer-main.hbs
- app/templates/components/forms/admin/content/social-links-form.hbs
Support is renamed to Blog
Fixes #1805
> Rename support link to blog link

- app/templates/components/modals/tax-info-modal.hbs
Tax Rate value cannot be negative or more than 100.
Fixes #2624
> Limit tax rate value from 0 to 100

- app/templates/admin/users/view/settings.hbs
- app/templates/settings/contact-info.hbs
Fixed #2702 
- Making the `Admin/Setting` UI similar to `Settings/User`
Fixes #2702 
**Screenshot**
>  Updating UI of Admin/User/ContactInfo

- tests/integration/helpers/ticket-attendees-test.js
create ticket-attendees test
- using normal arrays instead of actual classes to get the result
Fixes #2708
> test: ticket-attendees integration test

- app/templates/components/forms/user-profile-form.hbs
> UI enhancement in `Profile Form`

- app/controllers/admin/users/view/events/list.js
- app/templates/admin/users/view/events.hbs
Fixes #2680 
- Made the user events table similar to other event tables.
- Made some UI enhancements in `Draft` and `Past` event section of users
Fixes #2680
> Making user event table similar to other event tables

- app/templates/components/modals/cfs-proposal-modal.hbs
> Align buttons in mobile view in cfs-proposal modal

- app/components/quick-filter.js
- app/templates/components/quick-filter.hbs
This makes the quick filter component responsive for mobile view. Currently the search bar almost gets hidden for smaller devices.
- Add button row in mobile view.
Fixes: #2399
> Fix mobile view for quickfilter component.

- app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
This makes the event roles labels inline.
- Make the labels inline.
Fixes: #2768
> Make event roles inline.

- app/templates/components/forms/wizard/basic-details-step.hbs
This shows the event topic while editing the event.
- Sanitized the event topic.
Fixes: #2706
> Show selected topic name while editing event.

- app/helpers/can-modify-order.js
- tests/integration/helpers/can-modify-order-test.js
If the order is completed and somehow upon discount, comes to an amount of 0, it should be made non-cancellable
Fixes #2722
> Make sure that discounted orders non cancellable

- app/templates/components/events/view/overview/general-info.hbs
This makes sure that link headers are smaller in mobile devices while normal sized in laptop
-  introduce conditions for mobile devices
Fixes #2701
> Fix link overflow in mobile devices

- app/templates/components/ui-table/cell/admin/users/cell-event-roles.hbs
Reverts fossasia/open-event-frontend#2769
> Revert "Make event roles inline."

- app/templates/admin/messages.hbs
Place the save button in Messages in Admin at the bottom
Fixes #2684
> Place the save button in Messages in Admin at the bottom

- app/controllers/admin/events/list.js
- app/controllers/index.js
- app/models/event.js
- app/templates/admin/events/list.hbs
- app/templates/components/ui-table/cell/admin/event-is-featured.hbs
- app/templates/index.hbs
After this PR, a `Featured Event` toggle can be seen in the admin-event panel.
After commit phase 1 (Toggle Addition) the admin bar looks like this
- Adding a `Featured Event` toggle in admin/events
- Created a new local component in admin scope for toggling
Fixes #1925
> Frontend part of featured event functionality

- app/components/forms/events/view/create-discount-code.js
- app/templates/components/forms/events/view/create-discount-code.hbs
Currently a discount code can be created without selecting a ticket.
- Define a custom validation rule to check for atleast one ticket checked.
Fixes: #2723
> Add ticket required validation in discount code.

- app/routes/index.js
- app/templates/index.hbs
This refactor ensures that fastboot shoebox is used correctly.
> Index route: remove function interfering with cache shoe

- app/controllers/events/view/sessions/edit.js
> Fixing typo in Error Message of Edit Session

- app/templates/admin/reports/kubernetes-server-logs.hbs
Kubernetes Server Logs present in Reports have no significance bcoz they are not implemented
- Adds coming soon to Kubernetes server logs
Fixes #2792
> admin: adds coming soon to kubernetes server logs in reports section

- app/templates/public.hbs
Empty space at the end of the event detail page in mobile view. 
Fixes #2694
> Empty space in Mobile view in Event Detail Page

- app/controllers/orders/view.js
- app/templates/components/forms/orders/attendee-list.hbs
- app/templates/orders/view.hbs
- package.json
- yarn.lock
Enhances the UI of order printouts using printThis.
> Enhance order invoice print output

- app/controllers/events/view/tickets/access-codes/create.js
- app/controllers/events/view/tickets/access-codes/edit.js
Corrects the error instruction for access code
- Update `access-codes/edit.js`
Fixes #2819
> Corrects the error instruction for access code

- app/templates/components/forms/orders/guest-order-form.hbs
`Reset Password` screen in `Guest Order` Form goes not responding .
Fixes #2753
> fix: reset-password screen goes not responding in guest order form

- app/controllers/events/view/tickets/add-order.js
> Enabled sorting in ember table on basis of ticket price

- app/templates/components/orders/event-info.hbs
- app/templates/components/orders/ticket-holder.hbs
Fixes-#2839
Made necessary UI changes
- Standardise font and unsquash stripe image in orders/ticket-holders
- remove colon spacing in event-info
> UI improvement in order components

- app/components/public/ticket-list.js
- app/templates/public/index.hbs
This makes sure that only the concerned event applies the discount code
Fixes #2869
> Event identifiers being checked before discount code processing

- app/templates/components/forms/session-speaker-form.hbs
- add an if condition to remove the null valued speaker
Fixes #2663
> Remove null speakers from dropdown

- app/controllers/index.js
- app/routes/index.js
Optimizes the code for computing filteredEvents, and fixes the quick search filter.
Fixes #2863
>  Fix quick search and date filters on home page

- app/controllers/orders/view.js
- using loader service to load the tickets route to download tickets
Fixes #2652
> Ticket refactoring: Download Tickets Request Change

- netlify.toml
- Configure deployment on netlify
Fixes #2901
> Configure netlify

- app/controllers/admin/content/translations.js
- app/controllers/orders/view.js
- app/services/loader.js
- app/templates/orders/view.hbs
- Modify tickets download service
- Refactor download tickets action
- Refactor translations downloads according to downloader service.
Fixes #2906
> Refactor download file service to fix tickets download

- app/routes/admin/sessions/list.js
- app/templates/admin/sessions.hbs
- Adding tabbed navigation for `Confirmed Sessions`.
Fixes #2889
> Adding tabbed navigation for Confirmed Sessions

- app/templates/events/view.hbs
Fixes #2867 
- Changed the referring link to `Model Url`
> Make use of URL field in event model to preview the event

- app/templates/components/ui-table/cell/cell-tickets.hbs
Reverts fossasia/open-event-frontend#2643
Fixes #2934
> Revert "Adding Event URL in manage event section"

- app/controllers/orders/view.js
- app/templates/orders/view.hbs
Fixes #2936 
- Download tickets button was not working in Firefox.
- Changed filename for tickets pdf upon download.
- Make changes to make button work in firefox (Add button to document body and revoke after downloading)
- Change filename
> Fix: Make download button work in Firefox and alter tickets filename

- app/controllers/orders/view.js
Fixes #2913 
Adds 800ms delay to prevent premature printing of the invoice with missing fields.
> feat: Add delay to printing of invoice

- Dockerfile
- hooks/build
Fixes #2940 
Enables automated proper deployments of master, development and any releases on Dockerhub.
> feat: Set up automated docker deploy
