app/templates/components/forms/wizard/sessions-speakers-step.hbs
=> chore: comment out custom form widget

app/templates/components/tables/utilities/search-box.hbs, app/templates/events/view/tickets/index.hbs
Fixes #3589 #3605 
fixes the ticket dashboard Table CSS Overflow on Small Device Screens.
Also fixes the manage events dashboard search-box overflow on small screen devices :
I have fixed it by setting the css overflow property to scroll.
=> fix: Ticket dashboard  table css overflow on small screens

app/templates/index.hbs
Fixes #3309 
**changes it propose**
when there are less than or equal to three the "show more call for speaker " button will not be visible .
=> fix: show "more call for speaker" button when appropriate

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #3603 
fixes the weird alignment of The ticketing system buttons(i.e. free ticket, paid ticket ,donation ticket) on the create event page on small screens.
=> fix: ticketing system buttons alignment

app/templates/events/view.hbs
Fixes #3592 
In event dashboard there was a weird vertical shift on clicking the publish button . I fixed this by adding an extrra condition to check is unverified-user-message is available or not .
in http://localhost:4200/events/d48cc85c/export also -
=> fix: fixing weird vertical shift in event dashboard

app/utils/computed-helpers.js
Fixes #3632 
Send event timings in event timezone and render time correctly on event basic details page.
=> fix: Send event startsAt and endsAt time in event timezone

app/components/tables/utilities/search-box.js, app/controllers/admin/events/list.js, app/controllers/events/list.js, app/routes/admin/events/list.js, app/routes/events/list.js, app/templates/components/tables/utilities/search-box.hbs
Fixes #3532 and Partial fix for #3642
=> feat: Add debounce on search field and remove included resources

app/helpers/is-input-field.js
Fixes #3406 
When displaying the attendee list on the frontend, few blank fields with labels were getting rendered I have fixed it by implementing a check if there is a value returned through get request
[Before](https://pasteboard.co/ID0lgBN.png)  [After](https://pasteboard.co/ID0klcW.png)  
- Shifted is-input-field helper check at the top of each loop
- Implemented a check for value is present in get data
=> fix: added check for required-fields and rendering gender

app/components/forms/events/view/create-discount-code.js, app/components/forms/wizard/basic-details-step.js, app/components/forms/wizard/sessions-speakers-step.js, app/helpers/is-input-field.js
=> fix: Remove date and time validations

app/templates/components/footer-main.hbs
Fixes #3697 
copyright © 2019 Eventyay Should be there instead of Open event.
=> fix: footer copyright credits

app/components/paypal-button.js, ember-cli-build.js, package.json, yarn.lock
Related: #3634 
Vendor JS reduced from 4.1 MB to 3 MB
Paypal Checkout lib itself was of 1 MB
=> chore: Lazy load paypal button

app/controllers/public.js, app/templates/public.hbs
fixes : #3656 
**visible for other pages**
=> fix: side menu icon should not be visible in mobile when there is no menu 

app/components/forms/session-speaker-form.js, app/routes/public.js, app/templates/components/forms/session-speaker-form.hbs, app/templates/public/cfs/edit-speaker.hbs, app/templates/public/cfs/new-speaker.hbs
=> fix: Email Override possible for all users

app/components/modals/cropper-modal.js
=> chore: migrating cropper-modal to ES6

app/templates/components/orders/order-summary.hbs
=> feat: Defining cancelled orders in order view template

README.md
Fixes #3668 
Current Netlify Badge is too much different from other badges we are using. Hence updated
=> chore: update consistent netlify badge

app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
Fixes #3719 
don't show cancel button when order state is cancelled .
=> fix: hide cancel button when order state is cancelled

app/templates/components/forms/wizard/sessions-speakers-step.hbs
- Let us not uncover the widget even after the release, And work on local until it is ready for deployment.
=> chore: Hiding custom widget until it is complete

app/adapters/application.js, app/components/forms/reset-password-form.js, app/controllers/oauth/callback.js, app/controllers/public/index.js, app/controllers/register.js, app/services/device.js, app/services/loader.js, config/environment.js, scripts/replace-config.js
=> refactor: fix hasOwnProperty and format code

app/routes/public/index.js, app/styles/pages/public-event.scss, app/templates/components/public/event-map.hbs, app/templates/public/index.hbs, config/environment.js
=> feat: Fallback to embedded iframe map

app/templates/components/public/session-item.hbs
=> fix: Use proper image sizes for session speaker avatar

app/components/forms/orders/order-form.js, app/components/widgets/forms/billing-info.js
=> fix: Defining computed countries property

app/routes/events/view/speakers/create.js, app/templates/components/forms/session-speaker-form.hbs
=> fix: Sessions were restricted to limit 20

app/components/forms/orders/order-form.js, app/mixins/custom-form.js, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs
Fixes:  #3806 
Fixes: #3780 
Fixes: #3406 
In the attendee form validation for gender field was not working so i added it's validation identifier in 
`gender` field. 
The second issue was to make country field as drop-down, as it was text before.i added validation for it too. Also refactor the code little for readibility.
1. when gender field is field -
2 - when gender field is not required -
3 - country drop-down with flags -
4 - validate gender when required and not given with country -
=> fix: make country as dropdown and add validation for gender

app/routes/my-sessions/list.js
=> fix: arrange unschedule session based on their event-time

app/models/speaker.js
Fixes #3789 
Shows the linkedlink in speaker info, which was not showing previously -
=> fix: Editing a Speaker shows Linkedin link

app/components/forms/orders/order-form.js, app/mixins/custom-form.js, app/models/attendee.js, app/models/custom-form.js, app/templates/components/forms/orders/order-form.hbs, app/utils/dictionary/age-groups.js
Fixes #3796 
Related Server PR [#6744](https://github.com/fossasia/open-event-server/pull/6744)
Added `ageGroup` Field in `Attendee Form`
=> feat: add ageGroup Field in attendee form

app/controllers/public/index.js, app/routes/application.js, app/services/auth-manager.js, app/services/current-user.js
=> feat: Changing current user loading method using async promises

app/components/forms/admin/settings/system-form.js, app/models/setting.js, app/templates/components/forms/admin/settings/system-form.hbs
Refers https://github.com/fossasia/open-event-server/issues/6093
=> fix: Removing secret from FE

app/styles/components/speaker-list.scss
=> enh: speaker image is showing properly in mobile

app/controllers/events/view/tickets/attendees/list.js, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs
=> fix: Correcting the extravaluePaths

package.json
ember-cli-htmlbars-inline-precompile is not needed anymore with dependencies upgrades.
=> chore: removing template-inline-precompile

app/components/forms/wizard/basic-details-step.js
Fixes #3521 
Added minOrder-maxOrder & minPrice-maxPrice validation in ticket-input.
**(Server checks are already present.)**
=> fix: minOrder-maxOrder & minPrice-maxPrice validation in basic-details-step

package.json
Fixes #4018 
We aren't using createRecord in fastboot, but it still requires it for some reason. 
https://github.com/emberjs/data/pull/6692
=> fix: Add crypto to fastboot dependencies

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs, package.json, yarn.lock
Fixes #2544 
Preview link - [https://deploy-preview-3852--open-event-fe.netlify.com/e/93efcaec](https://deploy-preview-3852--open-event-fe.netlify.com/e/93efcaec)
=> fix: Removing ember-scroll-to addon

app/controllers/public/index.js, app/templates/components/forms/orders/order-form.hbs
=> fix: Choosing Ticket holder same as ticket buyer not makes the text light gray 

app/routes/public/sessions/list.js, app/templates/public/sessions/list.hbs
Refers #3650
Fixes #4023
- Sessions were not rendering due to lack of space.
- Introduced infinity loader and checked the trigger offset, both are working quite well
=> feat: Implementing infinityModel at public session route

app/controllers/events/view.js, app/controllers/events/view/settings.js, app/templates/events/view.hbs, app/templates/events/view/settings.hbs
=> enh: move Delete button to event settings page

app/routes/public/role-invites.js
=> fix: Disable role invite processing in fastboot mode

app/mixins/event-wizard.js
Fixes #4058 
Now Events can be saved as draft without filling the location field.
=> fix: remove location check from event-wizard mixin

package.json, yarn.lock
Reverts fossasia/open-event-frontend#4049
Fixes #4062 
- This broke the every request the infinityLoader was sending to the server, hence neither the speaker nor session page was working.
=> Revert "chore(deps-dev): bump ember-source from 3.16.1 to 3.16.2"

docs/installation/local.md
=> chore(docs): update API_HOST url for localhost

app/components/modals/event-delete-modal.js, app/components/modals/event-transfer-modal.js
Fixes #4084 
made event delete & tansfer confirmation case sensitive.
=> fix: make event delete & transfer confirmation modal case sensitive

app/controllers/events/view/edit/attendee.js, app/controllers/events/view/tickets/add-order.js, app/controllers/events/view/tickets/order-form.js, app/controllers/orders/new.js, app/controllers/public/index.js, app/mixins/event-wizard.js
Fixes #3916 
If we're performing an operation on each element of an iterable and ```await``` is a part of each operation then the program is not taking full advantage of parallelization benefits of ```async```/```await```. Each successive operation will not start until the previous one has completed.
Using ```Promise.all()``` to ```await``` all the requests that were kicked during the loop to finish will create all the promises at once.
This pull request fixes this issue.
=> fix: Remove awaits in loop

app/routes/application.js
From 10 seconds to 5 seconds of initial page load
=> feat: Parallelize application requests

app/initializers/extensions.js, app/services/current-user.js, app/services/device.js, tests/test-helper.js
=> chore: fix relative import

yarn.lock
=> chore: .lock file conflicts

README.md
=> chore: update netlify link in README

.gitignore
=> fix: added .vscode and .nvmrc in .gitignore

config/deprecation-workflow.js
Logs are extremely hard to read with more than 50k lines.
Fixes issue https://github.com/fossasia/open-event-frontend/issues/4024
=> chore: Silence the evented-api-usage warnings

app/controllers/public/index.js, app/sentry.ts, ember-cli-build.js
=> chore: Capture and process order errors properly in Sentry

app/components/forms/reset-password-form.js, app/templates/components/forms/reset-password-form.hbs
=> feat: better reset-password-form

app/templates/attendee-app.hbs, app/templates/organizer-app.hbs
Fixes #3529 
Replaced `fluid` class with `medium` in `attendee-app.hbs` file.
-
-
-
=> fix: Changed the semantic class for the image in attendee and organizer app

ember-cli-build.js, package.json, yarn.lock
=> chore: Move tinyColorPicker from bower to npm

tests/helpers/setup-integration-test.js
Deprecated and spams the console
=> chore: Remove ember-l10n/test-helpers

app/models/event.js, app/models/user.js
Deprecated and spams the logs, and a completely empty callback!
There should be a lint for this
=> chore: Remove ready event listener

app/components/forms/orders/order-form.js, app/templates/components/widgets/forms/billing-info.hbs
=> fix: added frontend checking

package.json, yarn.lock
=> chore: setup pre-commit

app/controllers/events/view/tickets/access-codes/create.js, app/controllers/events/view/tickets/access-codes/edit.js, app/controllers/events/view/tickets/discount-codes/create.js, app/controllers/events/view/tickets/discount-codes/edit.js
=> chore: improve error reporting and fix typos

app/components/forms/admin/settings/system/mail-settings/test-email-form.js
=> fix: testsEmail prompt description

app/templates/account/billing/invoices/list.hbs, app/templates/events/import.hbs, app/templates/events/list.hbs, app/templates/events/view/index.hbs, app/templates/events/view/sessions/list.hbs, app/templates/events/view/speakers/list.hbs, app/templates/events/view/tickets/access-codes/list.hbs, app/templates/events/view/tickets/attendees/list.hbs, app/templates/events/view/tickets/discount-codes/list.hbs, app/templates/events/view/tickets/orders/list.hbs
{{sort_by}} was being treated as a composable helper
and thus all builds like #4301 and mainly #4298 were breaking
Some changes were reverted in #4322, but changing to
{{this.sort_by}} makes it unambiguous and also octane
compatible
=> chore: Change to angle bracket syntax for sort_by

app/templates/components/events/view/export/api-response.hbs, app/templates/components/events/view/export/download-common.hbs
Fixes #4104
URL segments in the export section of an event page were overflowing, they have now been fixed.
=> fix: url overflow in event export section

app/components/modals/event-delete-modal.js, app/components/modals/user-delete-modal.js
For some reason, on previous conditions, property was recomputed,
but UI wasn't updated. that only happened in production builds as well.
Changing the condition slightly as a workaround worked.
Upstream Issue: https://github.com/emberjs/ember.js/issues/18988
Introduced in https://github.com/fossasia/open-event-frontend/pull/4294 (https://github.com/fossasia/open-event-frontend/pull/4294/commits/f6bcfa191397366064e398f72966550639059423)
Fixes #4383
=> fix: Change tracked condition to make computed work

app/styles/partials/utils.scss, app/templates/components/event-card.hbs, app/templates/components/forms/login-form.hbs, app/templates/components/forms/register-form.hbs, app/templates/components/quick-filter.hbs, package.json, yarn.lock
=> feat(ui): Change to default rounded look

app/components/public/ticket-list.js, app/routes/public/index.js
Fetch infos about tickets, speakers, sessions, etc parallely.
Should be ideally done in their own components but OK for now
Also include event and tickets in discount code query
=> feat: Parallelize event page fetch

app/routes/events/view/index.js
Reduces event overview page load time significantly, removes redundant promise for event details, as ember resolves models hierarchically, it's already resolved before the hook is called.
Fix for #4099
=> feat: parallelize event overview api requests

app/initializers/accounting.js, app/templates/admin/sales/discounted-events.hbs, app/templates/admin/sales/index.hbs, app/templates/admin/sales/locations.hbs, app/templates/admin/sales/marketer.hbs, app/templates/admin/sales/organizers.hbs, app/templates/admin/sales/revenue.hbs, app/templates/components/event-invoice/invoice-summary.hbs, app/templates/components/events/view/overview/event-tickets.hbs, app/templates/components/orders/order-summary.hbs, app/templates/components/public/ticket-list.hbs, app/templates/components/ui-table/cell/admin/sales/status/cell-amount.hbs, app/templates/components/ui-table/cell/events/cell-amount.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-price.hbs, app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-price.hbs, app/templates/components/ui-table/cell/events/view/tickets/cell-add-order-total.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs, app/templates/event-invoice/review.hbs
For some reason, `format-number` was used to represent money in the app which removed any decimal part and rounded it off to integer
Before:
After:
=> fix: Properly format money everywhere

app/components/public/ticket-list.js, app/helpers/currency-symbol.js, app/styles/partials/utils.scss, app/templates/components/public/ticket-list.hbs, app/utils/dictionary/payment.ts, tests/integration/helpers/currency-symbol-test.js
=> feat: Order Amount calculation integration

app/routes/events/view/edit/sponsors.js
Due to mutation, it was throwing an error
if switched to more than once
Fixes #4501
=> fix: Prevent mutating data in sponsors event wizard page

.eslintrc.js, app/components/forms/orders/order-form.js, app/components/forms/wizard/attendee-step.js, app/models/custom-form.js, app/routes/events/view/edit/attendee.js, app/routes/orders/new.js, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/wizard/attendee-step.hbs, app/utils/text.ts, tests/unit/utils/text-test.ts
=> feat: Add attendee custom form option

app/models/custom-form.js
New field 'name' was added in custom form and it is
populated from backend, so new custom forms in
frontend were initialized without any name because
the previous logic of loading name as custom property
was removed. This is a temporary fix since custom forms
will start to be created on backend instead of frontend
Fixes #4506
=> fix: Assign custom form name on init

app/routes/events/view/edit/sessions-speakers.js
=> fix: Prevent mutating data in sessions event wizard page

app/templates/components/forms/orders/attendee-list.hbs
Fixes #4519 
Complex custom form values was not visible in attendee information.
Make complex custom form values visible by checking if that particular field is complex or not.
=> feat: Show complex custom form values for attendee info

app/components/forms/orders/order-form.js, app/components/forms/session-speaker-form.js, app/models/attendee.js, app/models/session.js, app/models/speaker.js, app/templates/components/forms/session-speaker-form.hbs
The duplication is so horrendous that it took me 3 days to figure out
=> feat: Add speaker and session custom form input

app/styles/partials/colors.scss, app/templates/components/public/social-links.hbs
Fixes #4551 
Social icons not there on public event page
By removing extra classes like `share` and `square`, icons are working fine.
=> fix: Social icons on public event page

app/components/public/ticket-list.js, app/components/unverified-user-message.hbs, app/controllers/public/index.js, app/styles/partials/utils.scss, app/templates/components/forms/orders/guest-order-form.hbs, app/templates/public/index.hbs, tests/integration/components/unverified-user-message-test.js
Fixes #4543
Email Reset Icon Added:
Verification Error Message added in Ticket List:
=> feat: Recreate free order buying process

app/components/forms/session-speaker-form.js, app/templates/components/forms/session-speaker-form.hbs
Fixes #4027 
In create speaker form we can't check and uncheck add a new proposal
Use checkbox for add new proposal 
- [] I have added tests that prove my fix is effective or that my feature works
=> fix: Use checkbox for adding new proposal in create speaker form

app/components/forms/session-speaker-form.js, app/components/forms/wizard/sessions-speakers-step.js, app/models/custom-form.js, app/routes/events/view/edit/sessions-speakers.js, app/routes/public/cfs/edit-session.js, app/routes/public/cfs/edit-speaker.js, app/utils/sort.ts, package.json, tests/unit/utils/sort-test.ts, yarn.lock
=> feat: Add field order to session and speaker forms

app/router.js
Fixes #4578 
The speaker edit route was pointing to the session edit route when the page was reloaded because of conflict in their ids in the route.
Use separate route for editing speaker and session
=> fix: Separate route for speaker and session edit

app/templates/components/ui-table/cell/cell-sessions-dashboard.hbs, app/templates/components/ui-table/cell/cell-sessions.hbs, app/templates/components/ui-table/cell/cell-speakers-dashboard.hbs, tests/integration/components/ui-table/cell/cell-sessions-dashboard-test.js, tests/integration/components/ui-table/cell/cell-sessions-test.js, tests/integration/components/ui-table/cell/cell-speakers-dashboard-test.js
Fixes #2898 
No descriptive message when the speaker or session is not present
Show descriptive message
=> fix: Descriptive message when no speaker/session

app/routes/events/view/edit/attendee.js
Fixes #4597
Ember Data strikes again. There is a custom function `query` used everywhere throughout the project which filters out the items from server. But ember data returns all the items from local in memory DB because how cool it is, and this custom query method does not take it into account. Hence, once all custom form fields are loaded in memory, it returns all the items rather than just the attendee custom form
=> fix: Filter attendee form from all custom forms

app/components/forms/wizard/basic-details-step.js, app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #4585 
No error message was shown to the user regarding required event location in event create wizard step 1.
Show error message if the user tries to save an event without entering event location.
=> fix: Add location required error message in wizard step 1

app/mixins/custom-form.js
Fixes #4586 
Session and speaker custom forms have few fields pre-selected for new events in wizard step 4.
Change default pre-selected fields
=> fix: Change default pre-selected fields in wizard step 4

app/templates/events/view.hbs
Fixes #4592
- Show "View"
- Open event link in new tab
- Only show "Preview" for unpublished events
=> feat: improve event dashboard top nav

app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/widgets/forms/ticket-input.hbs
Fixes #4624
Settings will be expanded by default for tickets
=> feat: show ticket box expanded with all settings

app/components/forms/admin/content/social-links-form.js, app/models/setting.js, app/routes/create.js, app/templates/components/footer-main.hbs, app/templates/components/forms/admin/content/social-links-form.hbs
Fixes #4617
Requires https://github.com/fossasia/open-event-server/pull/7163
- Added field for the Instagram social link.
- rename google + to google group in URL.
Unfortunately, Semantic UI doesn't have an icon for google-groups. I'm finding a suitable icon and will update.
=> feat: add instagram social link

app/components/ui-table/cell/events/view/sessions/cell-buttons.js, app/components/ui-table/cell/events/view/sessions/cell-session-state.js, app/controllers/admin/sessions/list.js, app/controllers/events/view/sessions.js, app/controllers/events/view/sessions/list.js, app/routes/admin/sessions.js, app/routes/admin/sessions/list.js, app/routes/events/view/sessions/list.js, app/templates/admin/sessions.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-session-state.hbs, app/templates/events/view/sessions.hbs, app/utils/dictionary/sessions.ts
=> feat: Add more session states

app/controllers/events/view/sessions/list.js
=> fix: Revert session state on failure

app/styles/libs/_helpers.scss, app/templates/components/forms/wizard/attendee-step.hbs, app/templates/components/widgets/forms/link-input.hbs
Fixes #4607
custom form field is visible even when the attendee form is turn off . Text under Information about attendee form is very light. 
-Make the Custom form field visible only when the attendee form is turn on . 
-change the color of the text under Information about attendee form to make it more readable and visible. 
-
- [ x
I have added necessary documentation (if appropriate)
=> fix: visibility of custom form field and info text color

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #4650
make required billing info field a checkbox instead of the radio.
=> fix: make billing info field checkbox

app/components/modals/publish-unpublish-modal.js, app/controllers/events/view.js, app/templates/components/modals/publish-unpublish-modal.hbs, app/templates/events/view.hbs
Fixes #4621 
There was no confirmation when user publish or unpublish his/her event.
Show confirmation pop-up whenever user tries to publish or unpublish his/her event.
=> feat: Implement event publish-unpublish confirm pop-up

app/serializers/session.js
For https://github.com/fossasia/open-event-server/issues/7164
=> fix: Delete complex field values if empty

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #4660
a) Add owner information to -> Add Organizer or Group Information
b) Owner Name -> Organizer or Group Name
c) Owner Description to -> About the Organizer or Group
d) Change "Name" to "Event Name" in the wizard form (step 1).
=> feat: change some fields name in basic details step

app/templates/events/view.hbs
Follow up #4655. Implement pop up confirmation for mobile devices as well.
=> feat: implement publish-unpublish pop up for mobile devices

app/controllers/events/view.js, app/templates/components/modals/publish-unpublish-modal.hbs, app/templates/events/view.hbs
Fixes #4525 
Possible to publish event from event manage overview page
Don't publish event (show error) without tickets
=> fix: Disallow publish event without tickets

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #4672 
When editing existing events ticket input is in expanded state which is not needed.
Don't expand ticket input when editing existing event. If event id already exists then there's no need to show expanded ticket input settings.
=> fix: Don't expand ticket input when editing existing event

app/routes/admin.js
=> fix: Forbid admin route for non admin user

app/config/environment.d.ts, app/sentry.ts, config/environment.js, package.json, yarn.lock
=> chore: Adds sentry APM

app/templates/components/forms/admin/settings/billing.hbs, app/templates/components/forms/admin/settings/ticket-fees-form.hbs, app/templates/components/forms/orders/order-form.hbs, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/forms/user-payment-info-form.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/modals/tax-info-modal.hbs, app/templates/components/widgets/forms/billing-info.hbs
Fixes #4618 - author @mariobehling 
Deactivates the autofill in Country fields in forms in the following:
1. Attendee form
2. Billing Information of Attendees during ticket payment process
3. Billing Information in Tax (Wizard Basic Details Step 1)
4. Billing Info of account
5. Speaker Submission Form in call for speakers
=> fix: disable browser autofill for Country fields in forms

app/router.js
Fixes #4685
- changes order for session edit url
-
-
=> fix: Change edit endpoints in router

app/serializers/session.js
=> fix: Handle exception while serialising session

ember-cli-build.js, package.json, yarn.lock
Fixes #4526 
Since we have reverted to rounded corners and undone any changes to default semantic theme, there is no use of depending on fork of semantic UI theme as it is difficult to maintain and causes random undebuggable bugs like the one linked.
To be fixed before merged:
=> chore: Finally remove @open-event/theme

app/templates/events/view.hbs
Fixes #4711 
fix color for unpublish state
=> fix: orange color for unpublish button

app/templates/components/quick-filter.hbs
Fixes #4717 
Front Page: Question Marks instead of Location Search Box
the PlacesAutocomplete is not working at the time, so  making this field as a normal Input field instead of <Widgets::Forms:: PlacesAutocomplete/>
=> fix: remove Question Marks instead of Location Search Box

app/components/forms/wizard/sessions-speakers-step.js, app/components/forms/wizard/sponsors-step.js
Fixes #4712 
Wizard Step 3 and Step 4: Not possible to save draft
Allow saving as draft on each step..
=> fix: save wizard as draft on each step

app/components/modals/session-notify-modal.hbs, app/components/modals/session-notify-modal.js, app/components/ui-table/cell/events/view/sessions/cell-notify.hbs, app/components/ui-table/cell/events/view/sessions/cell-notify.js, app/controllers/events/view/sessions/list.js, tests/integration/components/ui-table/cell/events/view/sessions/cell-notify-test.js
=> feat: Add session notify dialog

app/routes/events/view/sessions/list.js
Now, all required items are requested in a single request
instead of sending a thousand requests per page
=> fix: Include track and session type in org sessions view

app/controllers/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs
Broken after changes in #4733
Now, nested dropdown of with/without email is removed
=> fix: Session state dropdown with/out email removed

app/components/scheduler/unscheduled-session.js, app/templates/events/view/scheduler.hbs, tests/integration/components/scheduler/unscheduled-session-test.js
=> fix: Scheduler track color and obsolete action

app/controllers/admin/events/list.js
=> fix: make featured and promoted events sortable in admin

app/components/schedule.hbs, app/components/schedule.js, app/controllers/events/view/scheduler.js, app/routes/events/view/scheduler.js, app/routes/public/schedule.js, app/templates/events/view/scheduler.hbs, app/templates/public/schedule.hbs, app/utils/patches/fullcalendar.js, tests/integration/components/schedule-test.ts
Fixes #4760
Fixes #4778
Fixes #4168 
Fixes #4167 
Fixes #4183 
Fixes #4446
=> feat: New scheduler implementation

app/models/social-link.js
=> fix: Add null check on name of social link

app/templates/events/view/scheduler.hbs
=> feat: Add scrollbar in unscheduled sessions

app/components/schedule.ts, app/styles/partials/all.scss, app/styles/partials/fullcalendar.scss, types/global.d.ts
Make scheduler column widths wider and scrollable
Before: 
After:
=> feat: Adjust scheduler resource column widths

app/models/social-link.js
Fixes #4802
Show `globe` icon if the URL is not a standard social media URL.
=> fix: show globe icon for general web links

app/controllers/admin/events/list.js
=> fix: Show error details on deleting event

app/controllers/events/view/speakers/list.js, app/templates/components/ui-table/cell/events/view/speakers/cell-buttons.hbs
=> feat: improve speaker list page column organization

app/templates/components/public/session-item.hbs, app/templates/components/public/speaker-item.hbs
Fixes #4000 
Speaker name was too close to speaker image, there was no link on session and text was not selectable.
- Increase gap between speaker's image and name.
- Make text selectable.
- Link speaker sessions.
=> fix: Add margin around speaker name and make text selectable

app/helpers/text-color.ts, app/routes/public/index.js, app/templates/components/public/speaker-item.hbs
=> fix: Handle undefined text color

app/templates/components/forms/user-payment-info-form.hbs
=> fix: correct order of fields in payment-info form

app/components/schedule.hbs, app/components/schedule.ts, app/templates/public/schedule.hbs
=> fix: make calender height auto

app/styles/pages/public-event.scss, app/styles/partials/utils.scss, app/templates/public.hbs
Fixes #4857 
Fixes #4858 
Fixes #4781
=> feat: Display event logo in public event page

app/controllers/events/view/scheduler.js
Fixes #4868 
Error introduced in https://github.com/fossasia/open-event-frontend/pull/4775/files#diff-cfb056a5cf26ae6847ecc6f81cc08d86R58, eventDetails was changed to `event` and remained to be replaced in one place in controller
=> fix: Schedule publish toggle crash

app/controllers/public.js, app/routes/public/sessions.js, app/styles/components/all.scss, app/styles/components/extras.scss, app/styles/partials/utils.scss, app/templates/public.hbs
=> feat: Add tracks and rooms filters on sessions page

app/components/forms/wizard/basic-details-step.js, app/components/forms/wizard/other-details-step.js, app/controllers/events/view/edit/attendee.js, app/controllers/events/view/edit/basic-details.js, app/controllers/events/view/edit/other-details.js, app/mixins/event-wizard.js, app/router.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/events/view/edit/other-details.hbs
Fixes #4671
Adding a new step in wizard
=> feat: Adding a step two in wizard form

app/router.js, app/routes/public/sessions-index.js
=> fix: Redirect from /sessions to /schedule

app/components/forms/wizard/other-details-step.js, app/components/widgets/forms/link-input.js, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/components/widgets/forms/link-input.hbs, app/utils/computed-helpers.js
Fixes #4610 
- Offer a dropdown menu of all kinds of social media services and require the user to only fill in the user name.
- Change the name "External Event URL" to "Website"
=> feat: implement dropdown for social media in other-details step

app/controllers/public/session/view.js, app/templates/components/public/speaker-item.hbs, app/templates/public/session/view.hbs
=> fix: Link sessions in speaker list to sessions page

app/routes/public/speakers.js
Fixes #4866
Making page size to 21 is giving better performance than 12 in terms of breaks while scrolling on a pageSize of 12 and total time also. And Also loads fast. So this is kind of trade of between total time and loading time I guess. So I found pageSize 21 as a best option.
=> fix: increase page size to 21 for speakers

app/mixins/event-wizard.js
Refers https://github.com/fossasia/open-event-frontend/pull/4905#issuecomment-685512578
Follow up #4905
=> fix: addition info step description

app/components/widgets/forms/link-input.js, app/templates/components/forms/session-speaker-form.hbs, app/templates/components/widgets/forms/link-input.hbs
Refers #4609
Made social media links on all forms in a way that users only need to add their username or other short forms.
=> feat: only request to fill username for social links in forms

app/templates/components/ui-table/cell/cell-event-general.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4885
- On the table please link the logo and event name to the specific event dashboard (of the event itself).
- Slightly increase the space between the logo and event name
- Slightly decrease the space between the event name and the below buttons
=> feat: link event logo and name to event dashboard

app/components/forms/wizard/attendee-step.js, app/components/forms/wizard/custom-form-input.hbs, app/components/forms/wizard/custom-form-input.ts, app/components/forms/wizard/custom-forms/table.hbs, app/components/forms/wizard/custom-forms/table.ts, app/routes/events/view/edit/attendee.js, app/routes/events/view/edit/sessions-speakers.js, app/styles/libs/_helpers.scss, app/templates/components/forms/wizard/attendee-step.hbs, app/templates/components/forms/wizard/sessions-speakers-step.hbs, package.json
=> feat: Edit Custom Form Fields

app/components/widgets/forms/link-input.js
=> fix: Check for address and link nullability in LinkInput

app/templates/components/forms/orders/order-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4609
=> feat: use LinkInput for url fields in order-form

app/templates/components/footer-main.hbs
=> fix: open internal footer links in same tab and change text

app/templates/components/public/side-menu.hbs
=> fix: Only show schedule and calendar on public page when published

app/components/forms/wizard/basic-details-step.js, app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs, app/templates/public/index.hbs
Fixes #4849 
- Fixed the redirection based on URL hash and anchor tags. Now the anchored div relative to the URL hash shows up at the top of the screen on page load.
- Earlier it required two clicks initially on page load to jump to a particular section of the event page using the side-menu. This was so because the first click was required to bind the anchor scroll action with the click event. It did not trigger the scroll action on the first click. Added scroll action to the first click.
- https://open-event-frontend-d12ttsngk.vercel.app/e/41bb1094#info
- https://open-event-frontend-d12ttsngk.vercel.app/e/41bb1094#tickets
- https://open-event-frontend-d12ttsngk.vercel.app/e/41bb1094#organizer
- https://open-event-frontend-d12ttsngk.vercel.app/e/41bb1094#getting-here
These links direct to …
=> fix: page scroll with URL hash redirection.

app/routes/explore.js, app/templates/components/explore/side-bar.hbs
And debounce the search filter
Fixes #4971
=> fix: Remove map and autocomplete from explore

app/components/forms/wizard/other-details-step.js, app/templates/components/forms/wizard/other-details-step.hbs
Fixes #2302 (completing remaining part of wizard step 2 of licence )
=> fix: License of Event Data & Content clear field

app/components/schedule.hbs, app/components/schedule.ts
=> fix: Rerender calendar on timezone change

app/templates/components/footer-main.hbs
Fixes #4995 
Short description of what this resolves:
Changed the URL and the section name from "Event Blog" to "Blog" in footer.
=> chore: change event blog url

app/templates/verify.hbs
Fixes #
Altering email verification message on successful verification of users #4989
Showing Email Verification message after checking authentication
- case1 : Authenticated
Message: Your email has been successfully verified!
- case2: Not Authenticated
Message: Your email has been successfully verified! Please login to continue.
=> fix: change email verification message on success

app/components/forms/wizard/basic-details-step.js, app/mixins/event-wizard.js, app/models/event.js, app/templates/components/forms/wizard/attendee-step.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/forms/wizard/sponsors-step.hbs, app/templates/components/public/event-map.hbs, app/templates/public/index.hbs
=> feat: Integrate online events

app/components/widgets/time-zone-picker.hbs, app/components/widgets/time-zone-picker.ts, app/templates/public/schedule.hbs, app/templates/public/sessions.hbs
=> feat: Pick local timezone for online events by default

app/models/event.js, app/templates/components/forms/wizard/other-details-step.hbs, app/templates/components/public/ticket-list.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4957
Requires https://github.com/fossasia/open-event-server/pull/7253
=> feat: add refund policy section in other-details step

app/router.js, app/routes/events/view/index.js, app/routes/events/view/team.ts, app/routes/events/view/team/index.ts, app/routes/events/view/team/permissions.ts, app/templates/components/events/view/overview/manage-roles.hbs, app/templates/components/modals/add-user-role-modal.hbs, app/templates/events/view.hbs, app/templates/events/view/index.hbs, app/templates/events/view/team.hbs, app/templates/events/view/team/index.hbs, app/templates/events/view/team/permissions.hbs, tests/integration/components/events/view/overview/manage-roles-test.js, tests/unit/routes/events/view/team-test.ts, tests/unit/routes/events/view/team/index-test.ts, tests/unit/routes/events/view/team/permissions-test.ts
=> feat: Create team and permissions page

app/templates/components/widgets/forms/rich-text-editor.hbs
=> fix: insert link in description field

app/templates/components/public/event-map.hbs
=> fix: Restore map hide toggle behaviour

app/controllers/application.js, app/models/setting.js, app/templates/application.hbs, app/templates/components/forms/admin/settings/system-form.hbs
Fixes #5071 
Fixes #5028 
Cookie Policy and Link can now be edited in Admin Settings
=> feat: Add cookie policy editor and fix hide behaviour

app/components/public/session-item.hbs, app/components/public/session-item.js, app/models/setting.js, app/routes/public/session/view.js, app/styles/components/track-item.scss, app/utils/url.ts, package.json, tests/unit/utils/url-test.ts, yarn.lock
=> feat: Add video and slides to session

app/models/setting.js, app/templates/components/footer-main.hbs, app/templates/components/forms/admin/content/social-links-form.hbs
Requires this [PR](https://github.com/fossasia/open-event-server/pull/7266)
Fixes #5022
=> feat: add telegram & gitter social links

app/mixins/event-wizard.js
Fixes #5117 
For some reason, babel wasn't transpiling `data.tickets?.length || 0` correctly. It transpiled it to 0 statically meaning no matter what the case, number of tickets were evaluated to 0
=> fix: Number of ticket calculation transpilation

app/components/forms/admin/settings/billing.js, app/templates/components/forms/admin/settings/billing.hbs
=> fix: make some admin billing fields optional

app/templates/components/widgets/forms/ticket-input.hbs
=> fix: absorb fee required for donation ticket too

app/components/ui-table/cell/admin/sales/cell-action.js, app/controllers/admin/sales/invoices.js, app/templates/admin/sales.hbs, app/templates/components/ui-table/cell/admin/sales/cell-action.hbs
=> fix: Seperate the admin/sales tab into 2 subtabs

app/components/widgets/forms/ticket-input.js, app/helpers/confirm.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/widgets/forms/ticket-input.hbs
Fixes #4623
Fixes #5095
@iamareebjamal , when i am clicking no in confirm modal, it is executing action, and on yes it's not. means that in this, yes is working as no, and no is working as yes. rest is working correctly.
=> fix: removing ticket group, some extra line and adding a popup

app/components/widgets/forms/link-input.js
Fixes #5115 
The implementation was correct in https://github.com/fossasia/open-event-frontend/pull/541 (https://github.com/fossasia/open-event-frontend/pull/541/commits/a4b0290fd2ed209d12f18e0313eee6d6ee7bdea7) but for some reason was made wrong in https://github.com/fossasia/open-event-frontend/pull/580 (https://github.com/fossasia/open-event-frontend/pull/580/commits/bbd3851db75a3f810fead46a3453f1c633d588e8)
If a link contains `http(s)://` it split by `://` and made protocol `https` + `://` and address rest of the link
But when it was changed, it made proto `https` and address rest of the link, so if someone pasted `https://hello.com`, the final URL will become `httpshello.com`
Anyway, LinkInput is too complex and big and should be broken down into simpler components
=> fix: Add split :// to link in component

app/components/forms/admin/settings/ticket-fees-form.js, app/controllers/admin/settings/ticket-fees.js, app/templates/components/forms/admin/settings/ticket-fees-form.hbs
=> fix: Add global ticket fees settings

app/components/widgets/forms/link-input.js, app/templates/components/widgets/forms/link-input.hbs, app/utils/computed-helpers.js
=> fix: adding extra social link

app/components/public/side-menu.js, app/templates/components/public/side-menu.hbs
=> fix: Show speakers menu only when speakers present

app/services/sanitizer.js
Fixes #4542 
Fixes #5178 
Example Event with line breaks and links https://open-event-frontend-czssukq39.vercel.app/e/295ce8c5
=> fix: Allow newline in sanitized HTML

app/controllers/public.js, app/templates/public.hbs
Fixes #5161 
Fixed the issue of empty location line in the header of the public event page.
- Fixed by creating a computed property as suggested by @iamareebjamal
=> fix: Show online or mixed location in event page header

app/components/ui-table/cell/cell-date.hbs, app/controllers/account/billing/invoices/list.js, app/routes/event-invoice/review.js, app/templates/event-invoice/review.hbs
And reload event invoice manually in route because as usual, ember-data `reload` true doesn't work
https://github.com/emberjs/data/issues/3704
=> fix: Use UTC timezone for invoice issue dates

app/components/modals/cropper-modal.js, app/components/orders/order-summary.js, app/controllers/events/view/tickets/add-order.js, app/router.js
Deprecated https://deprecations.emberjs.com/v3.x/#toc_ember-metal-get-with-default
=> chore: Replace getWithDefault with nullish coalescing

app/components/ui-table/cell/events/cell-download-invoice.js, app/components/ui-table/cell/events/cell-event-invoice.js, app/controllers/account/billing/invoices/list.js, app/models/event-invoice.js, app/routes/account/billing/index.js, app/routes/account/billing/invoices/list.js, app/templates/account/billing.hbs, app/templates/account/billing/invoices.hbs, app/templates/components/ui-table/cell/events/cell-download-invoice.hbs, app/templates/components/ui-table/cell/events/cell-event-invoice.hbs, app/templates/event-invoice/review.hbs, tests/acceptance/invoices-test.js
=> fix: Invoice UI enhancements

app/routes/event-invoice/paid.js, app/routes/event-invoice/review.js
=> fix: Redirect to login from invoice detail

app/controllers/create.js, app/routes/events/view/edit.js
=> fix: don't jump to main page or step 3 in wizard

app/components/forms/wizard/basic-details-step.js
=> fix: Change event times according to timezone change

.dockerignore, Dockerfile, config/environment.js, config/nginx.conf, scripts/container_start.sh, scripts/fastboot-server.js
Fastboot is consuming too much resources and slowing down user experience (waiting time/performance), and also the behavior of the site differs on fastboot and client render, and makes it difficult to write single code and use features like cookie authentication for long periods of login. Hence, we are disabling fastboot in production as the site is already significantly fast and after some more aggressive caching on frontend and backend, it'll be even more faster
=> chore: Bundle nginx in docker for disabled fastboot

config/environment.js
In #5244, we changed the default API to production, but tests started failing because a user account was not present on production, so now we choose the API based on environment
=> fix: Change default API based on environment

app/controllers/admin/users/list.js, app/mixins/ember-table-route.js, app/routes/admin/users/list.js, app/templates/components/ui-table/cell/admin/users/cell-created-at.hbs, app/templates/components/ui-table/cell/admin/users/cell-first-name.hbs
=> feat: Allow admin to search users by lastName and email

app/components/forms/wizard/basic-details-step.js
Fixes #5235
**Short description of what this resolves:**
When user changes minimum order to greater than maximum or vice versa ,prompt will be given.
**Checklist**
=> fix: bug with maximum and minimum tickets per order

app/routes/events/view/tickets/orders/list.js
=> fix: search via user email in order table

app/components/forms/wizard/sessions-speakers-step.js
=> fix: CFS date field validation working in wizard step 5

app/components/events/view/publish-bar.ts, app/mixins/event-wizard.js, app/models/event.js, app/templates/components/forms/wizard/basic-details-step.hbs
=> fix: need to connect to your stripe account error

app/models/event.js
was showing error even if stripe box is unticked
=> fix: stripe validation condition fix

app/components/forms/wizard/sessions-speakers-step.js, app/templates/components/forms/wizard/sessions-speakers-step.hbs
=> fix: make CFS optional like adding org info wizard step 1

app/components/forms/register-form.js, app/controllers/register.js
Fixes #4399 
The email specified in this issue is invalid, so this pull request resolves the error of validating an email without ".com", ".io", etc.
The code for validating an email id using the "email" identifier which is validating the email id without ".com", so by changing the email identifier by regular expression resolves this issue.
Changes "email" identifier by "regExp[/^[A-Za-z0-9_]([\.-]?[A-Za-z0-9_])*@[A-Za-z0-9_]([\.-]?[A-Za-z0-9_])*(\.[A-Za-z0-9_]{2,3})+$/]" in app/components/forms/login-form.js 
-
-
-
=> fix: Update email validation

app/templates/components/quick-filter.hbs
changes placeholder "search for events" to "search location"
fixes #5240
=> fix: change location search placeholder text

app/components/schedule.hbs
=> feat: allow scheduler slot duration of 5 min

app/services/l10n.js
Fixes #5347
It changes the the language names to the original languages respectively.
Before:
After:
=> fix: show language names in original language

app/components/public/session-item.hbs
Color area "jump difference"  issue resolved #5343
Fixes #5343
In the public schedules, if the user expands a session the color area "jumps" a bit. The size of the color area before and after the expansion is different. This PR resolves it. Now Area should always be the same.
- Removed Unwanted CSS (Ui divider)
- Added required margin and resolved the jump issue.
=> fix: Remove divider to resolve UI jumping in session overview card

app/models/speakers-call.js
Fixes #5340
As the event start date can't be before the current date, so adding cfs date before the current date will solve the issue.
=> fix: Set valid CFS time range

app/controllers/events/view/speakers/create.js, app/controllers/events/view/speakers/edit.js
=> fix: Allow organizer to add speaker without email

app/templates/components/events/view/overview/event-sponsors.hbs, app/templates/components/tables/default.hbs
Fixes #5329 
introducing new prop to show/hide search box.
=> fix: take out search box from sponsor table

app/services/l10n.js
Fixes #5347 
Fixes spelling of some languages and sorts them in alphabetical order
=> fix: spelling and sort languages in alphabetical order

app/components/forms/wizard/custom-form-input.hbs, app/templates/components/forms/wizard/sessions-speakers-step.hbs
Fixes #5013 
Simplifies wizard Step 3 and 5 as stated in the issue.
-Wizard step 3 : demoted "Add Custom form field" from heading to standard text.
-Wizard step 5 : "Customize registration form" renamed to -> "Customize submission forms"
-
-
=> fix: Wizard step 3 and 5 enhanced accordingly

app/controllers/events/view/speakers/list.js
Fixes #4559 
Event id was undefined, now fixed
- Added Speaker Property
=> fix: Add extra value paths for view speaker handler

app/routes/account/danger-zone.js
=> fix: Only prevent fulfilled or pending order users from deletion

app/components/forms/orders/guest-order-form.js, app/controllers/public/index.js, app/templates/components/forms/orders/guest-order-form.hbs
=> feat: Allow users to set password while registering for order

app/templates/components/public/call-for-speakers.hbs
=> fix: call for speaker page messages

app/components/nav-bar.js, app/templates/components/nav-bar.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5448
=> fix: simply nav bar on public page

app/templates/public.hbs
Fixes #4608 
Initially the Social Links(twitter) widget display on all the Event Pages including _new-session_ , _edit-session_ , _new-speaker_, _edit-speaker_  pages.  Left side bar not show on these listed pages but right twitter(social links) side bar widget is shown.
This PR solves this issue. Now the right side Social links widgets only visible on those pages which are listed in left side bar. Now the social Links widget not shown on _new-session_ , _edit-session_ , _new-speaker_, _edit-speaker_  pages. 
Controller of event public page contains _displaySideMenu_ function which hide left side bar menu at these four pages. This PR uses this function to hide right side widget at these four pages.
- Social Links widgets only visible on the pages listed in left side bar.
___screenshots__ …
=> fix: Show Social Links only on Event Pages that are listed on the left side bar

app/templates/events/view/index.hbs
Fixes #5463 
This PR removes empty space between tables/boxes in event dashboard page.
-Remove empty spaces between tables
__Screenshots__
=> fix: Remove Empty Spaces between Boxes in Event Dashboard Page

app/templates/events/view.hbs
Fixes #5474 
**Changes proposed in this pull request**
1. Remove unnecessary line breaks.
**Before**
**After**
=> fix: Removed unneccesary line breaks in event title

app/controllers/register.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5433
=> fix: remove intermidiate step of login while registering

app/templates/attendee-app.hbs, app/templates/components/events/view/overview/manage-roles.hbs, app/templates/components/forms/admin/settings/images-form.hbs, app/templates/components/forms/admin/settings/payment-gateway-form.hbs, app/templates/components/forms/events/view/create-access-code.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/organizer-app.hbs, translations/bn.po, translations/de.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/pl.po, translations/ru.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
Fixes #5452
Spaces added before brackets and removed before commas.
=> fix: Brackets and commas spacing

.eslintrc.js, app/models/microlocation.ts, app/models/video-stream.ts, app/serializers/video-stream.ts, package.json, tests/unit/models/video-stream-test.ts, yarn.lock
For #5101
~~For some reason, ember data is not working correctly with relationships. Need to do more research~~
Fixed
=> chore: Add Video Stream models

app/controllers/events/view/speakers/list.js
=> fix: Refresh model after speaker deletion

app/components/forms/wizard/other-details-step.js, app/components/widgets/forms/link-field.hbs, app/components/widgets/forms/link-field.ts, app/components/widgets/forms/link-input.js, app/components/widgets/forms/social-link-field.hbs, app/components/widgets/forms/social-link-field.ts, app/models/social-link.js, app/styles/partials/utils.scss, app/templates/components/forms/wizard/other-details-step.hbs, app/utils/computed-helpers.js, app/utils/dictionary/social-media.ts, tests/integration/components/widgets/forms/link-field-test.ts, tests/integration/components/widgets/forms/social-link-field-test.ts
=> feat: Implement new link field

app/components/unverified-user-message.hbs, app/templates/verify.hbs, tests/integration/components/unverified-user-message-test.js
Fixes #5516 
update notification mesaages for verifying account.
Frist 2 points (changes) have done in this PR.
Working on third point(change).
=> fix: Update notification messages for verifying account

app/styles/partials/overrides.scss, app/templates/components/orders/order-summary.hbs, app/templates/orders/view.hbs
Fixes #5559 #5566 
Remove spaces between boxes. Enhance mobile view.
- remove spaces between boxes.
- Event Information box is visible in mobile view.
- Order summary table is also be a table in mobile view as well.
- Buttons "Tickets" and "Invoice should have some spacing in between.
__before__
__after__
=> fix: Order Page: Remove empty spaces

app/templates/components/nav-bar.hbs
Fixes #5564 
__before__
__after__
=> fix: Mobile: Substitute Create Event with Login

app/components/public/add-to-calender.ts
Fixes #5072
Add options for add to calendar
-
-
-
=> feat: Added options for Outlook, Yahoo to add to calendar

app/templates/components/footer-main.hbs
Fixes #5563 
With this PR the footer on the mobile view have the same spacing to the left and right as the above area - with the tiles.
__Screenshots__
__before__
__after__
=> fix: Footer use same width as above tiles in mobile view

app/components/forms/wizard/attendee-step.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5537
=> fix: move custom fields in attendee form in the end

app/controllers/admin/users/list.js
Fixes #5542  fix: Admin panel member since changed to date
Changes:
=> fix: Admin panel member since changed to date

app/components/forms/wizard/sessions-speakers-step.js, app/routes/index.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5578
=> fix: don't cfs filter when cfs is disabled

app/components/widgets/forms/image-upload.js
=> fix: No error shown when image upload fails

app/components/forms/orders/order-form.js
=> fix: Company field validation in form

app/index.html
=> chore: Preload fonts in HTML

app/templates/orders/new.hbs
Fixes #5603 
remove empty space from new order page.
__screenshots__ 
__before__
__after__
=> fix: Get rid of unsed spaces between boxes in templates of the order page

app/templates/orders/pending.hbs
Fixes #5615
Moves the Paypal/Pay Now button (on the order page) to the right hand side as requested. (refer image attached) and removes the extra white space.
Attachments -
=> fix: Change position of Paypal/Pay Now Button

app/templates/components/forms/orders/order-form.hbs
Fixes #5629 
change the icon  for acknowledgement is the same as for ticket holder see in the screenshot for the better understanding.
=> fix: change the icon of the Acknowledgement

app/templates/components/orders/event-info.hbs
Fixes #5614 
This PR update the area to show the information according to the attendee pdf as follows:
- When an event has a location, show "At" and the location behind.
- When an event is an online event show "Online Event"
- When the event is a mixed event show "Event taking place online and at [location here]."
- When an event location or online details are "to be announced" show: "Location or online event details to be announced".
=> fix: Show Location, Online Event, Mixed Event or To be Announced info correctly

app/templates/orders/view.hbs
Fixes #5632 
Changed Download Invoice icon
=> fix: Change Download Invoice Icon

app/models/event-statistics-general.js, app/serializers/event-statistics-general.js, app/templates/components/ui-table/cell/cell-sessions-dashboard.hbs, app/templates/components/ui-table/cell/cell-speakers-dashboard.hbs
Fixes #5010 
required https://github.com/fossasia/open-event-server/pull/7453
On the events dashboard at https://eventyay.com/events/live in the speakers and sessions column the status "Withdrawn" and "Canceled" are missing. This PR add them. 
__Screenshots__
=> fix: Add status "Withdrawn" and "canceled"  into sessions and speakers column

app/controllers/events/view/tickets/orders/list.js, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-amount.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs
Fixes #5668 
- In the first column show full name.
- take out the date and time in the first column (we already have it in the second column)
=> fix: Show full name and remove date and time in Organizer Orders Overview Page

app/router.js, app/templates/admin/settings.hbs, app/templates/admin/settings/frontpage.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5110
> List all start page restrictions in a subtab on the Admin Settings page here https://eventyay.com/admin/settings -> in https://eventyay.com/admin/settings/frontpage
related https://github.com/fossasia/open-event-frontend/issues/4697
=> fix: list front page restriction in frontpage tab

app/components/account/contact-info-section.js, app/components/account/password-section.js, app/components/forms/admin/content/pages-form.js, app/components/forms/admin/content/social-links-form.js, app/components/forms/admin/settings/analytics-form.js, app/components/forms/admin/settings/images-form.js, app/components/forms/admin/settings/microservices-form.js, app/components/forms/admin/settings/payment-gateway-form.js, app/components/forms/admin/settings/system-form.js, app/components/forms/events/view/create-access-code.js, app/components/forms/events/view/create-discount-code.js, app/components/forms/events/view/edit-session.js, app/components/forms/orders/order-form.js, app/components/forms/register-form.js, app/components/forms/session-speaker-form.js, app/components/modals/add-system-role-modal.js, app/components/modals/add-user-role-modal.js, app/components/modals/admin/content/new-event-sub-topic-modal.js, app/components/modals/admin/content/new-event-topic-modal.js, app/components/modals/admin/content/new-event-type-modal.js, app/components/modals/confirm-event-transfer-modal.js
Reverts fossasia/open-event-frontend#5685
=> Revert "chore: remove deprecated sendAction()"

app/components/forms/admin/settings/analytics-form.js, app/components/forms/admin/settings/billing.js, app/components/forms/login-form.js, app/components/forms/orders/order-form.js, app/components/forms/user-payment-info-form.js, app/templates/components/forms/admin/settings/billing.hbs, app/templates/components/forms/login-form.hbs, app/templates/components/forms/user-payment-info-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5655
=> fix: don't trigger submit action twice

app/utils/dictionary/demography.ts
Fixes #5604 
remove all old countries.
=> fix: Remove historic countries that do not exist today from country list

app/helpers/round-up.js, app/templates/events/view/tickets/index.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5631
=> fix: ticket sales value 

app/templates/components/forms/wizard/basic-details-step.hbs
Fixes #5654 
Standardize spacing between sections see in the screenshot for the better understanding.
=> fix: Wizard Step 1: Standardize spacing between sections 

app/templates/components/forms/orders/order-form.hbs, app/templates/components/orders/ticket-holder.hbs
Fixes #5624 
Icon changed for the "Ticket Buyer" information. 
Attachments -
=> fix: Icon updated for "Ticket Buyer Information"

app/components/forms/wizard/attendee-step.js, app/components/forms/wizard/custom-forms/table.hbs, app/components/forms/wizard/custom-forms/table.ts, app/templates/components/forms/wizard/attendee-step.hbs
Fixes #4596
Implemented removing function for custom form field added.
-Attendee form's template should be changed
-Remove action is inserted into the Attendee form component
-In custom table template, remove cell is activated
=> feat: Implement deleting custom form field

app/templates/components/public/side-menu.hbs, app/templates/public/index.hbs
Fixes #4849
anchor label is changed  from 'owner' to 'organizer'
-public.hbs and side-menu.hbs templates are changed
=> fix: Organizer Menu Item does not go to the section

app/components/forms/wizard/custom-forms/table.hbs, app/components/forms/wizard/wizard-footer.hbs, app/controllers/admin/events/list.js, app/controllers/admin/messages/list.js, app/controllers/admin/reports/system-logs/activity-logs.js, app/controllers/admin/reports/system-logs/mail-logs.js, app/controllers/admin/reports/system-logs/notification-logs.js, app/controllers/admin/sales/index.js, app/controllers/admin/sales/invoices.js, app/controllers/admin/sessions/list.js, app/controllers/admin/users/list.js, app/controllers/events/list.js, app/controllers/events/view/sessions/list.js, app/controllers/events/view/speakers/list.js, app/templates/admin/sessions.hbs, app/templates/components/event-card.hbs, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-session-state.hbs, app/templates/events/view/sessions.hbs
Fixes #5609 
This Pr make all listed area translatable.
areas that are make translatable:-
- Dashboard
- Speakers
- Sessions and session filters
- Session columns: Accepted and other statuses
- Admin sections
- Wizard
- Location/Online
- Dropdown event types etc.
- Custom Attendee Form fields
- Publication sentence on wizard bottom
- Speaker and Session form
- Frontpage and Search
- Tags
=> fix: make listed areas translatable

app/styles/partials/overrides.scss, app/templates/pricing.hbs
Fixes #5647 
__before__
__after__ converting to deutsch
=> fix: Make pricing page translatable

app/routes/index.js
Fixes #5579 
reduce events on front page.
- Featured Events: 6
- Upcoming Events: 12
- Call for Speakers: 6
=> fix: reduce number of events on front page

app/controllers/events/view/tickets/orders/list.js, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs, tests/integration/components/ui-table/cell/events/view/tickets/orders/cell-order-test.js
Fixes #
feat: Removed order delete functionality
-
-
-
Changes:
=> fix: Remove order delete functionality

app/templates/components/forms/orders/order-form.hbs
Fixes #5608 
**Corrected Acknowledgement text and buttons** - (_Snapshots After correction_)
For paid tickets:- 
For free tickets:-
=> fix: Change acknowledgement text and button

app/templates/components/nav-bar.hbs
Fixes #5721 
fix position of logout icon in other languages
__Screenshots__
__before__
__after__
=> fix: position of logout icon in other languages

app/templates/components/widgets/forms/time-picker.hbs
fixes https://github.com/fossasia/open-event-frontend/issues/5741
=> fix: time-picker in mobile view in wizard session-step

app/components/forms/orders/attendee-list.js, app/templates/components/forms/orders/attendee-list.hbs
Fixes #
feat: Add download ticket option for each attendee
-
-
-
=> feat: Add download ticket option for each attendee

app/components/forms/wizard/sessions-speakers-step.js, app/controllers/events/view/scheduler.js, app/models/microlocation.ts, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/events/view/scheduler.hbs
Fixes #4164
Make rooms custom-sortable by using Up and Down buttons.
-specific room actions are inserted into session-speaker-form component
-Template is changed to add up and down button
-microlocation modal is changed to store position info
=> feat: Make rooms sortable

app/components/public/session-item.hbs, app/components/public/stream/video-stream.ts, app/styles/libs/_helpers.scss
=> feat: Enhance Video Stream UI

app/templates/explore.hbs
Fixes #5754 
Reduce width of left side menu
__screenshot__
__before__
__after__
=> fix: Reduce width of left side menu

app/components/public/add-to-calender.hbs, app/components/public/session-item.hbs, app/controllers/account/billing/invoices/list.js, app/controllers/admin/sales/invoices.js, app/controllers/admin/sessions/list.js, app/controllers/admin/users/list.js, app/controllers/events/list.js, app/controllers/events/view/sessions/list.js, app/controllers/events/view/tickets/orders/list.js, app/templates/admin/sales/revenue.hbs, app/templates/components/event-invoice/invoice-summary.hbs, app/templates/components/order-card.hbs, app/templates/components/public/call-for-speakers.hbs, app/templates/components/public/ticket-list.hbs, app/templates/components/session-card.hbs, app/templates/components/ui-table/cell/cell-event-date.hbs, app/templates/components/ui-table/cell/cell-simple-date.hbs, app/templates/components/ui-table/cell/cell-validity.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-date.hbs, app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-order.hbs, app/templates/components/ui-table/cell/events/view/tickets/discount-codes/cell-validity.hbs, app/templates/components/ui-table/cell/events/view/tickets/orders/cell-order.hbs, app/templates/event-invoice/review.hbs, app/templates/explore.hbs, app/templates/public.hbs, app/templates/public/sessions.hbs
Fixes #5490
Make event format as in this example: 4 Dec, 2020 5:00 PM (IST)
This is good for most public pages
call for speakers, e.g. https://eventyay.com/e/a315169f/cfs
=> fix: time standardization in two formats only

app/templates/components/currency-amount.hbs, app/templates/events/view/tickets/index.hbs
Fixes #5781 
Earlier:--  Paid donation tickets do not show up on the orders overview page. The calculation of tickets sales works correctly. However the donation tickets show 0 in the table.
this PR resolve this.
__before__
__after__
=> fix: Paid Donation ticket sale stats

app/components/public/session-item.hbs
Fixes #5783 
move the description to the expanded area
__before__
__after__
=> fix: Move session description display to "expanded area"

app/controllers/events/view/tickets/index.js, app/templates/events/view/tickets/index.hbs
Fixes #5780 
Sales in orders now shows 0.00 instead of 0 if the income of sales has been zero. 
After :
=> fix: Show 0.00 instead of 0 for Sales

app/components/public/session-item.hbs, app/components/public/session-item.js, app/components/public/stream/video-stream.ts, app/controllers/events/view/videoroom/list.js, app/models/video-stream.ts, app/router.js, app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs, tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-title-test.ts, tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts
=> feat: Make video URL more user friendly

app/templates/components/events/view/overview/event-apps.hbs, app/templates/components/events/view/overview/event-sponsors.hbs, tests/integration/components/events/view/overview/event-apps-test.js
=> fix: Change "Apps" to "Website Generator" and other improvements

app/templates/orders/view.hbs
Fixes #5623 
Fixes https://github.com/fossasia/open-event-server/issues/7397
-
-
-
=> fix: Download ticket and invoice made available to ticket purchaser only

app/components/tables/default.js, app/controllers/events/view/sessions/list.js, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/events/view/sessions/list.hbs
Fixes #5307
Table height is adjusted to wax and wane automatically and dropdown direction is calculated properly.
-Table::Default component is patched to emit action of rendering end.
-Pre-calculation of dropdown direction is implemented
-CellButton component is modified to add direction option
=> fix: Dropdown menu results in internal scroll bar

app/components/footer-main.js
=> fix: Convert non-cached pages to array before sorting

app/styles/partials/footer.scss
Fixes https://github.com/fossasia/open-event-frontend/issues/5808
=> fix: increase height of language dropdown

app/components/forms/orders/order-form.js
Fixes #5851 
Checkbox for selecting ticket holder same as ticket buyer is checked initially (with details displayed). User can toggle to turn it off.
- [] I have added necessary documentation (if appropriate)
=> fix: Preselect Ticket holder same as Ticket Buyer in Order Form

app/mixins/event-wizard.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5855
=> fix: Adding and removing field without error in wizard step 2

app/components/widgets/forms/link-field.ts
=>  fix: set url to null instead of https when it is null

app/styles/partials/overrides.scss, app/templates/orders/view.hbs
Fixes #5852 
- Download Tickets button changes to All Tickets
- Icon for button changes to download icon
Please share feedback and suggestions.
=> fix: Download Tickets -> All Tickets

app/templates/components/orders/event-info.hbs
Fixes #5863 
"Go to event page" link added in expired event page
Image of the change :
=> fix: Go to Event link added in Expired event page

app/components/public/social-links.js, app/controllers/public.js, app/models/social-link.js, app/styles/pages/public.scss, app/styles/partials/utils.scss, app/templates/components/public/social-links.hbs, app/templates/public.hbs, app/utils/dictionary/social-media.ts
=> fix: Show social links as icon

app/controllers/orders/view.js, app/routes/events/view/tickets/orders/list.js, app/templates/orders/view.hbs
Fixes https://github.com/fossasia/open-event-server/issues/7479
=> fix: Show order buttons to admins

app/routes/pages.js
Fixes #5875
In #5775, application stopped loading pages as its model and since, the footer pages were broken
=> fix: Fetch pages before findBy

app/controllers/public/sessions.js, app/routes/public/sessions.js
=> fix: Preserve scrolling position while filtering sessions

app/templates/components/ui-table/cell/cell-event-date.hbs
=> fix: Use event end time in cell-event-date

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
Fixes #4993 
Standard Search box should be for event name.
and Provide an option to choose between "Mixed Event", "Online", "Location based" and similar to areas like > Date
- Show a standard search box "Event Name" above the filter box (instead of Location)
- Provide an option to choose between "Mixed Event", "Online", "Location based" and similar to areas like > Date
- When location based event is chosen provide an option to enter a certain location (as of now)
- Finally standardize width of left sidebar to match width of the left public event pages sidebar
=> feat: Make search event name specific and add location type filter

app/templates/components/ui-table/cell/cell-sponsor-image.hbs
Fixes #5844
Max height and width of sponsor logos are now 40px and 80px respectively.
SCREENSHOTS - 
Before-
After-
=> fix: Sponsors logo max height and width added

app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/components/explore/side-bar.hbs, app/templates/explore.hbs
Fixes #5756 
add images filter
=> feat: Add images filter in explore page

app/components/event-card.js, app/styles/libs/_helpers.scss, app/templates/components/event-card.hbs
Fixes #5926 
1. the info "Online Event" if the event is not location based and
2. "Online Event and at [address here]" if it is a mixed event
3. show long date type for the event
4. show both start and end time of event 
**Screenshots -**
=> fix: online event and enhance date/time in front page

app/components/public/ticket-list.js, app/templates/components/public/ticket-list.hbs
Fixes #5914
If an event has only free and donation tickets do not show "promotional code". (Also reduce the spacing between "Total" and "Order now" then)
If an event has only free tickets and no other tickets do not show the credit card icons neither.
SCREENSHOTS -
=> fix: Promotional code/ Cards displayed according to ticket type

app/components/forms/orders/order-form.js, app/models/social-link.js
Fixes https://github.com/fossasia/open-event-frontend/issues/5853
=> fix: Attendee form questions order in order-form

app/styles/libs/_helpers.scss, app/templates/components/event-card.hbs
Fixes #6003
Height changes happened in #5933 distorted the vertical event card. Fixed the height by conditionally changing it for only index page
Screenshot -
=> fix: Explore Page: Vertical event card height fixed

app/components/event-card.js, app/components/explore/side-bar.js, app/controllers/explore.js, app/routes/explore.js, app/templates/explore.hbs
=> fix: Search term should not get added to event categories

app/routes/events/view/team/permissions.ts
Fixes #5794 
Adds translation to Teams permission page
=> chore: Make team area translatable

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js
=> fix: Show Room without dropdown and Video Source for BBB

app/styles/libs/_helpers.scss, app/styles/partials/utils.scss, app/templates/components/public/side-menu.hbs
Fixes #6118
remove icons on the desktop view.
Screenshot -
=> fix: Public Event Sidebar: Hide icons in side menu dekstop

app/controllers/events/view/tickets/attendees/list.js
Fixes #6111 
Sort attendee orders with latest orders on top.
-
-
-
=> fix: sort attendee orders according to date and time

app/templates/events/view/sessions.hbs, app/templates/events/view/speakers.hbs
Fixes #5907
In Session and Speakers page, the links(canceled, withdrawn etc) were disabled due to the overlapping buttons.
SCREENSHOTS -
DESKTOP
TABLET
MOBILE
=> fix: Dashboard: session/speaker page button overflow fixed

app/components/schedule.ts, app/templates/public/schedule.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/4996
=> fix: set min time in calendar

app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/orders/ticket-holder.hbs
Fixes #6173 
Previously on filling the large email adresses and the location adress , gets overflow through their containers, more on the screenshots.
But now this is fixed.
=> fix: overflow of the data elements from the container

app/components/nav-bar.js, app/templates/components/nav-bar.hbs
Fixes #6220 
Removed search box from all attendee, other-details, session-speakers, sponsors & basic-details page.
=> fix: Hide search box on wizard pages

app/components/forms/wizard/basic-details-step.js, app/components/widgets/forms/time-picker.js, app/styles/libs/_helpers.scss, app/templates/components/widgets/forms/time-picker.hbs
Fixes #6117 
Previously we were able to create the events keeping the starting time and ending time same and this pr fixes that issue.
- [YES ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ YES] My branch is up-to-date with the Upstream `development` branch.
- [ NOT CHECKED YET] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ NO] I have added tests that prove my fix is effective or that my feature works
- [ NOT REQUIRED] I have added necessary documentation (if appropriate)
=> fix: creating events with same starting and ending time

app/styles/components/extras.scss, app/styles/libs/_helpers.scss, app/styles/partials/utils.scss, app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-title.hbs
=> fix: Video Tab: Icons aligned when event or video room has a long name 

app/controllers/events/view/sessions/list.js, app/styles/partials/buttons.scss, app/templates/components/ui-table/cell/events/view/sessions/cell-buttons.hbs, app/templates/components/ui-table/cell/events/view/sessions/cell-lock-session.hbs
Fixes #6221 
This PR enchances the look of session table.
The last task is covered in the PR #6207 
Screenshot with normal font size
Screenshot after 10% increment in font-size(see 110% in url bar)
Screenshot after 20% increment in font-size
Screenshot after 33% increment in font-size
=> fix: Session table styling

app/templates/components/forms/admin/settings/system/captcha-form.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/3390
-  disabled `enable google recaptcha button`.
=> fix: Missing info where Captcha is used in admin section

app/templates/events/view.hbs
Fixes #6277 
ordered the menu tab to the following order: Overview, Tickets, Speakers, Sessions, Scheduler, Video, Team, Settings
- Replaced the tabs
-
-
=> fix: Organizer Menu Tab: Change Order

app/components/forms/wizard/basic-details-step.js
Fixes #6288 
When max price is greater than min price or vice-versa ,it no longer gives error.
=> fix: price validation logic of donation ticket

app/styles/partials/snackbar.scss
Because the snackbar is in-view on mobile (`bottom: 0`) rather than out of view like on desktop (`bottom: -100px`), clicking on elements in that area of the page on mobile will be blocked by the presence of a snackbar even though the snackbar is not visible. 
- Snackbar always starts at -100px from bottom
=> fix: Prevent snackbar from blocking touches on mobile

app/templates/components/events/view/overview/general-info.hbs
=> fix: "Click here to add" for social links directs to the wrong wizard step 

app/mixins/event-relation.js
A serializer was created to convert string event identifier to event ID while saving the event or event relationship. However, event ID may have already been replaced sometimes and sometimes originalId is undefined, so in this case, valid event ID was being replaced with undefined. So, we check for null or undefined before replacing event ID
Fixes #6263
=> fix: Don't override evenr ID if undefined

app/components/url-box.js, app/controllers/events/list.js, app/templates/components/ui-table/cell/cell-link.hbs, app/templates/components/url-box.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6330
=> fix: add url box and width distribution

app/models/event.js, app/templates/components/forms/wizard/basic-details-step.hbs, app/templates/components/orders/after-order-message.hbs, app/templates/orders/pending.hbs, app/templates/orders/view.hbs
Fixes #5560
required #https://github.com/fossasia/open-event-server/pull/7611
=> feat: Add afterOrderMessage field in event

app/controllers/admin/users/list.js, app/models/user.js, app/templates/components/ui-table/cell/admin/users/cell-user-verify.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/5040
=> feat: Enable admins to change users from "Unverified" to "Verified"

app/components/forms/orders/order-form.js
Fixes #7634
Reverts #5851 
The logic of when to preselect same as buyer is not that straightforward and prevents successful submission of order form
=> fix: Revert preselecting same as buyer

app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/forms/orders/order-form.hbs, app/templates/components/orders/order-summary.hbs
=> fix: wrong download option, billing icon and text

app/utils/validators.js
I suggested these changes on PR #6414  after it got merged.
Fixes PR #6414
the regex was also passing this url but it is not correct
https://instagr.am.com/username 
After the changes everything will work fine
=> fix: error in regex for instagram profile url

app/styles/components/all.scss, app/styles/components/events/view/overview/general-info.scss, app/templates/components/events/view/overview/general-info.hbs
Fixes #6331 
This PR adds url box over public url's
If the event is not live
it the event is live , also check the height remains same as previous
on smaller screens
@iamareebjamal  @mariobehling I have also tested this feature with multiple languages and it is working just fine, you can test it out , thanks
=> feat: added url box on public event pages

app/controllers/admin/events/list.js
=> fix: Sort events by descending in admin

app/styles/components/stream.scss, app/styles/partials/nav-bar.scss, app/templates/components/nav-bar.hbs
Fixes #6333 
Updated the button as well as eventyay positions
- Side panel button position changed
- eventyay name position changed
Screenshot
=> fix: Virtual Events: Moved Big Blue Button minimize button to avoid overlap

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs
Follow up for : #6435 
Currently order is not processed in the first go due to the consent fields having a value false even while they are ticked.
The bug was generated in the above mentioned PR
=> fix: Error on submitting order form while consent options are ticked

app/components/modals/contact-organizer.js, app/controllers/public/index.js, app/templates/components/modals/contact-organizer.hbs, app/templates/components/public/ticket-list.hbs, app/templates/public/index.hbs
Fixes #5811 
**What functions do we need for the implementation**
=> feat: Add Contact organizer feature

app/templates/components/events/view/overview/speaker-session.hbs
=> fix: Display number of speakers in event overview page

app/components/public/stream/jitsi-stream.ts
Fixes #6487 
This PR removes embed meeting option from toolbar from the jitsi meeting call.
we can see that option is removed now.
=> fix: Removed embed meeting option from toolbar

app/helpers/session-color.js, tests/integration/helpers/session-color-test.js
Fixes #6521 
Previously the status badges colors were not matching , but now it is resolved.
I used same source of colors which is stateColorMap for speakers page also, so that if one changes , the other will automatically gets changed.
On speaker page
On sessions page
=>  fix: made same color of status badges on the speakers as well as session pages

app/components/events/view/overview/speaker-session.js, app/models/event-statistics-general.js, app/routes/events/view/speakers/list.js, app/templates/components/events/view/overview/speaker-session.hbs, app/templates/events/view/speakers.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6549
- about this do I need to create a attribute on server or on frontend it would be like `this.data.speakers.map(x => if x.sessions.length === 0  {count = count +1;})` (tried this it was not working as expected @iamareebjamal )
=> fix: adding Without session filter to speaker

package.json, yarn.lock
Reverts fossasia/open-event-frontend#6609
=> Revert "chore(deps-dev): bump ember-h-captcha from 2.0.6 to 2.0.7"

package.json, yarn.lock
This reverts commit 8f38e2fe7e4c4d53272582229afb3ca9f2331b56.
=> Revert "chore(deps-dev): bump ember-source from 3.20.3 to 3.25.1"

app/templates/components/public/call-for-speakers.hbs
Fixes #6715
For speaker that are already in the system the button should still be available.
**Speaker not in the system**
**Speaker in the system**
=> fix: CfS: "Edit Speaker Details" button not available after CfS is closed

app/components/public/stream/side-panel.hbs
Fixes #6629 
The minimise side panel button overlaps the date and speakers button. This PR ensure the right side of the date does not overlap.
=> fix: overlapping of minimise button of side_panel

app/components/schedule.hbs, app/components/schedule.ts
Fixes  `from the technical meeting`
- Starting time of calendar min session time
- Default - event days view instead of single day view
https://user-images.githubusercontent.com/56407566/109747608-7718fa00-7bfd-11eb-9261-d8e2f97c87d0.mp4
=> fix: default calendar view on public page

app/controllers/public/exhibition/view.js
=> fix: "Get in touch" heading should only show up if there is actually a button "contact" or "email"

app/components/forms/events/view/videoroom-form.hbs, app/components/forms/events/view/videoroom-form.js, app/controllers/events/view/videoroom/list.js
as discussed in meeting
from meeting notes - Renaming event video room does not rename video room on sidepanel - Meghal
=> fix: allow editing of event video room name

app/components/modals/add-room-modal.hbs, app/controllers/events/view/scheduler.js, app/models/microlocation.ts, app/templates/components/forms/wizard/sessions-speakers-step.hbs, app/templates/public.hbs
Fixes #As discussed in meeting -
Microlocation:
hidden_in_scheduler False
Event Wizard - Switch
Video Room - Switch
It should not show in scheduler, public page
Show all Video Stream Rooms
server pr - https://github.com/fossasia/open-event-server/pull/7813
=> fix: add hidden in scheduler for rooms

app/components/public/event-venue.hbs, app/styles/partials/event-card.scss, app/templates/components/order-card.hbs
Fixes #6908 
Previously there was in overlapping in order card at `my-tickets.`
This PR removes overlapping between event location and order details.
=> fix: remove overlapping in order card in my tickets.

app/templates/components/forms/session-section.hbs
Fixes #7009
Increase file limit to 30 MB in session speaker form
=> fix: Increase file limit to 30 MB in session speaker form 

app/controllers/public/sessions.js
Fixes https://github.com/fossasia/open-event-frontend/issues/6927
before
https://github.com/fossasia/open-event-frontend/issues/6927#issuecomment-812489418
After
=> fix: schedules are showing twice when sorting by popularity

app/components/public/stream/jitsi-stream.ts
as mentioned in meeting notes - 
Jitsi shows “invite button” in new version on eventyay - Meghal
=> fix: Jitsi: Hide invite button

app/controllers/public.js
=> fix: Show event link if event is online event in "Location Field" in calenders(other than ical)

app/components/ui-table/cell/events/view/videoroom/cell-video-url.js, app/templates/components/ui-table/cell/events/view/videoroom/cell-video-url.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6190
> Clicking on the table heading, e.g. in the video source URL area results in an ember error and moves the "Additional Information" content to the "Password" column
this is an ember table issue so we can't de much about it.
- taking out https
=> fix: take out https from video source URL

app/controllers/orders/new.js
this PR fix order issue regarding billing info.
=> fix: order issue regarding billing info

app/components/events/view/publish-bar.ts
Fixes https://github.com/fossasia/open-event-frontend/issues/7357
When creating an event with an account that has not verified the email the message shown is:
"Unknown Error has occurred."
-----
message changed to-> "Please confirm the verification email before creating an event"
=> fix:Message when trying to create an event with a non verified account is not helpful.

app/components/side-bar.js, app/styles/libs/_helpers.scss, app/templates/public/sessions.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/6761
also contains some changes in https://github.com/fossasia/open-event-frontend/pull/7456
=> fix: schedule page cut off in mobile view

app/templates/admin/sales.hbs, app/templates/admin/sales/index.hbs
Fixes #7650
fix tabbedNavigation and UiDropDown at Admin Sales Page.
=> fix tabbedNavigation and UiDropDown at Admin Sales Page.

app/templates/groups/edit/followers.hbs
Fixes #7664 
User would be able to select other tabs when on followers tab.
=> fix: group edit tabs

app/templates/components/forms/orders/order-form.hbs
Fixes #7817 
The order now button on registration events has an usual color. Please change it to the blue color which is used on other buttons.
Before | After
-------- | ---------
=> fix: Change color of "Order" button on registration events

app/styles/partials/utils.scss, app/templates/components/orders/order-summary.hbs
Fixes #7813
Fixes #7812
Before | After 
----------- | -----------
=> Update order-summary table on order page

app/controllers/public/index.js, app/models/ticket.js, app/templates/components/public/ticket-list.hbs, app/templates/public/index.hbs
Fixes #7815 
Fixes #7814
Fixes #7809
=> fix: Update Ticket and Registration Section on Event Public Page

app/templates/public/index.hbs
Fixes #7822 
The registration box on the event page currently shows empty boxes for the deleted registration types. Only show boxes of active types.
=> fix: Only Show Registration tickets which are active

app/models/group.js
=> fix: public url under admin groups list

app/templates/components/ui-table/cell/admin/groups/cell-group-name.hbs
=> fix: group name not showing in admin group table

app/templates/components/orders/company-info.hbs
Fixes #7883 
The order company information box shows the "Name" instead of "Organisation" in the left column of the box. Please correct this and show "Organisation" in all company boxes in the order process and final order page.
change variable from registered company to organization
=> fix: changed registeredComany to organization

app/components/promoted-group-card.js, app/templates/components/group-card.hbs, app/templates/components/orders/event-info.hbs, app/templates/components/orders/ticket-holder.hbs, app/templates/components/promoted-group-card.hbs, app/templates/orders/new.hbs
Fixes https://github.com/fossasia/open-event-frontend/issues/7985
Fixes https://github.com/fossasia/open-event-frontend/issues/8005
Fixes https://github.com/fossasia/open-event-frontend/issues/8004
=> fix: standard group card height

Dockerfile
Trying again since the github-actions bot didn't like my [previous one](https://github.com/fossasia/open-event-frontend/pull/8047) and closed it.
Signed-off-by: Marco A. Gutierrez <marco@marcogg.>
Failing automated docker build through github actions with the following error:
```
[...]
#7 [builder 3/7] RUN apk add git python-dev make g++ gettext
#7 0.880 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
#7 0.995 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
#7 1.213 ERROR: unable to select packages:
#7 1.244   python-dev (no such package):
#7 1.244     required by: world[python-dev]
[...]
```
You can find the full log [here](https://github.com/fossasia/open-event-frontend/runs/4127741393?check_suite_focus=true).
It seems …
=> python-dev is not found, changing to python2-dev

package.json
Originally from #8092 
This should prevent the repeated questions of users who try installing the project on node 16. Currently only node <=14 is supported.
=> feat: Added node js check below 15 in package.json

app/routes/group-public.js
Fixes #8005 
Fixes #8007 
```
WARNING: You requested a record of type 'event' with id '7' but the adapter returned a payload with primary data having an id of 'e9663c48'. Use 'store.findRecord()' when the requested id is the same as the one returned by the adapter. In other cases use 'store.queryRecord()' instead.
```
I enabled my console warnings today and figured out what's the error by seeing this warning message. This was because of ```ember-data``` as we guessed. Now this should work fine. Tested on api.eventyay.com
=> fix: event cards now show up everytime as expected with correct information on group public page

app/controllers/group-public.js, app/templates/components/forms/group/group-view.hbs
Fixes #8131 
As discussed in the meeting, user thumbnails removed when the user is not logged in.
=> fix: error when accessing group page

app/components/public/add-to-calender.ts
Fixes #8179 
**Yahoo**
**Outlook**
=> fix: remove HTML tags from calendar description text

app/mixins/custom-form.js
Fixes #8201 
To test: **Create a new event and turn on speaker-session forms and turn on audio and video fields**
=> fix: make video & audio field in session edit form visible

app/styles/pages/public-event.scss, app/templates/public.hbs
=> fix: event logo cut off in events with long titles & addresses

app/components/public/add-to-calender.ts
=> fix: remove harcoded host links from session calendar urls

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/attendee-list.hbs, app/templates/components/widgets/forms/billing-info.hbs
=> Make Tax and Business ID optional

app/utils/dictionary/social-media.ts
Fixes #8667 
Mastodon link is wrong
Replace link Mastodon from "https://mastodon.com" to "https;//"
=> fix-8667: Mastodon link is wrong

app/templates/components/forms/admin/settings/payment-gateway-form.hbs
Fixes #7984
Show test/live key of Stripe under Payments section
Load the key for Stripe under the Payments section, depending on the environment.
=> fix-7984:Show test/live key of Stripe under Payments section

app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs, app/utils/dictionary/age-groups.ts, translations/ar.po, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
Fixes #8787
- Change the "age" field of the custom form
- Change the age field of the custom form and display the following options:
`
18-24; 
25-34;
35-44;
45-54;
55-64;
65-74;
75-84;
85+;
I prefer not to say;`
=> feature-8787: Change the "age" field of the custom form

translations/ar.po, translations/bn.po, translations/de.po, translations/de_DIVEO.po, translations/es.po, translations/fr.po, translations/hi.po, translations/id.po, translations/ja.po, translations/ko.po, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
Fixes #8787
Add translate for the age field of the custom form
- Add translate for the age field of the custom form
=> feature-8787:add translate for the age field of the custom form

app/components/forms/wizard/custom-form-input.ts
Custom field in Attendee form should have the include value is True as default
Fixes #8818
- Custom field in Attendee form should have the include value is True as default
- Set isIncluded for customer field is true.
=> feature-8818: Custom field in Attendee form should have the include value is True as default

app/routes/events/view/edit/attendee.js, app/routes/orders/pending.js
Fixes #8833
Display custom form when adding 2 or more custom
Fix bug "when an organizer creates a second custom the standard and custom questions disappear when the user loads the form again."
=> fix-8833:Additional custom form disappears in attendee form setup

app/components/forms/orders/attendee-list.js, app/components/forms/orders/order-form.js, app/components/forms/session-speaker-form.js, app/components/forms/speaker-section.js, app/templates/components/forms/orders/order-form.hbs
Closes #8842 
The bug described by @lthanhhieu that got caused by a merge conflict with some other changes in attendee-list.js is resolved now. The selected genders are again displayed correctly. This time even better: with spaces after the commas.
Additionally, the genders in the speaker section are now displayed in logical order, not ordered by alphabet, which makes the selection a lot easier & faster (same was already done to the gender selection in the attendee section before).
=> fix for #8842: genders are displayed in the ticket confirmation

app/utils/dictionary/genders.ts
I assume that the new gender options (man, woman, non-binary,...) are not yet recognized by Weblate yet, because they lacked the corresponding tags. I added those now. Not sure whether that will actually help (will turn out after Weblate re-scanns the project), however I did some testing to make sure that this change does not break anything.
=> feat #8883: making gender options visible to weblate

app/components/forms/orders/order-form.js, app/models/attendee.js, app/templates/components/forms/orders/order-form.hbs
Fixes #8886
There was only one "Ticket holder is the same person as the ticket buyer" box for all the ticket holders when buying multiple tickets at one. This is not only highly impractically (considering that when buying multiple tickets, people often buy one for themselves and some more for others). It was also linked to some other problems, like the e-mail adress fields of the second (,third,...) ticket not being editable, once the user wants to use the buyer's data for the first ticket holder.
The bug is fixed by giving each ticket holder a "Ticket holder is the same person as the ticket buyer" option checkbox. This box is initially checked. When checked, the information (i.e.: e-mail, first name and last name) is copied from the buyer. The corresponding fields in this ticket holder's …
=> fix #8886: attach sameAsBuyer option to every ticket holder

app/components/forms/orders/order-form.js, app/models/attendee.js
Fixes #8905
When starting a new ticket buy submission, the "attendee is same as buyer" option was initially checked and filled in the buyer's credentials into the attendee section. However, this was only the case, if the buyer already had a first and last name given. This caused problems in cases where those names were only added later on. To solve this bug, the "attendee is same as buyer" option is now deactivated by default and the information is only auto-filled in the attendee's section, once that box is checked again.
PS: That also resolves the comment of @norbusan under PR #8891 to adjust the code, in order to treat attendees with only a first or a last name in the same way, as people, who have a first and a last name.
=> fix #8905: initial deactivation of sameAsBuyer

app/components/forms/orders/attendee-list.js, app/components/forms/orders/order-form.js, app/templates/components/forms/orders/order-form.hbs, app/utils/dictionary/language-form-1.ts, app/utils/dictionary/language-form-2.ts
Fixes #8906
1. The prompt was changed from "I consent to having my photo taken at Wikimania per the [photo policy](https://wikimania.wikimedia.org/wiki/2023:Photography_policy) ." to "I consent to the Wikimania [photo policy](https://wikimania.wikimedia.org/wiki/2023:Photography_policy)."
2. I added the option "Other" to the question "What is your native language, or what language are you most fluent in?". As this option is not needed in the question "Are you fluent in any other of the following languages?", a separation of the dictionary ```language_form.ts``` was needed into one dictionary with options for language question no. 1 (about the native language) and one dictionary for language question no. 2 (about the other languages).
3. The Arabic word for "Arabic" was corrected from عرب …
=> feat #8906: updating attendee form questions

app/components/public/ticket-list.js
Fixes #8919 
When a ticket is shown via access code, it disappears when a ticket number is selected
Fix for the original issue: `this.tickets` is a computed property that is initialized from `this.data` which
only contains the tickets that are shown by default. During the toggling of promo code, the access
code related ticket is added to `this.tickets` via `.addObject`, but when the cache is invalidated by
changing the property `orderAmount`, `this.tickets` is recomputed and falls back to the initial set
of tickets without the access code ticket.
Solution is to always add `this.accessCodeTickets` which contains the additional tickets.
Another fix proposed is to make the logic about promotional code handling correct.
As of now, if a promotional code is passed in, the code checks both …
=> Fix access code ticket disappearing 

app/services/l10n.js
Fixed issue #8844 
The date is not translate for Chinese and Bokmål because of `moment.js` translation file name.
- Add logic to modify translation file name to match with `moment.js` library.
- [X ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X ] My branch is up-to-date with the Upstream `development` branch.
=> fix #8844 make dates translatable

app/routes/events/view/index.js, app/routes/public/index.js
Server has page size of 20 if query is empty due to old package not migrated
setting 0 for no pagination
=> fix #8965 set no paginaton for tickets to override default server

app/templates/components/events/view/overview/event-setup-checklist.hbs
Fixes #8981 
- Badge form shown as green used even though is deactivated
- Badge form shown as green used even though is deactivated
=> fix-8981: Badge form shown as green used even though is deactivated

app/components/forms/wizard/sponsors-step.js, app/templates/components/events/view/overview/general-info.hbs, app/templates/components/forms/wizard/sponsors-step.hbs, app/templates/components/ui-table/cell/cell-sponsor-options.hbs, app/templates/pricing.hbs, translations/ar.po, translations/bn.po, translations/ca.po, translations/de.po, translations/de_DIVEO.po, translations/en.po, translations/es.po, translations/fr.po, translations/hi.po, translations/hr.po, translations/id.po, translations/ja.po, translations/ko.po, translations/messages.pot, translations/nb_NO.po, translations/pl.po, translations/ru.po, translations/sv.po, translations/te.po, translations/th.po, translations/vi.po, translations/zh_Hans.po, translations/zh_Hant.po
Fixes #8880 
- "Sponsors" was not changed on the left side bar of events.
- fix translate sponsors to supports
=> Feature-8880: Change Sponsors to Supporters

app/styles/partials/overrides.scss
Fixes #9091 
Removed the extra spacing above the event image in both the web and mobile view.
=> Fix: Event image spacing below

.github/CONTRIBUTING.md
The CONTRIBUTING.md file suggested to "set up the project on your local machine" but didn't actually provide instructions on how to do so. This PR adds a link to the document that describes the process.
=> Link to local setup documentation in CONTRIBUTING.md

app/components/public/stream/side-panel.hbs, app/components/public/stream/side-panel.ts, app/components/public/stream/video-stream.ts, app/services/selecting-language.js, app/styles/components/translation-dropdown.scss, app/styles/partials/overrides.scss
Fixes #9082 
- Enhance language dropdown button
- Enhance language dropdown button
=> Feature-9082 Enhance language dropdown button

app/routes/public/cfs/edit-speaker.js, app/routes/public/sessions.js
Fixes #7016
- Link redirect of current day results in user forward to wrong filtered page
- Link redirect of current day results in user forward to wrong filtered page
=> fix-7016: Link redirect of current day results in user forward to wrong filtered page

app/styles/pages/events.scss, app/templates/events/view/sessions/list.hbs
Fixes #9140
The value of the status dropdown list cannot be displayed in full
-  The value of the status dropdown list cannot be displayed in full
=> fix 9140: The value of the status dropdown list cannot be displayed in full 
